### ISSUE TITLE
Memory leak in re_create_simulation_from_binary (src/input.c:116)

### ISSUE THREAD

**Issue by sclaomir** [hannorein/rebound#109]
I've checked the source code using `cppcheck` and there is potential memory leak in `re_create_simulation_from_binary` function. 

In line 116 (if the binary file cannot be open) function returns `NULL` but the memory pointed to by `r` is not freed.

**Comment by hannorein** [comment]
Hi Slawek. Thanks for letting me know. Just to confirm, this only happens when the binary file was not found?

**Comment by sclaomir** [comment]
Yes. This memory leak can happen only in this situation.

For future you can think about automatic static code analysis. This can be done using e.g. coverity scan.
