### ISSUE TITLE
Python - segfault on adding particles with gravity = "tree"

### ISSUE THREAD

**Issue by rantonels** [hannorein/rebound#110]
The following minimal example

```python
import rebound

sim = rebound.Simulation()

sim.gravity = "tree"

print "adding particle #1"
sim.add(m=1)
print "adding particle #2"
sim.add(m=1)
print "added 2 particles"
```

prints

```
adding particle #1
adding particle #2
Segmentation fault (core dumped)
```

The issue only presents itself when using the ```"tree"``` module and the segfault only happens when adding the second particle. Adding/changing parameters to `add()` such as particle position or velocity has no effect on the issue.

This is on Ubuntu 15.10 and just installed through ```pip install rebound```.

**Comment by hannorein** [comment]
You need to create a simulation box before adding particles. This is needed to construct the tree.

**Comment by hannorein** [comment]
The code for this is 

    sim.configure_box(boxsize)

**Comment by hannorein** [comment]
Also, both particles in your example have the same coordinates. They need to have different positions.

**Comment by rantonels** [comment]
Thank you, it now seems obvious that the Barnes-Hut method requires a bounding box.

**Comment by hannorein** [comment]
I added a better error message to the code.  You might not be the only one who stumbles over the useless "segmentation fault" message.
