### ISSUE TITLE
Spaces vs tabs

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#111]
I would like to move to a consistent style where we use either tabs or spaces. I am tempted towards spaces. Four spaces for each tab, to be specific. Any strong feelings about this?

**Comment by dtamayo** [comment]
That sounds good.  I think I currently have separate settings for C and python, so I agree something consistent makes sense.  Spaces work for me.

**Comment by hannorein** [comment]
The conclusion is "4 spaces".
