### ISSUE TITLE
can't write data if usleep enabled

### ISSUE THREAD

**Issue by lasibai** [hannorein/rebound#151]
When I set the usleep value of my simulation to 1 or more, the reb_output_orbit function (called in rebound.c) doesn't create the file on which I'm trying to write data. But when I set usleep to a negative value (no OpenGL) it works fine.

**Comment by hannorein** [comment]
This sounds strange. It works for me. Can you provide a short problem.c file that illustrates the problem.

**Comment by lasibai** [comment]
I solved it, sorry about that. It was a scope issue in rebound.c
