### ISSUE TITLE
Old swift based WH integrator not conserving energy

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#162]
Can't get the energy conservation to work for the old swift based WH integrator. Maybe not worth fixing. WHFast should be superior in all possible ways. Unit test is in `test_integrator.py`.

**Comment by hannorein** [comment]
I think we should remove the old WH integrator. I don't see any reason why one would continue to use it rather than WHFast.

**Comment by dtamayo** [comment]
Agreed
