### ISSUE TITLE
Installing Rebound

### ISSUE THREAD

**Issue by NiDi26** [hannorein/rebound#163]
Good Morning,

I'm having trouble installing rebound. Python is what I use and have installed, how can I install rebound on Python? The website guideline is to copy a command in my terminal, but that gives me error and doesn't install rebound. Could you help me with that?

Thank you so much,
NiDi

**Comment by hannorein** [comment]
It would help if you let us know what the error is.

**Comment by NiDi26** [comment]
Thank you so os much for your quick response.


Here is what's going on:

I have python installed on my laptop. and the website says (http://rebound.readthedocs.org/en/latest/) to install rebound, just type in the following into a terminal. Well I open my python terminal and type that in, attached is the error I get. So I don't know how to install rebound using that command mentioned in the website.

pip install rebound

[http://rebound.readthedocs.org/en/latest/_images/dense.png]<http://rebound.readthedocs.org/en/latest/>

Welcome to REBOUND! — REBOUND 2.13.10 documentation<http://rebound.readthedocs.org/en/latest/>
rebound.readthedocs.org
Welcome to REBOUND!¶ REBOUND is an N-body integrator, i.e. a software package that can integrate the motion of particles under the influence of gravity.

Also I have downloaded the package provided here (https://github.com/hannorein/rebound) but don't know how to run it to install rebound. So my question is, having a windows and python installed, I don't know how to install rebound! Thank you so so much for your help in advance.
________________________________

**Comment by hannorein** [comment]
Again, I at least need to see the error message, otherwise I can't help. I don't see it in the above.

**Comment by NiDi26** [comment]
I just sent it as a screen shot. Would you mind looking at it? 
Thank you so much,Niusha 

-------- Original message --------

**Comment by hannorein** [comment]
You cannot attach a screenshot to a github issue. Maybe post a link to it?

**Comment by NiDi26** [comment]
I put "pip install rebound" in my python terminal as was said in the directions, and the error I get is "invalid syntax".


Could you tell me in steps how I can get rebound installed in a laptop with python installed on?

________________________________

**Comment by dtamayo** [comment]
Hi Niusha,

What operating system are you using? Does 

pip install numpy 

Or some other standard library work?

**Comment by NiDi26** [comment]
Hi,


I am using Windows, version 6.3.9600

it installs numpy

These are the set of errors I get in order:

1)Running setup.py bdist _wheel for rebound ... error

2)Command line error D8021 : invalid numeric argument '/wno-unknown-programs'

3)error: command 'C:\\Users\\my drive name\\ AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python \\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

4)Failed building wheel for rebound

5)Fail to build rebound

6)after a bunch of red stuff: failed with error code 1


Thank you so much for your help in advance!

________________________________

**Comment by dtamayo** [comment]
Hi Niusha,

Unfortunately REBOUND will not work on a Windows machine, only Mac & Linux.  We’ll update the documentation to make that information more prominent.
