### ISSUE TITLE
J2000 reference frame

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#167]
There are two options for the coordinate system in Horizons:
- Earth mean equator and equinox of reference epoch ("frame"):
- Ecliptic and mean equinox of reference epoch ("ecliptic")

Currently we are using "ecliptic". Would "frame" make more sense as the dafault?

See: ftp://ssd.jpl.nasa.gov/pub/ssd/Horizons_doc.pdf

**Comment by hannorein** [comment]
(I think the answer is no)

**Comment by dtamayo** [comment]
I think ecliptic makes more sense for doing N-body type integrations where you expect everything to be close to 0 inclination.  frame seems like it would be useful if you wanted to use REBOUND to predict what RA Dec you should look in the sky to find planets (and maybe also to compare to observational tables).  Maybe ecliptic should be default but we should add a kwarg for frame?

**Comment by hannorein** [comment]
There is now a keyword `plane` which can be either `frame` or `ecliptic`. `ecliptic` is the default.
