### ISSUE TITLE
Makefile error, C version

### ISSUE THREAD

**Issue by Haliph** [hannorein/rebound#176]
I ran the code 

git clone http://github.com/hannorein/rebound && cd rebound/examples/shearing_sheet && make && ./rebound

However, when it reaches the makefile, I get the following error:

make -C ../../src/
make[1]: Entering directory '/home/pi/rebound/src'
Compiling source file rebound.c ...
cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3 -march=native -Wall -g -Wno-unknown-pragmas -fPIC -DLIBREBOUND -DOPENGL -o rebound.o rebound.c
*** Error in `cc': double free or corruption (top): 0x0086cfd8 ***
Makefile:12: recipe for target 'rebound.o' failed
make[1]: *** [rebound.o] Aborted
make[1]: Leaving directory '/home/pi/rebound/src'
Makefile:12: recipe for target 'librebound' failed
make: *** [librebound] Error 2

Running just sudo ./make gives this error as well. I am attempting this install on a Raspberry Pi 3.

**Comment by hannorein** [comment]
1) Why do you compile it as root?
2) Why would you run an n-body code on a raspberry pi?
3) You have turned on OpenGL. Did you install the libraries? If not, turn it off in the makefile and try again.

**Comment by Haliph** [comment]
I turned off OpenGL but still get the error in cc:

Compiling shared library librebound.so ...
make -C ../../src/
make[1]: Entering directory '/home/pi/rebound/src'
Compiling source file rebound.c ...
cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3 -march=native -Wall -g -Wno-unknown-pragmas -fPIC -DLIBREBOUND  -o rebound.o rebound.c
*** Error in `cc': double free or corruption (top): 0x00f43de0 ***
Makefile:12: recipe for target 'rebound.o' failed
make[1]: *** [rebound.o] Aborted
make[1]: Leaving directory '/home/pi/rebound/src'
Makefile:12: recipe for target 'librebound' failed
make: *** [librebound] Error 2

As for running it on pi, I'm testing it's computing capabilities.

**Comment by hannorein** [comment]
Try removing `march=native` which might not work for arm architectures. Let me know what you find out about the computing capabilities.

**Comment by Haliph** [comment]
I removed the march=native tag from the Makefile.defs and it did get past the previous error. However, now a new error arises:

Compiling shared library librebound.so ...
make -C ../../src/
make[1]: Entering directory '/home/pi/rebound/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pi/rebound/src'

Compiling problem file ...
cc -I../../src/ -Wl,-rpath,./ -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3 -Wall -g -Wno-unknown-pragmas  problem.c -L. -lrebound -lm -lrt -o rebound
./librebound.so: undefined reference to `reb_display_init'
collect2: error: ld returned 1 exit status
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by hannorein** [comment]
make clean && make

?

**Comment by Haliph** [comment]
Of course! This now works, thank you.
