### ISSUE TITLE
/usr/bin/ld: cannot find -lGL

### ISSUE THREAD

**Issue by qshu** [hannorein/rebound#178]
Hi, Hanno
I try to run the examples by typing 
make 
in the examples/ directory.
It gives an error message as following:

Linking share library librebound.so ...
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
make[2]: *** [librebound.so] Error 1
make[1]: *** [librebound] Error 2
make: *** [bouncing_balls/.] Error 2

How I can fix it?
Qi

**Comment by hannorein** [comment]
You need to either install OpenGL and glut libraries (how to do this depends on your operating system) or turn off the visualization (set `OPENGL=0` in the Makefile)

**Comment by qshu** [comment]
thanks, I try to locate these libraries on Ubuntu 14.04 and link them to /usr/lib/, but I still can not do the visualization. So, I just turn off the visualization by setting OPENGL=0 and it works well for me.
