### ISSUE TITLE
Should binary files have shallow-copied pointers set to NULL?

### ISSUE THREAD

**Issue by dtamayo** [hannorein/rebound#187]
If I understand correctly, the binary files write shallow copies of structures.  Would it make sense for them to set any pointers that are not deep-copied to NULL to avoid later mis-access?

We were running into an issue where, even though REBOUNDx checks whether sim.extras is set before allowing you to access or set properties (to avoid a seg fault), when you reload a binary, sim.extras is set to the previous pointer value.  I'm happy to do this if you agree it makes sense.

**Comment by hannorein** [comment]
This should go in `reb_reset_temporary_pointers()`

**Comment by dtamayo** [comment]
Pull request #190
