### ISSUE TITLE
creating sim from file warnings

### ISSUE THREAD

**Issue by SeanBE** [hannorein/rebound#188]
When you initialise a simulation from the binary file, it gives you the warning "you have to reset function pointers" and states "Found x particles..". I was wondering if you've be able to hide these from the python layer? I'm creating quite a lot of them and its killing console output. Or should I just rebuild the library on my end without those statements?

**Comment by hannorein** [comment]
You raise a good point. I think the "Found x particles" warning should just go. And in the newest version the "you have to reset function pointers" warning only appears if you had function pointers setup. 

But I'll think about a better solution.

**Comment by hannorein** [comment]
This is now fixed using a way to send warning messages to python. If you get warnings, you can now easily hide them. See https://github.com/hannorein/rebound/blob/master/doc/changelog.rst

**Comment by SeanBE** [comment]
Awesome! Thanks @hannorein
