### ISSUE TITLE
contributing to docs

### ISSUE THREAD

**Issue by SeanBE** [hannorein/rebound#208]
Just wondering how you build rebound's docs locally. Wanted to see a change I made locally to one of the python method docstrings and it didn't pick it up.

I thought running `make doc` in the root dir would build the docs for both C++ and python source files.  
Am I missing something?

**Comment by hannorein** [comment]
Yes. For the C part, you need doxygen installed.

**Comment by SeanBE** [comment]
I've got all the dependencies. Looking at files under /doc/_build/html, it seems Sphinx didn't pick up my change. Build succeeds with 46 warnings. Is that what you're getting?

**Comment by hannorein** [comment]
Oh, one more thing: You might also need jupyter as it converts ipython notebooks...
