### ISSUE TITLE
Horizon system changes

### ISSUE THREAD

**Issue by SeanBE** [hannorein/rebound#223]
I believe the Horizon changes (http://ssd.jpl.nasa.gov/?horizons_news) have broken the add particle function. You can run the horizons test to see it hang on adding Earth. 

I'm looking into the telnet code but just letting you all know.

**Comment by hannorein** [comment]
I just pushed an update which works for me. Let me know if you still have trouble. I really wish NASA would come up with a better way to query their system than telnet...

**Comment by SeanBE** [comment]
I was just about to push the fix. You beat me to it!  Thanks anyway!
