### ISSUE TITLE
Hermes behaving strange after changing units

### ISSUE THREAD

**Issue by jilkoval** [hannorein/rebound#229]
It seems that something strange happens to Hermes when the simulation units are changed. Below is an example script (based on the [Eccentric comets example](https://github.com/hannorein/rebound/blob/4350fb8c1ef068a8a0923caa6a882021702bfaf2/ipython_examples/EccentricComets.ipynb)). 
```
import rebound
import numpy as np

sim = rebound.Simulation()
np.random.seed(42)

#integrator options
sim.integrator = "hermes"
dt = 0.1
sim.dt = dt
sim.testparticle_type = 1
sim.track_energy_offset = 1
tmax = 1e4

#### changing units
# sim.units = ('AU', 'yr', 'Msun')
# tmax = tmax / (2.*np.pi)
# sim.dt = dt / (2.*np.pi)
####
 
#massive bodies
sim.add(m=1., r=0.005)                     #sun
a_neptune = 30.05
sim.add(m=5e-5,r=2e-4,a=a_neptune,e=0.01)  #neptune
sim.N_active = sim.N

#semi-active bodies
n_comets = 5
a = np.random.random(n_comets)*10 + a_neptune
e = np.random.random(n_comets)*0.009 + 0.1
inc = np.random.random(n_comets)*np.pi/2.
m=1e-10
r=1e-7

for i in xrange(0,n_comets):
    rand = np.random.random()*2*np.pi
    sim.add(m=m, r=r, a=a[i], e=e[i], inc=inc[i], Omega=0, omega=rand, f=rand)
    
sim.move_to_com()
E0 = sim.calculate_energy()
sim.integrate(tmax)
dE = abs((sim.calculate_energy() - E0)/E0)

print dE
print sim.status()
```
It seems to work fine and the resulting dE is ~1e-13. However when I change the units of the simulation by un-commenting the three lines
```
sim.units = ('AU', 'yr', 'Msun')
tmax = tmax / (2.*np.pi)
sim.dt = dt / (2.*np.pi)
````
which changes the simulation units and re-scales of the time variables, the result is substantially different and dE is ~0.1.

Using whfast instead of hermes and doing the same exercise works fine.

I am wondering if I'm doing something wrong or there is a trouble with hermes?
Thanks.

**Comment by hannorein** [comment]
Thanks for this. I think there could indeed be an issue with units being used together with HERMES. @silburt, you might want to look into this.  It think the reason is that when the mini simulation is created, the `G` variable is not set, but should be set to whatever the global simulation uses.

**Comment by silburt** [comment]
Makes sense to me, we're not currently setting the mini sim to the global sim units. Thanks for pointing this out! I'll try and make the change either tonight or tomorrow morning.

**Comment by silburt** [comment]
jilkoval - do a git pull and give it another try. Let us know if it's still performing strangely. I think we solved the issue.

**Comment by jilkoval** [comment]
Seems to work fine now. Thanks.
