### ISSUE TITLE
Rebound Visualization crashes after upgrade to macos Sierra

### ISSUE THREAD

**Issue by silburt** [hannorein/rebound#231]
After upgrading my mac OS to Sierra, the rebound visualization in C no longer works, and crashes instantly. In my terminal, I get the following error:

 rebound[3341:78820] Metal library creation failed with error: Error Domain=MTLLibraryErrorDomain Code=3 "Compiler encountered an internal error" UserInfo={NSLocalizedDescription=Compiler encountered an internal error}

I've also attached the full bug report. 
[bugreport.txt](https://github.com/hannorein/rebound/files/586501/bugreport.txt)

The other aspects of rebound appear to be functioning normally.

**Comment by hannorein** [comment]
I think the short answer is that GLUT is depreciated and we should move to GLFW.

**Comment by hannorein** [comment]
I think I figured out where this is coming from. OSX does not support running GLUT on the child side of a fork. This worked before, but it was never officially supported. I think the only right thing to do is to move to GLFW as GLUT is not updated anymore. This means, however, that one needs to install GLFW manually as it might not come with the operating system. Unfortunately, nothing else seems to work cross-platform.

**Comment by silburt** [comment]
OK, good to know. I assume GLFW is supported by older osx versions (Mavericks, Yosemite)?

**Comment by hannorein** [comment]
Fixed in latest version.
