### ISSUE TITLE
softening in hermes

### ISSUE THREAD

**Issue by jilkoval** [hannorein/rebound#232]
Is it possible that hermes has a similar problem with sim.softening as in the Issue #229 with sim.G? I am having troubles reproducing results of hermes with ias15 when softening is set to a non-zero value. I can post an example script but perhaps a quick check will help. Thanks!

**Comment by hannorein** [comment]
Yes, I think this is correct. But HERMES resolves close encounters, so I'm surprised you want to use it together with softening. What's the setup?

**Comment by jilkoval** [comment]
Thanks for the quick reply. I understand that hermes switches to ias15 to resolve close encounters. But I expected that the same softening is used in both hermes integrators (whfast and ias15). I am actually testing hermes against an independent direct N-body integrator which uses softening.
So I'd expect the following test to give the same results for hermes and ias15. But that doesn't seem to be the case.
```
import rebound
import numpy as np

sim = rebound.Simulation()
np.random.seed(42)

#integrator options
sim.integrator = "ias15"
#~ sim.integrator = "hermes"
dt = 0.1
sim.dt = dt
sim.testparticle_type = 1
sim.track_energy_offset = 1
sim.softening = 5.0
tmax = 1e3

#massive bodies
sim.add(m=1., r=0.005)                     #sun
a_neptune = 30.05
sim.add(m=5e-5,r=2e-4,a=a_neptune,e=0.01)  #neptune
sim.N_active = sim.N

#semi-active bodies
n_comets = 5
a = np.random.random(n_comets)*10 + a_neptune
e = np.random.random(n_comets)*0.009 + 0.1
inc = np.random.random(n_comets)*np.pi/2.
m=1e-10
r=1e-7

for i in xrange(0,n_comets):
    rand = np.random.random()*2*np.pi
    sim.add(m=m, r=r, a=a[i], e=e[i], inc=inc[i], Omega=0, omega=rand, f=rand)
    
sim.move_to_com()
E0 = sim.calculate_energy()
sim.integrate(tmax)
dE = abs((sim.calculate_energy() - E0)/E0)

print dE
print sim.status()
```

**Comment by hannorein** [comment]
But you typically want to either resolve close encounters or use softening, I don't think it makes sense to use both.

**Comment by jilkoval** [comment]
Indeed, it makes sense. I wanted to compare hermes with an independent integrator (which uses softening) with settings as similar as possible. And therefore the fact that the softening is not passed to ias15 surprised me. But in overall context it makes sense. Thanks for clarifying.

**Comment by hannorein** [comment]
I see. Well, I still think it does not make much sense to use softening and resolve close encounters. But @silburt, you could easily set the softening parameter to the same in the mini simulation. I don't see any harm in that.

**Comment by silburt** [comment]
@jilkoval I added the softening parameter to Hermes so that the mini simulation syncs with the global. Do a git pull and give it another try.

**Comment by jilkoval** [comment]
Thanks! I updated Rebound and tested the above script again. However it is still giving different results for Hermes and IAS15. It seems that setting non-zero softening breaks the energy conservation of IAS15... probably I'm still misunderstanding something more general here.

**Comment by hannorein** [comment]
This is not surprising. The problem  you experience lies in HERMES, not IAS15. The softening is not being used in the reb_integrator_hermes_apply_forces function. I can only repeat myself in that I see little point in adding this when you are already resolving close encounters.

**Comment by jilkoval** [comment]
I see, thanks for the explanation, it is clearer now.
