### ISSUE TITLE
OpenGL and restarting simulations with planetesimal disks

### ISSUE THREAD

**Issue by silburt** [hannorein/rebound#237]
If OpenGL = 1 and I run a simulation (e.g. star, 2 planets), save it as a binary, and then restart the simulation adding a disk of planetesimals, the simulation will crash with the following error message: "Trace/BPT trap: 5"

However, if I conduct the same experiment with OpenGL = 0, everything seems to work no problem. Furthermore, if OpenGL = 1 and I restart the simulation without adding any planetesimals (i.e. start a sim, save as binary, restart sim), things also seem to work without any problems. So I wonder if adding new bodies is not being updated in the OpenGL visualization?

**Comment by hannorein** [comment]
I guess that should be working. But I haven't tried it out much with varying particle numbers.

**Comment by hannorein** [comment]
Hm. I cannot reproduce this. I tried it out with both the WHFast and SEI integrators and it seems to work for me. Can you post a minimal example that shows this issue (remove everything that is not necessary to reproduce this. Thanks!

**Comment by silburt** [comment]
Here's a simple (as I can make it) example which crashes when openGL is enabled but runs fine when it's disabled. Furthermore, it works fine if no planetesimals are added. No arguments to set, just compile and run. Saved it in a zip since github doesn't support .c files. 


[problem_simple.c.zip](https://github.com/hannorein/rebound/files/654977/problem_simple.c.zip)

**Comment by silburt** [comment]
In case it runs fine for you - when I run this with lldb, I get the following output:

librebound.so was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 42792 stopped
* thread #1: tid = 0x3e8eaf, 0x00000001000ab33a librebound.so`reb_display(window=0x0000000100394e20) + 42 at display.c:396, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x74)
    frame #0: 0x00000001000ab33a librebound.so`reb_display(window=0x0000000100394e20) + 42 at display.c:396 [opt]
   393  
   394  static void reb_display(GLFWwindow* window){
   395      struct reb_display_data* data = glfwGetWindowUserPointer(window);
-> 396      if (data->pause){
   397          return;
   398      }
   399      int width, height;

**Comment by hannorein** [comment]
Is that really the **minimal** example? ;-)

The error message looks like a race condition...
