### ISSUE TITLE
difference between introducing orbital parameters by hand or calling JPL

### ISSUE THREAD

**Issue by franpoz** [hannorein/rebound#239]
Why is different the result of the simulation when I introduce the orbital parameters of a comet by hand
than when I introduce them calling the JPL function? Any clue?

For example:

I load the planets, select the units, and the date when I want to start my simulation:

```
sim = rebound.Simulation() 
sim.units = ('day', 'AU', 'Msun')
date = "2016-06-24 05:07"
sim.add("Sun",date=date)
sim.add("Mercury",date=date)
sim.add("Venus",date=date)
sim.add("Earth",date=date)
sim.add("Mars",date=date)
sim.add("Jupiter",date=date)
sim.add("Saturn",date=date)
sim.add("Uranus",date=date)
sim.add("Neptune",date=date)   
```
Now, I introduce two comets: 

```
sim.add("NAME=P/2016 J1-A; CAP",date=date)
sim.add("NAME=P/2016 J1-B; CAP",date=date)
```
Then I start the integration etc.  This procedure give me a different result if I introduce the comets by hand, doing:

```
sim.add(primary=sim.particles[0], a=3.172091853514377, e=0.2282649364694034, inc=np.deg2rad(14.33019388861698), Omega=np.deg2rad(199.8562313234536), omega=np.deg2rad(46.58553660424926), M=np.deg2rad(359.264884189635), date=date,hash='J1-A')
sim.add(primary=sim.particles[0], a=3.17201441284855, e=0.2282306941231177, inc=np.deg2rad(14.33115571581087), Omega=np.deg2rad(199.8555058173028), omega=np.deg2rad(46.57923960945115), M=np.deg2rad(355.7912096053647), date=date,hash='J1-B')
```
Any suggestion about what I doing wrong?

Thank you everybody for your help =)

**Comment by dtamayo** [comment]
Hi Fran,

How did you get the orbital elements you put in by hand? If it was by putting in the orbital elements you get when you print them out with REBOUND after loading with HORIZONS, one problem is that REBOUND by default prints out orbital elements in jacobi coordinates, but when you add them by hand, you are explicitly setting the Sun as the primary (if you don't specify a primary, it will do it in Jacobi coordinates by default also). 

However, even fixing this, when you put in these values by hand, after they're converted to cartesian positions (which is what the code internally keeps track of), you can get a difference in the last bit that will cause the two simulations to diverge over time. To get exactly the same results, you have to use a binary format for starting simulations, and you need to get several details right in the integrator. Hanno and I just submitted a paper about this, and it's already implemented into REBOUND. You can get some more details under ipython_examples/Simulation_archive.ipynb.

**Comment by franpoz** [comment]
Hi Daniel, 

well, to get the elements I went to the JPL web site, and copy them directly from there by hand, e.g.,  http://ssd.jpl.nasa.gov/sbdb.cgi?ID=dK16J01a 

My real aim is to generate clones of this object in order to do a statistical study. Other point that is not clear for me about that is the epoch. When I copy those elements by hand, how can I include the epoch of them?
Regarding the coordinate system, when the integration is done and I print some of the elements to 
see their evolution, for example eccentricity Vs. time, which is the coordinate used?

I did this experiment using Mercury but I find interesting do it also with rebound.

Thank you very for your help! 
best,

fran

**Comment by hannorein** [comment]
I agree with everything Dan has said. If you want to be precise, you need to make sure you understand the coordinate systems used. By default REBOUND uses Jacobi coordinates. Also, have a look at the [orbital elements tutorial](http://rebound.readthedocs.io/en/latest/ipython/OrbitalElements.html).
