### ISSUE TITLE
OpenGL and WebGL Visualization of Simulation Archive snapshots

### ISSUE THREAD

**Issue by gmduvvuri** [hannorein/rebound#245]
If you have a saved binary Simulation Archive, would it be possible to create OpenGL visualizations that move through snapshots in the C version of REBOUND and/or similar WebGL visualizations in the python implementation? I see no convenient way to do either except for simply integrating all over again.

**Comment by dtamayo** [comment]
Like you said, the simulationarchive only holds snapshots, so if you're interested in frames between those snapshots I think you have to integrate again. The nice thing about the simulationarchive though, is that this second time through you can do the integrations from each snapshot in parallel, so a week-long integration can be done in a few minutes given enough cores.

That said, in the "astronomy" case where you're integrating for a good chunk of time, for reasonable simulationarchive sizes, your snapshots are always many orbits apart, so you're never going to see smooth Keplerian motion. For this case, where you're just interested in seeing the long-term evolution, I would think it would be good enough to make a movie from just the snapshots.

**Comment by hannorein** [comment]
Here is a code snipped that does what you are asking for. I think you raise a good point. We should implement a nicer way to use the widget with the Simulation Archive. 

```
sa = rebound.SimulationArchive("restart.bin")
sim0 = sa[0]
sim0.getWidget()
for s in sa:
    sim0.refreshWidgets()
```
