### ISSUE TITLE
whfast stalls when exact_finish_time==1

### ISSUE THREAD

**Issue by silburt** [hannorein/rebound#246]
I've been trying to get outputs of some specific timestamps using whfast, but the integrator appears to stall. I can make it stall for a couple of different examples, but attached I've constructed a specific simple example that stalls on my computer.

I *think* that it's coming from the fact that whfast is trying to integrate to a specific time and having trouble getting to that exact timestamp. If I set exact_finish_time = 0, the integration will complete no problem. 

[whfast_stall.ipynb.zip](https://github.com/hannorein/rebound/files/736387/whfast_stall.ipynb.zip)

**Comment by hannorein** [comment]
Minimal example, reproducing the issue. Note that this is not related to WHFast. Also note that the timestep is almost exactly equal to the output interval. 


```
import rebound
import numpy as np
sim = rebound.Simulation()
sim.integrator = "leapfrog"
sim.dt = 2*np.pi* 0.64108339**(1.5) / 31.
sim.add(m=0.92)
times = np.linspace(0,60,600)
exact_finish_time = 1
for t in times:
    print(t, sim.dt)
    sim.integrate(t, exact_finish_time)
```

**Comment by silburt** [comment]
Yes, I agree that it's not specific to WHFast. I also noticed that it stalls when trying different integrators too. In the future, I'll try and simplify my problem even more...

**Comment by hannorein** [comment]
See alos #485
