### ISSUE TITLE
Simulating Rubble Piles: Rotation and Orbits

### ISSUE THREAD

**Issue by gmduvvuri** [hannorein/rebound#251]
I am trying to use REBOUND to model the tidal disruption of an asteroid orbiting a white dwarf by approximating it as a rubble pile. Two issues I am running into are that:

If I want a particle in the rubble pile to rotate, I need to add a tangential acceleration relative to the center of the asteroid, along with a jerk that keeps that acceleration rotating. I cannot initialize particles with an acceleration or jerk, and cannot edit the source code accordingly.

Additionally, the way REBOUND calculates orbits with the WHFAST integrator, an individual particle's path is determined by its orbit around the white dwarf primary first, then interactions with other rubble pile particles. This leads to interpreting the particle as inclined, giving it a path that separates the pile in a manner entirely unassociated with the tidal forces. An OrbitPlot is attached for reference.
![test_3d](https://cloud.githubusercontent.com/assets/12900670/23249434/5c48e1ac-f972-11e6-87c4-162aa96e94a1.png)

Would another integrator solve this problem, or should I find some other simulation code (like PKDGRAV2) to handle my use case?

**Comment by hannorein** [comment]
In short, REBOUND is not the right code to simulate a rubble pile in a global simulation. If it is a weakly bound pile of small N and you work in the shearing sheet, this can work (e.g. for moonless in Saturn's rings), but for a global simulation like you have set up, there are many issues.

**Comment by hannorein** [comment]
Julien Frouard, Alice Quillen, and collaborators have done some amazing work on this topic!

https://academic.oup.com/mnras/article/458/3/2890/2589321
