### ISSUE TITLE
CL_INVALID_WORK_GROUP_SIZE (error -34) using gravity_opencl.c

### ISSUE THREAD

**Issue by glaville** [hannorein/rebound#26]
Hello

When I try to run the provided examples/opencl problem on our graphic hardware, the program always crash during the first thirty seconds of simulated time with the following error message:

> N_tot=  4096      t=  21.540000  cpu=  0.077756 [s]  
> Line No: 221 clEnqueueNDRangeKernel failed.
>    Error= -54

This errors usually indicates that the choosen work group (local) size is either invalid, or not a divider of the global work size. However, after adding some printf debugging to gravity_opencl.c, these size are always fixed to 32 and 4096 for all iterations.

Is this a known problem? If I try to indicate an automatic local size, by replacing &local_size in the source with NULL, the computation does not crash anymore, but runs much more slowly (about 1sec/timestep). Changing the work group size to 64 or 128 does not prevent the crash from ocurring, either.

PS : I modified the makefile a bit to enable compilation on Linux systems (export LIB=-lOpenCL). At the moment, this is only a hack, but I would be interested in submitting patches for Linux and Xeon Phi support, since I have the opportunity to test on these platforms.

**Comment by hannorein** [comment]
Then OpenCL Gravity routine is not working in the latest release, so I'll close this for now.
