### ISSUE TITLE
handling close encounters in python

### ISSUE THREAD

**Issue by birnstiel** [hannorein/rebound#260]
I was following the 'CloseEncounters' IPython notebook. In the last code cell, the collision detection depends on particle radius and the `collision_resolve` is set to 'merge' which automatically merges the particles.

According to the python API, `collision_resolve` can be set to `'merge'`, `'harsphere'` (a typo by the way) or to a function pointer. I wanted to write my own (python) function, but failed to find a reference. I only found the C-code where this function gets a simulation and a collision object as arguments, but failed to  implement that in python. Can this be done in python without using `sim.exit_min_distance` (which is only a fixed value, not dependent on the particle radii)?

I also tried to make the `collision_resolve` function throw an Encounter error and then handle it as in the 'CloseEncounter' notebook, but that just keeps throwing exceptions.

**Comment by hannorein** [comment]
I totally agree that the documentation could be better here! Here is a short example of how to do this in python:

https://gist.github.com/hannorein/a50499c0498992d1d2e85b0b9bbaf870

Keep in mind that if you have a lot of collisions, this might be slow and you might want to implement it in C. If there are few collisions, then python should work fine.

**Comment by birnstiel** [comment]
Thanks, Hanno, that solves it. I guess you can close this. If you don't mind me abusing this issue as a support forum: is there way to write this function in C but still use the convenient python interface? Or would I have to write the entire simulation in C then?

**Comment by hannorein** [comment]
Have a look at this example:

https://gist.github.com/hannorein/9b86177199cdadddc7a0c8af00b2e678

It's for an additional face, rather than a collision resolve function, but the basic setup is very similar, you just need to change the function header to receive one simulation struct and one collision struct.

I hope that helps.
