### ISSUE TITLE
No collisions detected using collision_tree module

### ISSUE THREAD

**Issue by Fatys** [hannorein/rebound#264]
Hi,
I've discovered REBOUND quite recently and I'm still getting to know its capabilities, so my apologies if this a stupid/elementary question. The problem I'm dealing with are collisions of test particles using the REB_COLLISION_TREE module. Ones its on, no collisions are detected (or the collision_resolve function is not called). Using the provided example "closeencounter_record" and using collision_direct module works fine, however switching to collision_tree gives no collisions. I've tried different combinations of gravity solvers, integrators and boundary conditions with no luck. Have I missed some parameters that need to be set (I've tried setting reb_configure_box, boxsize_max and opening_angle2) or is the problem somewhere else? I'm using version 3.3.1. Thanks for any reply. Petr

**Comment by hannorein** [comment]
Hi Petr! Do you initialize the tree before you add particle? If you do it the other way round, particles will not be added to the tree. Otherwise, maybe you can post a short example snipped of your code that runs and shows the problem?

**Comment by Fatys** [comment]
Ok, that was the problem. Now it works beautifully. Thank you!
