### ISSUE TITLE
Linking to glfw3

### ISSUE THREAD

**Issue by shangfei** [hannorein/rebound#265]
I installed glfw3 on my Mac with homebrew, and none of the aliases to the dynamic library is called libglfw3.dylib under my /usr/local/lib/. So I have to create an alias by myself.  

I am not sure whether this is common. If it is, maybe one should change "-lglfw3" in line 31 of Makefile.defs to "-lglfw"

**Comment by hannorein** [comment]
This is strange. For me it is called 'libglfw3.dylib'. But your are not the first person having this issue. Not sure what changed.

**Comment by shangfei** [comment]
For your reference, after installing glfw3, I have libglfw.3.2.dylib, libglfw.3.dylib and libglfw.dylib under /usr/local/lib/.

**Comment by hannorein** [comment]
Just uninstalled and reinstalled `glfw3` with homebrew. Now the library is called exactly what you have. So maybe they changed something? 

On an even stranger note, the previous version that got installed with homebrew was 3.3.1. Now it is 3.2. Very confusing.

**Comment by rieder** [comment]
In macports, it's also called glfw without the 3.

**Comment by shangfei** [comment]
That's weird...

**Comment by hannorein** [comment]
Changed it to glfw with b0747c0a. This seem to be the right thing to do for now... Let's see if anyone complains.
