### ISSUE TITLE
Energy Conservation in PrimordialEarth Example

### ISSUE THREAD

**Issue by birnstiel** [hannorein/rebound#271]
Running the `PrimordialEarth.ipynb`, I end up with a value of 

    dE = 1.3695294592446784e-05

Instead of something of the order of 1e-10. I'm using `rebound 3.4.0`.

**Comment by hannorein** [comment]
Yes, the HERMES integrator is still in development. Things have been and still will be changing until we publish the paper...

**Comment by hannorein** [comment]
The energy error is now much better in this example using the MERCURIUS integrator.
