### ISSUE TITLE
error when using visualization in C

### ISSUE THREAD

**Issue by silburt** [hannorein/rebound#272]
I just recently synced rebound to the master branch, and now when I try and compile rebound with OPENGL=1, I get:
ld: library not found for -lglfw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [librebound.so] Error 1
make: *** [librebound] Error 2

Rebound runs normally when OPENGL=0. I'm not sure if there's some missing package I now need, or what else might be the problem. Reverting to older versions of rebound, the visualization works fine.

**Comment by hannorein** [comment]
Make sure you've ran `make clean`. If it still doesn't work uninstall glfw, then reinstall it (I assume you're using homebrew).

**Comment by silburt** [comment]
Yes, reinstalling glfw via homebrew this solved the problem.
