### ISSUE TITLE
Can not seem to get examples working

### ISSUE THREAD

**Issue by lordpeano** [hannorein/rebound#279]
For example, I started with simplest in C.  The documentation indicates it would be something like 
Also, I am using Fedora 25 x84_64 KDE.

From first page of the documentation in Rebound.

make && ./rebound problem.c 
------------------------------------------------------
The result is as follows:
---------------------------------
Compiling shared library librebound.so ...
make -C ../../src/
make[1]: Entering directory '/home/harry/Rebound352/rebound-master/src'
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Compiling source file display.c ...
cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -Wall -g -Wno-unknown-pragmas -fPIC -DLIBREBOUND -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o display.o display.c
display.c:50:24: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
                        ^
compilation terminated.

**Comment by hannorein** [comment]
If you want the visualization you need to install `glfw`. Alternatively you can turn off OpenGL by setting `OPENGL=0` in the Makefile. Are also [here](https://github.com/hannorein/rebound/blob/master/doc/c_quickstart.rst#possible-issues-when-compiling-rebound).

Let me know if that helps.

**Comment by hannorein** [comment]
Also, you compile the code with `make`, you then run it with `./rebound`.

**Comment by hannorein** [comment]
For reference in case someone else is reading this: 

Make sure you have `glfw` installed. The package is called `libglfw3` on Debian like distributions. You'll also need the development files in the package `libglfw3-dev`.
