### ISSUE TITLE
examples link to glfw but only show console output

### ISSUE THREAD

**Issue by chriscamacho** [hannorein/rebound#281]
I can't see what I'm doing wrong? running make compiles cleanly showing no error messages not even at run time

I'm using Linux and have compiled and run my own code using glfw which runs just fine...

**Comment by hannorein** [comment]
I do not have an easy answer. You can try to install the newest version of GLFW. Also note that there is some confusion with to which library to link against: lglfw or lgflw3. Sorry for not being able to help more. I'm not an expert with GLFW and have not found a systematic way to get this working on all operating systems with all different versions of GLFW. If you find a solution that works for you, please post it here so people can find it.

**Comment by chriscamacho** [comment]
sorry I didn't realise that you needed to explicitly compile the library with OPENGL=1 assuming it was the same as the examples....

That said doesn't work with my intel broadwell hd5500 gpu, when I reduced the shader version so the shaders would compile, I then got a seg fault in the integrator, at which point I called it a loss...
