### ISSUE TITLE
typo in ipython example CloseEncounters

### ISSUE THREAD

**Issue by jilkoval** [hannorein/rebound#282]
I think there is a typo in the ipython example [CloseEncounters](https://github.com/hannorein/rebound/blob/master/ipython_examples/CloseEncounters.ipynb). In the function `mergeParticles` particle col_i1 is removed twice, while particle col_i2 should be removed as well:
```
...
mergedPlanet.m  = sum_mass
sim.remove(index=col_i1) 
sim.remove(index=col_i1)  # should be sim.remove(index=col_i2) ?
sim.add(mergedPlanet, assignHash=True)
...
```

**Comment by dtamayo** [comment]
Hi Lucie,

It's actually not a typo, because when you remove index 1, index 2 moves down to index 1, so you need to remove index 1 again. I admit that's a bit confusing, so I've changed it so it's 

sim.remove(index=col_i2) 
sim.remove(index=col_i1)

which has the right behavior. Thanks!

**Comment by jilkoval** [comment]
Ah, I see. Thanks for the clarification!
