### ISSUE TITLE
Python Examples Problems

### ISSUE THREAD

**Issue by lordpeano** [hannorein/rebound#285]
I an not sure what distros others are using, my choice is FedoIre.  However, my favourite version has moved from X11 to Wayland.  I would expect more of the Fedora distos will move the same direction.   I am presently using Fedora 25 Astro Spin.

I should note that I at best python newbie.  I upgraded to Rebound 3.5.2 and Python 3.6.1.  I have found is that the python_examples only work with python 2, & 2.7.  For python3 and 3.5 "import rebound" 
cannot be found.

I have not figured out how to get the right "rebound" to be imported.

**Comment by hannorein** [comment]
You're mixing up multiple issues here. You can use REBOUND from C or from python. Only the C version has the OpenGL visualization. The python version works with both python 2 and 3. Python packages installed for one version of python will not work for another. You need to install them twice.

**Comment by lordpeano** [comment]
This is an example of what I was talking about.   I used the simple_orbit in the python_examples.

[root@localhost simple_orbit]# python2 problem.py 
<rebound.Orbit instance, a=1.0 e=0.1 inc=0.0 Omega=0.0 omega=0.0 f=0.0>
<rebound.Orbit instance, a=1.4 e=0.1 inc=0.0 Omega=0.0 omega=0.0 f=0.0>
<rebound.Orbit instance, a=1.0 e=0.1 inc=0.0 Omega=0.0 omega=0.0 f=0.0>
<rebound.Orbit instance, a=1.40802691143 e=0.104492186431 inc=0.0 Omega=0.0 omega=0.0 f=0.0>
<rebound.Particle object, m=1.0 x=0.0 y=0.0 z=0.0 vx=0.0 vy=0.0 vz=0.0>
<rebound.Particle object, m=0.001 x=0.9 y=0.0 z=0.0 vx=0.0 vy=1.10609422946 vz=0.0>
<rebound.Particle object, m=0.0 x=1.2608991009 y=0.0 z=0.0 vx=0.0 vy=0.935925233399 vz=0.0>

[root@localhost simple_orbit]# python3 problem.py 
Traceback (most recent call last):
  File "problem.py", line 2, in <module>
    import rebound
ModuleNotFoundError: No module named 'rebound'

**Comment by hannorein** [comment]
I understand. You have to install rebound for python3. I cannot tell you how that works on your system, try something like `pip3 install rebound`. Side note: running this as root is in general not considered a good idea. It's easy to mess things up that can only be fixed by reinstalling everything from scratch.

**Comment by lordpeano** [comment]
python3 is installed.  This is from the bin 
wxrwxrwx. 1 root root     7 May 10 16:05 python -> python2
lrwxrwxrwx. 1 root root     9 May 10 16:05 python2 -> python2.7
-rwxr-xr-x. 1 root root  7096 May 10 16:05 python2.7
-rwxr-xr-x. 1 root root  1846 May 10 16:05 python2.7-config
lrwxrwxrwx. 1 root root    16 May 10 16:05 python2-config -> python2.7-config
lrwxrwxrwx. 1 root root     9 May 10 11:07 python3 -> python3.5
lrwxrwxrwx. 1 root root     8 May 10 11:07 python3-2to3 -> 2to3-3.5
-rwxr-xr-x. 2 root root 11224 May 10 11:08 python3.5
lrwxrwxrwx. 1 root root    17 May 10 11:07 python3.5-config -> python3.5m-config
-rwxr-xr-x. 2 root root 11224 May 10 11:08 python3.5m
-rwxr-xr-x. 1 root root   173 May 10 11:08 python3.5m-config
-rwxr-xr-x. 1 root root  3535 May 10 10:37 python3.5m-x86_64-config
-rwxr-xr-x. 1 root root   308 Jul 27  2016 python3-chardetect
lrwxrwxrwx. 1 root root    16 May 10 11:07 python3-config -> python3.5-config
-rwxr-xr-x. 1 root root   307 May 19 11:01 python3-coverage
-rwxr-xr-x. 1 root root 11709 Jul 25  2016 python3-isympy
-rwxr-xr-x. 1 root root   307 Jul 19  2016 python3-pyflakes
-rwxr-xr-x. 1 root root   312 Sep 20  2016 python3-pyinotify
lrwxrwxrwx. 1 root root    14 May 10 16:05 python-config -> python2-config

----------------------------------------------------------------
Also I have installed the Rebound-3.5.2

[root@localhost rebound-3.5.2]# ll
total 80
-rwxrwx---. 1 harry harry 35147 Nov 16  2016 LICENSE
-rwxrwx---. 1 harry harry  1224 Jun  1 13:01 MANIFEST.in
-rwxrwx---. 1 harry harry  5569 Jun  9 10:10 PKG-INFO
-rwxrwx---. 1 harry harry  4129 Jun  9 10:10 README.rst
drwxrwx---. 3 harry harry  4096 Jun  9 10:10 rebound
drwxrwx---. 2 harry harry  4096 Jun  9 10:10 rebound.egg-info
-rwxrwx---. 1 harry harry    38 Jun  9 10:10 setup.cfg
-rwxrwx---. 1 harry harry  4003 Jun  9 10:10 setup.py
drwxrwx---. 2 harry harry  4096 Jun  9 10:10 src
-rwxrwx---. 1 harry harry     6 Jun  9 10:09 version.txt

**Comment by hannorein** [comment]
Please read my reply again. You need to install rebound for every version of python you have installed. If you have python2 and python3, you need to install rebound twice!

**Comment by lordpeano** [comment]
I am not sure.  The instruction is Rebound-3.5.2 is to  " pip  install rebound".  This appears to make things work.

**Comment by lordpeano** [comment]
Sorry there is still problem. Yes the 'pip install rebound" worked for python2 and python3.   However, it didn't stay that way.
  
Situation:
I put a new folder with some of the python examples into a folder.  As an example, I copied to simple orbit example program.py to the new folder as simple_orbit.py.  I added the information for the missing planets.

python2 simple_orbit.py   worked
python3 simple_orbit.py   failed with "import rebound"    I tried to reset python3 with rebound with no luck.

**Comment by hannorein** [comment]
I'm sorry, I'll close this issue for now. This is really not a rebound issue. Have a look at how to install python packages in general. There are many different ways. Some people like the virtualenv framework to make it work with different python versions. Others prefer some distribution like anaconda.
