### ISSUE TITLE
Issue while using OpenMP with active bodies

### ISSUE THREAD

**Issue by dipto4** [hannorein/rebound#288]
Hi,
I was running a simulation with the sun, 4 giant planets and a disk of 1000 particles with mass and of `testparticle_type=1`. I set the sun and the four giant planets as active bodies and the others as test bodies. I was also using the IAS15 integrator with the basic gravity solver. However, when I ran the code using OpenMP using more than one thread, I did not notice a speedup. Is this expected?

**Comment by hannorein** [comment]
I think you should see a speedup. Can you post a short code snipped with the setup?

**Comment by dipto4** [comment]
Yeah sure! Here's the code that I am using.
```
    struct reb_simulation* const r = reb_create_simulation();

    float x[] = {5.05754531007,2.9413595645,-2.20069139194,-6.99803313213};
    float y[] = {-1.97131335053,7.35153022672,14.1069680611,8.32612016222};
    float z[] = {6.68434988152e-05,-0.000238638848542,0.000394766236412,0.000642407359181};
    float vx[] = {0.996289038105,-2.09949173744,-1.64191100063,-1.433090601};
    float vy[] = {2.5128627937,0.821489602051,-0.227846319468,-1.26688016317};
    float vz[] = {-6.97680509415e-08,8.42652728169e-05,3.48841051199e-05,-4.04508184914e-05};
    float m[] = {0.000954791938424,0.000285885980666,4.36624404335e-05,5.15138902047e-05};

    float radius[] = {0.000752718737538,0.000623704148279,0.000271228451342,0.000259070275142};

    r->G = 39.4769264214; 
    r->integrator = REB_INTEGRATOR_IAS15;
    r->gravity = REB_GRAVITY_BASIC;
    r->boundary = REB_BOUNDARY_NONE;
    r->collision_resolve_keep_sorted = 1;
    r->testparticle_type = 1;

    //solar system with planets and sun

    struct reb_particle sun = {0};
    sun.m = 1.0;
    sun.r = 0.00464913034382;
    sun.x = -0.00525322858041;
    sun.y = -0.00125333636188;
    sun.z = -4.59274920142e-08;
    sun.vx = -0.000206226456182;
    sun.vy = -0.00256095841771;
    sun.vz = -6.97680509415e-08;

    reb_add(r, sun);
    int j = 0;
    for (j=0;j<4;j++) {
        struct reb_particle planet = {0};
        planet.m = m[j];
        planet.r = radius[j]; 
        planet.x = x[j] ;
        planet.y = y[j] ;
        planet.z = z[j] ;
        planet.vx = vx[j]; 
        planet.vy = vy[j] ;
        planet.vz = vz[j];

        reb_add(r,planet);
    }
    r->N_active = r->N;
    //seeding random number generator
    time_t t;
    srand(time(&t));

    float disk_start = 16;
    float disk_end = 35;
    float pi = 3.14159265358979;
    for(int k =0;k<1000;k++) {
        struct reb_particle disk_particle = {0};
        float rnum = ((float) rand())/((float) RAND_MAX);
        float theta=rnum*2*pi;
        float semi_major = rnum*(disk_end-disk_start) + disk_start;
        disk_particle = reb_tools_orbit_to_particle(r->G,sun,9.54638698389e-08,semi_major,0.0,0.0,0.0,0.0,theta);

        disk_particle.r = 3.342e-6;
        reb_add(r,disk_particle);

    }

    reb_move_to_com(r);

    reb_output_binary(r , "data/data0.in");
    int t_0 = 0;
    int t_final = 30e6;
	
    int i = 0;
    char filename[50];    
    while (t_0 < t_final) {
		t_0+=1000;
		reb_integrate(r,t_0);
                printf("%i \n",i++);
                sprintf(filename, "data/data%d.in",i);
                reb_output_binary(r,filename);
	}

    reb_free_simulation(r);

```
I was running this using openMP with 4 threads. I did not notice a speedup.

**Comment by hannorein** [comment]
I can reproduce what you're finding. I do see a speedup for more particles. So you might still be in the limit of a small number of particles. I need to think about what is the bottleneck there...

**Comment by dipto4** [comment]
Just out of curiosity, how many particles did you need to observe a speedup? Also, are there any other methods to improve performance in rebound? 
Thanks a lot!

**Comment by hannorein** [comment]
I saw a 50% speedup with 1000 particles. For this kind of setup, you could look into the MERCURIUS integrator.

**Comment by dipto4** [comment]
Did you mean 10000 particles? I was using 1000 particles and it did not give me a speedup.
Thanks!

**Comment by hannorein** [comment]
Sorry, yes 10 times more.

**Comment by dipto4** [comment]
One more question: how many threads were you using when you got the 50% speedup?

**Comment by hannorein** [comment]
4

**Comment by hdevillepoix** [comment]
My issue is somewhat related:
I want to integrate ~10,000 pure test particles in a solar system that contains 10 massive particles.
The massive particles are ordered in sma. The test particles are not ordered in any particular way, and move around quite a lot since they are near planet crossing orbits.

I want speed and I am not too concerned about accuracy, so I am using WHFAST with a 4 day timestep.

I plugged my code into the OpenMP speed-up test example, integrated for 1000 years, and got:
`OpenMP speed-up: 1.437x (perfect scaling would give 24x)`

Also tried with limiting to 4 cores, to see if this is a case where the problem is too small for 24 cores:
`OpenMP speed-up: 1.328x (perfect scaling would give 4x)`
So it doesn't seem to be a too few particles issue.

Should I expect a better speed-up?
Maybe I am not using the best integrator for the job?

**Comment by hannorein** [comment]
That should be faster. Let me investigate. Just to confirm and get a good comparison, your 10 massive particles are Sun, Mercury -> Pluto?

**Comment by hdevillepoix** [comment]
Sun, Mercury -> Neptune + Moon.
I need the Moon at the beginning of the integration (integrating meteoroids that collided with the Earth, so I use the IAS15 integrator to resolve the pre-impact close encounter, and then switch to WHFAST). I don't need the Moon once that's done so I should probably merge it with the Earth. But I did the same speed-up tests after removing the Moon and got very similar results.

**Comment by hannorein** [comment]
Ok. Thanks. I think you're doing the right thing, but just to be absolutely unambiguous: WHFast cannot handle the Moon because it's a hierarchical system.

**Comment by hannorein** [comment]
There seem to be several issues creating this slowdown.

1) No matter what I do not get any speedup on OSX with the homebrew gcc-6 compiler. I can't figure out why. The threads get created but there seems to be a mutex lock blocking the other threads from doing any work.
2) On linux, I do get a speedup. 
3) WHFast was not optimized to handle the kind of simulation you asked about. I'm pushing an update in a little while which should work and allow you to have a significant speedup.

If anyone know what is going on with gcc's OpenMP implementation on Mac OSX, I'd be curious to find out!

**Comment by hdevillepoix** [comment]
Hmm interesting that the same compiler gives different behaviours on Linux and OSX. The speed-up numbers above were using a Cray compiler on Linux, but I was getting similar stuff with GCC.

Thanks so much for your help! :)

**Comment by hannorein** [comment]
Ok. Just pushed a new version. Try that out. Note that you want to work in democratic heliocentric coordinates (Jacobi coordinates are ordered but that doesn't make much sense for all the test particles). See this new example:

https://github.com/hannorein/rebound/blob/master/examples/solar_system_with_testparticles/problem.c#L25

Let me know if this helps!

**Comment by hdevillepoix** [comment]
That definitely helped quite a lot, speed-up jumped from 1.4x to 3.4x.
That's great, thanks!
I'm guessing the bottleneck is now somewhere else, because it only gets to 3.5x speed-up when using 10x more particles (1e5).

**Comment by hannorein** [comment]
Great! Yes, I'd need to do some profiling to see where the bottleneck is now...
