### ISSUE TITLE
Question: variation wrt to central mass?

### ISSUE THREAD

**Issue by dfm** [hannorein/rebound#289]
Hi team, This is a question so I'm not sure if this is the right place to ask. Happy to close if another venue is better.

I've been playing around with the C API to compute gradients of TTV models and everything is working well so far. Thanks for everything that you've done here! One thing that I haven't been able to work out (perhaps because I'm just being thick and don't fully understand what is going on): is it easy to compute the derivatives with respect to changes in the central mass? In other words, I'm interested in how the position and velocity would change with the mass of the central (as well as the reference orbital elements of the planet).

Thanks again!

**Comment by hannorein** [comment]
Good question! If you only have Newtonian gravity and there is no other force (which might set a scale for the problem), then this derivative is degenerate because gravity is scale invariant. So changing the central mass is the same as changing all the planet masses and the semi-major axes in the appropriate way. You can just use the chain rule to get the answer. Although admittedly I have not done the math myself. Fingers crossed it's not too messy.

**Comment by dfm** [comment]
Great. Yes - I haven't worked it through yet either, but I did manage to convince myself that I can do it. Thanks!

Another related question: The other thing that I need to compute is the gradient of the central's final coordinates with respect to the orbital elements of the planets. Do you have a quick tip for how to do this with the existing interface? Thanks again!

**Comment by hannorein** [comment]
I'm not sure I understand the question correctly. That would just be the standard way of using the variational equations. From the examples:

 ```
    sim = rebound.Simulation()
    sim.add(m=1.)
    sim.add(primary=sim.particles[0],m=1e-3, a=1)
    sim.add(primary=sim.particles[0],m=1e-3, a=a)
    var_da = sim.add_variation()
    var_dda = sim.add_variation(order=2, first_order=var_da)
    var_da.vary(2, "a")
    var_dda.vary(2, "a")

    sim.integrate(2.*np.pi*10.)
    print(sim.particles[1].x, var_da.particles[1].x, var_dda.particles[1].x)
```

On the last line, you can print out the derivatives of any coordinate of any particle. Let me know if this answers the question or if I misunderstood!

**Comment by dfm** [comment]
I see! I was confused about how the C API worked for the variational inference. The following seems to work, please let me know if I'm still off base. If I have a simulation with a star (added first) and two planets and I want to get the gradients with respect to the semi-major axis of the first planet, I would do something like:

```c
int var_i = reb_add_var_1st_order(r, -1);
r->particles[var_i+1] = reb_derivatives_a(1., r->particles[0], r->particles[1]);
reb_integrate(r, dt);
```

Then `r->particles[var_i]` would have the gradient for the star, `r->particles[var_i+1]` would have the gradients for the first planet, etc.

This means that when I do `r->particles[var_i+1] = reb_derivatives_a(1., r->particles[0], r->particles[1]);` it *knows* that the gradient is wrt to the second particle and fills in the variational particles on either side? This seems to give exactly what I want.

Thanks and sorry for the confusion!

**Comment by hannorein** [comment]
Ah, I didn't know you're using C. Yes to all your questions. 

These derivates can be confusing, especially at second order. We tried to come up with a somewhat reasonably intuitive API, but there is probably room for improvements. So don't hesitate to ask again if anything is unclear! I'm glad you're finding it useful!

**Comment by hannorein** [comment]
Just one more clarification:

> it knows that the gradient is wrt to the second particle and fills in the variational particles on either side?

By default all the variational particles are initialized to 0. With the function call 

`   r->particles[var_i+1] = reb_derivatives_a(1., r->particles[0], r->particles[1]);
`

You're setting the initial conditions corresponding to changing the second particle's semi-major axis. This only affects the second variational particle's coordinates, as it should: i.e. if you change the planet's semi-major axis at t=0, the star will not move at all.

**Comment by dfm** [comment]
Totally. I get it! I'm still wrapping my head around the right terminology. Thanks!
