### ISSUE TITLE
Restricted two body problem

### ISSUE THREAD

**Issue by AnnabellaMondino** [hannorein/rebound#292]
I want to simulate a massless particle around a massive body using IAS15/WHFAST.

First, I integrated the system and I obtained a non-uniform nor non-sinusoidal eccentricity value for massless particle.
After that, I added a second massive body (but keeping N_Active = 1) and the resulting time evolution for the eccentricity depends on the mass of this secondary one.

I do not know what is the problem.

Thanks in advance for your help.

**Comment by hannorein** [comment]
Hm. Can you post a short snippet of your code?

**Comment by AnnabellaMondino** [comment]
Hi,

Here I send you the problem.c file.

Best regards,
Annabella

-----------------------------------------------------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include "rebound.h"

const double J2planet            = 0; //16298e-6;     // J2 of Saturn
(Murray and Dermott p 531)
const double Mplanet            = 0.00028588598;     // mass of Saturn in
solar masses
const double ObliquityPlanet        = 0.;            // obliquity of the
planet
const double uam                  = 149597870700.0;    // ua in meters
const double Rplanet            = 0.000402866696684875; // radius of Saturn
in AU
const double k                = 0.01720209895;    // Gaussian constant
const double tmax            = 10005.8;        // Maximum integration time
//days
const double rad                  = M_PI/180.0;        // ua in meters
double n, ro, rhill;


void heartbeat(struct reb_simulation* r);
void force_J2(struct reb_simulation* r);

int main(int argc, char* argv[]){
    struct reb_simulation* r = reb_create_simulation();
    // Setup constants
    r->integrator            = REB_INTEGRATOR_IAS15;//WHFAST
    r->N_active            = 1;
        r->G                = k*k;
        r->exact_finish_time = 1;
    r->testparticle_type = 0;

    // Planet
    struct reb_particle planet = {0};
    planet.m  = Mplanet;
    reb_add(r, planet);

    // Massive Secondary Particle
    double a = 1.365055e+8/uam;
    double e   = 0.0000331;// Jacobson 2008
    double inc = 0.0;
    double Omega = 0;
    double pomega= 0;
    double omega  = (pomega-Omega)*M_PI/180;
    double lambda = 0;
    double f = (lambda-pomega) + 2* e *sin(lambda-pomega);
        double m  = 0.077e15/1.9891e30;

    struct reb_particle p = reb_tools_orbit_to_particle(r->G, planet, m, a,
e, inc, Omega, omega, f);
    //printf("%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\n",a, e, inc,
Omega, omega, f,m,planet.m);
    //printf("%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\n",p.x,p.y,
p.z, p.vx, p.vy, p.vz,p.m,planet.m);
    p.hash = 1;
    reb_add(r, p);

    // Additional
    ro    = p.x;
        rhill    = a * pow(p.m/(3.*(planet.m+p.m)),1./3.);// Hill radius
    if (rhill==0) {
      rhill = a *
pow(0.077e15/1.9891e30/(3.*(planet.m+0.077e15/1.9891e30)),1./3.);
    }

    n =sqrt(r->G*(p.m+Mplanet)/a/a/a);

    r->dt     = 0.001;// initial timestep
        double boxsize     = rhill;

    reb_configure_box(r, boxsize, 16, 400, 1);
    const struct reb_vec3d box = r->boxsize;


    // Massles Particle (whose orbital elements I want to analyse)
    a = 1.365055e+8/uam;
    e   = 0.0000331;
    inc = 0.0;
    Omega = 0;
    pomega= 0;
    omega  = (pomega-Omega)*M_PI/180;
    lambda = 0;
    f = (lambda-pomega) + 2* e *sin(lambda-pomega);
        m  = 0.;

    p = reb_tools_orbit_to_particle(r->G, planet, m, a, e, inc, Omega,
omega, f);
    //printf("%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\n",a, e, inc,
Omega, omega, f,m,planet.m);
    //printf("%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\t%.7e\n",p.x,p.y,
p.z, p.vx, p.vy, p.vz,p.m,planet.m);
    p.hash = 2;
    reb_add(r, p);


    reb_move_to_com(r);

    system("rm  elements.txt"); // delete previous output

    // Setup callback functions
    r->heartbeat         = heartbeat;
    r->additional_forces     = force_J2;

    reb_integrate(r, tmax);
}



void force_J2(struct reb_simulation* r){
    if (J2planet==0) return;
    // Star
    const struct reb_particle planet = r->particles[0]; // cache
    const int N = r->N;
#pragma omp parallel for
    for (int i=1;i<N;i++){
        const struct reb_particle p = r->particles[i];     // cache
        const double sprx = p.x-planet.x;
        const double spry = p.y-planet.y;
        const double sprz = p.z-planet.z;
        const double prx  = sprx*cos(-ObliquityPlanet) +
sprz*sin(-ObliquityPlanet);
        const double pry  = spry;
        const double prz  =-sprx*sin(-ObliquityPlanet) +
sprz*cos(-ObliquityPlanet);
        const double pr2  = prx*prx + pry*pry + prz*prz;
        const double fac  =
3.*r->G*J2planet*planet.m*Rplanet*Rplanet/2./pow(pr2,3.5);

        const double pax  = fac*prx*(prx*prx + pry*pry - 4.*prz*prz);
        const double pay  = fac*pry*(prx*prx + pry*pry - 4.*prz*prz);
        const double paz  = fac*prz*(3.*(prx*prx + pry*pry) - 2.*prz*prz);

        r->particles[i].ax -= pax*cos(ObliquityPlanet) +
paz*sin(ObliquityPlanet);
        r->particles[i].ay -= pay;
        r->particles[i].az -=-pax*sin(ObliquityPlanet) +
paz*cos(ObliquityPlanet);
    }
}


void heartbeat(struct reb_simulation* r){
    if(reb_output_check(r,0.1e0)){    // output file

        FILE* f = fopen("elements.txt","a");

        // Read Planet
        const struct reb_particle planet = r->particles[0];
        const int N = r->N;
        double x,y,z,xp,yp,zp,phi1;
        fprintf(f,"\n\n");

        // Write Massive Secondary Particle orbital elements
        struct reb_orbit o = reb_tools_particle_to_orbit(r->G,
r->particles[1],planet);

         fprintf(f,"%.15e\t%d\t%.15e\t%.15e\t%.15e\t%.15e\t%.15e\n",

r->t,r->particles[1].hash,o.a,o.e,o.inc,o.omega,r->particles[1].z);

        // Write Massless Particle orbital elements
        for (int i=2;i<N;i++){
            struct reb_orbit o = reb_tools_particle_to_orbit(r->G,
r->particles[i],planet);

             fprintf(f,"%.15e\t%d\t%.15e\t%.15e\t%.15e\t%.15e\t%.15e\n",

r->t,r->particles[2].hash,o.a,o.e,o.inc,o.omega,r->particles[1].z);
        }

        fclose(f);
    }
}

2017-08-17 21:43 GMT-03:00 Hanno Rein <notifications@github.com>:

**Comment by hannorein** [comment]
I don't see any obvious issues, but your code is very hard to read. Try to keep it as short as possible when posting it here. Cut out everything except if it is needed to reproduce the issue. 

Note that if you give a mass to the test-particle, and then move to the COM, things might depend on the mass of the particle. Again, try to cut out everything that is not needed. Often this helps a lot to find the problem.
