### ISSUE TITLE
The influence of Noutputs choice on the simulation

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#293]
Dear all, 

I'm surprise about the fact that same simulations, with the only difference in the Noutputs value, return very differents solutions.

I notice when I started to follow the example about 67P (python). Then, I decided to change somethings (just for fun) and extend further the back integration, until -10000yrs. I tried with Noutputs=10000 and Noutputs=1000. Atached are the plots:

Nouputs=1000
![dynamic_1000](https://user-images.githubusercontent.com/29211450/29710437-9070b69a-8990-11e7-9e92-bd7adb741c81.png)

Nouputs=10000
![dynamic_10000](https://user-images.githubusercontent.com/29211450/29710482-bf4c0e06-8990-11e7-8d73-40bb7585af0f.png)

The integrations seems to have the same behaviour until -2000 yrs, after that point everything is different. 

Any idea why does it happen?

Thank you very much to all! =)

Mileva

**Comment by hannorein** [comment]
The system is chaotic. Small differences in the initial conditions lead to big changes after a finite time. 

`sim.integrate(time)` is integrating the system exactly to the time you request. In the two examples `time` will be different and therefore REBOUND will choose different timesteps to get there. The differences are very small, 1e-16, after one timestep, but grow very quickly. 

One way to get the same result in both cases is to replace `sim.integrate(time)` with `sim.integrate(time, exact_finish_time=0)`.

I hope this helps.

**Comment by MilevaE** [comment]
Hi Hanno, 

thank you very much for your reply. Yes, I tried with your suggestion and works perfect. Attached plots:

Noutputs=1000
![dynamic_1000](https://user-images.githubusercontent.com/29211450/29720958-c4a05c6a-89bb-11e7-91cc-ac1303e96ec7.png)

Noutputs=10000
![dynamic_10000](https://user-images.githubusercontent.com/29211450/29720944-bc14880a-89bb-11e7-8d69-63e6f646c5ff.png)


I was expecting the same result for both integration since the only different between them was Noutput, which I interpreted just as a snapshot of the system. But it seems that takes an important role during the integration process, as you mentioned. 

Thank you very much for your help! =)

Cheers, 

Mileva

**Comment by hannorein** [comment]
Glad it worked!

**Comment by MilevaE** [comment]
Hi again, 

sorry to bother again, but I'm confuse about the coordinates when the integration is finished..I mean,
I know that by default REBOUND prints out orbital elements in Jacobi coordinates. Thus, that means that my above plots (semi-major axis, eccentricities etc Versus time) are not referred to the central body? I directly save them from the simulation doing: 

```
for i,timex in enumerate(times):
    sim.integrate(timex,exact_finish_time=0)
    x[0][i] = ps[5].x   
    y[0][i] = ps[5].y
    z[0][i] = ps[5].z
    x[1][i] = ps[9].x
    y[1][i] = ps[9].y
    z[1][i] = ps[9].z
    e[0][i] = ps[5].e
    a[0][i] = ps[5].a
    e[1][i] = ps[9].e
    a[1][i] = ps[9].a
    inc[1][i] = ps[9].inc
    omega[1][i]=ps[9].omega
    Omega[1][i]=ps[9].Omega


np.save("xjupiter_past",x[0])
np.save("yjupiter_past",y[0])
np.save("zjupiter_past",z[0])
np.save("y41_past",y[1])
np.save("x41_past",x[1])
np.save("z41_past",z[1])
np.save("ejupiter_past",e[0])
np.save("ajupiter_past",a[0])
np.save("e41_past",e[1])
np.save("a41_past",a[1])
np.save("inc41_past",inc[1])
np.save("Omega41_past",Omega[1])
np.save("omega41_small_past",omega[1])  
```

Sorry, I'm a bit struggle after read the orbital elements tutorial

**Comment by hannorein** [comment]
Yes, by default you get the orbital elements in Jacobi coordinates. Most of the mass in the Solar System is in the Sun, so these are almost the same as if you use heliocentric coordinates.

**Comment by MilevaE** [comment]
Hi Hanno, 

thanks for the clarification. Then, in order to obtain, strictly speaking, the orbital elements referred to the heliocentric distance I should do something like: 

```
for i,timex in enumerate(times):
    sim.integrate(timex,exact_finish_time=0)
    x[0][i] = ps[5].x   
    y[0][i] = ps[5].y
    z[0][i] = ps[5].z
    x[1][i] = ps[9].x
    y[1][i] = ps[9].y
    z[1][i] = ps[9].z
    e[0][i] = ps[5].calculate_orbit(primary=sim.particles[0]).e
    a[0][i] = ps[5].calculate_orbit(primary=sim.particles[0]).a
    e[1][i] = ps[9].calculate_orbit(primary=sim.particles[0]).e
    a[1][i] = ps[9].calculate_orbit(primary=sim.particles[0]).a
    inc[1][i] = ps[9].calculate_orbit(primary=sim.particles[0]).inc
    omega[1][i]=ps[9].calculate_orbit(primary=sim.particles[0]).omega
    Omega[1][i]=ps[9].calculate_orbit(primary=sim.particles[0]).Omega
```

is that correct? At least, the results are the same than previous code, what I interpreted as your explanation about most of the mass in the Solar System is in the Sun. 

Thanks for all your help and patience =)

Cheers, 

Mileva

**Comment by hannorein** [comment]
Correct!

**Comment by MilevaE** [comment]
Thanks!! =)
