### ISSUE TITLE
OpenGL Visualization on Linux

### ISSUE THREAD

**Issue by freeksdjhfgh** [hannorein/rebound#296]
May I know which linux distro and which version are you exactly using to test your codes? The C version OpenGL visualization runs very smoothly on my Macbook however on my Ubuntu based desktop PC it is not working. I have no problem compiling the file and running it in terminal, but it turns out that the frame rate is about 1 per 10 secs in the simulation, like powerpoint. I have tried to reinstall libglfw3-dev and even compiled the package directly from the source, but problem persisted. Are there any solutions? Many Thanks.

**Comment by hannorein** [comment]
Does it run faster if you turn off the visualization? If so, you are probably running a software renderer.

**Comment by freeksdjhfgh** [comment]
Do you mean by changing OpenGL = 1 to 0 in the makefile? I did so and the computation speed did not change. Actually the terminal side works perfectly fine. Just the pop-out visualization window hangs there without synchronizing. 

If it is caused by the software renderer, are there any ways to switch to the hardware accelerated one? Cheers.

**Comment by hannorein** [comment]
If the terminal version is fine (i.e. not slow), then the issue is somewhere related to OpenGL. But I'm afraid, I cannot provide any specific help. This depends on the combination of graphic card/linux version/opengl version/distribution. There are infinitely many combinations and potential problems. Try running some other standard OpenGL programs and games and see how the performance compares there.

**Comment by freeksdjhfgh** [comment]
I have ran glmark2, an OpenGL benchmark test and it worked very well. To explore the parameter space of the possible cause to this problem, I have installed Fedora/Ubuntu and tested both Intel/nVidia with/without the third party driver. Probably I am going to test it on my AMD card and install Debian but I suspected there will be no difference. It seems the problem lies within the buffer allocation or synchronizing with the refreshing rate, yet I have no idea of how to change that. 

Anyway thank you so much for you help and this fantastic code.

**Comment by hannorein** [comment]
I'm sorry that I can't help more. I don't have a desktop linux machine and can only test it either in a virtual machine or via the network. Both of these work, but I cannot make any claims about speed. Sorry for not being able to help more!
