### ISSUE TITLE
Possible integrator bug?

### ISSUE THREAD

**Issue by jacobfleisig** [hannorein/rebound#298]
Hello,

I am trying to run some code that has previously run with no issues.  However, it now seems as if the simulation is choking on the first time step.  The simulation runs, but returns no data or binary files.  I believe this is due to its failure to integrate one whole time step.  In short, I believe it cannot even reach one heartbeat, so any code I have written to be run every heartbeat is not being executed.

Thank you for any help you can give!  Attached are my Makefile and simulation file.

-Jake
[Makefile.pdf](https://github.com/hannorein/rebound/files/1334923/Makefile.pdf)
[mass_test.c.pdf](https://github.com/hannorein/rebound/files/1334922/mass_test.c.pdf)

**Comment by hannorein** [comment]
Hi Jake! Hm. It's really hard to debug it this way. Can you strip everything out of your code that does not relate to the problem itself (e.g. the save function). Really try to make it as short as possible. This might even help you narrow down the problem yourself. If it persists, please post the code here inside the comment (not as a pdf file, I cannot run that myself). 

Cheers!

**Comment by jacobfleisig** [comment]
Hello,

I have gutted everything except my routine to output sim progress to the screen once every orbital period. The screen will not output anything and I believe the problem is still persisting. Here is my code:

```
// Integrates a disk of eccentric particles
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <math.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <omp.h>
#include "rebound.h"

// initiate variables
void heartbeat(struct reb_simulation* r);
double tmax;
double orbit_time;
double orbit_counter;
double save_counter;
int num_saves_per_orbit;

int main(int argc,char* argv[]) {
	struct reb_simulation* r = reb_create_simulation();

	// setup constants
	r->G = 1;
	r->integrator = REB_INTEGRATOR_IAS15;
	r->heartbeat = heartbeat;
	r->dt = 1e-7;
	orbit_counter = 0.;
	num_saves_per_orbit = 1;
	orbit_time = 2.0*M_PI;
	
	// define scales
	double mass_scale =1.;
	double a_scale = 1.;
	
	// add a star	
	struct reb_particle star = {0};
	star.m = mass_scale;
	star.hash = reb_hash("The Sun");
	reb_add(r,star);
	
	// create orbital parameters and orbiting objects
	double n_particles = 10;
	double m_disk = 1e-3;
	
	for(int i=0;i<n_particles;i++){
		double m = mass_scale*m_disk*(1.0/n_particles);   
		double a = reb_random_uniform(0.9,1.1);         
		double e = 0.7;         
		double Omega = reb_random_uniform(0,2.*M_PI); // range from 0-2pi
		double omega = reb_random_uniform(0,2.*M_PI); // range from 0-2pi
		double mean_anom = reb_random_uniform(0,2.*M_PI);
		double f = reb_tools_M_to_f(e,mean_anom);
		double inc = 1e-4;
		
		struct reb_particle KBO = reb_tools_orbit_to_particle(r->G,star,m,a,e,inc,Omega,omega,f);
		KBO.hash = i;
		reb_add(r,KBO);
	}
	reb_move_to_com(r);
	
	// time info and command to integrate
	tmax = 4000*2.0*M_PI*sqrt(a_scale*a_scale*a_scale/mass_scale);
	reb_integrate(r,tmax);
	// ------------------
	printf("\n");
}

// output sim data for all orbiting particles
void heartbeat(struct reb_simulation* r){
	double last_dt = r->dt_last_done;
	orbit_counter += last_dt;
	save_counter += last_dt;	
	if ((orbit_counter>= orbit_time/num_saves_per_orbit) || (orbit_counter ==0.)) {
		// print progress to the screen		
		reb_output_timing(r,tmax);
	}	
}
```

**Comment by hannorein** [comment]
Thanks! That's much easier. I tried it out and it works for me. In fact it runs very smoothly. Try running`make clean` and `make`.

<img width="683" alt="screen shot 2017-09-26 at 9 44 12 pm" src="https://user-images.githubusercontent.com/53376/30891951-e823758a-a303-11e7-8702-490c5ff5ac27.png">

**Comment by jacobfleisig** [comment]
I have cleaned the directory and recompiled, but still no luck.  Very unusual that its not running on my machine.

**Comment by dtamayo** [comment]
A quick way to test whether you’ve changed anything that would cause problems might be to clone the repository in a new directory and try it there.

**Comment by jacobfleisig** [comment]
Tried that, still no luck. The code I'm running is identical to what I just gave you.  Is it possible that the rebound repository is not up to date?

**Comment by hannorein** [comment]
Are you using the one from GitHub? That should be up-to-date.

**Comment by hannorein** [comment]
No need to delete it. Just clone it in a different directory.

**Comment by hannorein** [comment]
Hm. Then I'm really not sure what could be the issue. @dtamayo, can you quickly try to run it on your computer? Shouldn't take more than a minute... Thanks!

**Comment by dtamayo** [comment]
Sorry for the delay, was stuck in the CITA jamboree! I just tried it on my computer and it runs fine too. Just to be explicit, I copied one of the example directories from rebound/examples to rebound/problems/ (in order to be at the right directory level and have the right Makefile) and then I replaced the contents of problem.c with your code.

**Comment by hannorein** [comment]
Jake, I'm sorry, but unless I can reproduce the error, I can't really help. What operating system and compiler are you using?

**Comment by jacobfleisig** [comment]
Everything is good now! I was using an outdated rebound.h file.  I had dragged it to my present working directory, which is why it did not update.  Thank you!

**Comment by hannorein** [comment]
Glad it got resolved!
