### ISSUE TITLE
colision and merged particles

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#299]
Dear all, 

I was wondering if exist in Rebound or Reboundx any tool to simulate the formation of the planets, through the collision of small particles (or protoplanets). I see some papers about it, and I found very interesting. Taking a look about the modules already available I don't see anything in particular with this purpose. However, I see that there is the some examples of collisional and merged planets...

Thanks all for your suggestions =)

best, 

Mileva

**Comment by hannorein** [comment]
Hi Mileva, 

Yes, you can do that with rebound. There are a couple of examples with colliding particles. You can write your own collision resolving routine if you want. Let me know if you have a specific question.

Hanno

**Comment by MilevaE** [comment]
Hi Hanno, 

sorry to bother again with this issue. Recently I've read some papers, using for example MERCURY, where authors perform a track of the water content of the planetesimals to evaluate the final fraction of water on the formed planets after all the collisions. 
Something like this plot (form Raymond et al. 2004):

![raymond2004](https://user-images.githubusercontent.com/29211450/36164147-c6f3407e-10eb-11e8-9e1b-f77829fec137.png)


I don't find on then any clue to know how do they track of water content during the collisions. 

Thus, my question is it would be possible to do it with Rebound?  

Thanks a lot for your help, 

best, 

MilevaE

**Comment by dtamayo** [comment]
Hi Mileva,

This is not implemented in REBOUND, but it would be straightforward to add additional parameters to particles with REBOUNDx and update water contents according to whatever prescription you like during collisions.

**Comment by MilevaE** [comment]
Hi Dani, 

I don't see very well how to do it. I'm going to check the available examples in Reboundx to see if there is something similar that help me to understand how to do it. 
Thanks for your reply =)

Best, 

MilevaE

**Comment by dtamayo** [comment]
REBOUNDx allows you to do things like

    sim.particles[1].params["water_content"] = 0.3

and later access it. So if you caught collisions in try/except blocks, e.g.

    try:
        sim.integrate(tmax)
    except rebound.Collision as e:
        # custom routine for how to update particles and their water contents

see the close encounters example in REBOUND

**Comment by MilevaE** [comment]
Thanks!! =D

**Comment by MilevaE** [comment]
Hi all, 
coming back to this problem, I don't understand how can I know which particles have collided during the simulation. Is there any function that allows me figure out this?

Thanks in advance for all your help! 
:)

**Comment by dtamayo** [comment]
This example shows how to do it. Probably the method at the bottom of the notebook will be most useful:

https://github.com/hannorein/rebound/blob/master/ipython_examples/CloseEncounters.ipynb

**Comment by MilevaE** [comment]
Hi Dani, 

indeed, super-useful example! thanks!
