### ISSUE TITLE
Can not install rebound 

### ISSUE THREAD

**Issue by juanorion1** [hannorein/rebound#304]
Hi,

I have some troubles installing REBOUND in my computer with Ubuntu.  
I tried doing:
sudo pip install rebound
then the terminal shows this message:

The directory '/home/juanorion1/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

then I tried doing:
sudo -H pip install rebound
then this  message shows in terminal:
Requirement already satisfied: rebound in /usr/local/lib/python3.4/dist-packages

I tried doing in ipython:
import rebound
then shows a message:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-86ef2706db59> in <module>()
----> 1 import rebound

ImportError: No module named rebound

Thanks so much for your help and sorry for my english.

Regards

**Comment by hannorein** [comment]
You seem to have issues with how your permissions are set. Note that you do not need to use superuser privileges to install rebound. The easiest way is to use a virtual python environment (virtualenv). 

    virtualenv venv  
    source ./venv/bin/activate
    pip install rebound

**Comment by juanorion1** [comment]
Thanks for answer my question so quick. I'll try this and see what happen.
