### ISSUE TITLE
Dynamically control the step parameter of IAS15

### ISSUE THREAD

**Issue by freeksdjhfgh** [hannorein/rebound#312]
Hi I am currently using IAS15 to simulate the evolution of a simple two body star-system. The semi-major axis of the system is supposed to decrease under tidal circularisation. Realising that the number of the calculations per checking time increases almost exponentially, is there any ways I can dynamically control the time step so as to finish the simulation within finite time? Thank you so much.

**Comment by hannorein** [comment]
When using IAS15, you cannot manually set the timestep. Increasing it just by a factor of a few would give you an error of order unity. I'm not sure I understand what you mean by "Realising that the number of the calculations per checking time increases almost exponentially". The timestep should always be a few % of the orbital period. However, if your system is not collisional, consider using a symplectic integrator such as WHFast. That should be faster by about an order of magnitude for moderate errors (1e-8).

**Comment by freeksdjhfgh** [comment]
Thanks for your comment. From what I observed the number of steps remains almost as a constant, and the exponentially increasing steps are due to the continuous decrease of the semi-major axis(thus exponentially increasing number of periods within the same simulation time dt). Given the fact that the computing power is saturated, the computing time required for the same dt increases exponentially. I think maybe other integrators will also face the same problem because it is physical. Anyway I will try to search for other possible methods and if you have some insights, please keep me posted. Many thanks.

**Comment by hannorein** [comment]
Yes, if the planet's period gets smaller, the timestep needs to get smaller too.
