### ISSUE TITLE
What is the Proper Way of Adding S-Type Planets in Binary Systems

### ISSUE THREAD

**Issue by ketozhang** [hannorein/rebound#313]
From this [iPython Example](https://rebound.readthedocs.io/en/latest/ipython/OrbitalElements.html) it is clear that there is an issue if you do the following:

```Python
import rebound
sim = rebound.Simulation()
sim.add(m=1., x=1., vz = 2.) #Star A
sim.add(m=1., a=1.) #Star B
sim.add(m=1.e-3, a=2.) #Planet ABb,  changed semi-major to scale graph better
sim.add(primary=sim.particles[1], a=0.01) #Test mass Bb, 
sim.status()

sim.move_to_com()
rebound.OrbitPlot(sim)
```

```
---------------------------------
REBOUND version:     	3.5.10
REBOUND built on:    	Nov 26 2017 21:40:38
Number of particles: 	4
Selected integrator: 	ias15
Simulation time:     	0.0000000000000000e+00
Current timestep:    	0.001000
---------------------------------
<rebound.Particle object, m=1.0 x=1.0 y=0.0 z=0.0 vx=0.0 vy=0.0 vz=2.0>
<rebound.Particle object, m=1.0 x=2.0 y=0.0 z=0.0 vx=0.0 vy=1.4142135623730951 vz=2.0>
<rebound.Particle object, m=0.001 x=3.5 y=0.0 z=0.0 vx=0.0 vy=1.7073567499443576 vz=2.0>
<rebound.Particle object, m=0.0 x=2.01 y=0.0 z=0.0 vx=0.0 vy=11.414213562373096 vz=2.0>
---------------------------------
```
![image](https://user-images.githubusercontent.com/13506487/33263207-d06cde6e-d31d-11e7-9fc6-a075332203b7.png)

The test mass is plotted incorrectly using `rebound.OrbitPlot` resulting an extremely eccentric orbit for Bb. The example suggest the order (B, Bb, A, ABb) which works for this case but not others. For example if I want to add another S-type orbits (e.g., A, Ab, B, Bb, ABb).

What is the general way do this?

**Comment by dtamayo** [comment]
Hi Keto, because OrbitPlot is plotting osculating orbits, I don't think there's a generic way to introduce logic that gives the right results in all cases. After version 3.5.10 it's straightforward to customize the plots yourself though. I have updated ipython_examples/OrbitPlot.ipynb to show how to do that in the section on advanced plotting at the bottom:

https://github.com/dtamayo/rebound/blob/03119fc29de4bf1a857cffc074f072642d08e5ad/ipython_examples/OrbitPlot.ipynb

Hope that helps

**Comment by hannorein** [comment]
Dan is right, there is no generic way of always giving the _right_ outcome. It will always involve some human insight into which body is orbiting which other body. The orbits plotted are instantaneous and not real particle trails (the real particle trails would not close). Dan's example shows nicely how to work around this manually. I'll close this issue for now, but feel free to reopen it if anything is unclear.

**Comment by ketozhang** [comment]
Great thank you!

Only question I have is how to plot the trails with the primary being the barycenter for both stars. For example a binary with very similar mass. Unfortunately there is no particle instance for the barycenter.

For example the ability to plot this:
![image](https://user-images.githubusercontent.com/13506487/33300553-e5a3bcf2-d3a5-11e7-8614-7ecc7e4121ee.png)

**Comment by dtamayo** [comment]
Yeah for that you need to get the conversion back to inertial coordinates from the reduced mass right, and account for the fact that calculate_orbit and sample_orbit are giving you Jacobi positions (relative to the 0 index particle) so you have to remove that offset. I think (but you should double check!) that this is correct:

```
sim = rebound.Simulation()
sim.add(m=1.) #Star A
sim.add(m=0.2, a=1., e=0.8) #Star B
sim.move_to_com()

import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots(figsize=(8,8))
ps = sim.particles

lim = 2 
ax.set_xlim([-lim, lim])
ax.set_ylim([-lim, lim])

linewidth=1.
for star in ps[:2]:
    ax.scatter(star.x, star.y, s=35*linewidth, marker='*', facecolor='black', zorder=3)

from rebound.plotting import fading_line

M0 = ps[0].m
M1 = ps[1].m

o = M0/(M0+M1)*(np.array(ps[1].sample_orbit())-ps[0].xyz)
lc = fading_line(o[:,0], o[:,1], linewidth=linewidth)
ax.add_collection(lc)

o = M1/(M0+M1)*(-np.array(ps[1].sample_orbit())+ps[0].xyz)
lc = fading_line(o[:,0], o[:,1], linewidth=linewidth)
ax.add_collection(lc)
```

![unknown-1](https://user-images.githubusercontent.com/3408023/33301270-e8c1f300-d3c2-11e7-9981-64664450295d.png)
