### ISSUE TITLE
Compile error in MPI example

### ISSUE THREAD

**Issue by ridlo** [hannorein/rebound#316]
I try to compile the MPI example, but found this kind of error, is it the configuration error or something else? What is "git" in here?
```
Compiling shared library librebound.so ...
make -C ../../src/
make[1]: Entering directory '/home/ridlo/rebound-master/src'
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Compiling source file rebound.c ...
mpicc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -Wall -g -Wno-unknown-pragmas -fPIC -DLIBREBOUND -DMPI -DGITHASH=0000000000gitnotfound0000000000000000000 -o rebound.o rebound.c
rebound.c: In function ‘reb_integrate_raw’:
rebound.c:658:48: error: ‘r’ undeclared (first use in this function)
     reb_communication_mpi_distribute_particles(r);
                                                ^
rebound.c:658:48: note: each undeclared identifier is reported only once for each function it appears in
Makefile:12: recipe for target 'rebound.o' failed
make[1]: *** [rebound.o] Error 1
make[1]: Leaving directory '/home/ridlo/rebound-master/src'
Makefile:14: recipe for target 'librebound' failed
make: *** [librebound] Error 2

```

**Comment by hannorein** [comment]
Not sure about the git message. The compile scripts use git to store the current hash in the binary. This allows you to find out which precise version of rebound was used to create an output file.

I do not have an answer about the MPI function that is missing without digging into it myself. I have not used the MPI functions in a long time (I just didn't have a need to). What is your use case? Are you sure MPI will help you (in many cases it will not)?

**Comment by ridlo** [comment]
Ok, I'm just curious, I try the example in /examples/selfgravity_disc_mpi and shearing_sheet_mpi and found that error. I actually also don't need MPI for now. :)

Thank you, I will just leave it here.

**Comment by hannorein** [comment]
Alright. I might close the issue then. I really can't find a very good use case for MPI. On a fast modern CPUs one can use 24 threads or so. If that's not enough, then going to MPI might help, but only for very large simulations. And it opens a can of worms. There are probably other more specialized codes that can handle these situations better.

**Comment by jcldc** [comment]
Hi,
I wanted to test MPI test case as ridlo did and I get exactly the same error compilation.
After digging in rebound.c code, this error makes sense. Indeed r variable is not declared before it's called in reb_communication_mpi_distribute_particles(r);

here is a snippet of the code :
```
655     struct reb_thread_info* thread_info = (struct reb_thread_info*)args;
656 #ifdef MPI
657     // Distribute particles
658     reb_communication_mpi_distribute_particles(r);
659 #endif // MPI
660     struct reb_simulation* const r = thread_info->r;
```
as we can see, **r** variable is declared in line 660 whereas **r** is used before at line 658 (if MPI is activated). This is why we get compilation error !
