### ISSUE TITLE
Error in running examples

### ISSUE THREAD

**Issue by HimanshuGiriaJain** [hannorein/rebound#317]
I tried git init and pasting the GLFW directory containing glfw3.h file also but still these errors:

fatal: Not a git repository (or any of the parent directories): .git
make[1]: Entering directory `/home/igcl/Desktop/REBOUND_WINTER_2017/hannorein-rebound-ebf9357/src'
Compiling source file display.c ...
cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -Wall -g -Wno-unknown-pragmas -fPIC -DLIBREBOUND -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o display.o display.c
display.c:50:24: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
                        ^
compilation terminated.
make[1]: *** [display.o] Error 1
make[1]: Leaving directory `/home/igcl/Desktop/REBOUND_WINTER_2017/hannorein-rebound-ebf9357/src'
make: *** [librebound] Error 2
igcl@igcl-Vostro-3900:~/Desktop/REBOUND_WINTER_2017/hannorein-rebound-ebf9357/examples/solar_system$

**Comment by hannorein** [comment]
Hm. The compiler can't find the GLFW files. What operating system are you using and how did you install GLFW? Also, have a look at these general tips related to GLFW in the documentation: http://rebound.readthedocs.io/en/latest/c_quickstart.html#possible-issues-when-compiling-rebound
