### ISSUE TITLE
Pesky Error and Close Encounter Question

### ISSUE THREAD

**Issue by czb5535** [hannorein/rebound#318]
Good afternoon,

I would like to first express my appreciation of rebound as it has made my research straightforward and swift.  It is truly a great software.  I have been using rebound (python version) to simulate potential terrestrial planet migrations in the early solar system for my undergraduate research.

First, a close encounter question.  My initial approach to catch close encounters was to go through the simulation archive with a bit of code that calculates the distance between all pairs of bodies and prints a message if that distance is less than a set trigger value.  This works, however, it does not catch all encounters from what I understand.  Since the archive is updated in intervals (1e4 years in my case) it only calculates the distances at those intervals, rather than throughout the simulation itself.  Is there a way to catch these possible encounters while the simulation runs?  I am using the following collision setup:

sim.collision = "direct"
sim.collision_resolve = "merge"
sim.exit_min_distnace = 0.1 #just for example

Further, could you explain 'sim.exit_min_distance', I am slightly confused as to how this works. 

Secondly, a pesky error that continues to rear its head.  When I run my simulations I sometimes get the error: 'Primary has no mass'.  Sometimes this occurs immediately, other times into the integration, and other times not at all.  I have no guess as to the source of this error and recognize no pattern to its occurrence.  Recently it has been occurring more than not, however, the simulations I am running now are setup identical (but with a few numbers changed) to the previous ones.  A generic version is below (imports left out):

dirname = "migration"+datetime.datetime.now().strftime("%y-%m-%d-%H-%M")
os.mkdir(dirname)
shutil.copy2("readmigration_2.py",dirname)
shutil.copy2("runmigration.py",dirname)
os.chdir(dirname)
filename = "simulationarchive.bin"

try: #open existing data file 
    sim = rebound.Simulation.from_archive(filename)
    sim.simulationarchive_filename = filename
    print("Restarting from simulation archive. Last snapshot found at t=%.1f"%sim.t)
except: 
    # Create new simualtion
    print("Creating new simulation.")
    sim = rebound.Simulation()
    sim.add(m=1,r=4.64e-3) # Sun
    sim.add(m=1.66e-7,r=1.62647e-6, a=0.3871, e=0.2056, inc=math.radians(7.004)) # Mercury
    sim.add(m=2.445e-6,r=4.0345e-5, a=0.7233, e=0.0068, inc=math.radians(3.394)) # Venus
    sim.add(m=3.0e-6,r=4.252e-5,a=1, e=0.0167) # Earth
    sim.add(m=3.22e-7,r=2.64133e-6, primary=sim.particles[2], a=0.0032363636, M=np.pi)
    # Mars like planet as a satellite of Venus
    sim.add(m=1/1047.355,r=4.7661e-4,a=5.2, e=0.0483, inc=math.radians(1.3)) # Jupiter
    sim.add(m=1/3501.6,r=4.01787e-4, a=9.5388, e=0.0560, inc=math.radians(2.488)) # Saturn
    sim.add(m=1/22869.,r=1.70393e-4,a=19.1914, e=0.0461, inc=math.radians(0.774)) # Uranus
    sim.add(m=1/19314.,r=1.65093e-4,a=30.0611, e=0.0097, inc=math.radians(1.774)) # Neptune
    sim.initSimulationArchive(filename, interval=1e4)

sim.collision = "direct"
sim.collision_resolve = "merge"
sim.exit_min_distnace = 0.1
sim.move_to_com()

sim.integrate(1e7) # 10Myr 

I then go through the archive and extract data.  It is when I run this bit of code I get the error. 
Interestingly, if I include the encounter detector I mentioned above I register collisions between all particles in the simulation and the sun.   I am certain the error does not lie within the code I use to read from the archive.  There have been runs where I will read a simulation archive while the simulation still runs (to see how things are going) and not get the error, but, when I go to read it a while later, I get the error.   This tells me that the error must occur at some time into running the above code.

Thanks you for the great software and your time.

**Comment by dtamayo** [comment]
Hi there,

You are right that you are not catching all the encounters if you check every 1e4 time units. You need to use the tools you mentioned, but

sim.collision = "direct"
sim.collision_resolve = "merge"

and 

sim.exit_min_distance = 0.1 #just for example

are different ways of doing similar things. The first will merge particles whenever they get within p1.r + p2.r from one another.

The second raises an exception whenever any pair of particles gets within 0.1 from one another.

The issue with the weird errors is probably coming from the fact that you can't use simulationarchives when the number of particles is changing through the simulation (see the list of caveats in the ipython_examples).

**Comment by czb5535** [comment]
Thank you that helps.

I was mainly interested in encounters as I suspect there will be no collisions.  Is there a built in method to detect close encounters in "real time" during the integration?  If not, is there anything in the docs you could refer me to that may help?

In the event there are no collisions, is there anything else that could cause the error?  Moreover, sometimes the error happens immediately when no time has passed for there have been a collision to change the number of particles.

**Comment by dtamayo** [comment]
sim.collision_resolve is just a function pointer, so a quick hack is to write your own python function, 

```
def my_collision(reb_sim, reb_col):
    sim = reb_sim.contents
    col = reb_col.contents
    
    # Do stuff
    print(col.p1, col.p2) # will print the indices of the two particles
    return 0

sim.collision_resolve = my_collision
```

The underlying C code expects a function that's passed a (C) simulation and collision structure, so the first two lines in the python function give you a python object from the ctypes object. You can then access them to do whatever you want below. You should then return 0 to indicate you don't want to remove either of the particles.

Hanno and I have talked about implementing a more user-friendly option, but this should work for now.

Not sure about your error. It sounds most likely like something in your setup. I believe the primary has no mass error comes from orbit conversion routines so some time must have passed to the point where you're calculating orbital elements (unless it's occurring when you initialize your simulation?). Hopefully that helps you narrow it down!

**Comment by hannorein** [comment]
See the new feature in version 3.5.11 that provides a nice way to do this. An example is given at the bottom of https://github.com/hannorein/rebound/blob/master/ipython_examples/CloseEncounters.ipynb
