### ISSUE TITLE
integrator 'bs' rebound

### ISSUE THREAD

**Issue by pemanpardo** [hannorein/rebound#324]
I am trying to use the integrator 'bs' in rebound (python) but when I tried it, I got a error that this integrator is not find it, Is this integrator no more available? I check in the API documentation and they say that it is.

**Comment by hannorein** [comment]
It is no longer available. Depending on your setup, I recommend using the IAS15 or mercurius integrator instead. I'll close this issue for now, but feel free to reopen if you have questions as to qhich integrator to choose.
