### ISSUE TITLE
possible bug in megno ?

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#325]
Hi guys, 

running the MEGNO algorithm I have obtained negative values.. it is the first time I see, I searched 
for information but I don’t find anything. Thus, could it be a bug? or in fact it could have any physical meaning? 

thanks in advance! 

MilevaE

**Comment by hannorein** [comment]
The MEGNO is calculated using a linear least square fit to fit a line to the Y(t) function (see MEGNO papers). The slope can be a negative number if the function oscillates.

**Comment by MilevaE** [comment]
Ok, I see. So, it would be also a chaotic nature, right? 

thanks a lot Hanno =)

**Comment by hannorein** [comment]
Ideally run a set of many simulations and make a parameter space map. Looking at just one realization is hard to interpret. If you want, you could look at the Y(t) function and see how it behaves (see again the MEGNO papers for some examples). You might also want to integrate for longer.

**Comment by MilevaE** [comment]
ok, thanks for all the suggestions!
