### ISSUE TITLE
Tracking Relative Distances of Particles

### ISSUE THREAD

**Issue by jkahn96** [hannorein/rebound#326]
I am attempting to simulate a system with multiple planets.  I would like to use the rebound.Encounter and rebound.Escape features to stop the system integration when a planet is within a certain distance from each other as well as when a planet escapes the system at a certain distance from the system.  In the ipython example, the example only works for a 3-body system; 1 sun and 2 planets.  I have attempted to modify it for greater than two planets in the system.  However, the distances that have been computed every time step are not satisfying the close encounter distance I have set, and I am having trouble understanding what particularly has been going wrong. Also, is there a more efficient way to do this so that the simulation doesn't calculate the orbital parameters every step, but rather at different times steps instead?  I keep running into a runtime error. 

```
import rebound 
import numpy as np
import math

#set up simulation
sim = rebound.Simulation()
sim.add(m=1.)
sim.add(m=1e-3,a=1.)
sim.add(m=5e-3,a=1.25)
sim.add(m=5e-3,a=1.5)
sim.add(m=5e-3,a=2)
sim.integrator= "whfast" # whfast integrator
sim.dt = .012 #set time step

print("Initial Configuration:")
sim.status()

sim = setupSimulation() # Resets everything
sim.exit_min_distance = 0.2
sim.exit_max_distance = 2.5

Noutputs = 2
torb = 2. * np.pi
times = np.linspace(0,5.*torb,Noutputs)
distances1 = np.zeros(Noutputs)
distances2 = np.zeros(Noutputs)
distances3 = np.zeros(Noutputs)
distances4 = np.zeros(Noutputs)

ps = sim.particles # ps is now an array of pointers. It will update as the simulation runs.

try:
    for i,time in enumerate(times):
        sim.integrate(time)
        dp1 = ps[1] - ps[2]
        print("dp1 :", dp1)
        dp2 = ps[2] - ps[3]
        print("dp2 :", dp2)
        dp3 = ps[3] - ps[4]
        print("dp3 :", dp3)
        #dp4 = ps[4] - ps[5]
        distances1[i] = np.sqrt(dp1.x*dp1.x+dp1.y*dp1.y+dp1.z*dp1.z)
        print("distance1 :", distances1[i])
        distances2[i] = np.sqrt(dp2.x*dp2.x+dp2.y*dp2.y+dp2.z*dp2.z)
        print("distance2 :",distances2[i])
        distances3[i] = np.sqrt(dp3.x*dp3.x+dp3.y*dp3.y+dp3.z*dp3.z)
        print("distance3 :",distances3[i])
        #distances4[i] = np.sqrt(dp4.x*dp4.x+dp4.y*dp4.y+dp4.z*dp4.z) #receive index out of range with this pair 
    print("No close encounters or escaping particles detected")
except (rebound.Encounter, rebound.Escape) as error:
    print(error)
    print(i)
```

**Comment by hannorein** [comment]
If you want to raise an exception when particles get close to each other you need to 
1) Give the particles a radius. For example: ``sim.add(m=1,r=0.1)``
2) Enable one of the collisions modules. For example ``sim.collision="direct"``
Then an exception will get raised whenever there is a collision. Let me know if this helps.

**Comment by jkahn96** [comment]
Hi hannorein.  Thank you for the information!  The exception is now being raised.  However, what are the units of the  `sim.exit_min_distance` and `sim.exit_max_distance` conditions, r_sun or AU?

**Comment by dtamayo** [comment]
It's whatever units you're using in the rest of the code. Feel free to reopen if you have any follow-up questions

**Comment by dtamayo** [comment]
Missed your last question! They cannot be set separately. You can alternatively give particles sizes and look for collisions. See the bottom of the CloseEncounters.ipynb ipython_example. There's currently no way to set separate exit_max_distances though
