### ISSUE TITLE
[enhancement] document using ephemeris to set up reb_simulation

### ISSUE THREAD

**Issue by chriscamacho** [hannorein/rebound#328]
in the solar_system example it states

"The data comes from the NASA HORIZONS system." 

(presumably https://ssd.jpl.nasa.gov/horizons.cgi?s_body=1#top)

while things like mass are obvious its is less obvious how position and velocity data as used in this example is derived. Additionally are there other values used or inferred by the information provided by the Nasa data that has an impact on global value of a reb_simulation

**Comment by hannorein** [comment]
I'm not sure I understand what your question is, but if you want to get data from NASA Horizons, you can look at this example: https://github.com/hannorein/rebound/blob/master/ipython_examples/Horizons.ipynb

**Comment by chriscamacho** [comment]
I guess I could write a python app to set a solar system up and save it as a binary file to load up in my C experiments, but I'd rather learn how to take ephemeris data and convert it into the data rebound requires 

for example I see nothing in the nasa data like Cartesian coordinates and vectors for velocity
