### ISSUE TITLE
Longitude of pericentre in orbit almost circular

### ISSUE THREAD

**Issue by pemanpardo** [hannorein/rebound#329]
I've just found that in rebound when you have a orbit with really low eccentricity ( < 1e-10) , and you place a particle with some argument of pericentre rebound change it and place the pericentre in another place, is there a command to get rid of this behave in rebound?

**Comment by hannorein** [comment]
May I ask what use case you have in mind for such small eccentricities?

**Comment by dtamayo** [comment]
I'm not sure I completely understand the question, but at low eccentricities pomega (longitude of pericenter) rather than omega (argument) is the right angle to use. You can use it for adding particles or access it with particle.pomega

**Comment by pemanpardo** [comment]
I am trying to compare my model with rebound and in my model I start the simulation with eccentricity zero and then I want to know how evolve the longitude of pericenter but also the change in eccentricity is really low so I am working with really small changes, I am plotting in t = 0, placing the particle in pomega = 60 degrees or omega = 60, I tried with both, and if you plot the same particle few time with the command fig = rebound.OrbitPlot(sim, periastron = True) you will see that the pericenter is changing even if you don't change the initial condition. For the same initial condition you can see that rebound place the longitude of pericenter in different places when the eccentricity is small than 1e-5.

**Comment by hannorein** [comment]
Hm. I can't really say more without either understanding the use case a bit more or seeing some code that shows the issue.

**Comment by hannorein** [comment]
I'll close this issue for now. If you think this is still an issue, please post some code that will allow me to reproduce it!
