### ISSUE TITLE
renormalization in MEGNO calculations?

### ISSUE THREAD

**Issue by muratxkaplan** [hannorein/rebound#334]
Hi all,

I would like to use REBOUND code for some MEGNO calculations. 
In some papers (like Goździewski et al 2001,A&A, 378), it is said that; it is necessary to renormalize the variational after a period of time in the case of chaotic motion.

Is there a renormalization time/parameter for variational in rebound code?

thanks in advance! 
Greetings, 
Murat

**Comment by hannorein** [comment]
Hi Murat,

That's a good question. I always go away without renormalization. If it's a chaotic system, then you know that it's chaotic by the time you need to renormalize anyway.  So no, at the moment there is no built-in renormalization method. But I agree that would be nice to have. If you feel up for it, please consider implementing it!

Hanno

**Comment by hannorein** [comment]
This is related to #437. I don't thinks there is a "right" way to do a renormalization. But if anyone thinks differently, I'd be happy to talk!

**Comment by hannorein** [comment]
A bit late, but this is now implemented as of version 3.21.
