### ISSUE TITLE
segmentation fault in reb_add with tree

### ISSUE THREAD

**Issue by jrob93** [hannorein/rebound#335]
For some reason I get 'Segmentation fault: 11' when I try to add more than one particle to a simulation, when REB_GRAVITY_TREE is used. See below for a short script that reproduces the problem. I'm not sure what's causing it, but I assume it is something in reb_tree_add_particle_to_tree.

Cheers

```
#include "rebound.h"
#include <stdio.h>

int main(int argc, char* argv[]) {

struct reb_simulation* r = reb_create_simulation();

	// // Uncomment here to cause fault
	// r->opening_angle2	= .5;
	// r->gravity			= REB_GRAVITY_TREE;

	struct reb_particle p1= {0};
	reb_add(r, p1);
	printf("particle 1 added\n");

	struct reb_particle p2= {0};
	reb_add(r, p2);
	printf("particle 2 added\n");

}

```

**Comment by hannorein** [comment]
You need to specify a size of the root box for the tree. This is done by calling

   reb_configure_box(r, box_size, 1,1,1);

**Comment by jrob93** [comment]
Just tried adding that in like so:

```
#include "rebound.h"
#include <stdio.h>

int main(int argc, char* argv[]) {

struct reb_simulation* r = reb_create_simulation();

	// Uncomment here to cause fault
	r->opening_angle2	= .5;
	r->gravity			= REB_GRAVITY_TREE;
	double box_size = 1;
	reb_configure_box(r, box_size, 1,1,1);

	struct reb_particle p1= {0};
	reb_add(r, p1);
	printf("particle 1 added\n");

	struct reb_particle p2= {0};
	reb_add(r, p2);
	printf("particle 2 added\n");

}
```

But I still get the same segmentation fault on the second call of reb_add

**Comment by hannorein** [comment]
That's because both particles have exactly the same coordinates.

**Comment by jrob93** [comment]
Ah okay, yep that is working now. Thanks!
