### ISSUE TITLE
fmemopen missing on old MacOS version

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#339]
fmemopen is missing on old versions of MacOS X (<10.13). This leads to error when trying to compile REBOUND. There is a replacement out there which we might want to use for those cases: https://github.com/NimbusKit/memorymapping

I'm not sure how to include it conditionally (I'd like to avoid a configure script).

**Comment by hannorein** [comment]
I need to find a computer with an old operating system...

**Comment by hannorein** [comment]
I added replacements for both `open_memstream` and `fmemopen` in the branch https://github.com/hannorein/rebound/tree/old_osx. This should only be necessary for old OSX versions. If you have the opportunity, could you check if this works for you?

Thanks!

**Comment by jrob93** [comment]
Awesome! I switched to the old_osx branch and it all seems to be working now. Thanks!

**Comment by hannorein** [comment]
Ok. Thanks! I need to check the licenses of these workaround and then I'll merge it into the master branch.

**Comment by hannorein** [comment]
I've tried out another way to get around this: just implementing my own version of these functions. This avoids having to include other people's code and do any conditional includes depending on the operating system version. This turned out a bit of a mess (On my own computer for example, pip thought I was still on an old OSX version because pip was installed before the OSX upgrade. The c version on the other hand recognized the correct OSX version. Seems like a rabbit hole). 

The new way is now on the no_memopen branch. All of the changes happen on the backend and there should be no changes to the user interface. I'll run a few more tests and if it works reliably, I'll merge it into the master branch.
