### ISSUE TITLE
Julian date for sim.add?

### ISSUE THREAD

**Issue by ivenzor** [hannorein/rebound#349]
It's not a big deal, but I was wondering if it's possible to directly pass a Julian date in sim.add?

I tried to use a Julian date but it seems it doesn't work:
>>> date="2451000.500"
>>> sim.add("Venus", date=date)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivenzor/.local/lib/python2.7/site-packages/rebound/simulation.py", line 1008, in add
    self.add(horizons.getParticle(particle, **kwargs), hash=particle)
  File "/home/ivenzor/.local/lib/python2.7/site-packages/rebound/horizons.py", line 29, in getParticle
    date = datetime.datetime.strptime(date,"%Y-%m-%d %H:%M")
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2451000.500' does not match format '%Y-%m-%d %H:%M'__

Best regards

**Comment by dtamayo** [comment]
It isn't possible currently, but I agree it would be useful for solar system applications. I'm not sure whether the support should be in REBOUND or not (perhaps @hannorein can give his opinion). If it's not in REBOUND, it looks like you do have to jump through some hoops to do the conversion yourself:

https://stackoverflow.com/questions/13943062/extract-day-of-year-and-julian-day-from-a-string-date-in-python

but it should be possible to pass a Julian date directly to horizons, so maybe it makes sense to implement it in horizons.py?

**Comment by hannorein** [comment]
This sounds like a good idea to me! The only issue that I could see is the possible confusion with various time standards. I'd love to not go down that rabbit hole!

**Comment by hannorein** [comment]
This was actually much easier to add than I thought! It's now in the lates upstream version. Syntax:

    sim.add("Earth", date="JD2458327.500000")
