### ISSUE TITLE
Is there any way to dissociate inertial mass and gravitational mass?

### ISSUE THREAD

**Issue by Titanosaurus** [hannorein/rebound#350]
I'm trying to understand the perturbation effects of Neptune on Uranus. I have integrated both in time and It shows fine, but now I would like to perform a previous and, lets say, unrealistic experiment. I want Neptune to have a huge inertial mass (so Uranus can't perturb it) but at the same time to keep it's true mass (so the perturbation on Uranu's due to the gravitational tug is still there).

Now I'm able to see the real situation, where Uranus and Neptune perturb mutually as a coupled system. Uranus imparts a tug that changes Neptune's position slightly and that new location implies a different pull for Uranus. I just want Neptune to follow it's orbit unperturbed while Uranus is perturbed by this body. Is there a way to do that?

I'm using Python.

And sorry for my bad english

**Comment by hannorein** [comment]
If I understand your question correctly, then simply add Uranus as a test particle. If you do that Uranus will not influence any other planet, but it will be influenced by Neptune. (you can also just set the mass of Uranus to zero).

**Comment by Titanosaurus** [comment]
Sorry for been such a noob and thank you for your response. I apreciate that a lot.
