### ISSUE TITLE
How to add correctly clones of a comet to the simulation  

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#351]
Hi!, 

I would like to create clones of a given comet, in order to study its orbital evolution from a statistical point of view. My PhD supervisor do that in Mercury, but  would like to implement that in Rebound. 

My problem is that, I obtain different result when I add a comet using the JPL call function than when add it just copy the info from the JPL website. Let's see an example to clarify: 

1. Calling JPL by the function, I do: 
`#sim.add(["Sun","Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune","NAME=Churyumov-Gerasimenko; CAP"],date="2017-12-10 12:00")`
 
2. Adding (manually) the [orbital parameters that are given in the JPL web site](https://ssd.jpl.nasa.gov/sbdb.cgi#top) just copying by hand:

```
sim.add(primary=sim.particles[0],
        M=92.07346224536946 *np.pi/180.,
        a=3.46473701803964,
        omega = 12.69446404906225*np.pi/180.,
        Omega = 50.18000114437616 *np.pi/180.,
        e = 0.6405847372930017,
        inc = 7.043698689343029*np.pi/180.)
```
I guess that the first option is the good one. However, my concerns come from that to add the clones to the simulation I have to use the second option (at least I do not know how to use the first option to add clones), but I see that the results are different even when I'm only considering the real comet information.

My suspects point that is a problem in the coordinate system. However, I don't understand how to solve, and how I should add particles using the second option to obtain the same result than using the first. 

Thanks in advance for any help! =)

**Comment by hannorein** [comment]
Hi Mileva,

Yes, the differences probably come from the different coordinate systems and I would also prefer the first version. In that one you are guaranteed that the coordinate systems are the same. If you want to create clones of a particle you could do something like this:

comet = sim.particles[-1] # last particle in list is the comet
sim.add(comet) # add the particle again
sim.particles[-1].x += 0.0001 # change the x coordinate of the newly added copy by a tiny amount

I hope this help!

Hanno

**Comment by MilevaE** [comment]
Hi Hanno, 

thanks a lot!

**Comment by ridlo** [comment]
this line will not update the particle parameters:
`ps[-1].calculate_orbit(primary=sim.particles[0]).e += 0.001 # change the eccetricity` 

maybe you should generate your clone in Keplerian coordinate first, and then you can `sim.add(m=0, a=..., e=..., inc=..., Omega=.., omega=.., M=...)` or instead M you can use t_perihelion for hyperbolic orbit.

I think for comet simulation you should use outgassing effect, and in rebound there is no such additional force by default. If you want, you can use reboundx to add this force. I tried to add this force a long time ago but didn't finish it yet.
