### ISSUE TITLE
Future of OpenCL-based gravity solver?

### ISSUE THREAD

**Issue by michaelaye** [hannorein/rebound#354]
Apple has announced the removal of OpenGL/CL support in future macOS versions.

Does this mean that running the REB_GRAVITY_OPENCL gravity solver will be impossible in those future versions?

Opened this issue to keep track of this question, I guess it could potentially guide future investments into workhorse machines, e.g. Linux instead of Mac.

Could a virtualized OpenCL still work for developing code before it's being sent off to a Linux machine with full OpenCL?

**Comment by hannorein** [comment]
I'll close this for now. Any implementation would have to be pretty specific and I simply have no use case for an OpenCL based gravity solver myself at the moment. If anyone needs one or is interested in developing one for REBOUND, I'd be happy to talk about it.
