### ISSUE TITLE
Error! REBOUND was not compiled/linked with OPENGL libraries. 

### ISSUE THREAD

**Issue by rafanw72** [hannorein/rebound#360]
Hi,
I received an error code: 

Error! REBOUND was not compiled/linked with OPENGL libraries. 

It happens even when I put export OPENGL=0 in the Makefile.

Thank you, 

Rafael Ribeiro

**Comment by hannorein** [comment]
Hi Rafael, 

How does your program file look like?

Hanno

**Comment by rafanw72** [comment]
Hi Hanno, 

It does like the lines below: 

`int main(int argc, char* argv[])
{
   FILE*pfile;
   pfile = fopen("stop.in","a");
   char filename[512] = "restart.bin";
   double Jup_T,Sat_T,ratio;
   int erro;
   disk1.No=6200;
   size_distribution_Nesvorny(disk1.No);
   struct reb_simulation* r = reb_create_simulation_from_binary(filename);// Trying to restart from the Simulation Archive.
   if (r==NULL)
   {
    r = reb_create_simulation(); // Collisions
    r->collision = REB_COLLISION_DIRECT;
    r->collision_resolve = reb_collision_resolve_merge;
    r->collision_resolve_keep_sorted = 1;
    r->heartbeat = heartbeat;
    r->integrator = REB_INTEGRATOR_MERCURIUS;
    struct reb_particle sun = {0};
    sun.m=M_sun;
    sun.hash = reb_hash("Sun");
    reb_add(r, sun);
    struct reb_particle primary = r->particles[0];
    //Giants Planets. 
    if(read_add_plan(argv[1],r)!=0) printf (" read_add done");
    r->N_active = r->N;
    // Planetesimal Disk- Superplanetesimals
    // Size_Distribution Nesvorny et al. 2016 
    for (int j=0;j<4;j++)
    {
        disk1.mass_superplanetesimal[j]=disk1.mass_diameter[j]/number_planetesimals[j]; // kg  // D 1000 km, D 100 Km, D 10 Km, D 1 Km
        if(read_add(argv[j+2],disk1.mass_superplanetesimal[j],r,j)!=0) printf (" read_add done");
        
    }
    printf("N>1000=%e\n", disk1.No);
    printf("Total mass of the disk %e\n", disk1.Total_Mass);
    r->testparticle_type=1; //(small particles == particles-interacting with the active particles_
    reb_move_to_com(r);
    }
    else
    {
       
        printf("Found simulation archive. Loaded snapshot at t=%.16f.\n",r->t);
    }
    r->integrator    = REB_INTEGRATOR_MERCURIUS;
    r->heartbeat = heartbeat;
    //r->simulationarchive_filename = filename;
    r->testparticle_type=1; //(small particles == particles-interacting with the active particles_
    r->dt=0.5; // years
    reb_integrate(r, tmax);
    fprintf(pfile,"1");
    fclose(pfile);
    printf("Done.\n");
}`


Thank you, 

Rafael Ribeiro

**Comment by hannorein** [comment]
(it looks a bit scrambled above)

Did you try running `make clean`?

**Comment by rafanw72** [comment]
It works, sorry to report that! 

Thank you, 

Rafael Ribeiro

**Comment by rafanw72** [comment]
###

**Comment by hannorein** [comment]
No worries! Happy to hear it works!
