### ISSUE TITLE
GPU Version Planned?

### ISSUE THREAD

**Issue by gmduvvuri** [hannorein/rebound#361]
Are there plans to make a GPU-version of REBOUND?

**Comment by hannorein** [comment]
Not by me, but I know that some others are working on getting REBOUND onto GPUs. What's your use case?

**Comment by gmduvvuri** [comment]
Curiosity because someone else asked me. I can ask them and forward their reply?

**Comment by hannorein** [comment]
Sure. 

In short: a GPU version makes only sense in very specific cases. For example a few massive planets and a lot of test particles. In contrast, REBOUND can do a lot of different things. Porting all of the integrators, gravity modules, etc to GPU would not make much sense.

**Comment by 7ayushgupta** [comment]
@hannorein Is there any existing GPU implementation that you know of?

**Comment by hannorein** [comment]
No. Note that any implementation would not be as general as the current CPU version of REBOUND.

**Comment by 7ayushgupta** [comment]
Yeah, sure. 
I have a very specific use-case which I can try to implement, by checking their code out.

**Comment by hannorein** [comment]
Got it. But sorry, I'm not aware of any REBOUND GPU implementation for that case. There might be some other codes which have been used specifically for that use case.
