### ISSUE TITLE
Calculate barycentric orbits

### ISSUE THREAD

**Issue by jrob93** [hannorein/rebound#362]
Hi,

I'm trying to use the rebound framework to convert between heliocentric and barycentric orbits. I've attached an example py script that adds two particles to the simulation. I first calculate the relative (heliocentric) orbit of each particle about the other. I then try to calculate the barycentric orbits of both particles relative to the system's centre of mass, by passing `sim.calculate_com()` as the primary in `calculate_orbit`.

I don't think my method is working, I was expecting the barycentric orbits to be the same as the heliocentric orbits, but just reduced in scale. For my simple circular orbits example the barycentric orbits are returned with some eccentricity. Any advice on how I could calculate the barycentric orbits?

Cheers,
James

```
import rebound

# Create a rebound sim with two particles
sim = rebound.Simulation()
m0=1
m1=1
a1=1
sim.add(m=m0)
sim.add(primary=sim.particles[0],m=m1,a=a1)
# sim.move_to_com()
sim.status()

# Calculate the relative orbits
print 'helio orbits'
orb0_hel=sim.particles[0].calculate_orbit(primary=sim.particles[1])
orb1_hel=sim.particles[1].calculate_orbit(primary=sim.particles[0])
print orb0_hel
print orb1_hel

# Calculate the barycentric orbits
print 'bary orbits'
com=sim.calculate_com()
orb0_bar=sim.particles[0].calculate_orbit(primary=com)
orb1_bar=sim.particles[1].calculate_orbit(primary=com)
print orb0_bar
print orb1_bar
```

**Comment by hannorein** [comment]
Hi James,

This can be very confusing. I think you're doing everything right. It just depends on the definition of what you mean by barycentric orbit. I think you might want to calculate the orbit of a test particle around the barycentre to get what you expect. Otherwise you're counting the mass of particle two twice (once in the COM, and once in the particle itself). 

Not sure if this helps!

Hanno

**Comment by jrob93** [comment]
Haha, yes I feel confused. I am trying to do something where I can easily convert between the two orbits shown below:
![relative_barycentric](https://user-images.githubusercontent.com/22542097/47753095-a9904200-dc53-11e8-91da-16d0d315f051.png)

My end goal is to convert between the heliocentric orbital elements of a solar system object, to the orbit relative to the barycentre of the entire solar system. So I would set up a rebound sim, add a particle that represents the centre of mass of the solar system, add the particle of interest on its heliocentric orbit, and then find the barycentric orbit of that particle relative to the centre of mass (particle 0).

**Comment by hannorein** [comment]
I'll close this for now. I think implementing this would be nice, but it could also lead to confusion. It's relatively easy to use the built-in calculate_orbit routine in REBOUND for this, all one has to do is choose the central object accordingly.
