### ISSUE TITLE
Mean Anomalies and Longitudes of Periastron are Incorrect for e=0 orbits

### ISSUE THREAD

**Issue by mckyrosenthal** [hannorein/rebound#365]
When adding planets with zero eccentricity, rebound seems to return incorrect values of mean anomaly and pomega. For example, if I run the following code:

`sim = rebound.Simulation()`

`sim.add(m=1.0)`

`ps = sim.particles`

`sim.add(m=1e-4, a=1.0, M=np.pi/2.,pomega=0,e=0)`
`sim.add(a=1.5, M=np.pi/2., pomega=0,e=0)`
`sim.move_to_com()`

I get the following for the orbital elements:

![image](https://user-images.githubusercontent.com/22303449/50615429-617edd00-0e99-11e9-8f0a-ffbef4a95f10.png)

Where the mean longitudes are correct, but the mean anomalies and longitudes of pericenters are incorrect. I explicitly passed e=0 and pomega=0 to both planets to make sure this was functioning correctly, but the issue is also present if both e and pomega aren't specified (unsurprising, since they default to 0). I understand that pomega is not well defined for a circular orbit, but I believe mean anomaly should still be well defined in this case?

Also, the issue changes if planets are initialized with period instead of semi-major axis:

`sim = rebound.Simulation()`

`sim.add(m=1.0)`

`ps = sim.particles`

`sim.add(m=1e-4, P=1.0, M=np.pi/2.,pomega=0,e=0)`
`sim.add(P=1.5, M=np.pi/2., pomega=0,e=0)`
`sim.move_to_com()`

Yields:
![image](https://user-images.githubusercontent.com/22303449/50615592-11ece100-0e9a-11e9-9b73-dc1676c3a380.png)

Initializing both planets with eccentricity e=1e-10 eliminates the issue.

**Comment by dtamayo** [comment]
Hi Mickey,

Thanks for the feedback with concrete examples. Like you say, pomega is undefined for a circular orbit, but so is the mean anomaly (all the different anomalies are measured from pericenter). For circular orbits the best variables to use for the phase are the mean or true longitude, which is measured from the x axis. 

Nevertheless, it would be nice if it defaulted to the value you put in. This might be possible for values of 0, but I'm not sure would be possible for arbitrary values. I don't think I can put this high on the priority list, but I'll think about whether there might be an elegant fix. In what application does this cause trouble?

**Comment by hannorein** [comment]
In the case of e=0, the longitude is not well defined either. Try adding a particle, then getting the orbital elements, and then adding the particle again but using the orbital elements from the first particle (all 6 of them). You should get the same answer.

(cc @dtamayo, who has thought about this quite a bit)

**Comment by dtamayo** [comment]
two responses within 10 minutes? Pretty good 👍

**Comment by mckyrosenthal** [comment]
Hi Hanno and Dan,

Thanks for the quick responses! Yeah, I did wonder if the fact that pericenter isn't well defined meant using M was also a poor variable to use. The issue originally arose because, when running the code in Python 2 (which I'm guessing isn't supported anymore), the mean longitudes had the same issues, which was giving me incorrect answers when looking at libration of the resonant angle in the 3:2 MMR. However, in Python 3 that issue isn't present. As Dan said, it would be nice if the values defaulted to the ones you put in even for circular orbits, but I can see why that probably won't work for general values, and as long as the mean longitudes are calculated correctly then for my particular application everything is still functioning correctly.

**Comment by dtamayo** [comment]
Hm, there was a patch a few months back that did fix an issue with mean longitudes in these edge cases. Are you sure it's not that you have different versions of REBOUND in python 2 and 3? 

I just tried installing a python 2 environment with the latest version and

```
sim = rebound.Simulation()
sim.add(m=1.0)
ps = sim.particles
sim.add(m=1e-4, a=1.0, l=np.pi/2.,pomega=0,e=0)
sim.add(a=1.5, l=np.pi/2., pomega=0,e=0)
sim.move_to_com()
```

gives the correct ps[1].l. I'll close this for now, but if you don't get the right behavior for the mean longitude in python 2 for circular orbits please do reopen it, because that would definitely be a bug.
