### ISSUE TITLE
Implementing a background matter distribution

### ISSUE THREAD

**Issue by chaoticinflaton** [hannorein/rebound#377]
Hi!

I'm trying to simulate the circular motion of two particles inside a background density distribution. This means that the particles are revolving around a common center of mass, but there is also an additional force arising from the background distribution at the particle position _r_. 

I am implementing this as an additional force:

F(r) = - 4*pi*G * (integrate( r^2 * rho(r) ) / r^2 (in the r-direction). 

I am then implementing this in cartesian coordinates as:

particle.ax += F(r) * x/r
particle.ay += F(r) * y/r

This is giving me absurd results, so I was wondering if this is the correct way of implementing a radial force in cartesian coordinates. Is there a way to implement a radial potential or force?

Thanks a ton!

**Comment by hannorein** [comment]
This looks alright. Are you sure your F(r) function is correct/meaningful?

**Comment by chaoticinflaton** [comment]
Okay, I just wasn't sure I was doing this correctly. I shall check my distribution. Thanks.

**Comment by hannorein** [comment]
I'll close this for now but feel free to open another issue if you're unsure about the implementation in REBOUND!

**Comment by chaoticinflaton** [comment]
Thanks!
