### ISSUE TITLE
Setting Up A Circular Orbit in a Background Matter Density

### ISSUE THREAD

**Issue by chaoticinflaton** [hannorein/rebound#381]
Hi

I want to set up a circular binary inside a background density field (a dark matter halo). 
The issue I face is that the particle collapses to the centre in the very first timestep itself. 

I am implementing the background field as an additional force on the particle.

Here is the relevant section of the code.

```
def grav_force(reb_sim):

    for part in ps:
    
        r = np.linalg.norm(part.xyz)
        dvdr = G*m_in(r)/(r*r)

        part.ax += -1.0*(dvdr/r)*part.x
        part.ay += -1.0*(dvdr/r)*part.y
        part.az += -1.0*(dvdr/r)*part.z
  
m = 200
x0 = 2.5
v0 = np.sqrt((G/x0) * (m_in(x0)) + 0.25*G*m/x0) # This comes from both the second particle and the dark matter mass enclosed providing the circular velocity. 

# Here I add two particles, one going in the positive y-direction, and the other the -ve y-direction, at equal distances from the origin. 
sim.add(m = m, x = x0, vy = v0)
sim.add(m = m, x = -x0, vy = -v0) 

ps = sim.particles

sim.additional_forces = grav_force
#sim.force_is_velocity_dependent = 1


t_half = np.pi*x0/v0

times = np.arange(0,t_half,10)
xs1 = np.zeros(len(times))
ys1 = np.zeros(len(times))
xs2 = np.zeros(len(times))
ys2 = np.zeros(len(times))

for i,t in enumerate(times):
    print i
    sim.integrate(t)
    xs1[i] = sim.particles[0].x
    ys1[i] = sim.particles[0].y
    xs2[i] = sim.particles[1].x
    ys2[i] = sim.particles[1].y

plt.plot(xs1,ys1)
plt.plot(xs2,ys2)
plt.grid()
plt.show()   
      
```

So I set the particles up by giving them equal and opposite circular velocities. At the first timestep, the particles crash into the origin and the simulation stalls. 

Is there an obvious mistake I am making?

Thanks a lot.
Himanish

**Comment by hannorein** [comment]
Hm. I don't see any obvious mistake. To further look into it, I'd need you to post the code again, maybe stripped down a bit and with all the constants defined so I can run it myself.

Thanks!

**Comment by chaoticinflaton** [comment]
Okay, thanks. 

I was wondering if there's some issue with the way I set up the circular orbit. 

Here's the code. You will have to add the definition of the parsec to the units file ('pc' : 3.086e16)




```
import rebound as re
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import quad

sim = re.Simulation()

sim.units = ('pc','yr','msun') # Add these units to the rebound units file and re-import. 

G = sim.G
norm = 257658.18100737795 # normalisation for isothermal DM profile. 
omega_m = 0.3

# This is the density profile. 
def ein(r):
    return norm * 1.0 / (r*r)

# This is the enclosed mass at radius r. 
mass_integ = lambda x: 4*np.pi*x*x*ein(x)
def m_in(r):
    return quad(mass_integ,0,r,epsrel=1e-6,epsabs=0)[0]
    
def grav_force(reb_sim):

    for part in ps:
    
        r = np.linalg.norm(part.xyz)
        dvdr = G*m_in(r)/(r*r)
        
        part.ax += -1.0*(dvdr/r)*part.x
        part.ay += -1.0*(dvdr/r)*part.y
        part.az += -1.0*(dvdr/r)*part.z

# Here the simulation stuff begins. 

m = 200
x0 = 10
v0 = np.sqrt(0.25*G*m/x0 + G*m_in(x0)/x0)

sim.add(m = m, x = x0, vy = v0)
sim.add(m = m, x = -x0, vy = -v0)

ps = sim.particles
sim.additional_forces = grav_force

t_half = np.pi*x0/v0

times = np.arange(0,t_half,1e4)
xs1 = np.zeros(len(times))
ys1 = np.zeros(len(times))
xs2 = np.zeros(len(times))
ys2 = np.zeros(len(times))

for i,t in enumerate(times):
    print i
    sim.integrate(t)
    xs1[i] = sim.particles[0].x
    ys1[i] = sim.particles[0].y
    xs2[i] = sim.particles[1].x
    ys2[i] = sim.particles[1].y

plt.plot(xs1,ys1)
plt.plot(xs2,ys2)
plt.grid()
plt.show()   
```
No matter what the mass enclosed at the initial radius is, the initial circular velocity sqrt(GM_in)/r should account for that, and make it a circular orbit. Or am I wrong in that understanding?

Thank you. 

Himanish

**Comment by hannorein** [comment]
This seems to work for me. I don't understand all the physics involved, but I do get a circular orbit out.

![Unknown-1](https://user-images.githubusercontent.com/53376/58350847-1314af80-7e35-11e9-9ec1-ff8b76365330.png)

**Comment by chaoticinflaton** [comment]
Hmm. Seems to be an issue with my normalisation and the form of my density profile. 

It works with this isothermal profile, but not with the NFW / other ones. In any case, I have identified where the issue lies. 

Many thanks for your time. 

Cheers.
