### ISSUE TITLE
MEGNO computation from SimulationArchive ?

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#382]
Hi guys, 

I'm running a long-term integration and I would need to check the MEGNO parameter from time to time, and update a plot along the integration runs. In this regard, I found very interesting the Simulation Archive thing but I'm not able to make it works, and I have this error message:

> Traceback (most recent call last):
>   File "test.py", line 27, in <module>
>     megno_f = sim.calculate_megno()
>   File "/usr/local/lib/python2.7/dist-packages/rebound/simulation.py", line 1081, in calculate_megno
>     raise RuntimeError("MEGNO cannot be calculated. Make sure to call init_megno() after adding all particles but before integrating the simulation.")
> RuntimeError: MEGNO cannot be calculated. Make sure to call init_megno() after adding all particles but before integrating the simulation.

Here and example: 

```
import rebound
import numpy as np

sim = rebound.Simulation()
sim.add(m=1.)
sim.add(m=1e-3, a=1.)
sim.add(m=1e-3, a=1.9)
sim.move_to_com()
sim.dt = sim.particles[1].P*0.05  # timestep is 5% of orbital period
sim.integrator = "whfast"

filename = 'testsa.bin'

Nout = 1000
times = np.logspace(0, 4, Nout)*sim.particles[1].P
sim.init_megno()
sim.exit_max_distance = 100.

for i, time in enumerate(times):
    sim.integrate(time, exact_finish_time=0) 
    sim.simulationarchive_snapshot(filename)
```

Now I want to access to the SimulationArchive and compute the MEGNO parameter:
 
```
sa = rebound.SimulationArchive(filename)
for i, sim in enumerate(sa):
    megno_f = sim.calculate_megno()
```
And here is where I obtain the error I mentioned previously. Is it that maybe I can not compute MEGNO from a SimulationArchive? Or I'm doing something wrong ?

Please, note that here I'm posting everything together but ideally the second part would be implemented in a different script to run it while the first par is running. Thus I can see the status 
of the simulation on real time and I don't have to wait to the end to check what is going on.

Thanks!

**Comment by hannorein** [comment]
Hm. Just to make sure: did you delete the simulation archive file before running the simulation? Otherwise you might access an old snapshot from an earlier simulation. 

If that's not it, it might be a bug and I'll need to look into it...

**Comment by MilevaE** [comment]
Hi Hanno, 
Thanks for your answer
yes, I deleted the simulation archive file before running the simulation... 

For some reason I'm not receiving the same error, now it says: 

> Segmentation fault (core dumped)

: /

**Comment by MilevaE** [comment]
As far I see, the problem seems to be that is not possible to access the simulation archive if I have 
call megno fuction by `sim.init_megno()`

**Comment by hannorein** [comment]
Thanks. I can reproduce this. I'll look into it.

**Comment by hannorein** [comment]
I think this should fix everything. Let me know if not!
