### ISSUE TITLE
Discontinuities in the evolution of the mean longitude

### ISSUE THREAD

**Issue by mstalport** [hannorein/rebound#385]
Hi! 

I’m a user of the python version of rebound (that I really appreciate by the way). 
I noticed what I think to be a bug in the `sim.integrate()` function. Indeed, I noticed some discontinuities in the evolution of the mean longitude of planets when I simulate a planetary system. Here below I show you a case example with whfast: a 1-planet system.  

```
import rebound 
import numpy as np
from matplotlib import pyplot as plt 

sim = rebound.Simulation() 
sim.add(m=1.0) 
sim.add(m=1e-3, a=1.0) 
sim.move_to_com() 
dt = 1.0*2*math.pi / 100. 
sim.dt = dt
sim.integrator = "whfast" 
N = 10000 

ML = np.zeros(N) # Mean longitude of the planet at each output timestep
t = np.zeros(N) # Time at each output timestep 
for k in range(N): 
    sim.integrate(k*dt*10, exact_finish_time=0) 
    t[k] = k/10. 
    ML[k] = sim.particles[1].l 

plt.scatter(t,ML,s=0.6)
```

These discontinuities disappear when I get rid of the argument `exact_finish_time=0` in the sim.integrate function. However, that's not very convenient since I don't benefit from the symplectic nature of the integrator. 
Also, changing the integration timestep changes the location of these bumps. And if the timestep decreases, then the amplitude of the discontinuity will be smaller. 

I suspect that the problem comes from the number of integration timesteps the function 'sim.integrate' needs to process before generating an output. If dt is the integration timestep and Dt the output timestep, then this number is given by Dt/dt and it should be an integer (equal to 10 in this example). However, as Dt/dt is a float, one can use round(Dt/dt) in order to get the right integer. But maybe that, instead of 'round', the function 'int' has been used. If it is so, as sometimes Dt/dt = 10 - 0.00...01, then in these cases the result will be int(Dt/dt)=9. Therefore, the output for the mean longitude will be shifted of one timestep. 
In the context of this hypothesis, I tried to add a small value to the integration time, in the sim.integrate function (the only change in the aforementioned code): 
`sim.integrate(k*dt*10 + 0.1*dt, exact_finish_time=0)`  
By doing so, I ensure that the new Dt/dt is always in ]10;11[. Therefore, if an 'int' is used instead of a 'round', this small increment should cancel the discontinuities problem (the number of integration timesteps before generating an output will always be 10). That is indeed what is observed. 

This is just an idea to solve the issue, as it explains all of my observations. However, maybe there is a specificity of the code I didn't get. 

Many thanks! 
Manu Stalport

**Comment by hannorein** [comment]
Hi Manu, 

I believe you're running into floating point issues here, i.e. 10.*dt != 9.*dt+dt. 

If you want to just integrate for 10 steps, you can call sim.step() 10 times, giving you exactly what you expect.

If you run a very long term integration, you can use the SimulationArchive with the `steps` argument to do something similar. 

I hope this helps!
 Hanno

**Comment by hannorein** [comment]
I'll close this for now, but feel free to reopen the issue if you have more questions about it!
