### ISSUE TITLE
Reduce tilmestep speed in visualization via GUI 

### ISSUE THREAD

**Issue by ReeceHumphreys** [hannorein/rebound#391]
Is there any way to reduce the speed in which time progresses using the simulation GUI for examples such as the solar system example?

If not what is the best practice for setting the rate at which time progresses?

**Comment by hannorein** [comment]
Yes! Set `reb_simulation->usleep` to the number of microseconds you want to wait between steps.  I hope this helps.

**Comment by hannorein** [comment]
I'll close this issue for now, but feel free to reopen should the above solution not work for you.
