### ISSUE TITLE
SimulationArchive Issue

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#397]
There seems to be an issue with loading a simulation from a SimulationArchive in certain cases. 

```
sim = rebound.Simulation()
sim.add(m=1)
sim.add(m=1e-3,a=1)
sim.add(m=1e-3,a=2)
sim.automateSimulationArchive("test.bin",interval=1.0,deletefile=True)
sim.integrate(10.)

sa = rebound.SimulationArchive("test.bin")
for i in range(10):
    sa9 = sa[9]
    print("%.16e %.16e"%(sa9.particles[0].x,sa9.particles[0].y))
    
sa = rebound.SimulationArchive("test.bin")
for i in range(10):
    print("%.16e %.16e"%(sa[9].particles[0].x,sa[9].particles[0].y))    
```

In the above code, the second for loop gives unpredictable results, suggesting a memory issue. I suspect the issue might come from python releasing the simulation object `sa[9]` too early because it is not referenced from anywhere (in contrast to the first loop where it is referenced by sa9).

**Comment by hannorein** [comment]
So I think my initial suspicion was right: As soon as the particles list is returned in `sa[9].particles` the reference count to the simulation object `sa[9]` becomes 0. However the particles list is just a wrapper using the memory location for the particles given by `sa[9]`. But since it's only an address (not a python object), python doesn't increase the reference count for the `sa[9]` object when creating the particle list object.

I'm not sure what the best way to fix this is.

**Comment by hannorein** [comment]
This seems to fix the issue and pass all the tests. Will merge it into the master branch unless I find any other unintended consequences.

**Comment by hannorein** [comment]
@dtamayo I'll merge this in unless you think this leads to any REBOUNDx related problems. I have a vague suspicion we talked about this a while ago but I can't remember!

**Comment by dtamayo** [comment]
I think the fix makes sense. I tested it out with REBOUNDx without any problems, and I can't see it having any unintended consequences! Thanks for checking
