### ISSUE TITLE
compiling -- integrator routines

### ISSUE THREAD

**Issue by aquillen** [hannorein/rebound#40]
I am finding some undefined symbols during the link, having to do with how the integrator routines are chosen/defined.   In current version, I can't find anywhere where integrator_part1() or other choices are set after the integrator is chosen.  I can work around this by adding defs, but probably there is some little piece of code missing from the current zip?  

Here is a piece of the compile output
Undefined symbols for architecture x86_64:
  "_integrator_part1", referenced from:
      _iterate in main.o
  "_integrator_part2", referenced from:
      _iterate in main.o
  "_integrator_update_acceleration", referenced from:
      _integrator_ias15_step in integrator_ias15.o
      _integrator_whfast_corrector_Z in integrator_whfast.o

**Comment by hannorein** [comment]
Hi Alice!

Thanks for opening this issue. We have changed quite a lot of things in the last couple of days to prepare for a new paper we are getting ready. So there is a good probability I have broken something. However, I just tried it and it works for me:

    wget https://github.com/hannorein/rebound/archive/master.zip
    unzip master.zip
    cd rebound-master/examples/outer_solar_system/
    make

Note that we changed how integrators are selected. They used to be defined in the Makefile. Now, you can choose them within the problem.c file. It could be that you are using an old Makefile with a new version of REBOUND. If this doesn't fix your problem, can you send me your makefile and your problem.c file? 

Hanno

**Comment by aquillen** [comment]
Aha! I think know what happened.     I had overwritten the integrator.c routine with an old Makefile.   It is my fault entirely.  It took a while for me to find as in the old Makefile the integrator.c is a link, yup I have noticed how the integrators are now chosen.   --- got to be careful inspecting the new Makefile.  
Thanks for getting back so fast!

**Comment by hannorein** [comment]
Glad it works!
