### ISSUE TITLE
NaN when computing MEGNO

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#400]
Hi, 
trying to get the minimum value of a planetary sytem inclination, I run a set of simulations where inc of the hole system (considered co-planar) is ranging from 90 to 35 deg (I discard already from 35 to 0 by other methods)   

Here is part of the code, where I compute MEGNO: 

```
import rebound
import numpy as np
import time
import random


def simulation(par):
    ib = par # unpack parameters
    sim = rebound.Simulation()
    sim.units = ('yr', 'AU', 'Msun')
    sim.integrator = "whfast"
    M_ts = 332946 #Earth mass in Solar mass 
    sim.ri_whfast.safe_mode = 0
    l1=random.randrange(0,360)
    l2=random.randrange(0,360)
    sim.add(m=0.29) # Star
    sim.add(m=1.18/M_ts/np.sin(ib), a=0.036, e=0.17, inc=0.0, l=np.deg2rad(75.6))     
    sim.add(m=2.89/M_ts/np.sin(ib), a=0.091, e=0.10, inc=0.0, l=np.deg2rad(229.6))    
    sim.add(m=10.8/M_ts/np.sin(ib), a=0.712, e=0.0, inc=0.0, l=np.deg2rad(l1))     
    sim.add(m=9.3/M_ts/np.sin(ib), a=0.849, e=0.0, inc=0.0,  l=np.deg2rad(l2))     
    sim.move_to_com()
    ps = sim.particles
    os = sim.calculate_orbits()
    sim.dt = 0.10 * os[0].P  # 5% del periodo del planeta mas interno
    t_integra = 1.e5*os[3].P # periodo del planeta mas externo
    sim.init_megno()
    sim.exit_max_distance = 10.
    sim.exit_min_distance = 0.001
    ibb=np.rad2deg(ib)
    try:
        sim.integrate(t_integra, exact_finish_time=0)
        megno = sim.calculate_megno()
        return megno,ibb
    except rebound.Escape:
        # Particle escaped, system clearly chaotic
        return 10.,ibb
    except rebound.Encounter:
        return 20.,ibb
```

At some point in the simulation, when inc is lower than 53deg I started to have NaN results:
```
 [ 1.99944069 35.        ]
 [ nan         36.01851852]
 [ 2.00028909 37.03703704]
 [ 1.99653255 38.05555556]
 [ nan         39.07407407]
 [ 2.00012008 40.09259259]
 [ 1.99921891 41.11111111]
 [ 1.9986559  42.12962963]
 [ 2.00025481 43.14814815]
 [ nan         44.16666667]
 [ 1.99813987 45.18518519]
 [ 2.00044258 46.2037037 ]
 [ 1.99821663 47.22222222]
 [ 2.00187131 48.24074074]
 [ 2.00008166 49.25925926]
 [ 2.00026515 50.27777778]
 [ 2.00034566 51.2962963 ]
 [ nan         52.31481481]
 [ 1.99977216 53.33333333]
 [ 2.00034353 54.35185185]
```

I'm trying to understand what can be causing the NaN results, including some exception to 
see there is some physical meaning for this (ejection, collision etc) but seems that is not the case..

Any suggestion to better understand this issue? May it has a physical meaning or it could be a code bug?

Thanks a lot in advance!

Ps. I can provide with the full code if needed :)

**Comment by hannorein** [comment]
It looks like you're integrating for quite a while (1e5 orbits). If the orbits are chaotic, the distance between real and shadow particles grows exponentially, so you will reach the limits of floating point numbers (1e308) relatively quickly. Check what the position and velocity coordinates of the variational particles look like. If they are very large, you might need to 
1) integrate for a short time
2) renormalize the variational particles at regular intervals. This is currently not implemented in REBOUND (I did not run into this problem myself). It requires some digging around under the hood of REBOUND, but it shouldn't be hard to do.

**Comment by MilevaE** [comment]
Hi Hanno, 

thanks for your answer. You are right about the floating point thing, the position and velocity coordinates of the variational particles are extremely large. But, in such a case, this actually means a chaotic behaviour, isn't? What is what I'm looking for. 

However, I'm still concern about why happen for some particular values of inclination, and not for the values around. For example, in the list of values I provided at the begging: 

```
 [ 1.99944069 35.        ]
 [ nan         36.01851852]
 [ 2.00028909 37.03703704]
 [ 1.99653255 38.05555556]
 [ nan         39.07407407]
 [ 2.00012008 40.09259259]
 [ 1.99921891 41.11111111]
 [ 1.9986559  42.12962963]
 [ 2.00025481 43.14814815]
 [ nan         44.16666667]
 [ 1.99813987 45.18518519]
 [ 2.00044258 46.2037037 ]
 [ 1.99821663 47.22222222]
 [ 2.00187131 48.24074074]
 [ 2.00008166 49.25925926]
 [ 2.00026515 50.27777778]
 [ 2.00034566 51.2962963 ]
 [ nan         52.31481481]
 [ 1.99977216 53.33333333]
 [ 2.00034353 54.35185185]

```

I don't understand how a system can be unstable for 52.3deg but not for 51.3deg or 54.3deg ...
any clue?

Thanks  a lot!

**Comment by MilevaE** [comment]
I think we can close the issue since the question has been solved, Thanks a lot Hanno!!

Just in case some else have the same issue, I would like to share here the what I have done, and my interpretation. Please, fell free to correct it or comment it if you find better solution/interpretation. 

I've modified the code in order to check regularly the value of MEGNO, and if this is larger than 50 (clearly chaotic) I set the value of 50. I notice than then, I have not longer nan, since these errors apparently come from a chaotic motion which grow fast and provoke the floating point thing in our integration time. In my code now I set to MEGNO=50  for this issue, =10 when particles escape, =20 when a close encounter happens. With this choice I can inspect the plot (see bellow) and understand what happen in the system: 

![MegnoVsInc_test_nan](https://user-images.githubusercontent.com/29211450/68581290-6d074100-0478-11ea-9be7-f3fbe6bdfac0.png)

One can see several "steps" in the plot, which belong to these choices I've described above. 
In this particular case, I would say that the system (in general) is clearly chaotic. Only in the range from 90deg to ~73deg we can ensure the stability of the system. From 73deg to 45deg we have many chaotic scenarios with MEGNO=50, bellow 45deg we start to have MEGNO=20 (i.e., close encounter happens), and from 20 deg to down we have MEGNO=10 (i.e., ejection of any of the particles). 

Hanno, do you have any particular suggestion, or opinion? Let me know if this interpretation is wrong to remove it.

**Comment by hannorein** [comment]
Your interpretation is correct. Any value larger than 2 can be considered chaotic. 

It makes sense that small differences (52.3deg vs 51.3deg) in the initial conditions can lead to large jumps in the Megno. The saparatrix can be complicated.

Also note that the Megno is only an indicator, not a mathematical proof of chaos. But the discussion quickly gets very philosophical, less practical.

There are rare cases where you might want to renormalize the variational particles to be able to integrate for longer timescales and thus get a better estimate of the Lyapunov exponent. But I think this is a rare case.

Hanno
