### ISSUE TITLE
Python: allow specification of z-axis limits on orbit plots

### ISSUE THREAD

**Issue by ajtribick** [hannorein/rebound#404]
It would be useful to be able to specify the axis range for the z-axis in the orbit plot when slices are enabled, currently this is not possible. The parameter name should presumably be `zlim`.

**Comment by hannorein** [comment]
That functionality is already implemented via the `slices` parameter. Try setting it to a floating point number between 0 and 1. 

If that is not good enough, note that `OrbitPlot` returns `fig, ax_main, ax_top, ax_right` and you can call `set_ylim()` on the axes yourself to fiddle with it and get exactly what you want.

(I initially did what you suggested and had something similar to a `zlim` parameter. Laying out the three plots with matplotlib is surprisingly/annoyingly complicated. )
