### ISSUE TITLE
Error messages while downloading the python version

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#409]
Hello, I was trying to download the python version of the code using pip install. But it returned the below error messages:

"
 Building wheel for rebound (setup.py) ... error
  ERROR: Complete output from command /Users/ZhexingLi/anaconda/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-install-tkyyiign/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-wheel-qjh9c06o --python-tag cp36:
  ERROR: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/simulation.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/horizons.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/widget.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/units.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/plotting.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/tools.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/interruptible_pool.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/simulationarchive.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/particle.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/data.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
  copying rebound/rebound.h -> build/lib.macosx-10.7-x86_64-3.6/rebound
  running build_ext
  building 'librebound' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ZhexingLi/anaconda/include -arch x86_64 -I/Users/ZhexingLi/anaconda/include -arch x86_64 -DLIBREBOUND -Isrc -I/Users/ZhexingLi/anaconda/include/python3.6m -c src/rebound.c -o build/temp.macosx-10.7-x86_64-3.6/src/rebound.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for rebound
  Running setup.py clean for rebound
Failed to build rebound
Installing collected packages: rebound
  Running setup.py install for rebound ... error
    ERROR: Complete output from command /Users/ZhexingLi/anaconda/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-install-tkyyiign/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-record-160yx51u/install-record.txt --single-version-externally-managed --compile:
    ERROR: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/simulation.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/horizons.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/widget.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/units.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/plotting.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/tools.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/interruptible_pool.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/simulationarchive.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/particle.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/data.py -> build/lib.macosx-10.7-x86_64-3.6/rebound
    copying rebound/rebound.h -> build/lib.macosx-10.7-x86_64-3.6/rebound
    running build_ext
    building 'librebound' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ZhexingLi/anaconda/include -arch x86_64 -I/Users/ZhexingLi/anaconda/include -arch x86_64 -DLIBREBOUND -Isrc -I/Users/ZhexingLi/anaconda/include/python3.6m -c src/rebound.c -o build/temp.macosx-10.7-x86_64-3.6/src/rebound.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/ZhexingLi/anaconda/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-install-tkyyiign/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-record-160yx51u/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ql/19_ssrzd6_b7gmt9byvrnhrm0000gn/T/pip-install-tkyyiign/rebound/
"

Can anyone help me and see what's going on here? Am I missing some applications to run this? Thanks in advance!

**Comment by hannorein** [comment]
I'm not familiar with conda, but just googling the error message suggests trying this command:

`xcode-select --install`

**Comment by hannorein** [comment]
I'll close this for now, but feel free to reopen it if you continue to have problems with the conda installation.

**Comment by zhexingli** [comment]
Thank you!

**Comment by zhexingli** [comment]
I understand that we can do pip install for python version and github link for C version. Is there a way to download the python version of rebound using github link instead of pip install?

**Comment by hannorein** [comment]
Just clone the repository, then run `pip install . `

**Comment by zhexingli** [comment]
if I simply do:
git clone https://github.com/hannorein/rebound.git
will it include the python version as well?

**Comment by zhexingli** [comment]
without running pip install

**Comment by hannorein** [comment]
I'd suggest you do a bit of research on how to install python packages in general. Maybe create a virtual environment...
