### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by kristianpedersen** [hannorein/rebound#410]
Python 3.7.2 64 bit
Windows 10.0.18363

First, I got an error about missing build tools, which I fixed.

Now, I'm stuck on this error (text version below):

![image](https://user-images.githubusercontent.com/5204369/74605397-0ec9aa00-50c8-11ea-84d4-7ab311fc5824.png)

**Comment by hannorein** [comment]
Windows is not supported.

**Comment by kristianpedersen** [comment]
I didn't see that mentioned anywhere. Did I miss it? Might save someone else the trouble.

**Comment by hannorein** [comment]
https://rebound.readthedocs.io/en/latest/python_quickstart.html

**Comment by kristianpedersen** [comment]
I got it working by using Ubuntu as my Windows command line:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by hannorein** [comment]
Glad to hear that you got it working!
