### ISSUE TITLE
Calling Rebound

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#411]
I successfully installed rebound through 'pip install' and can see the rebound folder in the main directory. But I'm unable to call rebound for some reasons in python. Does anyone have any idea of what's going on? I tried to uninstall and install again but it's the same problem.

For example, when I 'import rebound' in my script and did sim = rebound.Simulation(), python returns an error message saying 'module 'rebound' has no attribute 'Simulation'', leading me to wonder if installation is correct and complete...

**Comment by hannorein** [comment]
That sounds strange. Did you maybe accidentally create a directory or file with the name rebound? That could take preference when loading it with 'import rebound'. If you're not already doing it, try using a virtual environment.

**Comment by zhexingli** [comment]
Let me try the virtual environment.

**Comment by zhexingli** [comment]
You're right. This is silly. It turned out that I had a python file that is also called rebound... Changed the name and it's all good now.. Thx.

**Comment by hannorein** [comment]
I'm glad you got it working!
