### ISSUE TITLE
Legend for OrbitPlot

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#412]
Apologize for the lots of posts recently as I'm just getting familiarize with REBOUND. Is there a way to add a legend for OrbitPlot such as indicating which orbit belongs to which planet because a lot of times planet letter are not ordered according to their separation. Is it something that user can easily add or the developer has to edit in the source code?

**Comment by hannorein** [comment]
No worries about the posts! This is a rather specific request and will require some matplotlib hacking. Have a look at the source code of the OrbitPlot routine and see if you can adapt it to your needs.
