### ISSUE TITLE
Unit question in rebound

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#413]
Hello, I know the unit system in rebound is discussed in the documentation, but I still need some further clarification/confirmation because for some part I'm still a little bit confused. So the default unit system is in AU, Msun, and Yr/2pi. When I specified it at the beginning of the system as unit = 'AU, Msun, year', does everything in the inputs and outputs afterwards are in units of AU, Msun, and Year? For example, when I run the simulation for say 1 million years. All I need to specifiy is 1 million years in the input right? Not 1 million * 2*pi for the default case? Also, when specifying the time step, sim.dt, what unit is it in? Is it still in years in this case? Or fraction of the total running time? For this 1 million year case, if I want the time step to be 1 year, does sim.dt = 1 within the (AU,Msun, Year) unit system I specified? Or is it something else?

**Comment by dtamayo** [comment]
Yup! Once you set the units for time distance and mass, all parameters take values in those units, so dt is in years if you set it to 'years', and if you specify the physical radius of particles, it should be in AU if that's what you're using

**Comment by hannorein** [comment]
In case this helps with the confusion: all the unit system does is change the numerical value of the gravitational constant G in the code! So you could also completely ignore the unit system of REBOUND and just use whatever units you want. You just have to choose G consistently. 

I'll close this issue for now but feel free to reopen it!

**Comment by zhexingli** [comment]
Great, thx for the answers!

**Comment by zhexingli** [comment]
Sorry to keep asking this. I know the best unit system is when assuming G=1 and using solarmass, AU, and year/2pi system. But a lot of times I don't want to deal with the 2pi to avoid confusion sometimes so I often work with yr, AU, Msun unit system. However, when I run a test case with very short period of time: 10 years integration time and time step of sim.dt = 0.001 years, it keeps telling me that:

"RuntimeWarning: WHFast convergence issue. Timestep is larger than at least one orbital period.
  warnings.warn(msg[1:], RuntimeWarning)"

even though my shortest period is 20 times longer than provided sim.dt. So here's part of my code:

sim = rebound.Simulation()
sim.units = ('yr','AU','Msun')
sim.integrator = 'whfast'
sim.ri_whfast.safe_mode = 0
sim.dt = 0.001

sim.add(m=0.1977) # Star 
sim.add(m=3.18e-6, e=0.0, omega=np.pi/2, P=0.023789185489390827) # planet b
sim.add(m=3.63e-6, e=0.0, omega=np.pi/2, P=0.053484654346338124)  # planet c
sim.add(m=3e-6, e=e, omega=np.pi/2, P=P)
sim.move_to_com()

sim.init_megno()
sim.exit_max_distance = 100.
try:
     sim.integrate(10, exact_finish_time=0)
     megno = sim.calculate_megno()
     return megno
except rebound.Escape:
     return 10. # At least one particle got ejected, returning large MEGNO.


I don't think there's anything wrong with my code. Right? Is there anyway to get around this warning message without changing the unit system? Thank you.

**Comment by hannorein** [comment]
What is P in your code?

**Comment by zhexingli** [comment]
P for each planet is orbital period, in years.

**Comment by zhexingli** [comment]
sorry, one sec, some lines of code are missing here.

**Comment by zhexingli** [comment]
Here's how P is defined for the third planet

Ngrid = 100
par_P = np.linspace(0.023789185489390827,0.053484654346338124,Ngrid)
par_e = np.linspace(0.,0.3,Ngrid)
parameters = []
for e in par_e:
    for P in par_P:
        parameters.append((P,e))

**Comment by hannorein** [comment]
I suspect that one of these particles has a close encounter and then you will get this warning (rightly so). Do you have close encounters?

**Comment by zhexingli** [comment]
You're right. It's very likely for the test particle. Just to make sure, within my unit system, there isn't a problem with my code right? sim.dt is 0.001 years step size and in this test case integration time is 10 years correct?

**Comment by hannorein** [comment]
Yes, this shouldn't be related to the unit system. It's just that the encounter is not properly resolved. If you really want to hide the message, you can either make use of the python warnings package or set the variable `ri_whfast.timestep_warning` (`ri_whfast._timestep_warning` inpython) to `1`.

**Comment by zhexingli** [comment]
Ok got it . Thank you so much.
