### ISSUE TITLE
Progress output

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#415]
Is there a way for rebound to produce progress outputs during simulation integration so to let users know how much has been done and how much to go (such as a percentage estimate to completion)? Is there a flag somewhere that uses can turn on or it needs to be implemented in the future? Thanks.

**Comment by hannorein** [comment]
It depends a lot on the application. 
I typically do something like:

```
times = np.linspace(0.,tmax,100)
for i, t in enumerate(times):
    sim.integrate(t)
    print("done: %.2f%%" % (i/100))
```
