### ISSUE TITLE
Unable to install rebound with pip install rebound

### ISSUE THREAD

**Issue by Olivier-Lakoue** [hannorein/rebound#423]
Hello to All,

i leave in France and i eard about rebound wich seems to be a great api.

I use Anaconda/Jupyter Nb, I've triyed to install  with "pip install rebound" and i got errors.

Perhaps i've made a mistake, or take a wrong package ... can you help me ?

Thanks in advance.
Olivier.

  ----------------------------------------
  ERROR: Failed building wheel for rebound
  Running setup.py clean for rebound
Failed to build rebound
Installing collected packages: rebound
  Running setup.py install for rebound ... error

**Comment by hannorein** [comment]
Hi Oliver, 

I don't use anaconda myself and with the limited information you've posted, I really cannot helpt you out much.

Hanno

**Comment by Olivier-Lakoue** [comment]
hi Hanno,

Thanks for your quick answer.

I didn't want to send you complete error log, find it below.

I saw that you posted Jupyter Nb examples, how can you uses it without Anaconda ?

Many thanks for your help.

"C:\Users\A147701\" is my windows user path.

---------------

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\A147701\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"'; __file__='"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\A147701\AppData\Local\Temp\pip-wheel-t4koda3v' --python-tag cp37
       cwd: C:\Users\A147701\AppData\Local\Temp\pip-install-xnvjgl_j\rebound\
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\rebound
  copying rebound\data.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\horizons.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\interruptible_pool.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\particle.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\plotting.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\simulation.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\simulationarchive.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\tools.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\units.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\widget.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\__init__.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\rebound.h -> build\lib.win-amd64-3.7\rebound
  running build_ext
  building 'librebound' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DLIBREBOUND -Isrc -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/rebound.c /Fobuild\temp.win-amd64-3.7\Release\src/rebound.obj -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
  clÿ: Ligne de commande error D8021ÿ: argument num‚rique non valide '/Wno-unknown-pragmas'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for rebound
  Running setup.py clean for rebound
Failed to build rebound
Installing collected packages: rebound
  Running setup.py install for rebound ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\A147701\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"'; __file__='"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\A147701\AppData\Local\Temp\pip-record-nk895z2f\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\A147701\AppData\Local\Temp\pip-install-xnvjgl_j\rebound\
    Complete output (26 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\rebound
    copying rebound\data.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\horizons.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\interruptible_pool.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\particle.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\plotting.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\simulation.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\simulationarchive.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\tools.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\units.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\widget.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\__init__.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\rebound.h -> build\lib.win-amd64-3.7\rebound
    running build_ext
    building 'librebound' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DLIBREBOUND -Isrc -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/rebound.c /Fobuild\temp.win-amd64-3.7\Release\src/rebound.obj -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    clÿ: Ligne de commande error D8021ÿ: argument num‚rique non valide '/Wno-unknown-pragmas'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\A147701\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"'; __file__='"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\A147701\AppData\Local\Temp\pip-record-nk895z2f\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

(base) C:\Users\A147701>





ERROR: Command errored out with exit status 1:
   command: 'C:\Users\A147701\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"'; __file__='"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\A147701\AppData\Local\Temp\pip-wheel-t4koda3v' --python-tag cp37
       cwd: C:\Users\A147701\AppData\Local\Temp\pip-install-xnvjgl_j\rebound\
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\rebound
  copying rebound\data.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\horizons.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\interruptible_pool.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\particle.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\plotting.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\simulation.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\simulationarchive.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\tools.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\units.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\widget.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\__init__.py -> build\lib.win-amd64-3.7\rebound
  copying rebound\rebound.h -> build\lib.win-amd64-3.7\rebound
  running build_ext
  building 'librebound' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DLIBREBOUND -Isrc -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/rebound.c /Fobuild\temp.win-amd64-3.7\Release\src/rebound.obj -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
  clÿ: Ligne de commande error D8021ÿ: argument num‚rique non valide '/Wno-unknown-pragmas'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for rebound
  Running setup.py clean for rebound
Failed to build rebound
Installing collected packages: rebound
  Running setup.py install for rebound ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\A147701\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"'; __file__='"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\A147701\AppData\Local\Temp\pip-record-nk895z2f\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\A147701\AppData\Local\Temp\pip-install-xnvjgl_j\rebound\
    Complete output (26 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\rebound
    copying rebound\data.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\horizons.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\interruptible_pool.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\particle.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\plotting.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\simulation.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\simulationarchive.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\tools.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\units.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\widget.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\__init__.py -> build\lib.win-amd64-3.7\rebound
    copying rebound\rebound.h -> build\lib.win-amd64-3.7\rebound
    running build_ext
    building 'librebound' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DLIBREBOUND -Isrc -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include -IC:\Users\A147701\AppData\Local\Continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/rebound.c /Fobuild\temp.win-amd64-3.7\Release\src/rebound.obj -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    clÿ: Ligne de commande error D8021ÿ: argument num‚rique non valide '/Wno-unknown-pragmas'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\A147701\AppData\Local\Continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"'; __file__='"'"'C:\\Users\\A147701\\AppData\\Local\\Temp\\pip-install-xnvjgl_j\\rebound\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\A147701\AppData\Local\Temp\pip-record-nk895z2f\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by hannorein** [comment]
You're trying to install REBOUND on Windows. REBOUND is not compatible with Windows and needs linux/osx.

**Comment by Olivier-Lakoue** [comment]
Ok many thanks !

i have a linuw computer too, so i'll try with it.
Thanks a lot !
regards.
