### ISSUE TITLE
Orbital elements for Poincare canonical coordinates?

### ISSUE THREAD

**Issue by shadden** [hannorein/rebound#425]
Hi Hanno, 
  Is there currently any built-in functionality for computing orbital elements in heliocentric Poincare canonical coordinates? These coordinates use heliocentric positions but conjugate momenta based on the barycentric velocities as described in, e.g., Laskar & Robutel 1995 (https://ui.adsabs.harvard.edu/abs/1995CeMDA..62..193L/abstract). From what I gather, these elements aren't an option in the Simulation.calculate_orbits method. Are the underlying routines used by the Simulation.calculate_orbits method callable in python so that I could just use them with the appropriate position and velocity coordinates?
- Sam

**Comment by hannorein** [comment]
Are these different from the democratic heliocentric coordinates?

**Comment by hannorein** [comment]
If not, here's what you could do if you can calculate the positions and velocities manually:

```
p1 = rebound.Particle(m=1,x=1)
p2 = rebound.Particle(m=0,x=2,vy=1)
orbit = p2.calculate_orbit(primary=p1,G=1)
```

Maybe that helps?

**Comment by shadden** [comment]
Yes, I believe they are the same as democratic heliocentric coordinates

**Comment by dtamayo** [comment]
The terminology is super confusing (and somewhat confused) in different papers, but yes, I do think heliocentric positions and barycentric velocities are democratic heliocentric coordinates. Hernandez and Dehnen 2017 section 3.1 I think is very helpful for making the distinction clear.

I don't think there's any built-in functionality for calculating those orbital elements. I think you could hack it with something like

```
com = sim.calculate_com()
com.x = ps[0].x
com.y = ps[0].y
com.z = ps[0].z
orbit = ps[i].calculate_orbit(primary=com)
```

**Comment by shadden** [comment]
Thanks! The Morbidelli 2002 celestial mechanics book also appears to refer to these as democratic heliocentric coordinates

**Comment by dtamayo** [comment]
I think it's mostly Wisdom that refers to democratic heliocentric coordinates as 'canonical heliocentric coordinates'

**Comment by hannorein** [comment]
And in case it helps, here's how we calculate the democratic heliocentric coordinates (not the orbital elements):  https://github.com/hannorein/rebound/blob/master/src/transformations.c#L320

**Comment by acpetit** [comment]
Hey,

Technically they are only one set of canonical  heliocentric coordinates if you talk about the positions and momenta. The difference between the classical and democratic heliocentric orbital elements comes from the Hamiltonian splitting and to what you put in the Keplerian part and the indirect part.

Cheers,
Antoine

**Comment by shadden** [comment]
To add to Dan's nice hack, you also need to include something like:
`com.m = sim.particles[0].m`

Does Simulation.calculate_orbit use sim.G * (primary.m + particle.m) for period/semi-major axis conversion?

**Comment by hannorein** [comment]
Yes.

**Comment by dtamayo** [comment]
At least the way David defines them, the difference is in whether the momenta are related to barycentric velocities specifically (dem hel.) or general inertial velocities (what he calls 'can hel. coord'). But yes, I agree that the way you split the Hamiltonian matters, because that sets the mass that goes into the reduced 1-body problem and changes the orbital elements! 

In particular, the orbital elements implementation takes p.m + primary.m as the central mass in the reduced 1-body problem. So if you know what splitting you want to use and what you want to use (Hernandez and Dehnen 2017 Sec 4 reviews the various choices in the literature), then you can reverse engineer your com.m to give you what you want. 

Such a pain!

**Comment by hannorein** [comment]
I'll close this for now. Dan's trick seems to provide an easy way to calculate these elements if needed.

Also, it seems that anyone who wants to use these coordinates really needs to understand all the details. So, I think providing this as an out-of-the-box functionality within REBOUND might lead to more confusion than help.
