### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by green0range** [hannorein/rebound#426]
I get the following warning when running pytest: 

> ~/.anaconda3/lib/python3.7/site-packages/rebound/simulation.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>     from collections import MutableMapping

**Comment by hannorein** [comment]
Thanks. I'm not quite sure I understand the message, but I'll look into it.

**Comment by hannorein** [comment]
Took me a while to fix this. But thanks for pointing this out.
