### ISSUE TITLE
Error when using pip install rebound

### ISSUE THREAD

**Issue by tbstein** [hannorein/rebound#427]
Hello,
I tried to use 
`pip install rebound`
on fedora 31 but I got this error message. 

Thank you in advance.

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nr11xnhb/rebound/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nr11xnhb/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nu8bivzz/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/tobias/.local/include/python3.7m/rebound
         cwd: /tmp/pip-install-nr11xnhb/rebound/
    Complete output (123 lines):
    fatal: not a git repository (or any parent up to mount point /)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/rebound
    copying rebound/widget.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/units.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/tools.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/simulationarchive.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/simulation.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/plotting.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/particle.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/interruptible_pool.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/horizons.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/data.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/__init__.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/rebound.h -> build/lib.linux-x86_64-3.7/rebound
    running build_ext
    building 'librebound' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/rebound.c -o build/temp.linux-x86_64-3.7/src/rebound.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_ias15.c -o build/temp.linux-x86_64-3.7/src/integrator_ias15.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_whfast.c -o build/temp.linux-x86_64-3.7/src/integrator_whfast.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/integrator_whfast.c: In function ‘reb_integrator_whfast_init’:
    src/integrator_whfast.c:773:32: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      773 |     if (ri_whfast->allocated_N != N){
          |                                ^~
    src/integrator_whfast.c: In function ‘reb_integrator_whfast_part2’:
    src/integrator_whfast.c:1056:44: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
     1056 |             if (ri_whfast->allocated_Ntemp != N){
          |                                            ^~
    src/integrator_whfast.c:1070:36: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
     1070 |             for (unsigned int i=1;i<N;i++){
          |                                    ^
    src/integrator_whfast.c:1082:36: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
     1082 |             for (unsigned int i=1;i<N;i++){
          |                                    ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_saba.c -o build/temp.linux-x86_64-3.7/src/integrator_saba.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/integrator_saba.c: In function ‘reb_saba_corrector_step’:
    src/integrator_saba.c:155:44: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      155 |             if (ri_whfast->allocated_Ntemp != N){
          |                                            ^~
    src/integrator_saba.c:171:36: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      171 |             for (unsigned int i=1;i<N;i++){
          |                                    ^
    src/integrator_saba.c:183:36: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      183 |             for (unsigned int i=1;i<N;i++){
          |                                    ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_mercurius.c -o build/temp.linux-x86_64-3.7/src/integrator_mercurius.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/integrator_mercurius.c: In function ‘reb_mercurius_encounter_step’:
    src/integrator_mercurius.c:276:29: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      276 |     for (unsigned int i=0; i<r->N; i++){
          |                             ^
    src/integrator_mercurius.c:281:37: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      281 |             if (r->N_active==-1 || i<r->N_active){
          |                                     ^
    src/integrator_mercurius.c: In function ‘reb_integrator_mercurius_part1’:
    src/integrator_mercurius.c:359:30: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      359 |     if (rim->dcrit_allocatedN<N){
          |                              ^
    src/integrator_mercurius.c:369:24: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      369 |     if (rim->allocatedN<N){
          |                        ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_eos.c -o build/temp.linux-x86_64-3.7/src/integrator_eos.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/integrator_eos.c: In function ‘reb_integrator_eos_drift_shell1’:
    src/integrator_eos.c:359:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      359 |     for (int i=0;i<N;i++){
          |                   ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_leapfrog.c -o build/temp.linux-x86_64-3.7/src/integrator_leapfrog.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_janus.c -o build/temp.linux-x86_64-3.7/src/integrator_janus.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/integrator_janus.c: In function ‘reb_integrator_janus_synchronize’:
    src/integrator_janus.c:259:32: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
      259 |     if (r->ri_janus.allocated_N==r->N){
          |                                ^~
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator_sei.c -o build/temp.linux-x86_64-3.7/src/integrator_sei.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/integrator.c -o build/temp.linux-x86_64-3.7/src/integrator.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/integrator.c: In function ‘reb_update_acceleration’:
    src/integrator.c:183:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      183 |             if(r->N>r->ri_mercurius.allocatedN_additionalforces){
          |                    ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/gravity.c -o build/temp.linux-x86_64-3.7/src/gravity.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/boundary.c -o build/temp.linux-x86_64-3.7/src/boundary.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/display.c -o build/temp.linux-x86_64-3.7/src/display.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/display.c: In function ‘reb_display_copy_data’:
    src/display.c:1083:13: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
     1083 |     if (r->N>data->allocated_N){
          |             ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/collision.c -o build/temp.linux-x86_64-3.7/src/collision.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/collision.c: In function ‘reb_collision_search’:
    src/collision.c:188:25: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
      188 |                         if (rmin2_ab>rsum*rsum) continue;
          |                         ^~
    src/collision.c:191:7: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
      191 |       if (r->collisions_allocatedN<=collisions_N){
          |       ^~
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/tools.c -o build/temp.linux-x86_64-3.7/src/tools.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/derivatives.c -o build/temp.linux-x86_64-3.7/src/derivatives.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/tree.c -o build/temp.linux-x86_64-3.7/src/tree.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/particle.c -o build/temp.linux-x86_64-3.7/src/particle.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/particle.c: In function ‘reb_remove’:
    src/particle.c:227:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      227 |             for (int i=0;i<rim->encounterN;i++){
          |                           ^
    src/particle.c:235:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      235 |             if (index<rim->encounterNactive){
          |                      ^
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/binarydiff.c -o build/temp.linux-x86_64-3.7/src/binarydiff.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/output.c -o build/temp.linux-x86_64-3.7/src/output.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/input.c -o build/temp.linux-x86_64-3.7/src/input.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/simulationarchive.c -o build/temp.linux-x86_64-3.7/src/simulationarchive.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DLIBREBOUND -Isrc -I/usr/include/python3.7m -c src/transformations.c -o build/temp.linux-x86_64-3.7/src/transformations.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/transformations.c: In function ‘reb_transformations_whds_to_inertial_posvel’:
    src/transformations.c:301:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
      301 |     for (int i=1;i<N;i++){
          |                   ^
    gcc -pthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g build/temp.linux-x86_64-3.7/src/rebound.o build/temp.linux-x86_64-3.7/src/integrator_ias15.o build/temp.linux-x86_64-3.7/src/integrator_whfast.o build/temp.linux-x86_64-3.7/src/integrator_saba.o build/temp.linux-x86_64-3.7/src/integrator_mercurius.o build/temp.linux-x86_64-3.7/src/integrator_eos.o build/temp.linux-x86_64-3.7/src/integrator_leapfrog.o build/temp.linux-x86_64-3.7/src/integrator_janus.o build/temp.linux-x86_64-3.7/src/integrator_sei.o build/temp.linux-x86_64-3.7/src/integrator.o build/temp.linux-x86_64-3.7/src/gravity.o build/temp.linux-x86_64-3.7/src/boundary.o build/temp.linux-x86_64-3.7/src/display.o build/temp.linux-x86_64-3.7/src/collision.o build/temp.linux-x86_64-3.7/src/tools.o build/temp.linux-x86_64-3.7/src/derivatives.o build/temp.linux-x86_64-3.7/src/tree.o build/temp.linux-x86_64-3.7/src/particle.o build/temp.linux-x86_64-3.7/src/binarydiff.o build/temp.linux-x86_64-3.7/src/output.o build/temp.linux-x86_64-3.7/src/input.o build/temp.linux-x86_64-3.7/src/simulationarchive.o build/temp.linux-x86_64-3.7/src/transformations.o -L/usr/lib64 -lpython3.7m -o build/lib.linux-x86_64-3.7/librebound.cpython-37m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lpython3.7m
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nr11xnhb/rebound/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nr11xnhb/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nu8bivzz/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/tobias/.local/include/python3.7m/rebound Check the logs for full command output.

**Comment by hannorein** [comment]
Hello Stranger,

I'm not sure this is a rebound problem. It looks like pip cannot find the python library to link against. Putting the error message in a search engine suggests you try installing the python-dev tools:

https://stackoverflow.com/questions/8400272/usr-bin-ld-cannot-find-lpython2-7

Hanno

**Comment by tbstein** [comment]
Hello Hanno,
thank you for telling me that this isn't a rebound problem. Sadly none of the proposed solutions in your link helped me. I'll try to look for other people having similar pip problems now. Thank you for helping.

Tobias

**Comment by hannorein** [comment]
Hi Tobias, 

Ok. Again, it looks to me as if you need to install python dev tools and/or sort out some path issues on your system. I'll close this for now but if you think it's an issue with REBOUND after all, please feel free to reopen it!

Hanno
