### ISSUE TITLE
Possible bug(s) in collision detection with MERCURIUS

### ISSUE THREAD

**Issue by christophb02** [hannorein/rebound#428]
Hello Hanno,

while working with MERCURIUS I realized that the designated collision search routine "REB_COLLISION_MERCURIUS" is actually not implemented (in collision.c) ... is this a bug (because special treatment for MERCURIUS appears to be already included for REB_COLLISION_DIRECT) or a feature yet to come?

And while looking through the implementation I found something else - line 60 of collision.c - could there be an "else" missing?!

Thank you for your great work and help!

All the best and stay safe,
Christoph Burger

**Comment by hannorein** [comment]
Hi Christoph,

`REB_COLLISION_MERCURIUS` is just a place holder at this point. The (direct) collision search is called directly from within the integrator. I should update the comment in the rebound.h file (this is the only place it still exists).

Regarding the missing `else`. Hm. Yes. I think you're right. I need to think about the logic a bit more and go through the commits to see where the error comes from (it's been so long!). 

Thanks for pointing this out. 

Hanno

**Comment by christophb02** [comment]
Just saw the fix, thanks a lot for the quick response!

Christoph

**Comment by hannorein** [comment]
Thank you for noticing it!
