### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by Wonby** [hannorein/rebound#429]
display.c: 50: 24: Fatal error: GLFW / glfw3.h: No such file or directory
  #include <GLFW / glfw3.h>

Thanks

**Comment by hannorein** [comment]
If you want to use the OpenGL visualization then you need to install GLFW3.

**Comment by hannorein** [comment]
I'll close this for now, but if feel free to open it again if you continue to have problems.

**Comment by Wonby** [comment]
Thanks a lot! problem solved!
