### ISSUE TITLE
Bug with MERCURIUS and exact_finish_time=1?

### ISSUE THREAD

**Issue by christophb02** [hannorein/rebound#434]
Hi Hanno,

I believe I have found another bug connected to MERCURIUS. I integrate a simple test system and everything looks fine, except for the end state, i.e. after the very last timestep (I found it by monitoring the total energy). Took me quite a while to narrow it down, but then I realized that it only happens when setting `exact_finish_time` to 1.
I think the problem is that the coordinates seem to be updated to/from democratic-heliocentric in place for MERCURIUS (unlike with WHFast), which means that whenever synchronizing you end up with inertial coordinates, and have to transform back before the next timestep. This back-transformation appears to be missing after the synchronization in line 639 and/or 644 in the `reb_check_exit()` function in `rebound.c`, which means that the very last (reduced) timestep is then wrongly computed in inertial coordinates?! I have also tested fixing the problem by directly inserting a `ri_mercurius.recalculate_coordinates_this_timestep = 1` after the synchronization(s) and it works!

This also made me thinking whether it might be a good idea to place a `ri_mercurius.recalculate_coordinates_this_timestep = 1` directly in `reb_integrator_mercurius_synchronize()` since whenever synchronizing MERCURIUS you want to transform back to democratic-heliocentric at the beginning of the next timestep anyway?

Hope this makes sense to you and I am not missing something here :-)

Thank's a lot!
Christoph Burger

**Comment by hannorein** [comment]
Hi Christoph,

Thanks a lot for the detailed bug report! And sorry for the slow response. I think what you say makes sense. Let me think about it for a bit and come up with a good unit test for it...

Hanno

**Comment by hannorein** [comment]
Sorry that it took me so long. Everything you said was correct! The fix you proposed sounds good, at least I could not come up with any obvious side effects (although time might prove me wrong). Thank you so much for digging into it and even proposing a solution! Much appreciated!


For reference, here is a short code snippet which reproduces the dependence on `exact_finish_time` before c22f47a. It works in the latest version. 

```
import rebound
import rebound.data
import numpy as np
sim = rebound.Simulation()
rebound.data.add_outer_solar_system(sim)
sim.integrator = "mercurius"
sim.ri_mercurius.safe_mode = 0
sim.dt = sim.particles[1].P/30.
E0 = sim.calculate_energy()
sim.integrate(10,exact_finish_time=1)
E1 = sim.calculate_energy()
print(np.abs((E1-E0)/E0))
```

**Comment by christophb02** [comment]
Hi Hanno,

my pleasure! I'm happy if I can give something back :-) And no need to apologize of course, you always respond very quickly!

I have also some "bad news" unfortunately ... when thinking through the changes and their effects on the MERCURIUS integration step logic, I found another potential issue. In `reb_integrator_mercurius_part1()` (in `integrator_mercurius.c`) the recalculation of dcrit is done (starting at line 386) once triggered by setting `recalculate_dcrit_this_timestep` to 1 before (e.g., by the user in heartbeat). If this happens without prior synchronization then synchronization is triggered here (line 389), but this would leave the `particles` array in inertial coordinates, which would be bad for the subsequent computation of dcrit (which assumes dem.-hel. coord.) and especially also for the upcoming timestep to be integrated (which also requires dem.-hel. coord. if I'm not mistaken).
It appears that the underlying problem is that the `is_synchronized` flag does not contain all the necessary information, because it doesn't tell whether the `particles` array is still in inertial or already in dem.-hel. coordinates (with WHFast this isn't an issue because there the coordinate transformations happen not in-place but in a separate array).
A possible solution would be to run `reb_integrator_mercurius_inertial_to_dh()` after the synchronization in line 389 I think (if that fixes all possible combinations then?!).

Does this make sense to you? This time I didn't encounter the problem when running the code but only when thinking through the logic, so hope I didn't miss anything crucial!

Thanks a lot for all your help!
Christoph

**Comment by hannorein** [comment]
Hi Christoph,

Thanks for that. Your solution looks good. I think I'll add a `recalculate_coordinates_this_timestep=0` afterwards as well. Otherwise it will unnecessarily recalculate the coordinates again during the next timestep (`recalculate_coordinates_this_timestep=1` is set by `synchronize`).

Thanks again,
  Hanno

**Comment by christophb02** [comment]
Oh yes, now it's perfect, and seems to cover all possible combinations.

Thanks so much,
Christoph
