### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by emeraldcri** [hannorein/rebound#435]
Hi, since my computer runs Windows I've installed a virtual machine running Linux to install Rebound. When I tried to install rebound with `pip install rebound` it gave me an error, i wanted to know what is the problem and if there is some way to solve it.

This is what happened when i tried to install rebound:

Collecting rebound
  Using cached rebound-3.12.1.tar.gz (241 kB)
Building wheels for collected packages: rebound
  Building wheel for rebound (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cri/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6u_7kiye/rebound/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6u_7kiye/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nhft6wt0
       cwd: /tmp/pip-install-6u_7kiye/rebound/
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/rebound
  copying rebound/widget.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/units.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/particle.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/data.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/tools.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/interruptible_pool.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/horizons.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/plotting.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/__init__.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/simulation.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/simulationarchive.py -> build/lib.linux-x86_64-3.7/rebound
  copying rebound/rebound.h -> build/lib.linux-x86_64-3.7/rebound
  running build_ext
  building 'librebound' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  gcc -pthread -B /home/cri/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DLIBREBOUND -Isrc -I/home/cri/anaconda3/include/python3.7m -c src/rebound.c -o build/temp.linux-x86_64-3.7/src/rebound.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
  src/rebound.c:25:10: fatal error: stdio.h: No such file or directory
   #include <stdio.h>
            ^~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for rebound
  Running setup.py clean for rebound
Failed to build rebound
Installing collected packages: rebound
    Running setup.py install for rebound ... error
    ERROR: Command errored out with exit status 1:
     command: /home/cri/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6u_7kiye/rebound/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6u_7kiye/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sm19v2eo/install-record.txt --single-version-externally-managed --compile --install-headers /home/cri/anaconda3/include/python3.7m/rebound
         cwd: /tmp/pip-install-6u_7kiye/rebound/
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/rebound
    copying rebound/widget.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/units.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/particle.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/data.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/tools.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/interruptible_pool.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/horizons.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/plotting.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/__init__.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/simulation.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/simulationarchive.py -> build/lib.linux-x86_64-3.7/rebound
    copying rebound/rebound.h -> build/lib.linux-x86_64-3.7/rebound
    running build_ext
    building 'librebound' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -B /home/cri/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DLIBREBOUND -Isrc -I/home/cri/anaconda3/include/python3.7m -c src/rebound.c -o build/temp.linux-x86_64-3.7/src/rebound.o -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=d15889dce6327b47ace8111b0b376361aba81ff9 -DLIBREBOUND -D_GNU_SOURCE -fPIC
    src/rebound.c:25:10: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
              ^~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/cri/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6u_7kiye/rebound/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6u_7kiye/rebound/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-sm19v2eo/install-record.txt --single-version-externally-managed --compile --install-headers /home/cri/anaconda3/include/python3.7m/rebound Check the logs for full command output.

**Comment by hannorein** [comment]
When I google the error message, it suggests that you need to install some of the development tools with your packet manager. I.e. 

    sudo apt-get install libc6-dev

**Comment by emeraldcri** [comment]
Ok, thanks for replying

**Comment by evellynnat** [comment]
Thank you! I was having the same problem
