### ISSUE TITLE
WHFAST and MERCURIUS : additional_forces "averages" the real evolution?

### ISSUE THREAD

**Issue by rafanw72** [hannorein/rebound#438]
Hi Hanno, 

I was trying to use an additional force using MERCURIUS that depends only on the positions of the particles. It works but the eccentricity evolution of the particle (affected by my additional force) shows the average of its "real evolution". Using IAS15 everything works very well!  Please, look at the graphs below. 

My questions are:" Is there anything more than "r->additional_forces" that I need to use to MERCURIUS integrator adding an additional force? " What does the public member " unsigned int allocatedN_additionalforces" means? 

 The black curve represents the "real evolution" whereas the red curve represents the evolution of the eccentricity of the particle using the additional force. 

![mercurius_e_t_hill3](https://user-images.githubusercontent.com/44381852/81517799-674cc400-9312-11ea-9eb0-ac01f3bc1344.png)
 Fig 1.: Eccentricity's evolution using MERCURIUS and an additional force. 
 
![ias15_max_precision_e_t](https://user-images.githubusercontent.com/44381852/81517839-80ee0b80-9312-11ea-9837-b098e43c176e.png)
 Fig 2.: Eccentricity's evolution using IAS15 and additional force:

Thank you very much for your help, 

Cheers, 

Rafael Ribeiro

**Comment by hannorein** [comment]
I don't quite understand what you mean when referring to the various "real", "interpolating", "non-interpolating" evolutions. Why are there four curves?

The additional forces should just work the same way as with IAS15. The `allocatedN_additionalforces` variable is for internal use only. 

Maybe you can post a short (emphasis on short) piece of code?

**Comment by rafanw72** [comment]
Thank you for answering me so fast!  Sure, I'm sorry for not being clear enough. 

I integrated a test particle suffering the effects of artificial forces that mimic the perturbations of the giant planets. 

Then, I compared the eccentricity evolution of this particle with the artificial forces and without them. The case without artificial forces (I'm calling "real evolution case" or "non-interpolating evolution") I used the giant planets like active particles in the simulation using MERCURIUS integrator.
  
The black curves in Fig 1 and 2 are the same and represent the "real evolution case" with MERCURIUS: test particle + giant planets. 

The red curve in Fig. 1 represents the artificial case (or "interpolating evolutions"), i.e, test particle + artificial forces that mimic the perturbation of giant planets using MERCURIUS. 

The red curve in Fig. 2 represents the same artificial case that Fig.1 but using IAS15. 

As you can see, the artificial case with IAS15 resembles very well with what I expected compared with the "real evolution case". Although using MERCURIUS the eccentricity evolution is like the average of the eccentricity of the "real evolution case". 

Once that you say that the additional forces should work the same way as with IAS15, I was wondering what happened here. 

Ok, I will post a short piece of code to represent that.

Thank you very much, 

Rafael Ribeiro

**Comment by hannorein** [comment]
Again, should be ok. 

1) Do you have `safe_mode=1`?
2) Do you have the critical radii large enough so that it is not constantly being integrated with IAS within MERCURIUS? (additional forces are not applied during encounters)

**Comment by rafanw72** [comment]
Yes, I do! 
I think it should be ok. I'll close this issue for now and do more tests. 

I'll let you know! 

Thank you!
