### ISSUE TITLE
Dockerhub image for use with Kogence

### ISSUE THREAD

**Issue by gravitas21** [hannorein/rebound#439]
Hi Hanno,
Is there any pre-existing docker image for rebound repository so I can load models into the Kogence platform and run them? If it is possible, can I fork away the repo and create a docker image from that? I am currently using rebound simulations for my thesis here in Nepal and I want to leverage any help Kogence resources could provide since computing resources are a bit short in the developing world. Or let me know if there are any other platforms more suited for this purpose.
Query response on Kogence forum: https://kogence.com/app/wiki/index.php?title=Topic:Vm5iiivqnsv7y1et&topic_showPostId=vm5wr4qzai5mwrs5&fromnotif=1#flow-post-vm5wr4qzai5mwrs5 

Lastly, thank you very much for this brilliant open-source library, its really doing its bit for bridging the gap in the research that can be done in astrophysics.

**Comment by hannorein** [comment]
Hi,

I don't think there is an existing REBOUND docker image that is readily available. But I don't see a reason why not. Seems pretty straightforward!

Hanno

**Comment by gravitas21** [comment]
Great! I'll let you know when it's done.

**Comment by gravitas21** [comment]
Hello Hanno, so I made an ephemeral type rebound project, the project is public and those with good experience with rebound and bash scripting can modify accordingly. As for the docker image, my Win10 Home OS doesn't support docker so anyone with MacOS or Linux, feel free to try and set up a permanent type model for rebound on kogence. Thank you!

Link: https://kogence.com/app/docs/Rebound

**Comment by hannorein** [comment]
Thanks a lot. I might look into using this in the future! I'll close the issue for now (people searching for an image should be able to find it).
