### ISSUE TITLE
Possible mix-up of indices in particles array upon collision resolve?

### ISSUE THREAD

**Issue by christophb02** [hannorein/rebound#440]
Hi Hanno,

first of all let me apologize that I have to bother you so often in recent weeks!

I may have found an issue:
After each timestep `reb_collision_search()` is called. In this function, first all pairs of colliding bodies are identified and stored in the `collisions` array, via their indices in the `particles` array. After that all found collisions are looped over, and the `collision_resolve` callback function is called for each one. In this function the user can either directly deal with the collision (e.g., remove bodies) or set the respective return value to let Rebound remove bodies if desired.
Isn't it a fundamental problem then that the `collisions` array contains only a static list of index-pairs (indices in the `particles` array)? For example, if two (or more) collisions are detected, and, say, when treating the first one by removing one of the colliding bodies, then the (static) information in the `collisions` array (the index-pairs) becomes outdated (once the subsequent collision is processed) since indices in the `particles` array have changed due to removing the body before?!

Does this make sense to you, or have I missed something?
This has been bothering me for some time now, and up to now I have circumvented the (potential) issue by first collecting all the hashes and then dealing with collisions in heartbeat, which is called after each call to the collision search, but that's not true for MERCURIUS anymore, where collisions are detected (and resolved) in the encounter step (without running heartbeat everytime). This is very deep inside our complex hybrid-code and I can't come up with a straight-forward test setup, so it's possible that I have simply missed something essential here?!

Thanks for your help and All the Best!
Christoph Burger

**Comment by hannorein** [comment]
Hi Christoph,

I think you might be right. The limit you're working in (removing many particles in a given timestep) is not one I've tested before. So far, I've either considered cases with many collisions but without removing particles (Saturn's rings), or cases where particles collide rarely (unstable planetary systems). But that's not a good excuse!

However, note that even when fixing the indexing problem, there is still a problem. When you modify/remove a particle, you should have to redo the entire collisions search because any trajectory could have changed. So a "perfect" collisions detection algorithm is this:

1) Search for collisions
2) Sort them by time
3) Resolve the first one
4) Go back to 1) until there are no more collisions. 

That would be unreasonably slow and complex, so we have to cut corners somewhere. I'll think about the indexing problem. I think this could be improved (not sure about fixing every possible case) in this loop here: https://github.com/hannorein/rebound/blob/master/src/collision.c#L365

Thanks for digging into this and letting me know!
Hanno

**Comment by hannorein** [comment]
Actually, line 372 in that function might already do something like this. But it might not work in all cases, i.e. where the keep-sorted flag is set to 1.

**Comment by hannorein** [comment]
Hi Christoph, 

Although it might be impossible to come up with a satisfactory solution for every case, what are the specific settings for your hybrid use case. 

- Mercurius (I assume)
- What is collision_resolve_keep_sorted set to?
- What is the typical number of particles?
- Do you use test particles? If so, whats the typical number?

Since you noticed this issue, it seems that you get multiple collisions in one timestep. Can you elaborate a bit why you get so many collisions? Or is this a rare event that just happens to mess up things?

Thanks!
  Hanno

**Comment by christophb02** [comment]
Hi Hanno,

thanks for the quick response!

Our use cases so far were indeed systems where collisions are rare - along the lines of dozens of embryos (active bodies) + hundreds of planetesimals (testparticle type 1) distributed in the terrestrial planet region around a solar-type star. So in principle, and when using MERCURIUS, actual physical collisions are certainly rare. However, we plan to simulate earlier phases with a large number of collisionally interacting planetesimals in the future too. But besides that, even in our current use cases there are many potential pitfalls: In order to detect physical collisions already in advance I set a Rebound radius which is considerably larger than the actual bodies and find actual (physical) collisions by evaluating the two-body orbit once Rebound signals a "collision" (I found this to be an elegant way to know in advance when and how bodies will collide and can start a respective SPH collision sim accordingly, without the need of simulating the whole system backwards in time). Another point that comes to my mind is that I am experimenting with a functionality where planetesimals (testparticles) are "activated" (I convert them to active bodies) whenever they have mutual close encounters, in order to approximately include dynamical friction among them. In all those cases it can well happen that two or more "collisions" (i.e., overlapping Rebound radii) occur in parallel, so even if rare, there is potential for erroneous results - imagine that instead of removing an embryo, a gas giant is removed (if both are active bodies and indices get mixed up this may happen sooner or later...). Back to your question - we use MERCURIUS, but also a version of our hybrid framework with WHFast + IAS15, where the whole system is integrated with IAS15 during encounters (sounds brute force but works surprisingly well in some applications).

If the problem is not solved, I believe the user should at least be clearly warned in such a case, because as it is now it is not really obvious that this problem can occur. Even when looking into the code there is for example the randomization of the `collisions` array, which happens directly before the collision callback function (`collision_resolve`) is called for each, and this gives the strong impression that the code is well equipped for treating also several collisions in parallel (at least that gave me this impression until i dug deeper a couple of days ago).

I am actually not sure about the additional problem that you see if the index issue were fixed - why should trajectories of other bodies vary if some collision is resolved? Isn't the collision search and resolve well defined by:

> At some time t, first all colliding pairs are identified (by overlapping Rebound radii), then (after randomization) for each pair `collision_resolve` is called, whose return value signals whether and which of the colliding bodies are to be removed.

Or are you maybe thinking about the other collision search algorithms (LINE, LINETREE, ...)? Perhaps I am biased towards the DIRECT search here...

Giving this some more thought: May it be a solution to handle the indexing issue in `reb_remove()`? It is called whenever `collision_resolve` signals to remove one or both bodies, and should be the only place where index changes occur?! If so, the whole `collisions` array could be checked and if necessary corrected for all index changes in `reb_remove()`. This shouldn't be run-time-critical, even if `collision_resolve_keep_sorted=1` I suppose (as long as only few collisions occur per timestep and removals are not extremely frequent). Even if not perfect (e.g., due to the potential trajectory changes you mentioned), this would at least prevent potentially erroneous outcomes like removing the wrong body/index.

Oh, and it just also occurred to me that a return value of 3 of `collision_resolve` (signalling to remove both bodies) may regularly result in index issues, because the removal of the two bodies is done consecutively in `reb_collision_search()`?!
(Perhaps I am missing something obvious, it's already pretty late here ;-)

Thanks (and sorry for the long message)!
Christoph

**Comment by hannorein** [comment]
There are many really tricky cases. Think of Newton's cradle. Resolving something like that with a large timestep would really go beyond what REBOUND is doing. 

What you describe at the end is exactly what I suggested too. Most of the logic is already there (https://github.com/hannorein/rebound/blob/master/src/collision.c#L365), it's just not working. I'll look into it.

**Comment by christophb02** [comment]
I see your point. Once several collisions are detected and some of them involve the same bodies then you can of course run into race conditions when resolving them sequentially (but I think it can be assumed that a user is aware of this obvious problem). I was thinking more about the simpler case where several collisions may occur in parallel, but without any body being in more than one collision at a time, so that they can be treated independently and the order of treatment doesn't matter.

I actually suggested to implement it inside `reb_remove()`, because that's where the potential index reordering happens (and this information is thus readily available), instead of the for-loops you pointed to. On the other hand in the for-loops you directly have the information which collisions are yet to be processed, which is not available inside `reb_remove()` ... so it's tricky either way I guess :-) 

Thanks for looking into this! It will definitely help our hybrid code efforts once we can omit the logic to deal with those index issues!

All the Best,
Christoph

**Comment by hannorein** [comment]
Some notes (mainly for myself):

- The default behaviour will be that multiple collisions will be allowed for the same particle in the same timestep. The user can overwrite this in the collisions resolve routine by checking a particles `last_collision` parameter
- Resolving the collisions in the right order will not be guaranteed.

**Comment by hannorein** [comment]
I *think* the latest push to the `collisionlogic` branch should work. As usual, taking into account all possible combinations, the logic turned out way more complicated than it appeared at first. I'm kind of surprised anything at all work in the first place. I'll stare at it for a little longer and might add some unit tests, then merge it into the master branch. 

Thanks again for pointing this out. Fixing this was long overdue...

**Comment by christophb02** [comment]
Thank you very much for solving this! It looks good now, and should work for the scenarios and parameter settings we are using as far as I can see.

Thanks again and All the Best,
Christoph
