### ISSUE TITLE
Retrogade Orbit question - orbital elements

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#443]
Hello,

I am using REBOUND to study retrograde orbits, however I have been getting strange angular values ​​for my orbital elements, different from those described in the range of [-pi,pi].

Could I be doing something wrong or forgetting some detail?

This is my data output:

```
MAX/MIN VALUE Omega : 3.140180937928993 / -3.139379856132213
MAX/MIN VALUE omega : 5.806793034685439 / -5.946449257228306
MAX/MIN VALUE lambda : 6.196697412788598 / -6.1850029209217885
MAX/MIN VALUE M : 3.134145867240421 / -3.138567527404079
MAX/MIN VALUE pomega : 3.1381749249953717 / -3.1387644338407585
MAX/MIN VALUE f : 5.953787842000865 / -5.843698007300172
MAX/MIN VALUE : 3.1394181200392794 / -3.139904737069269
```
As I understand it REBOUND returns only values ​​within [-pi, pi] for orbital elements.

This is my code:

```

import numpy as np
import rebound
import matplotlib.pyplot as plt

timepoints = 2000
datapoints = 18
mu=0.001

ptest_data = np.zeros((datapoints,timepoints))
t = []

sim = rebound.Simulation()
sim.units = "yr","Msun","AU"
sim.add(m=(1-mu)) # Star
sim.add(m=mu, a=1, e=0,primary=sim.particles[0])
sim.add(a=1.6, e=0.5, inc=np.pi,primary=sim.particles[0])
print("G = {0}.".format(sim.G))
sim.dt = 0.001
sim.move_to_com()
time = np.linspace(0,300000,timepoints)
sim.status()
#sim.init_megno()
pp = sim.particles

for i,times in enumerate(time):
    sim.integrate(times)

    t.append(sim.t)
    ptest_data[0][i] = pp[2].x
    ptest_data[1][i] = pp[2].y
    ptest_data[2][i] = pp[2].vx
    ptest_data[3][i] = pp[2].vy
    ptest_data[16][i] = pp[2].z
    ptest_data[17][i] = pp[2].vz

    ptest_data[4][i] = pp[2].calculate_orbit(primary = pp[0]).a
    ptest_data[5][i] = pp[2].calculate_orbit(primary = pp[0]).e
    ptest_data[6][i] = pp[2].calculate_orbit(primary = pp[0]).n
    ptest_data[7][i] = pp[2].calculate_orbit(primary = pp[0]).Omega
    ptest_data[8][i] = pp[2].calculate_orbit(primary = pp[0]).omega
    ptest_data[9][i] = pp[2].calculate_orbit(primary = pp[0]).l
    ptest_data[10][i] = pp[2].calculate_orbit(primary = pp[0]).M
    ptest_data[11][i] = pp[2].calculate_orbit(primary = pp[0]).pomega
    ptest_data[12][i] = pp[2].calculate_orbit(primary = pp[0]).f
    ptest_data[13][i] = pp[2].calculate_orbit(primary = pp[0]).theta
    #ptest_data[14][i] = sim.calculate_megno()
    ptest_data[14][i] = 0
    ptest_data[15][i] = pp[2].calculate_orbit(primary = pp[0]).inc

sim.status()

```

**Comment by dtamayo** [comment]
Are the angles incorrect, or just not within -pi,pi? Note that at Inc=pi,
several of your angles are actually undefined, eg Omega, and any angle
measured from the node (like Omega)

**Comment by dtamayo** [comment]
I meant angles measured from the node (like omega) (lowercase!)

**Comment by gabiruzo** [comment]
I think just not within -pi,pi. 

As I understand it, if I don't define the angles initially they will start with 0 and that's what I'm getting for t = 0. But I believe the problem is that some of them are out of -pi, pi. 
The correct value for omega would be within the range of -pi, pi, right ?

**Comment by hannorein** [comment]
Note that you can add or subtract 2*pi from the angles as many times as you want. That way you can get it into the range that you want. Adding or subtracting 2*pi from any angles does not change the orbit.

**Comment by gabiruzo** [comment]
Hello Daniel and Hanno. Thanks for helping, I apologize for being bothering with several questions recently.

I guessed the REBOUND automatic change angles to [-pi,pi].

If I need any more related to that I will reopen the topic.
