### ISSUE TITLE
Installing rebound in Python3.7

### ISSUE THREAD

**Issue by Moulane92** [hannorein/rebound#444]
Hi,

I have problem with rebound in Python3.7. It is working perfectly with python2.7.
I have installed with "pip3.7 install rebound" and it seems installed  in my repository. It shows:

Requirement already satisfied: rebound in /usr/local/lib/python3.7/site-packages (3.12.2)

But when I use it in Python3.7, it gave me an error !

Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rebound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rebound'
>>> 

Any idea ?

Thanks in advance
Youssef

**Comment by hannorein** [comment]
Hi Youssef, 

I don't think this is a problem specific to REBOUND. There seems to be some issue with python not finding the packages installed by pip. Do other packages work? You could try setting up a virtual environment (venv) and install REBOUND within the venv. That often helps with these sort of problems.

 Hanno

**Comment by Moulane92** [comment]
Hi Hanno,

Thanks for the prompt reply, It is really weird. Python3.7 is working well with all the other packages.
I already tried with a virtual environment (venv) as described here (https://rebound.readthedocs.io/en/latest/python_quickstart.html)

But doesn’t work too ?

Thank you,
Youssef

**Comment by Moulane92** [comment]
Hi Hanno,

OK, I solved it.

Thanks,
Youssef
