### ISSUE TITLE
collision problem

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#445]
Hello,

I  am facing difficulties in analyzing stability maps using the REBOUND. In my case, I expected collisions around the entire eccentricity 0.4 region (many of these orbits in this region are escaping and not colliding).
I am using the physical radius of the sun and jupiter for my example. Any tips ?

My code : 
```
import rebound
import numpy as np
import matplotlib.pyplot as plt
global mu
mu = 0.001


def simulation(par):
    a, e = par
    sim = rebound.Simulation()
    #sim.units = ('yr', 'AU', 'Msun')
    print(par)
    sim.add(m=(1-mu),r=0.0046422) # Star
    sim.add(m=0.001, a=1, e=0,l=0,r=0.00046607333333333,primary=sim.particles[0])
    sim.add(m=0, a=a, e=e, inc=np.pi,primary=sim.particles[0])
    sim.move_to_com()
    ps=sim.particles
    tyears = ps[1].P
    sim.init_megno()
    sim.exit_max_distance = 30.
    sim.collision = "linetree" #already tryed direct, line and tree
    try:
        sim.integrate(50000*tyears*2*np.pi) # integrate for 5e4 years 
        megno = sim.calculate_megno()
        if np.isnan(megno) == True :
            print(" NaN found possibly chaotic",par)
            return 10
        else:
            print(megno,par)
            return megno
    except rebound.Collision:
        print("collision",par)
        return 10.
    except rebound.Escape:
        print("escape", par)
        return 10. #
```
collision = direct
![direct](https://user-images.githubusercontent.com/53542579/87447185-a6c4b480-c5d0-11ea-87d7-2302e3ebee47.png)

collision = linetree
![linetree](https://user-images.githubusercontent.com/53542579/87447188-a75d4b00-c5d0-11ea-9dd2-d6eb955c6332.png)

I expected something closer to that

![expect](https://user-images.githubusercontent.com/53542579/87447383-e55a6f00-c5d0-11ea-90d8-e6c12836c4b9.PNG)
reference: https://link.springer.com/article/10.1007/s40314-015-0295-3

Could this expressive difference be related to the integrators IAS15 and Bulirsch Stoer ?

**Comment by hannorein** [comment]
Hm. Your code looks good to me. (use the direct collision detection method for simulations like this).

And your results are not completely wrong either, just not nearly as clean as the result in the paper. 

I'm really not sure what to suggest. It could be that there is an issue because of the retrograde orbits. It looks like you're using IAS15. Retrograde orbits might require you to have a very small timestep to not miss the interactions at a conjunction. IAS15 might not pick that up automatically. You could try choosing a fixed timestep and play around with it to see if that changes your results.

**Comment by gabiruzo** [comment]
Hello Hanno,

To select the desired timestep using IAS15, it is necessary to add only `sim.dt = value` or I need to add some more code ? 
I am thinking of a value around `dt = 0.0001 - 0.00001` as the initial value for the test.

**Comment by hannorein** [comment]
No, you also need to set epsilon to zero.

https://rebound.readthedocs.io/en/latest/c_api_integratorstructs.html#_CPPv4N31reb_simulation_integrator_ias157epsilonE

**Comment by hannorein** [comment]
Here's how I would estimate the timestep: It needs to be small enough so that the planets cannot pass through their mutual Hill sphere in one timestep. If they are on retrograde orbits, the relative speed between the two planets is large, thus the timestep should be small.

**Comment by gabiruzo** [comment]
Ok, I got it.
I believe I should use the command `sim.ri_ias.epsilon = 0` in this case to remove the adaptive step. As described in the source code https://rebound.readthedocs.io/en/latest/_modules/rebound/simulation.html
I'll try it and see what happens.
Thanks for the help and the tips.

**Comment by gabiruzo** [comment]
Hi Hanno,

I'm running the simulation using a fixed timestep, but the calculation is a little slow. In the meantime I thought I could test other options as well, one of my ideas is to change the value of epsilon in order to make the timestep a little more accurate for my case. What do you think ? I could study more about the integrator in C / Python and think about some possibility.

**Comment by hannorein** [comment]
I think these are challenging simulations, so it's not surprising that they are slow. 

I would advice against changing epsilon. IAS is a high order integrator, it's either converged, or not converged at all. 

You could try using WHFast for these integrations which might be more appropriate anyway.

**Comment by gabiruzo** [comment]
Hello,

After some tests and a detailed reading on the integrator IAS15 paper I am convinced that the result obtained above is the real result, because as described the integrator shows better results than the integrators MVS, BS, RADAU ... etc.
I'm just not sure about the initial dt (dt_trial) which value to use so that there is no problem in the first steps as escaping orbits.
furthermore the calculation with `epsilon = 0` is still running (my simulation machine is not the best) and looking at the data in a rough way I didn't see any significant changes in the results
I also used `WHFast` to obtain the map and compare the results with `IAS15` I noticed similar results,which supports the fact that is correct.

However, I still have a doubt about the collision modules, as I am working with a two-dimensional problem the most attractive module would be `SWEEP` due to its description. Is this module active / implemented? wouldn't he be the best for this problem?

`LINETREE` also seems to be very interesting for this case due to the overlap of trajectories. From what I was able to understand from the IAS15 paper, the relationship between the speed of the bodies can affect the constants that define the timesteps (which I think can happen next to the conjunctions for the retrograde orbit). Wouldn't this module also be more interesting than the direct?

**Comment by hannorein** [comment]
You should definitely use the DIRECT collision module. The other modules are for planetary rings and other systems which have a very high collision frequency. 

Furthermore, your results should not depend on physical collisions. Whenever two planets enter their mutual hill sphere, you will get random behaviour. The physical radius should be much smaller than the hill radius. 

If I were to run the simulations, I would use:
- the DIRECT collision routine with particle radii set to their hill radius
- WHFast integrator with a timestep calculated as I described above
- do a convergence study to make sure my timestep is small enough.

**Comment by gabiruzo** [comment]
Hey Hanno,
I believe my doubts have been answered. Thank you very much for your attention.
I think we can close the topic, what do you think?

**Comment by hannorein** [comment]
Sure. Feel free to reopen another issue if anything comes up. I'm happy to help...
