### ISSUE TITLE
Coordinates System

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#451]
Hello,

I've been finding it difficult to convert my inertial system to a synodic system and I would like to check some things related to my Poincaré sections.

1) As far as I could understand when using the command sim.move_to_com () the system will be moved to the baricenter, then the output coordinates of the integration of this system will be baricentric?

2) As I have been working with PCR3BP I hope that my jacobi constant will be maintained throughout the integration, and I only get reasonable values ​​of the C variation when I use the Jacobi integral for Jacobian coordinates in the inertial frame, described below.

  ` r1 = np.sqrt (np.square ((mu * np.cos (t)) + x) + np.square (y + (mu * np.sin (t))))`
   ` r2 = np.sqrt (np.square (x - (1-mu) * np.cos (t)) + np.square (y - (1-mu) * np.sin (t)))`
    `C = (2 * ((((1 - mu) / r1) + (mu / r2)) + 2 * (x * vy - y * vx) + (- np.square (vx) - np.square (vy)) ) `

When I use the Jacobi integral for the inertial reference in barycentric coordinates, the C values ​​are outside of expectations, varying a lot. What could I be doing wrong?

I also ran some tests with my Poincaré sections.

This is my inertial section for C=0.

![poincaremaptentativa7](https://user-images.githubusercontent.com/53542579/93649318-134d9c80-f9e2-11ea-842f-ef25e4cd1791.png)

And this is my synodic section for C=0.

![poincare_rot_tentativa7](https://user-images.githubusercontent.com/53542579/93649316-1052ac00-f9e2-11ea-8c85-cc10bffa890f.png)

I expect something with the same shape, but my sections seems a bit drifted.

![image](https://user-images.githubusercontent.com/53542579/93649449-66bfea80-f9e2-11ea-8907-983a9dddc1da.png)

Any idea ?

Gabriel.

**Comment by hannorein** [comment]
Hi Gabriel, 

I'm not sure where you problem lies. I suspect you're not calculating the Jacobi constant correctly. Here's the code I use to calculate it. Maybe that helps you:

```
p0 = sim.particles[2] - sim.particles[0]
p1 = sim.particles[2] - sim.particles[1]
p0d = np.sqrt(p0.x**2+p0.y**2)
p1d = np.sqrt(p1.x**2+p1.y**2)
J = (p.vx**2 + p.vy**2)/2. - sim.particles[0].m/p0d - sim.particles[1].m/p1d - sim.particles[1].n*(p.x*p.vy - p.y*p.vx)
```

Hanno

**Comment by gabiruzo** [comment]
Hi Hanno,

From your code I found an error related to my code after some tests. However, there is still something more to work out. I believe that I am going the right way. I am checking points (surface cross) in the order of 10 ^-6 and this has already greatly reduced the drift in my section, as I increase the number of time steps in the 10 ^ 6 integration interval I get more accurate results but the computational cost is still very relevant.

Anyway, I will continue testing and I intend to test by modifying the coordinates for the synodic frame and testing by modifying the equations.

I appreciate the attention you've been giving me lately. Thank you.

Gabriel.
