### ISSUE TITLE
Horizons Query

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#452]
Hi Hanno,
    I've been using REBOUND for almost a year now and this issue has never come up until the last few days. From a list of bodies (i.e. planets and some massive small bodies), I use the Simulation.add("bodyname", date=some_datetime) function to query Horizons for the state of the solar system at some date. Recently, I've noticed the process 'hanging' on one of the bodies (no obvious pattern) and so I force stop the program, restart kernel, and run again. The second time around, I only get 'Object not found' messages, which certainly isn't the case. I checked the source code for why that particular message might be displayed, and it seems there's a whole for particularly the case I'm experiencing.

It seems the connection is being closed immediately after start (maybe closed by host?)

The frustrating thing is that I can't without a doubt recreate the issue, if I spam run on the function, sometimes it will error out and sometimes it will start adding the bodies and hang somewhere along the way and need to be stopped.

Have you experienced any of this? Any known fixes? Is Horizons mad at me?

I'll be pulling the ephemerides by hand for now I guess.

Please let me know what I can do to help solve this.

Best,
    -Robert Melikyan

**Comment by shadden** [comment]
Just FYI, I've been experiencing this issue as well

**Comment by dtamayo** [comment]
I think this is an issue on the JPL Horizons side...I forget who I was talking to, but I think it's just a single workstation and it can get overloaded when lots of requests happen to come in when someone runs a big script. These sporadic failures would make our unit test for Horizons fail randomly so we ended up removing it...I don't think there's anything simple that we can do on the REBOUND end. What I always do is save a REBOUND binary or simulation archive once I get the ephemerides so I don't have to query over and over, but that doesn't solve the problem of getting them the first time!

**Comment by Rmelikyan** [comment]
Thanks Dan for the insight. I have also been saving those queries as binaries... of course it's now that I'm starting a new project that I'm really noticing the issue. *sigh*
I guess we just have to bug JPL to upgrade their telnet situation

Best,
    -Robert Melikyan

**Comment by hannorein** [comment]
Thanks for letting me know. I've just tried it out and it works for me.  🤷‍♂️ 

However, I believe JPL has been working on some changes. So it could be possible that their changes will break the REBOUND interface at some point. The interface has never been a proper "API", just an easy-to-break telnet hack. So please don't hesitate to let me know if any other problems come up and I'll try to fix them as soon as possible.
