### ISSUE TITLE
Disabling gravitational interactions on particles

### ISSUE THREAD

**Issue by ReeceHumphreys** [hannorein/rebound#453]
Is there a way to disable gravitational interactions between selected particles? If so what is the optimal method for doing so. If not is this a planned features for future releases?

**Comment by hannorein** [comment]
Hi Reece, 

You can't select to turn on/off the interaction on a particle-particle basis, but what you can do is use "semi-active test particles". 

Semi-active particles see all massive particles, and the massive particles see the semi-active particles. But semi-active particles do not see each other. Maybe that's what you need? The two variables to look into are Nactive and test_particle_type. Let me know if that helps!

Hanno

**Comment by ReeceHumphreys** [comment]
Worked perfectly. Thank you!
