### ISSUE TITLE
.cite() for REBOUNDx

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#454]
I added a new [.cite()](https://github.com/hannorein/rebound/blob/master/rebound/citations.py) function to the simulation object, returning the relevant papers for the current simulation.

I could also check if REBOUNDx was used, then output the REBOUNDx paper. But this functionality could also be added to REBOUNDx itself. That way, the individual REBOUNDx modules could all come with their own citation. Thoughts?

**Comment by dtamayo** [comment]
Thanks, I think that's a great idea! Will implement after this round of applications
