### ISSUE TITLE
Question Frames

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#455]
Hello,

I'm confused with coordinates again. I'm trying to plot my poincaré section in co-rotating frame for the C3RBP. In general, sections are usually presented in the synodic framework.
I already checked the necessary prerequisites, for a x,vx plot y=0 vy0*vy>0, Jacobi constant is conserved.

![image](https://user-images.githubusercontent.com/53542579/96640160-28775d00-12f9-11eb-9b45-0eb0230f70b3.png)

The image above is my section in the inertial frame. 
The below is my section on the co-rotating frame(a little weird).

![image](https://user-images.githubusercontent.com/53542579/96640346-67a5ae00-12f9-11eb-9d89-d3f4b4aa74c0.png)

well, what I'm doing is that during the integration I do the transformations of the inertial frame(xp,yp) to co-rotating frame(xro,yro), using this:
`xro = xp * np.cos(tp) + yp * np.sin(tp)`
`yro = -xp * np.sin(tp) + yp * np.cos(tp)`
`vxro = vxp + yp`
`vyro = vyp - xp`

What could be causing my problem? Would there be any difference that I'm not considering?

I am also trying to reproduce other figures (which are not related to those mentioned above) presented in the solar system dynamics book chapter 9 with the initial conditions mentioned by the author being x0 = 0.205, y0 = 0, vx0 = 0 and y0 obtained by C = 3.02 and I'm getting images that don't seem to be correct. If I am not wrong, is vy0 in the inertial frame referenced by the expression mentioned above `(vyro = vyp - xp)`,? I guess they need to be the same at t=0.

Gabriel

**Comment by dtamayo** [comment]
My advice would be to leave the test particle out of it, and make sure you can put a planet on a circular orbit in a rotating frame such that it stays at a single point. That will clarify whether you've set up the masses correctly so that the orbital period is 1, and whether you're dealing with the barycenter correctly

**Comment by gabiruzo** [comment]
@dtamayo Already did it, seems ok to me.

**Comment by gabiruzo** [comment]
Trying to do the first example on Solar System Dynamics example book for regular orbits :
x0=0.55 , C_j = 3.07 I've a difference on C_j value when i get the exactly values for the a0=0.6944 and e0=0.2065 for the x0 and vy0 described on my program I get the same value for a0 and e0 but a different value for C_j = 3.069223779258562 before `move_to_com` and after `move_to_com`  C_j = 3.0681207674575637.

Here is my code.
```
x0 = 0.552005400999001
vy0 = 1.4814789392954786
print(vy0)
Noutputs=100000
x=[]
y=[]
vx=[]
vy=[]
t=[]
sim = rebound.Simulation()
sim.add(m=1.)
sim.add(m=mu,a=1.,e=0.)
sim.add(m=0.,x=x0,y=0,vx=0,vy=vy0)
p = sim.particles[2]
p0 = p - sim.particles[0]
p1 = p - sim.particles[1]
p0d = np.sqrt(p0.x**2+p0.y**2)
p1d = np.sqrt(p1.x**2+p1.y**2)
J = -2*((p.vx**2 + p.vy**2)/2. - sim.particles[0].m/p0d - sim.particles[1].m/p1d - sim.particles[1].n*(p.x*p.vy - p.y*p.vx))
print(J)
sim.status()
sim.move_to_com()
ps = sim.particles
sim.status()
o=sim.calculate_orbits()
for orbit in o:
    print(orbit)
p = sim.particles[2]
p0 = p - sim.particles[0]
p1 = p - sim.particles[1]
p0d = np.sqrt(p0.x**2+p0.y**2)
p1d = np.sqrt(p1.x**2+p1.y**2)
J = -2*((p.vx**2 + p.vy**2)/2. - sim.particles[0].m/p0d - sim.particles[1].m/p1d - sim.particles[1].n*(p.x*p.vy - p.y*p.vx))
print(J)
year = 2*np.pi # One year in units where G=1
tf = 1000000 # end time in years 10^5
times_year = np.linspace(0,tf*year, Noutputs) 
p=sim.particles[2]
for i in range(Noutputs):
    sim.integrate(times_year[i])
    x.append(p.x)
    y.append(p.y)
    vx.append(p.vx)
    vy.append(p.vy)
    t.append(sim.t)
    
```

So

```
def inertial_rotating(x,y,vx,vy):
    xr = x * np.cos(t) + y* np.sin(t)
    yr = x * np.sin(t) + y* np.cos(t)
    vxr = vx + y
    vyr = vy - x
    return xr,yr,vxr,vyr

def checkcross(xr,yr,vxr,vyr,t):
    for i in range(len(xr)):
        if np.abs(yr[i]) <= 1e4:
            if vyr[i]*vy0 >=0:
                if t[i] >=100000:
                    xc.append(xr[i])
                    yc.append(yr[i])
                    vxc.append(vxr[i])
                    vyc.append(vyr[i])
    return

```

And i get this :

![image](https://user-images.githubusercontent.com/53542579/96659540-96358000-131d-11eb-9f5f-366d39c071b6.png)

I'm a bit lost in this aspect.

**Comment by hannorein** [comment]
Hi Gabriel, I'm afraid I can help you there. I don't think this is an issue related to REBOUND.

**Comment by gabiruzo** [comment]
Hey Hanno.

The map on inertial frame seems ok and rebound is working fine too. I'll try do long simulations and refine my crosscheck

**Comment by gabiruzo** [comment]
Updating. Problem with sections solved, I've changed the algorithm to check crossing for a more usual poincaré algorithm.
Now the only problem is the difference between frames, I think this one is more easier to solve.
Thanks for the help @hannorein @dtamayo.
