### ISSUE TITLE
Fast heartbeat function in Python

### ISSUE THREAD

**Issue by acpetit** [hannorein/rebound#458]
I mainly use REBOUND from its Python interface and I am interested in defining a heartbeat function to be able to monitor the simulation on the fly and extract relevant statistics (e.g. resonant angles amplitude,...)

However when one define a Python function as the heartbeat function, as expected, the performances drop significantly (by a factor 20). 

The documentation suggests that a C function can be passed as the heartbeat function. Could you provide me a simple workable example that I could build on. I can try to improve the documentation if I come up with something useful without too much of a performance loss.

**Comment by hannorein** [comment]
Have a look if this helps:

https://github.com/hannorein/rebound/blob/master/ipython_examples/Cheartbeat.ipynb

**Comment by acpetit** [comment]
This definitely helps a lot, thanks 👍 I will play a bit with it and keep you updated.
