### ISSUE TITLE
Question: Radiation pressure and orbital elements

### ISSUE THREAD

**Issue by joolof** [hannorein/rebound#460]
First of all, thanks a lot for an amazing code!

As the title says, this is more of a question than an issue: I want to include the effect of radiation pressure on small dust grains (that would be test_particle = 0) and compute their "updated" orbital parameters.

Let's say that I have a test particle orbiting a solar mass star. When initializing the simulation, I set the central mass to 1, and add one test particle. Its position and velocity is computed for this stellar mass. At t = 0, the test particle now has a beta ratio of let's say 0.1 (ratio between radiation pressure and gravitational forces) and it "feels" a central mass of Mstar * (1 - beta). This is to simulate that a small grain is released from a parent body with given initial conditions.

When computing the orbital parameters, there is a factor G*Mstar, but for the test particle, Mstar should be multiplied by (1-beta) and for instance the eccentricity of the particle should immediately increase. 

To do the actual integration, I could update the acceleration using the "additional forces" feature of rebound and include the (1-beta) factor there, but having the orbital parameters would also be useful for the analysis.

How wrong would it be to initialize the simulation with Mstar = 1, include all the test particles (so that they have the correct initial velocities), and then change the stellar mass to Mstar(1-beta) just before starting the integration?  

Thanks!

**Comment by hannorein** [comment]
Hi Johan,

It depends a bit of what you want to do. If you only have test particles, all of them having the same beta, then you can just change the mass of the star and the dynamics scale. Including radiation pressure only makes sense if you have other particles in the simulation as well. 

When it comes to initializing orbits and calculating orbital elements, REBOUND allows you to give the "primary" as an argument. You could use a artificial particle which is not in the simulation, but has the same position as the star, and a mass according to the beta value. This way, a circular orbit would give you an eccentricity of 0, for example. 

When it comes to implementing the radiation pressure force, have a look at @dtamayo's REBOUNDx if you haven't done so already. 

I hope this helps.
  Hanno

**Comment by joolof** [comment]
It does help, thanks a lot for the quick answer!
Johan
