### ISSUE TITLE
TTV example disappeared? 

### ISSUE THREAD

**Issue by MilevaE** [hannorein/rebound#461]
Hi all, 

If remember well,  in a recent past there was an example of how to compute the expected TTVs of a given system using ipython. 
Unfortunately, is not longer available. Is there any chance to have this example back? 
The example now is a bit different, more focused on the fit. 

If I'm wrong, and this example never existed, is it possible to compute the expected TTVs of a given system via REBOUND?
It would help to check the expected amplitude of the TTVs to test if make sense to follow a system with times-series photometry.

Thanks in advance!,
Mileva

**Comment by hannorein** [comment]
What about this?

https://github.com/hannorein/rebound/blob/master/ipython_examples/TransitTimingVariations.ipynb

**Comment by hannorein** [comment]
This example here has been around for 4 years: https://github.com/hannorein/rebound/blob/master/ipython_examples/TransitTimingVariations.ipynb

I don't remember there being another one...

**Comment by MilevaE** [comment]
Thanks a lot Hanno!, 

for some reason I was recalling something different. I close here. 

best,
Mileva
