### ISSUE TITLE
Any way to add a *fixed particle*?

### ISSUE THREAD

**Issue by kaiwu-astro** [hannorein/rebound#463]
Dear Dr. Rein,

I am a PhD student. My research is about planetary system simulation in star clusters. In the simulation the planetary system are likely to be perturbed by other stars, so I want to add some other stars into the planetary system as fixed particles, because these stars does not evolve in the system.

I know REBOUND may not be designed to carry out such simulation, but currently REBOUND is the most hopeful tool to do this. (I tried MERCURY, but it becomes extremely slow when I add the other star) 

I tried 2 ways to realize this model: (host star, 1 planet, 1 fixed star)
1. Add the host star + planet + fixed star   -->  integrate for very short time   -->  make a new simulation instance with host + fixed star + inherit the planet information from the last instance   -->  integrate for very short time  -->  make a new simulation instance... In this way the position of the fixed star is *corrected* frequently
2. Add the host star + planet, and fixed star as external force, which gives newtonian force on the host star and the planet

There is one paper ( [Cai et al 2017](https://academic.oup.com/mnras/article/470/4/4337/3867314)) which has the same goal, and the author uses REBOUND with the first way here to realize the model. 

I tested both ways. I thought I should get very similar result, but I didn't. Attached is the ipython notebook of my test.

[Rebound_bug_report.ipynb.zip](https://github.com/hannorein/rebound/files/5651817/Rebound_bug_report.ipynb.zip)

I wonder,
1. What caused the difference in the result? Did I write the external force correctly?
2. Do you have any suggestion on how should I realized such model?

Thanks in advance for your help.

Regards,
Kai Wu

**Comment by hannorein** [comment]
Hi Kai, 

It sounds like REBOUND is a good choice here. 

I'm not quite sure what you're trying to achieve by having a "fixed star". If you really want it to be at a fixed position, you can just add its gravitational force manually in the additional_forces routine. 

But maybe you can elaborate a bit why you want to keep it fixed? I suspect, you just need to think a bit about how you want to model your system. If you have a star cluster, then the stars shouldn't be fixed. You probably want to have close encounters of passing stars with your planetary system.

Hanno

**Comment by kaiwu-astro** [comment]
Hi Dr. Rein,

Thanks a lot for your reply.

Yes you are right. Actually the aim is to simulate the close encounters of passing stars and planetary system. Thus, the passing stars feel the forces from the star cluster. They have their trajectory in the cluster, and they influence the planetary system.

I was wondering why the additional_force I wrote did not give the correct simulation result. I wrote it in Python. I have tested it for a whole day. Now I have figured out that `the additional_force funtion given to REBOUND cannot use Python`**` operator `(power calculation). When I write the gravitational force, I used `ax += M / r**3 * x`, but now I know I should write like `ax += M / r / r / r * x`. 

Could you please include this this restriction in Forces.ipynb the example of REBOUND (and maybe also in REBOUNDx)? 

Kai

**Comment by hannorein** [comment]
Dear Kai, 

I'm glad it's working now. Your comment about the ** operator doesn't quite make sense. I think you might misunderstand something about the python syntax, rather than something related to REBOUND.

Hanno
