### ISSUE TITLE
additional_forces with extra parameters in C

### ISSUE THREAD

**Issue by joolof** [hannorein/rebound#465]
Hi,
I am not extremely familiar with C, so apologies if this is a very naive question. I would like to pass some extra parameters to the additional_forces function and I honestly do not know how to do it.

I have a structure called "parameters" that contains some values (e.g., inner/outer radius) which are required when computing the additional force. I could put them as global variables, but I would rather avoid that and read them from an input file or something.

So my "additional_forces" function would like 

`void drag_force(struct reb_simulation* r, Parameters *parameters)`

But I don't know how to pass the `parameters` to rebound when defining the `r->additional_forces`. I checked the different examples on additional_forces but the function always takes only one argument.

Many thanks,

Johan

**Comment by hannorein** [comment]
Hi Johan, 

It depends a bit on what you want to do. If you're only working with one simulation at a time in your program, you could just use a global variable. 

Hanno

**Comment by joolof** [comment]
Hi Hanno,
Thanks for the quick answer. In principle, I would be running only one simulation so I guess I could use several global variables. 

The reason why I was trying to use a structure is that there are several intermediate steps. For instance, I have a total mass, an inner/outer radius, a density slope etc, and I need to compute a normalization factor (e.g., \rho_0) which will not change throughout the simulation, so I need to compute it only once. I was thinking that evaluating this \rho_0 at each timestep may unnecessarily slow the thing down.

I would rather not have the \rho_0 as a hard-coded constant value because it is far from intuitive (e.g., putting 1.763e-14 it is not obvious that the simulation is done for 0.1 earth mass or something). And as far as I can tell, I cannot define a global variable that depends on other global variable

`const double rin = 100. * AU;`
`const double rout = 2. * rin;`
would not work.

I originally opened the issue because I am not sure what to search for on how to pass the extra arguments to the `r->additional_forces`, could you give me some pointers on what I should be looking for (e.g., in some examples, it is referred to as a callback function)?

Many thanks,
Johan

**Comment by hannorein** [comment]
Hi Johan, 

I think you're mixing up several different ideas regarding global variables, constant variables, and structures. So the issue is not so much about rebound rathe than C, but here's a short snippet that might help you get going in the right direction:

```
void additional_forces(struct reb_simulation* sim);
const double AU=1.2;
double rin;
double rho;

int main(){
   rin = AU*3;
   rho = rin*4;
   sim = ...
   sim.additional_forces = additional_forces;
}

void additional_forces(struct reb_simulation* sim){
    force = rho*sim.particles[1].x;
}

```

Hanno

**Comment by joolof** [comment]
Oh. Well, that should do it indeed, learn something new everyday :) Thanks for your patience!
Johan
