### ISSUE TITLE
segmentation fault when removing particles with mercurius

### ISSUE THREAD

**Issue by Findus23** [hannorein/rebound#468]
Hi,

This seems like quite some edge-case, but I think it is still a bug, so I'll report it here for completes sake:

It seems like when deleting a particle from a simulation using mercurius before any integration has run, rebound crashes with a segmentation fault.

This is the simplest example where I can reproduce the issue:
```python
from rebound import Simulation

sim = Simulation()
sim.integrator = "mercurius"

sim.add(m=1)
for i in range(5):
    sim.add(m=0.1, a=i)

# sim.integrate(1)

sim.remove(index=1)
```

Uncommenting the `sim.integrate(1)` line fixes the crash. I assume there is something in the setup of mercurius that doesn't expect particles to be deleted before they are integrated.

**Comment by hannorein** [comment]
Thanks for reporting this. Indeed, this seems to be an edge case which we haven't considered. I'll provide a fix shortly.

**Comment by Findus23** [comment]
Many thanks for the quick fix.
