### ISSUE TITLE
Python Exception in Callback should halt rebound simulation

### ISSUE THREAD

**Issue by Findus23** [hannorein/rebound#479]
follow-up to #475 and inspired by the example in #478

using a Python callback for `sim.collision_resolve` seems to be working, but there is one usability issue: It seems like Pyhton Exceptions are ignored and the program continues as if nothing happens.

quick example:
```python
import rebound
from rebound.simulation import POINTER_REB_SIM, reb_collision


def collision_resolve_handler(sim_p: POINTER_REB_SIM, collision: reb_collision):
    a = 100 / 0
    if True:
        raise ValueError("something has gone wrong")
    return 0  # don't change original particles


sim = rebound.Simulation()
sim.integrator = "mercurius"
sim.collision = "direct"
sim.collision_resolve = collision_resolve_handler
sim.add(m=1)
sim.add(m=1e-3, r=0.5, a=1)
sim.add(m=1e-3, r=0.5, a=1, f=0.1)
sim.integrate(0.005)
sim.status()
```
outputs
```text
Exception ignored on calling ctypes callback function: <function collision_resolve_handler at 0x7f4e81f38040>
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/reboundtest/poc_exception.py", line 9, in collision_resolve_handler
    a = 100 / 0
ZeroDivisionError: division by zero
Exception ignored on calling ctypes callback function: <function collision_resolve_handler at 0x7f4e81f38040>
Traceback (most recent call last):
  File "/home/lukas/PycharmProjects/reboundtest/poc_exception.py", line 9, in collision_resolve_handler
    a = 100 / 0
ZeroDivisionError: division by zero
[...]
```

While one could probably work around this by passing a boolean to the function that gets set on an exception and don't call the next sim.integrate() when it is true, I think it would be nicer if this was handled by rebound (I guess it has to be done in C, I don't know ctypes enough to know if this is easily possible).

Another side effect of this is that one can't halt the execution during a collision using CTRL+C as the KeyboardInterrupt is also ignored.

**Comment by hannorein** [comment]
I think this is the correct behaviour. The execution of the C part of the code can't just stop when you get a python exception in the callback function. The C part might be in the middle of allocating some memory, writing to a file, etc. 

I think you either need to write the callback function in C, or make sure you don't get exceptions. But maybe someone who understands the concepts behind ctypes has a better solution.

**Comment by Findus23** [comment]
> The C part might be in the middle of allocating some memory, writing to a file, etc.

Sorry if I didn't make this clear. I didn't mean that the integration should halt immediately, but just that it should not continue on after the time step is finished. But I guess this is only possible if there is an easy way in C to check if the function threw any exceptions.

**Comment by hannorein** [comment]
I can't see a way to do that. If you want to exit the simulation after the timestep is complete, set in C:

```
r->status = REB_EXIT_ERROR; 
```

or in python:
```
sim._status = 1
```

**Comment by Findus23** [comment]
Many thanks again this should be enough to work around the issue and for anyone in the future wondering about the same to stumble across this issue.
