### ISSUE TITLE
Add Travis-CI support

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#48]
Make a simple travis script to check if all examples compile.

**Comment by hannorein** [comment]
Added all the c examples in #bf2e2f4. Still need to add the python examples.

**Comment by hannorein** [comment]
The #47 pull request also broke basically all the python examples. I think I fixed everything now. Travis now checks most examples. It can't test the more complicated ones yet (ones that require MPI, GRAPE). It also still has an issue with matplotlib when it need to use a colorbar. Somehow it wants to have an X environment for that. I'm giving up on adding these few extra examples to the tests for now. 

Currently all that is tested is that everything compiles and runs without a syntax error. It doesn't check for the right answer. I think this is good enough for now. I think adding (and maintaining!!) tests like energy conservation as a unit test takes more time than it's worth.

**Comment by hannorein** [comment]
Sorry about the assigned/unassigned stuff, just wanted to ping @dtamayo and @dsspiegel .

**Comment by dtamayo** [comment]
Sorry for creating all this extra work for you getting everything running with the new changes.  I was obviously quite naive in the number of examples this would affect.  I agree this test is quite valuable for avoiding this in the future!

**Comment by dsspiegel** [comment]
Hey, being unemployed and actively seeking, I don't think I'll have time to contribute more than commentary in the near future.  I recognize that you weren't actually asking me to, just pinging me....  Just letting you know.

Just a quick template for now (I'm sure you could do this or better than this, but wanted to contribute something since I was thinking of it...):

    import unittest
    from math import log10
    from rebound import function_to_test

    ASSIGNED_NUMBER_OF_ORBITS = 10
    REQUIRED_RELATIVE_ENERGY_ACCURACY = 1.e-8

    class Test_problem_to_test(unittest.TestCase):
        # set up problem here ... something like,
        # blah1 = ...
        # blah2 = ...

        def test_number_of_orbits(self): # for instance...
            # set up problem here..., assign a number of orbits, say 10
            number_of_orbits = Test_problem_to_test.blah1. # count the number of orbits in the rebound problem
            self.assertEqual(number_of_orbits, ASSIGNED_NUMBER_OF_ORBITS)

        def test_energy_error(self): # for instance...
            # set up problem here..., assign a number of orbits, say 10
            initial_energy = Test_problem_to_test.blah2
            final_energy = Test_problem_to_test.blah3
            relative_final_energy = final_energy / initial_energy
            allowed_places = int(-log10(REQUIRED_RELATIVE_ENERGY_ACCURACY))
            self.assertAlmostEqual(1., relative_final_energy, places=allowed_places)

    # and so on...


    if __name__ == '__main__':
        unittest.main()

**Comment by hannorein** [comment]
Thanks dave, but as I said before, I'm not keen on this sort of test. At least I will not implement and maintain it. I think it might simply not be worth the time.

**Comment by hannorein** [comment]
Travis seems to be doing it's job now, so I'm closing the issue.
