### ISSUE TITLE
Mercurius doesn't seem to report invalid whfast configuration

### ISSUE THREAD

**Issue by Findus23** [hannorein/rebound#480]
Hi,

(I hope I am not getting annoying with the issues, but I always find it easier to always create issues, even if the "issue" is not severe enough to warrant fixing it as it indirectly documents them and allows others to quickly find out if they are doing it wrong and how to do it right)

It seems like when using mercurius `reb_integrator_whfast_init` is never called and therefore the validation of the settings is never done. (e.g. not using a corrector and non-jacobi-coordinates at the same time)
https://github.com/hannorein/rebound/blob/95a30482c98962978d5c6789e88566b83a66d844/src/integrator_whfast.c#L773-L775

quick example:
```python
from rebound import Simulation
from rebound.data import add_solar_system

switch = True  # doesn't throw error
# switch = False # properly shows error

sim = Simulation()
if switch:
    sim.integrator = "mercurius"
else:
    sim.integrator = "whfast"

sim.ri_whfast.safe_mode = 0
sim.ri_whfast.coordinates = 'democraticheliocentric'
sim.ri_whfast.corrector = 11  # should not be possible with democraticheliocentric coordinates

add_solar_system(sim)
sim.integrate(100)
```

**Comment by hannorein** [comment]
(Opening as many issues as possible is great! As you said, better to respond here than in an e-mail so other people can see it)

Hm. You're right. Actually, is there any setting in `ri_whfast` that makes sense changing when MERCURIUS is turned on?

**Comment by Findus23** [comment]
(Great, I'll see what else I'll be stumbling across in the next months)

Do you mean if it there are any `ri_whfast` parameters that a user of mercurius might want to change (I think all of them make sense to change with mercurius) or if there are any `ri_whfast` parameters which should have different default values with mercurius (not sure, as I am not yet that familiar with the `coordinates` details, but probably there are few use cases where mercurius is used, but the planets stay properly ordered for jacobi coordinates)?

**Comment by hannorein** [comment]
I'm not sure there is any setting in `ri_whfast` that affects mercurius. mercurius only uses the Kepler solver from WHFast, none of the other settings are used.

**Comment by Findus23** [comment]
Ah, I didn't know that, but that explains a lot why I never saw real changes in results or performance. And looking at the code `ri_whfast.timestep_warning` seems to be the only one with an effect. 

https://github.com/hannorein/rebound/blob/95a30482c98962978d5c6789e88566b83a66d844/src/integrator_whfast.c#L183

Maybe in this case it should be the other way round: Mercurius should throw a warning if any `ri_whfast` is set as they are going to be ignored. 

Do I also understand this correctly that no matter which setting, Mercurius always uses the same coordinates for the planets and everything mentioned in https://rebound.readthedocs.io/en/latest/ipython/AdvWHFast.html has no effect?

**Comment by hannorein** [comment]
Ah. Good point about the `ri_whfast.timestep_warning`. 

Yes, none of these options have an effect. They are in fact incompatible with MERCURIUS. MERCURIUS needs the default kernel, democratic heliocentric coordinates, and can't use correctors.

**Comment by Findus23** [comment]
And just for completion I assume that Mercurius works similar to whfast with safe_mode = 0, so on a collision I need to call
```python
sim.integrator_synchronize()
sim.ri_mercurius.recalculate_coordinates_this_timestep = 1
sim.ri_mercurius.recalculate_dcrit_this_timestep = 1
```

but not `sim.ri_whfast.recalculate_coordinates_this_timestep = 1`, right?

**Comment by hannorein** [comment]
Unless you're setting up something exotic, the collisions should always occur during the IAS15 part of mercurius step (i.e during a close approach). You don't need to do anything other than handling the collisions itself. If particle masses change significantly during the collision, then it would make sense to set `sim.ri_mercurius.recalculate_dcrit_this_timestep=1`.

**Comment by hannorein** [comment]
I'll close this for now. Maybe the documentation could be better, but I don't think there is anything wrong with the current implementation.
