### ISSUE TITLE
Saving and loading checkpoints for megno

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#482]
Is there a way for megno to save checkpoints during the simulation so that if the program crashes due to power outage, it can pick up where it's left off? In the examples I think the results are saved altogether when all simulations are done because of parallel processing. Or for example, I ran a simulation with integration time of 10^6 years and after checking the results, 10^8 years seems to be better. Is it possible to run the 10^8 years simulation based on the 10^6 years results and how can we load previous results? Thanks.

**Comment by hannorein** [comment]
Have a look at the SimulationArchive. That is doing exactly what you're looking for.

**Comment by zhexingli** [comment]
Oh Thank you Hanno. I didn't know that example is for this. Will check it out!
