### ISSUE TITLE
Altering mean anomaly causes AttributeError

### ISSUE THREAD

**Issue by georgeBell25189120** [hannorein/rebound#488]
Hello, I am an MPhil student attempting to reproduce some work on the Nice model from the Clement et al. (2021) paper "Born Eccentric: Constraints on Jupiter and Saturn's pre-instability orbits" (originally done in Mercury6) in Python REBOUND. I have an issue when I try to follow part of their scenario in section 3.2 where integrating the solar system with five giant planets in a resonance chain  and a planetesimal disk for 100 Kyr does not produce an instability: "If the instability has not occurred after 100.0 Kyr, the mean anomaly of the innermost ice giant is shifted by 90° to trigger the instability (Nesvorný, 2011)." I have attempted to directly alter the value of the mean anomaly for the innermost ice giant in Rebound, i. e.

ps["Uranus"].M += np.pi/2

However this causes the error message "AttributeError: can't set attribute". I was wondering whether there is a different way of doing this in Rebound. Thanks.

**Comment by hannorein** [comment]
Hi George, 

This attribute is read-only at the moment. I guess it would be a worthwhile feature to allow setting these attributes. You need to read construct a new particle with the same orbital elements as your original one, except M, which you change. Use `ps["Uranus"].calculate_orbit()` to get all orbital elements. Then create a new particle with rebound.Particle(). Then overwrite the original particle in the simulation. I hope that makes sense!

Hanno

**Comment by georgeBell25189120** [comment]
Hello Hanno,

Thank you for your prompt response, that is very helpful to me.

Regards,

George

**Comment by hannorein** [comment]
Hi George. So I've implemented this in the latest version of REBOUND (just pushed it to github). You should now be able to modify orbital elements in-place. 

Note that this might have unexpected consequences. It's important to know that the orbital elements one is modifying this way are Jacobi coordinates. Thus, if one modifies the particle with index `i`, then the orbital elements of particles with index `j>i` will change if particle `i` has a mass `m>0`. 

If Jacobi coordinates are not desired, one needs to use the `sim.calculate_orbits()` syntax which allows one to specify the coordinate system (by passing the appropriate `primary`, e.g. `primary=sim.particles[0]` for heliocentric coordinates), and then modify the particle manually. I don't see a way to make this more intuitive -- coordinate systems in celestial mechanics can be confusing.

**Comment by georgeBell25189120** [comment]
Hello Hanno,

Thank you for implementing this. In my project I have consistently used heliocentric coordinates. I agree that coordinate systems can be confusing!

Regards,

George

**Comment by hannorein** [comment]
Great. 

For reference and to avoid any confusion in case someone finds this thread later: `ps["Uranus"].M` returns the mean anomaly in Jacobi coordinates and `ps["Uranus"].M += np.pi/2.` will (self-consistently) change the mean anomaly in Jacobi coordinates. This will not affect Neptune's Cartesian coordinates, but it will slightly alter Neptune's orbital elements in Jacobi coordinates.

**Comment by georgeBell25189120** [comment]
Hello Hanno,

I have run the program with mean anomaly and I notice that when the result of adding np.pi/2 to the mean anomaly is > np.pi, the mean anomaly prints out as a negative number. For example when `ps["uranus"].M = 1.6672172614825627` `ps{"uranus"].M += np.pi/2` prints out as `-3.0451717189021394` rather than `3.2380135188`. I think it is looping from np.pi to -np.pi rather than from 0 to 2*np.pi. Thanks.

**Comment by hannorein** [comment]
That makes sense. The angles are invariant under adding/subtracting 2 pi.

**Comment by georgeBell25189120** [comment]
Hello Hanno,

Thank you. Would it be OK to proceed to integration with the negative value of the mean anomaly?

Regards,

George

**Comment by hannorein** [comment]
Yes. You can add or subtract 2*pi from an angle as many times as you like! (Unless you're doing quantum mechanics 😉)

**Comment by georgeBell25189120** [comment]
Hello Hanno,

Thanks again for all your help, I will continue on. 

Regards,

George
