### ISSUE TITLE
Reproducability of SimulationArchive

### ISSUE THREAD

**Issue by Findus23** [hannorein/rebound#495]
This is not that important, but something I just noticed and thought I'd report it.
In Rein & Tamayo 2017 the SimulationArchive is described as bit-by-bit reproducible, which I interpreted meaning that running the same code (with the same input parameters) that saves a SimulationArchive in the end, creates the exact same file.
(If it just means that all simulation output will be the same, then this is probably not an issue).

I tried testing it and it seems very close, but one or two values seem to differ.

Testcode:
```python
import sys
from ctypes import c_uint32

from rebound import Simulation, Particle

sim = Simulation()
sim.ri_mercurius.hillfac = 3

sim.add(Particle(m=32, hash="sun", simulation=sim))
for i in range(2, 30):
    sim.add(Particle(m=1, a=i, hash=c_uint32(i), simulation=sim))

for i in range(3):
    sim.integrate(i)
    print(i)
sim.save(f"tmp/{sys.argv[1]}.bin")
```
```bash
➜ python poc_binary.py a
0
1
2
➜ python poc_binary.py b
0
1
2
```
```diff
➜ diff <(xxd tmp/a.bin) <(xxd tmp/b.bin)
78c78
< 000004d0: 0800 0000 0000 0000 aede 6b08 8e4b f73f  ..........k..K.?
---
> 000004d0: 0800 0000 0000 0000 a04e 29af 9590 f73f  .........N)....?
154c154
< 00000990: 0400 0000 0000 0000 7bf3 0600 5700 0000  ........{...W...
---
> 00000990: 0400 0000 0000 0000 d3da 0300 5700 0000  ............W...
```
The two files:
[files.zip](https://github.com/hannorein/rebound/files/5965039/files.zip)

I assume that these two values are nothing important, but it might still be worthwhile checking what those values are that are not the same during the two simulation runs.

**Comment by hannorein** [comment]
The walltime is different.

**Comment by Findus23** [comment]
Ah, I didn't expect the walltime to be stored in the snapshot files. That of course explains it, thanks.
