### ISSUE TITLE
collision_resolve only called once

### ISSUE THREAD

**Issue by Findus23** [hannorein/rebound#503]
This was originally meant to be a far larger issue, but the remaining things resolved themselves when looking closer at the code, so I'll just ask this one question:

I take reb_collision_resolve_merge as an inspiration and it explains that it will always be called twice for each collision with swapped particles.

https://github.com/hannorein/rebound/blob/19232f3aab582e500cb4bab09c09f774aeed1691/src/collision.c#L735-L740

This makes sense and I am expecting the same for my collision_resolve function.

This is an example using mercurius and a few planets that will collide after a few years (thanks to retrograde orbits). The collision_resolve function logs the two particles that collide and then will always keep the more massive one.

```python
import sys
from ctypes import c_uint32

from matplotlib import pyplot as plt
from rebound import Simulation, Particle, OrbitPlot
from rebound.simulation import reb_collision
from scipy.constants import astronomical_unit, pi, kilo

sim = Simulation()
sim.units = ('yr', 'AU', 'kg')
sim.ri_mercurius.hillfac = 3
sim.integrator = "mercurius"
sim.collision = "direct"


def resolve(sim_pointer, collison: reb_collision):
    sim: Simulation = sim_pointer.contents
    p1 = sim.particles[collison.p1]
    p2 = sim.particles[collison.p2]
    print("collison:")
    print(f"{p1.hash.value} <-> {p2.hash.value}")
    print(f"{p1.m:.2f}")
    print(f"{p2.m:.2f}")
    if p1.m > p2.m:
        print("delete second object")
        return 2
    else:
        print("delete first object")
        return 1


sim.collision_resolve = resolve
sim.ri_ias15.min_dt = 1e-8

sim.add(Particle(m=1e30, hash="sun", simulation=sim))
radius = 6000 * kilo / astronomical_unit

for i in range(2, 15):
    sim.add(Particle(m=1e24 + i * 1e10, a=3 + i / 20, r=radius, hash=c_uint32(i), simulation=sim))

for i in range(3, 10):
    sim.add(Particle(m=1e24 + i * 1e11, a=3 + (i + .5) / 20, Omega=1, inc=pi, r=radius, hash=c_uint32(i + 100),
                     simulation=sim))

for i in range(0, 500, 10):
    sim.integrate(i)
    print(i, sim.N)
print("remaining", sim.N)
print([p for p in sim.particles])

fig, ax_main = OrbitPlot(sim)
plt.show()
```

Now I would expect `resolve()` to be called twice and that I would need to handle that similar to the code linked above.

But it turns out this is not the case and it is only called once per collision:

```text
0 21
10 21
20 21
30 21
40 21
50 21
60 21
70 21
80 21
90 21
100 21
110 21
120 21
130 21
140 21
150 21
160 21
collison:
10 <-> 109
1000000000000099975430144.00
1000000000000900047306752.00
delete first object
170 20
180 20
190 20
200 20
210 20
220 20
230 20
240 20
250 20
260 20
270 20
280 20
290 20
300 20
310 20
320 20
collison:
6 <-> 5
1000000000000059978547200.00
1000000000000050046435328.00
delete second object
330 19
340 19
350 19
360 19
370 19
380 19
390 19
400 19
410 19
420 19
430 19
440 19
450 19
460 19
470 19
480 19
490 19
remaining 19
```
Originally I was quite confused why the p1 and p2 particles were switching around randomly between calls, but it turns out this is intentional. And when thinking about it, it also makes sense to not get statistical issues in scenarios with very large amount of collisions.
https://github.com/hannorein/rebound/blob/f82a2a097995c34b6471b8bf913bbb9215ae6e36/src/collision.c#L335-L341

But the main question remains: Why is the function only called once?

(this might also interest @Rmelikyan)

**Comment by hannorein** [comment]
If you remove a particle, then it can't call the collision resolve function a second time (because at least one particle is missing). If you look at the code, you'll see that when a particle gets removed during a collision, there is a for-loop, checking if the particle that got removed is part of any other collision in the queue. If so, it sets the index in the collision structure to the special value of -1 and will skip it later.

Let me know if that answer the question!

**Comment by Findus23** [comment]
So if I understand it correctly, one could delete this line:
https://github.com/hannorein/rebound/blob/19232f3aab582e500cb4bab09c09f774aeed1691/src/collision.c#L736
and rebound would still work exactly the same as the function always returns 1 or 2 (so always one particle deleted)

**Comment by hannorein** [comment]
No. One particle could have multiple collisions with different particles during the same timestep. This code ensures that there is only one collision per particle per timestep (a random one, because the collisions are randomized)

This is not a perfect solution of course. The problem is that if a particle has multiple collisions, then the collisions would need to be sorted in time. Also, after every collision, the collisions search would need to start from scratch because a single collision can affect every other collision.

**Comment by Findus23** [comment]
Indeed, I forget that not every simulation consist of a scenario where there is a lot of time of nothing between every simulation.

Many thanks for the hint, I think that answers this question. (and unfortunatly prepares the next one)
