### ISSUE TITLE
User defined merge and escape functions with active and semi-active particles

### ISSUE THREAD

**Issue by georgeBell25189120** [hannorein/rebound#504]
Hello Hanno, I enquired a couple of weeks ago about directly modifying mean anomaly in a Nice model instability simulation, which you resolved for me in REBOUND 3.15.0 and I have another question about a different aspect of this problem. 
The Nice model simulation I am running is based on Clement et al. (2021) "Born Eccentric" so I integrate `sim.N_active = 6` (the Sun, Jupiter, Saturn and three ice giants) and 1000 semi-active particles (which are comets in the Kuiper belt) for 100 Kyr. Clement uses the addition of the mass of the Kuiper belt as an artificial instability trigger so I set `sim.testparticle_type = 1` and divided total mass by number of comets to get the mass for each comet. I am interested in comets which pass within 0.413 AU of Saturn (its Hill radius) and would like to be able to retrieve details of these interactions but my current merge function instead seems to merge comets with each other unphysically and I am wondering how best to do this. 
I would also like to remove particles from the simulation when they escape the Solar system, which I define as going beyond 50 AU from the Sun (such as an ejected ice giant). I have attempted to implement this as a try and except with excepts for merging and escape but the second except causes an error message for invalid syntax. I am not sure how to incorporate both exceptions. Thanks.

**Comment by Findus23** [comment]
> but the second except causes an error message for invalid syntax

Can you by chance share that bit of code with the two excepts?
Maybe it is just a trivial type.

**Comment by georgeBell25189120** [comment]
Hello Lukas, attached is the section of code with the two excepts. Thanks.

![Try and two excepts](https://user-images.githubusercontent.com/78485797/108530352-6bf4ce80-72cd-11eb-9a01-894de34e4f77.png)

**Comment by hannorein** [comment]
Hi George! 

Regarding the first part of your question on detecting encounters with Saturn. Set the radius of Saturn to the distance you're interested in, e.g. 0.413 AU. If you turn on the collision search, you will get callbacks or exceptions for these events. It's up to you what you do there, e.g. output it to a file, etc. 

The second part regarding escaping particles: You could add a box to your simulation with `sim.configure_box(100)`. If you do that, everything that leaves the simulation box of 100 length units will be removed from the simulation. 

I'm not sure about the error. I'd need to see the full code to reproduce the issue (what you've posted above doesn't quite show how you setup the simulation). 

I hope this helps. 

Hanno

**Comment by georgeBell25189120** [comment]
Hello Hanno, 

Thanks again for your help.

So I could set `ps['Saturn'].r = 0.413`. Would you also recommend setting other planetary radii to their Hill radius as I would not be as interested in comets which had already undergone close encounters with other planets which could result in capture? Also, how would I turn on the collision search in Python?

The collision box is like the one in the example for simulating Saturn's rings. Thanks for that idea. 

I have attached the code up to this point as a txt file to show how I set up the simulation, sorry it's not a neat read. 

[REBOUND 190221.txt](https://github.com/hannorein/rebound/files/6011386/REBOUND.190221.txt)

**Comment by hannorein** [comment]
What you do with the other planets is up to you. If you're not interested in their encounters, you can set their radii to zero. You can turn on the collision search in python with `sim.collision = direct`. You will at some point have to think about how to make your simulation faster. Right now you're using IAS15 and your simulation might be prohibitively slow. Have a look at the mercurius integrator.

**Comment by georgeBell25189120** [comment]
Hello Hanno,

It might be best to note the other encounters anyway, if only to exclude those comets from consideration. Many of my simulations at the moment are being run on the University of Lincoln cluster so simulation speed isn't an issue yet but thanks for the tip about the MERCURIUS integrator. I am going to experiment with these ideas, I may have to get back to you if something else arises but for now I will close the issue.
