### ISSUE TITLE
Let's Open a Discussion Section?

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#506]
Hi Hanno,

Have you thought about opening a discussion section for this repository? It seems like a more appropriate place for certain types of questions that I come across sometimes without the pressure of claiming some sort of issue within the project.

If you think this would be valuable to the community, this [link](https://docs.github.com/en/discussions/quickstart) takes you to the github 'how to' page. 

Thanks for the consideration,

-Robert

**Comment by hannorein** [comment]
Thanks for the suggestion. I've enabled it (I think -- let me know if I not)!
