### ISSUE TITLE
Mercurius integrator problem

### ISSUE THREAD

**Issue by gabiruzo** [hannorein/rebound#512]
Hello,

I'm having problems with the Mercurius integrator, for some reason my kernel is dying. Tested on my physical machine and on the Colab Notebook cloud. This is only happening in one of my stability map programs. This problem does not occur when I use WHFast or IAS15 only with Mercurius.

Does anyone know what may be happening?

Here is my code :

```
global jup_e

jup_e = 0.05


import time
start_time = time.time()

import rebound
import numpy as np
import matplotlib.pyplot as plt
global mu
global k


m2 = 10**(-3)
m3 = 5*10**(-5)
m1 = 1-m2-m3
mu=m3
year = 2.*np.pi # One year in units where G=1
tf = 10**(5) # end time in years
times = np.linspace(0,tf*year, 2)




def simulation(a,e):
    sim = rebound.Simulation()
    sim.add(m=m1,r=0.0046422) # Star
    sim.add(m=m2, a=1, e=jup_e,r=0.00046607333333333,primary=sim.particles[0])
    sim.move_to_com()
    sim.add(m=m3, a=a, e=e, inc=np.pi)
    sim.integrator ="mercurius"
    sim.dt = 0.01
    name = str(e)
    f = open(str(name+"_jupiter_"+str(jup_e)+"_3bp" + ".txt"),'w')
    ps=sim.particles
    sim.init_megno()
    sim.exit_max_distance = 10.
    sim.exit_min_distance = 0.0005
    sim.collision = "direct"
    par=a,e
    print(par)
    a_data = str(a)
    e_data = str(e)
    try:
        for i,time in enumerate(times):
            sim.integrate(time) 
            megno = sim.calculate_megno()
            if megno >= 8 or np.isnan(megno == True):
                if np.isnan(megno) == True :
                    f.write("25"+"," + a_data+","+e_data + "\n")
                    return 10
                else:
                    f.write(str(megno)+"," + a_data+","+e_data + "\n")
                    return megno
    except rebound.Encounter:
        f.write("15"+"," + a_data+","+e_data + "\n")

        return 15.
    except rebound.Collision:
        f.write("10"+"," + a_data+","+e_data + "\n")

        return 20.
    except rebound.Escape:
        f.write("20"+"," + a_data+","+e_data + "\n")

        return 25.
    
    g = open(str(name+"_jupiter_"+str(jup_e)+"_3bp_runtime" + ".txt"),'w')
    g.write("--- %s seconds ---" + str((time.time() - start_time)))
    g.close()
    f.close()
    
a_min = 0.3
a_max = 2.5
print(a_min)
print(a_max)
n = 601
a_steps = np.zeros(n)
a_steps[0]= a_min
for i in range(1,n):
    a_steps[i] = a_steps[i-1] + 0.004
print(a_steps)
print(a_steps[1] - a_steps[0])

e_steps = np.zeros(21)
e_steps[20] = 0.9999
for i in range(1,20):
    e_steps[i] = e_steps[i-1] + 0.05
print(e_steps)

for j in range(20):
    for i in range(0,n):
        simulation(a_steps[i],e_steps[j])     


```

**Comment by Findus23** [comment]
Hi,

When I try to run the code I get

> Fatal error! Exiting now. Variational gravity calculation not yet implemented.

https://github.com/hannorein/rebound/blob/df0d0c5dcf6f9c2d73f65bb1dcad989553c5f7c9/src/gravity.c#L1087

which I think seems to indicate that variational equations (as used by MEGNO) are not supported with the gravity calculation of Mercurius.

And indeed https://rebound.readthedocs.io/en/latest/python_api.html#rebound.Simulation.init_megno says

> MEGNO is currently only supported in the IAS15 and WHFast integrators.

**Comment by hannorein** [comment]
That's correct. I don't see a good use for combining MERCURIUS and variational equations. As soon as there are collisions, the system is highly chaotic. 

I guess a more graceful exit would be nice!

**Comment by gabiruzo** [comment]
Ok, I got it.

I thought that because mercurius is a combination of IAS15 and WHFast this could work. Thanks.

**Comment by hannorein** [comment]
I'd suggest you use WHFast and check for collisions, as you already do in your code. For a stability map, Mercurius is really of no use.

**Comment by gabiruzo** [comment]
Thanks for the help and suggestion
