### ISSUE TITLE
issue restarting simulation from saved file

### ISSUE THREAD

**Issue by bungler0** [hannorein/rebound#514]
I've been trying to stop and restart simulations so that I can continue integrating the same simulation for long periods of time. However, when I test the stop and restart, I can't get it to replicate the result of continuous integration. For example, I start by integrating a simulation for 2 years, using both a SimulationArchive (interval = .5) as well a saved copy of the simulation at time 1 and time 2. 
```
simbase = draw_sim() 
simbase.automateSimulationArchive("singlebase.bin", interval = .5)
simbase.integrate(1)
simbase.save("singlebase_1.bin")
simbase.integrate(2)
simbase.save("singlebase_2.bin")
```
[draw_sim just sets up the simulation w planets etc.]
Then, I do the same thing but only integrate up to 1 year:
```
simfront = draw_sim()
simfront.automateSimulationArchive("singlefront.bin", interval = .5)
simfront.integrate(1)
simfront.save("singlefront_end.bin")
```
Then I use the saved bin from the end of simfront to create a copy, and reset my function pointers:

```
simback = rebound.Simulation("singlefront_end.bin")
simback.integrator = "IAS15"
simback.collision = "direct"
simback.collision_resolve = c
simback.G = G
simback.dt = dt
simback.automateSimulationArchive("singleback.bin", interval = .5)
simback.integrate(2)
simback.save("singleback_end1.bin")
```
However, when I compare the particles from `singlebase_2.bin` and `singleback_end1.bin`, they've ended up with slightly different positions and velocities. This isn't really an issue for just integrating over 2 years, but when it's over longer periods of time the differences are quite drastic. 
Interestingly, I've found that `singlebase_1.bin` and `singlefront_end.bin` are exactly the same, so there's nothing wrong with the saving and reloading. I'm honestly not sure what could be causing the drift. 
If it's relevant, my simulations deal with a lot of particle collisions between massless particles and planets/stars - the real issue I'm trying to solve is that when I do this stop/restart test over longer times, I'm getting different collisions in the continuous integration as compared to the stopped and restarted one.

**Comment by hannorein** [comment]
Hm. Let's see if we can figure out whats going on here. 
1) You don't seem to use `singlebase.bin` or `singleback.bin` at all. If you get rid of all the `automateSimulationArchive` calls, do you still get the same issue?
2) Can you reproduce the issue with a simpler setup? For example by replacing `draw_sim` with something like `rebound.data.add_outer_solar_system(sim)` so I can reproduce it?

You probably know this already, but just in case: Because the binary files store among other things the walltime, they won't be exactly equal if you just do a diff on the command line. So always compare something physically meaningful, e.g. the positions of particles.

**Comment by hannorein** [comment]
FWIW, [there is a unit test](https://github.com/hannorein/rebound/blob/main/rebound/tests/test_simulationarchive.py#L366) which should check for the kind of behaviour you describe. So something must be different between your setup and the one in the unit test.

**Comment by bungler0** [comment]
When I say "exactly the same", I am referring to comparing the x, y, z, m, vx, vy, and vz values of each particle, and "different" is also referring to those values (different on a meaningful level, e.g. much greater than e-14). In fact I'm getting different patterns of particle collisions depending on whether or not I do the integrations continuously, which is pretty troublesome as I am specifically looking for those particle collisions. 

1. I used the bins to verify that end states were correct, and found that the middle state of singlebase.bin exactly matched singlebase_1.bin and the end state of singlefront.bin. The end state of singlebase.bin did not match the end state of singleback.bin, or singleback_end1.bin. 
I went back and did the same experiment without the SimulationArchives, and

2. My situation is quite different from the unit test, as I've given radii for my planets and I have many (hoping to get upwards of 10,000) massless particles in the system as well, whose collisions I am tracking. However, even without the massless particles, I am running into issues with just integrating the system.
Here I've explicitly written out what the `draw_sim()` function does to set up the system:
```
sim = rebound.Simulation()
sim.G = 39.441677
sim.add(m = 0.0898, r = 0.1192*Rsun_to_AU, hash = 'a')
sim.add(m = 1.374*Mearth_to_Msun, a=1.154e-2, e=0, inc=(90-89.728)*deg_to_rad, 
        Omega=1, omega=1, M=320.2328615005874, r = 1.116*Rearth_to_AU, hash='b')
sim.add(m = 1.308*Mearth_to_Msun, a=1.580e-2, e=0, inc=(90-89.778)*deg_to_rad,
        Omega=1, omega=1, M=302.03085481266083, r = 1.097*Rearth_to_AU, hash='c')
sim.add(m = 0.388*Mearth_to_Msun, a=2.227e-2, e=0, inc=(90-89.896)*deg_to_rad,
        Omega=1, omega=1, M=-421.17961121323583, r = 0.788*Rearth_to_AU, hash='d')
sim.add(m = 0.692*Mearth_to_Msun, a=2.925e-2, e=0, inc=(90-89.793)*deg_to_rad,
        Omega=1, omega=1, M=-270.15332650367066, r = 0.920*Rearth_to_AU, hash='e')
sim.add(m = 1.039*Mearth_to_Msun, a=3.849e-2, e=0, inc=(90-89.740)*deg_to_rad,
        Omega=1, omega=1, M=-187.20059131394225, r = 1.045*Rearth_to_AU, hash='f')
sim.add(m = 1.321*Mearth_to_Msun, a=4.683e-2, e=0, inc=(90-89.742)*deg_to_rad,
        Omega=1, omega=1, M=-136.97239841027107, r = 1.129*Rearth_to_AU, hash='g')
sim.add(m = 0.326*Mearth_to_Msun, a=6.189e-2, e=0, inc=(90-89.805)*deg_to_rad,
        Omega=1, omega=1, M=-89.87573477315452, r = 0.755*Rearth_to_AU, hash='h')
sim.integrator = "IAS15"
sim.dt = days_to_yr/10
sim.integrate(1000)
```
And then integrated continuously through 1000 years. I then did the same setup for sim2, but integrated it in a loop, incrementing 100 years at a time:
```
sim2 = rebound.Simulation()
sim2.G = 39.441677
sim2.add(m = 0.0898, r = 0.1192*Rsun_to_AU, hash = 'a')
sim2.add(m = 1.374*Mearth_to_Msun, a=1.154e-2, e=0, inc=(90-89.728)*deg_to_rad, 
        Omega=1, omega=1, M=320.2328615005874, r = 1.116*Rearth_to_AU, hash='b')
sim2.add(m = 1.308*Mearth_to_Msun, a=1.580e-2, e=0, inc=(90-89.778)*deg_to_rad,
        Omega=1, omega=1, M=302.03085481266083, r = 1.097*Rearth_to_AU, hash='c')
sim2.add(m = 0.388*Mearth_to_Msun, a=2.227e-2, e=0, inc=(90-89.896)*deg_to_rad,
        Omega=1, omega=1, M=-421.17961121323583, r = 0.788*Rearth_to_AU, hash='d')
sim2.add(m = 0.692*Mearth_to_Msun, a=2.925e-2, e=0, inc=(90-89.793)*deg_to_rad,
        Omega=1, omega=1, M=-270.15332650367066, r = 0.920*Rearth_to_AU, hash='e')
sim2.add(m = 1.039*Mearth_to_Msun, a=3.849e-2, e=0, inc=(90-89.740)*deg_to_rad,
        Omega=1, omega=1, M=-187.20059131394225, r = 1.045*Rearth_to_AU, hash='f')
sim2.add(m = 1.321*Mearth_to_Msun, a=4.683e-2, e=0, inc=(90-89.742)*deg_to_rad,
        Omega=1, omega=1, M=-136.97239841027107, r = 1.129*Rearth_to_AU, hash='g')
sim2.add(m = 0.326*Mearth_to_Msun, a=6.189e-2, e=0, inc=(90-89.805)*deg_to_rad,
        Omega=1, omega=1, M=-89.87573477315452, r = 0.755*Rearth_to_AU, hash='h')
sim2.integrator = "IAS15"
sim2.dt = days_to_yr/10

for i in range (11):
    sim2.integrate(i*100)
```
And these are the results I got from `sim.status()`:
```
REBOUND version:     	3.16.0
REBOUND built on:    	Mar  1 2021 20:27:21
Number of particles: 	8
Selected integrator: 	ias15
Simulation time:     	1.0000000000000000e+03
Current timestep:    	0.000098
---------------------------------
<rebound.particle.Particle object at 0x7f93fbf201c0, m=0.0898 x=-1.5096286246538948 y=-1.4509462553614894 z=0.001784431550816134 vx=-0.00224761856751482 vy=-0.002686110285650419 vz=1.318350520381836e-06>
<rebound.particle.Particle object at 0x7f93fbf20a40, m=4.1257647600000004e-06 x=-1.4983558857059205 y=-1.4529548625368844 z=0.0017507888102132403 vx=3.118891221086446 vy=17.373900537862994 vz=0.02530854163634968>
<rebound.particle.Particle object at 0x7f93fbf201c0, m=3.9275839200000004e-06 x=-1.505610952839111 y=-1.4661991230605937 z=0.0017395498257754007 vx=14.49493713442613 vy=3.8394093842215415 vz=-0.04262757291282083>
<rebound.particle.Particle object at 0x7f93fbf20a40, m=1.16506312e-06 x=-1.5141002917323108 y=-1.4290808592071205 z=0.0018777192146158218 vx=-12.302497029547576 vy=-2.6656805412519162 vz=0.05559941983472352>
<rebound.particle.Particle object at 0x7f93fbf201c0, m=2.07789608e-06 x=-1.5326221557469992 y=-1.4331086382617473 z=0.0019181320227699375 vx=-6.833988665623325 vy=-8.702158706441383 vz=0.004070143937360746>
<rebound.particle.Particle object at 0x7f93fbf20a40, m=3.1198468599999995e-06 x=-1.471233202902029 y=-1.450673054156679 z=0.001646046503467843 vx=-0.09000959554237895 vy=9.617440073293468 vz=0.02836510880062363>
<rebound.particle.Particle object at 0x7f93fbf201c0, m=3.96661954e-06 x=-1.4923837648271503 y=-1.4944062898083998 z=0.0016462995124567848 vx=8.105276687353335 vy=3.18378270496619 vz=-0.020977781754535286>
<rebound.particle.Particle object at 0x7f93fbf20a40, m=9.7889324e-07 x=-1.4872619011621766 y=-1.3931576179452676 z=0.0018002414474324617 vx=-7.0398915002234626 vy=2.7410833469990448 vz=0.02694309708952098>
```
And from `sim2.status()`:
```
REBOUND version:     	3.16.0
REBOUND built on:    	Mar  1 2021 20:27:21
Number of particles: 	8
Selected integrator: 	ias15
Simulation time:     	1.0000000000000000e+03
Current timestep:    	0.000122
---------------------------------
<rebound.particle.Particle object at 0x7f93fbf20940, m=0.0898 x=-1.5096249320546866 y=-1.4509464826257275 z=0.0017844186496676982 vx=-0.0012507109632032992 vy=-0.0013494662277523163 vz=1.208168909695783e-06>
<rebound.particle.Particle object at 0x7f93fbf20dc0, m=4.1257647600000004e-06 x=-1.5004172489006329 y=-1.4439341077986787 z=0.0017747225163392629 vx=-10.563011447814477 vy=13.9093819034973 vz=0.05537964459177446>
<rebound.particle.Particle object at 0x7f93fbf20940, m=3.9275839200000004e-06 x=-1.5250157942980314 y=-1.454716695471303 z=0.001830067833555622 vx=3.525841703239328 vy=-14.510438254086985 vz=-0.03938853397450925>
<rebound.particle.Particle object at 0x7f93fbf20dc0, m=1.16506312e-06 x=-1.4897923818257197 y=-1.440509124847119 z=0.0017154398892497958 vx=-5.7384428455624095 vy=11.134626560489334 vz=0.07017553253183169>
<rebound.particle.Particle object at 0x7f93fbf20940, m=2.07789608e-06 x=-1.5038062870377868 y=-1.4224025786729568 z=0.0018298701698752347 vx=-10.807986507948625 vy=2.3102681078379073 vz=0.04686438528978511>
<rebound.particle.Particle object at 0x7f93fbf20dc0, m=3.1198468599999995e-06 x=-1.547533373240563 y=-1.4555575264355174 z=0.0019148779401436682 vx=1.1897393253398536 vy=-9.592921228945034 vz=-0.0334041633057917>
<rebound.particle.Particle object at 0x7f93fbf20940, m=3.96661954e-06 x=-1.4961890622685157 y=-1.4960138642414258 z=0.0016590980913251932 vx=8.28509272894133 vy=2.5160231838257237 vz=-0.022257406997716497>
<rebound.particle.Particle object at 0x7f93fbf20dc0, m=9.7889324e-07 x=-1.570962722115503 y=-1.4434423247410162 z=0.0019915246186709003 vx=-1.0002272965079102 vy=-7.5205617260717625 vz=-0.008823016739789446>
```
Which are clearly not the same endpoint. 
Since the system itself is not integrating correctly, this problem then gets compounded when I add particles and collisions. As I said above, I'm getting different collisions depending on whether or not I integrate continuously. 

For reference, these are the constants I used in the above two simulations:
```
Rsun_to_AU = 0.00465047
Rearth_to_AU = 4.2635e-5
days_to_yr = 1/365.25
Mearth_to_Msun = 3.00274e-6 
deg_to_rad = math.pi/180
```

**Comment by hannorein** [comment]
IAS15 is using adaptive time steps. However, by calling `sim.integrate(100)` you force REBOUND to reduce the last timestep so that it gives you back exactly the time coordinates at time 100. This will affect all future time steps (at the machine precision level, so it only matters for situation like yours where you care about the this level of precision or reproducibility). Use the `exact_finish_time=False` flag in the `integrate()` flag to avoid this issue.

**Comment by bungler0** [comment]
Hmm. Using the exact_finish_time=False flag solves the issue in the system-only integration, but once I add in the particles it's still giving me different collisions based on continuity. I'll rustle up a simpler example, but in the meantime, is there anything in the addition of (massless) particles and collision handling that could potentially disrupt reproducibility? I am using a custom collision_resolve method that removes particles as their collisions are detected (and does some auxiliary bookkeeping) , and I am using the direct form of collision detection.

**Comment by hannorein** [comment]
Hm. I think this should work on the REBOUND side of things (of course, there could always be a bug). But the problem could very well be in your `collision_resolve` function. But I would need to see an example that I can run myself to say more. Just to make sure, do you use the latest REBOUND version?

**Comment by bungler0** [comment]
Well, somewhere along the way of creating an example of the issue, I somehow solved the issue and now everything is running perfectly! Most likely it was an error on my part, but thank you so much for bearing with me! I really appreciate it.

**Comment by hannorein** [comment]
Glad to hear its working!
