### ISSUE TITLE
Particle.r - units?

### ISSUE THREAD

**Issue by void4** [hannorein/rebound#526]
When  I initialize a simulation with

```
sim = rebound.Simulation()
sim.add("solar system")
```

the sun and planets have no radius values.

I can set them with

```
for i in range(9):
    sim.particles[i].r = [?,?,?,?,?,?,?,?,?][i]
```

But I don't know what unit the `r` values should have, it doesn't seem to be documented. Will they have to be specified in *AU* by default?

**Comment by hannorein** [comment]
REBOUND doesn't use a fixed set of units. You just need to be consistent. If you setup orbits in astronomical units, then all other length units that appear anywhere (including the radius) are also in astronomical units. The "solar system" example you currently use, does use astronomical units.
