### ISSUE TITLE
JPL's HORIZONS query

### ISSUE THREAD

**Issue by AstroEloy** [hannorein/rebound#530]
I have noticed that if I do a query with rebound for a specific date and the whole solar system, the position and velocity of the earth are different from those returned directly by Horizons.

What is the reason for this? Is it because of the reference system? Is there any way to fix it and have Rebound get exactly the same answer from Horizons?

    from astroquery.jplhorizons import Horizons
    import rebound

    time = '2015-03-30T21:33:52.000'
    JD = Time(time).jd
        
    #JPL'S HORIZONS
    obj = Horizons(id="Geocenter", location="@sun", epochs=JD, id_type='id').vectors()
    print(obj['x']*1.496e+8, obj['y']*1.496e+8, obj['z']*1.496e+8) #km

    #REBOUND
    sim = rebound.Simulation()
    date = "JD"+str(JD)
    sim.units = ('s', 'km', 'kg')

    sim.add("Sun", date=date)
    sim.add("Mercury", date=date)
    sim.add("Venus", date=date)
    sim.add('Geocenter', date=date)
    sim.add("Luna", date=date)
    sim.add("Mars", date=date)
    sim.add('Jupiter', date=date)
    sim.add('Saturn', date=date)
    sim.add('Uranus', date=date)
    sim.add('Neptune', date=date)

    sim.N_active = sim.N
    print(sim.status())

**Comment by hannorein** [comment]
Hm. REBOUND uses `@0` instead of `@sun`. Any chance that's the difference?

**Comment by AstroEloy** [comment]
Thanks! Closer but still different..

**Comment by danielk333** [comment]
I'm not familiar with how astroquery implements its methods but when i was trying to correlate results from different API's with `jplephem.spk` and a local kernel i found that the time scale used was very important (jplephem uses Barycentric Dynamical Time for example)

After a quick look at [astroquery](https://astroquery.readthedocs.io/en/latest/jplhorizons/jplhorizons.html) i found
> Note that all input epochs, both calendar dates/times and Julian Dates, refer to UTC for ephemerides queries, TDB for element queries, and CT for vector queries.

May that has something to do with it?

**Comment by hannorein** [comment]
Regarding `@sun`. You'd either need to change this manually in the `horizons.py` file (just search for `@0`), or once you've imported the particle data, just move to the heliocentric frame `sim.move_to_hel()`.

**Comment by AstroEloy** [comment]
It works! Thank you very much!
