### ISSUE TITLE
OpenMP code doesn't listen to setting OMP_NUM_THREADS

### ISSUE THREAD

**Issue by teuben** [hannorein/rebound#537]
this is the code I see used to set the processors:

int np = omp_get_num_procs();
omp_set_num_threads(np);

there must be some cute generic way to not saturate the processor (and more than often hyper-threads don't help at all).

**Comment by hannorein** [comment]
Hi Peter! I'm not sure I understand your question. What are you trying to do?

**Comment by teuben** [comment]
I was trying to force it to use only 4 processors, bit it claims it's using
8. I thought this environment variable was supposed to work

**Comment by hannorein** [comment]
When you say "it claims it's using 8", do you mean the printout of REBOUND on the screen? If so, note that [it prints out](https://github.com/hannorein/rebound/blob/main/src/rebound.c#L617) the result of `omp_get_max_threads()`. I agree that's confusing. I think it would make more sense to print out the result of `omp_get_num_threads()`.

**Comment by hannorein** [comment]
Actually I take that back. `omp_get_num_threads()` will return the current number of threads during a parallel calculation, but it will return 1 in serial code. Not sure what the best approach here is. I'd need to look more into it...

**Comment by teuben** [comment]
agreed. I never solved it in NEMO, where I had some hybrid of listening to OMP_NUM_THREADS and using a keyword np=

btw, if you take out the  omp_set_num_threads(np); call, it worked wiht the env.var and if you don't set it, it takes the max. I'm confused myself also now. What the hexk is the omp_set call for otherwise.....

**Comment by hannorein** [comment]
According to [this](https://stackoverflow.com/a/22816325/115102), `omp_set_num_threads()` overrides the value of `OMP_NUM_THREADS`. But yes, I'm also a bit confused.

**Comment by teuben** [comment]
I can only get yours to work when i use
int np =omp_get_max_threads();
then the default is 8, and OMP_NUM_THREADS  sets it correctly to what I want.....
i know it's counter to that link you sent...   can you try this on your mac? i'm on ubuntu 20.10

**Comment by hannorein** [comment]
I'm not entirely sure what you're trying to achieve. But I've tried out the OpenMP example in REBOUND and it works as expected on Linux (Debian 4.19.160-2).

**Comment by teuben** [comment]
The mystery deepens. I'll try it on a few different linux systems. Just to be clear again, I wanted to run in e.g. 2 cores by prepending the command with OMP_NUM_THREADS=2

**Comment by teuben** [comment]
perhaps my mind is more clear now in the morning.  I see what you are trying to do. You are forcing it to use all the cores and MT's that the CPU has, hence the 8 in my case. Normally you would want to leave out the omp_get and omp_set, and leave it to the caller. In that case it will listen to the environment variable. So maybe some cautionary words that is fixes it to the max.

**Comment by hannorein** [comment]
Correct. The example runs the simulation twice. Once with the number of threads equal to the number of available processors and once with only one thread. Then it calculates the speedup. I can add a few cautionary words, but I think the comments in the code already say more or less exactly what it does:

```c
// Get the number of processors
int np = omp_get_num_procs();
// Set the number of OpenMP threads to be the number of processors
omp_set_num_threads(np);
...
// Reduce the number of threads to 1 and run again.
omp_set_num_threads(1);
```

**Comment by teuben** [comment]
certainly that those two lines of code are typically not how you would code your own application. I believe they just can be left out, and give the control to the caller via setting OMP,   or alternatively another method of omp_set_num_threads().
Perhaps the comment could be that if you had choosen np = omp_get_max_threads() it would listen to OMP_NUM_THREADS, and then my confusion would have never occured.

But this confusion didn't come without a benefit (for me at least), I've now properly (?) implemented this idea in NEMO, where we use a nemo_main(), and not the generic main().  So we do some work (e.g. parsing commandline) before the user gets control, and now I've  set the # processors based on:
    1. OMP_NUM_THREADS, if present   (it uses omp_get_max_threads()  here)
    2. np=  system keyword, if present


In particular with modern laptops where MT is turned on, using all "processors" is generally a bad idea.  I think zoom is one of those apps that seems to grab them all, and give no power to the user.

**Comment by hannorein** [comment]
I don't know, I disagree a little. I prefer to set the number of threads in the code, not via an environmental variable. If everything (including the number of threads used) is in the same place (code), it's much more straightforward to understand where the settings come from. But this gets a bit philosophical -- I don't think there is a REBOUND issue here, so I'll close this thread for now.
