### ISSUE TITLE
Some Angle Computations Seem Shifted

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#539]
Hi Hanno,

I was working with data from some simulation archives and ran into a discrepancy between the outputted true anomaly and that which should be returned (according to documentation). I'm attaching a figure which shows *f* vs *t* and that *f* is being output from -270 -- 90 rather than the expected -180 -- 180. Maybe this is an easy fix?

[Rebound_true_anomaly_bug.pdf](https://github.com/hannorein/rebound/files/6548811/Rebound_true_anomaly_bug.pdf)

In this figure you can see a continuous plot of *f* for asteroid Flora and 4 orbitplots showing *f* = -90, 0, -270, -180

**Comment by hannorein** [comment]
Hi Robert. I probably don't need to explain this to you, but angles are only defined up to k*360 degrees for arbitrary integer k. So is the issue that you need to add or subtract 360 degrees? Or are the angles actually shifted and if so by how much?

**Comment by Rmelikyan** [comment]
I included the figure to prove to you and myself that the angles output by Rebound are correct. 0° appears to be the periapsis etc... I was under the impression that Rebound always returned angles in radians from -pi to pi. The only transformation I applied to this output was the conversion from radians to degrees (*180/pi). If this is not the case, then I have misidentified a non-issue. It is true that the provided angles can certainly be worked with effectively. I was just confused as to why the output was -3pi/2 to pi/2.

Thanks for the clarification.

**Comment by hannorein** [comment]
Thanks! You're not the only one who asked this question. So I will add an extra `mod2pi()` call to all angles in the orbital element routine. It's a little bit slower and might loose a bit or two in precision, but I think that's worth it...

**Comment by hannorein** [comment]
Sorry for the slow response! 

I think having a flag would be too complicated. People would first need to understand why the flag exists, where it applies, etc. I think the right solution is to always return the angles in a given range (by calling mod2pi).

**Comment by Rmelikyan** [comment]
Sounds good!

**Comment by hannorein** [comment]
(keeping this open so I don't forget)

**Comment by hannorein** [comment]
Hi Robert, 

I've been looking into this, but I am a bit confused. It seems [the code](https://github.com/hannorein/rebound/blob/main/src/tools.c#L1081) is already calling `mod2pi` on the true anomaly before returning it. So the range should be `[0 2pi]`. How are you calculating the orbits? And which version of REBOUND do you use (this was changed 4 months ago). 

Thanks,
   Hanno

**Comment by Rmelikyan** [comment]
Rebound version was 3.16

If this makes any difference (it shouldn't?) I notice a discrepancy in the range of the output when dealing with archived sims rather than during the original instance of the simulation.

i.e. The above figure I supplied was produced in a secondary jupyter notebook which opened and analyzed a saved state from a sim I had developed in a primary notebook.

**Comment by hannorein** [comment]
I think this is because you're using an older version of REBOUND which didn't have the mod2pi in there.

**Comment by Rmelikyan** [comment]
Great! Glad this was just a version issue after all. Sorry for the confusion!
