### ISSUE TITLE
noParticles error

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#540]
Hi all,

I have been running simulations with ~10 planets around a star. I was surprised to find the following error raised in some (just a handful) runs:

`rebound.NoParticles: No more particles left in simulation.`

How can this be? Even if somehow all planets are ejected/collide, the star shouldn't be going anywhere. I assume this is some kind of numerical issue then.

I am not updating anything between timesteps. My Python code is just a single call to `sim.integrate(tmax)`, after initializing the planets. I have an open box, with size set to 500 AU and collisions enabled. I am using IAS15 to integrate. The issue doesn't appear when I use MERCURIUS.

Sorry for the sparse details; I'll try to post a minimum example soon (it is a bit hard because of the chaos of the problem). But in the meantime, any ideas would be most welcome. I am stumped.

Thanks!
Nick

**Comment by hannorein** [comment]
If you use an open box and all planets get ejected/collide, then the star will likely have some finite velocity and will eventually drift out of the box by itself. So if you have an open box, you might want to 1) make it very big and 2) periodically call `move_to_com()` to keep the surviving planetary system close to the centre. Alternatively, you could write your own function that you call periodically and check for the distance between all planets and the star (heliocentric distance), then remove the very far away planets and the call `move_to_com()`. The latter approach would avoid having to fine tune the interval.

**Comment by nchoksi4456** [comment]
Thanks for the idea! I will check.

**Comment by nchoksi4456** [comment]
> Alternatively, you could write your own function that you call periodically and check for the distance between all planets and the star (heliocentric distance), then remove the very far away planets and the call move_to_com(). The latter approach would avoid having to fine tune the interval.

Like this? Here I am eliminating particles by hand, so there is no REBOUND box setup (`sim.boundary` and `sim.configure_box` are never set).

```
        
	sim.move_to_com()
	for time in times:
		sim.integrate(time, exact_finish_time = 0)
		for particle in reversed(sim.particles[1::]):
			dhelio = np.sqrt(  (sim.particles[i].x - sim.particles[0].x)**2 + (sim.particles[i].y - sim.particles[0].y)**2 + (sim.particles[i].z - sim.particles[0].z)**2  )
			if(dhelio > 1000*cgs.AU):
				sim.remove(i)
				sim.move_to_com()
```
Also, just to confirm -- this setup above can and should be used regardless of which integrator I am using, right? 

Thanks again!

**Comment by hannorein** [comment]
Looks great! How often you call it shouldn't matter too much. If you call it more often, you will catch leaving particles earlier. If you call it less often, it will save some CPU time.

Small trick to do the heliocentric distance calculation with less code:

```
np.linalg.norm((sim.particles[1]-sim.particles[0]).xyz)
```

**Comment by nchoksi4456** [comment]
Thanks Hanno! This solved the issue. Closing the thread.
