### ISSUE TITLE
Integration time is too long

### ISSUE THREAD

**Issue by metehanakcan** [hannorein/rebound#542]
Hi,

I added sun, earth, moon and test particle( a artificial satellite) in my C code. I integrated for just 1 year but it takes 3 hours. I removed test particle and added Mars then everything is correct, it just takes a few minutes. I didn't solved that.

Thank you, 
Metehan.

**Comment by hannorein** [comment]
Hi Metehan, an artificial satellite might complete 1e4 orbits in one year. Nevertheless, a 3 hour integration seems excessively long. To say anything else, you need to share your example code or provide a bit more information: what integrator do you use, what's the timestep, etc.

**Comment by metehanakcan** [comment]
if i choose primary is sun for moon and satellite, time is so long, when i choose primary is Earth instead of Sun for them, time is take a few minutes but result of orbital elements are wrong, i check from Horizon. i added below my code and results.
thank you,
Metehan.

results of my code: SATELLITE
a = -3.0353093809451929e+02
e = 1.0066012620795777e+00
inc = 7.9309839178373209e-03
Omega = 1.9941458436325107e+02
omega = 3.5973422742334446e+02
f = 6.7980535391046848e+00

horizon data:   2459325.500000000 = A.D. 2021-Apr-21 00:00:00.0000 TDB 
 EC= 7.098801965434588E-01 QR= 1.002383930295833E+00 IN= 1.577133473069401E-01
 OM= 2.111351758566461E+02 W = 3.534021961039144E+02 Tp=  2459320.593946972862
 N = 1.534684095103604E-01 MA= 7.529241550507316E-01 TA= 6.289890873743142E+00
 A = 3.455068969278364E+00 AD= 5.907754008260895E+00 PR= 2.345759633194719E+03
`  
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <math.h>
#include "rebound.h"
#include "tools.h"



#define PI 3.14159265358979323846


void heartbeat(struct reb_simulation* r);
double e_init;
double tmax;




int main(int argc, char* argv[])
{
   struct reb_simulation* r = reb_create_simulation();
	//r->G            = 0.00029591220828559104;

	r->G 		= 6.67384e-11;  	//	m^3 kg-1 s-2
	r->dt 		= 60*60*24*1;		// 	 a day,  in seconds 
	tmax		= 60*60*24*10.; 	//   	1 years, 	in seconds
    	r->ri_whfast.safe_mode     = 0;        
	r->integrator        = REB_INTEGRATOR_IAS15;    
	


	struct reb_particle sun;
  
	sun.m=1.988544e30; sun.x=0.000000000000000e+00; sun.y=0.000000000000000e+00; sun.z=0.000000000000000e+00;
	sun.vx=0.000000000000000e+00; sun.vy=0.000000000000000e+00; sun.vz=0.000000000000000e+00;

	reb_add(r, sun); 



	struct reb_particle primary = r->particles[0];

	// orbital elements orders = r -> G, primary, m, a, e, inc, Omega(long.ascen), omega(arg. peri), f(true anomaly)
	//heliocentric (coordinates) orbital elements	

	struct reb_particle earth = reb_tools_orbit_to_particle(r->G, primary,5.97219E+24,
	1.000827333888226*149597870.700*1000, 1.672974045655197E-02, 2.041214192637905E-03*PI/180, 
	1.622596770946175E+02*PI/180, 3.034561444283431E+02*PI/180, 9.532401087398509E+01*PI/180);
	
	reb_add(r,earth);


	struct reb_particle moon = reb_tools_orbit_to_particle(r->G, r->particles[0],7.349E+22,
	9.367746015743872E-01*149597870.700*1000, 6.761877180385856E-02, 7.749859632294932E-02*PI/180,
	2.091619571313481E+02*PI/180, 1.794616424750330E+02*PI/180, 1.724488247219111E+02*PI/180);

 	reb_add(r,moon);


  	struct reb_particle satellite = reb_tools_orbit_to_particle(r->G, r->particles[0], 0, 
	3.815090566566681*149597870.700*1000, 7.377849461690565E-01, 2.775270904675583E+00*PI/180,
	2.010573012686224E+02*PI/180, 5.193044181702400E+00*PI/180, 3.547898442505017E+02*PI/180 );


	
	
	reb_add(r,satellite);

	r->N_active = r->N -2;
	reb_move_to_com(r);
	r->heartbeat        = heartbeat;
	reb_tools_megno_init(r);

	////e_init = reb_tools_energy(r);
	//system("rm -f energy.txt");
	//system("rm -f orbits.txt");
	reb_integrate(r,tmax);
	
	
}

void heartbeat(struct reb_simulation* r){
 if (reb_output_check(r, 1.)){
	
        reb_output_timing(r, tmax);
        reb_integrator_synchronize(r);
	FILE* f = fopen("sattelite_chaos.txt","a+");
        fprintf(f,"        %.20e     %.20e\n",r->t, reb_tools_calculate_megno(r));
	fclose(f);
	
	//printf("        %.20e     %.20e\n",r->t, reb_tools_calculate_megno(r));

       // FILE* f = fopen("energy.txt","a");
       // double e = reb_tools_energy(r);
       // fprintf(f,"%e %e\n",r->t, fabs((e-e_init)/e_init));
       // fclose(f);
	//reb_output_orbits(r,"orbits.txt"); 



 for( int i=3; i<=3;i++){
	struct reb_orbit o= reb_tools_particle_to_orbit(r->G, r->particles[i], r->particles[0]);
	if (i == 1){printf("\nOBJECT : EARTH\n");}
	if (i == 2){printf("OBJECT : MOON\n");}
	if (i == 3){printf("OBJECT : SATELLITE\n");}

//printf("gezegen numarası: %d----------------------------------------------------\n", i);
	printf("a = %.16e\n", (o.a/149597870.700/1000));
	printf("e = %.16e\n", o.e);
	printf("inc = %.16e\n", o.inc = (o.inc*180/PI)<0 ? (o.inc*180/PI)+360 : (o.inc*180/PI));   
	printf("Omega = %.16e\n",o.Omega = (o.Omega*180/PI)<0 ? (o.Omega*180/PI)+360 : (o.Omega*180/PI) );
	printf("omega = %.16e\n", o.omega = (o.omega*180/PI)<0 ? (o.omega*180/PI)+360 : (o.omega*180/PI));
	printf("f = %.16e\n", o.f = (o.f*180/PI)<0 ? (o.f*180/PI)+360 : (o.f*180/PI));

    }
  
	
     }


	
    

}

  `

**Comment by hannorein** [comment]
It depends on what you want to do. If you are interested in the Earth and Moon system, it would make sense to put the Earth-Moon barycentre at the origin, then add the sun as an external perturbation. But if you are interested in Mars as well as your e-mail suggests, then you probably want to keep the sun near the origin. 

You say the orbits are "wrong" but now what's wrong. Note that you might want to calculate the Moon's orbit with respect to the Earth, but the Earth's orbit with respect to the Sun. Choosing a primary for the calculation of orbits is different from choosing a primary for the integration method or coordinate system.

**Comment by metehanakcan** [comment]
Thank you for your answer

**Comment by hannorein** [comment]
I'll close this issue for now but feel free to reopen if there still is a problem.
