### ISSUE TITLE
user-defined output file to record mergers

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#543]
Hi all, 

Super simple question: I would like to record mergers and write info to an output file, similar to the example provided [on the docs](https://rebound.readthedocs.io/en/latest/c_examples/closeencounter_record/). The only change I'd really like to make is  for the filename to be user-defined, from the Python wrapper. 

Is there a simple way to make this change in `collision_resolve_merge`? I was thinking I could make "merger_filename" an attribute of the simulation class that would then be easily accessed directly in the collision resolve function. But I got lost when I tried to do this in practice. Suggestions on which lines in the source code to change to go about this, or suggestions for another method, would be appreciated!

Thanks!
Nick

**Comment by hannorein** [comment]
Hi Nick, 

Good questions. Many possible solutions:

1. REBOUNDx offers some functionality like this. But this might be overkill for this simple use case.
2. You could use a global variable. But this is risky if you ever work with more than one simulation at a time.
3. Use some other variable that is not used in your simulation. This is obviously dangerous too. 
4. The best solution: you can do what you suggested and add a field to the simulation structure in these too locations:
- The rebound.h file, for example after this line https://github.com/hannorein/rebound/blob/main/src/rebound.h#L533
- The simulation.py file, after this line (needs to match the location you changed in rebound.h): https://github.com/hannorein/rebound/blob/main/rebound/simulation.py#L2144

You can then set the field with 
```
from ctypes import create_string_buffer
p = ctypes.create_string_buffer(b"hello")
sim.yourname = p.value
```

**Comment by nchoksi4456** [comment]
Thanks Hanno! Your instructions for suggestion 4 worked like a charm.
