### ISSUE TITLE
different results with and without safe_mode = 1 for a very simple system

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#545]
Hi all

I've stumbled on some non-sensical results when I turn MERCURIUS's safe mode off. Not sure what's going on, since the issue persists even when I reduce to the simplest case of a star + one planet. In the plots below I am showing the distance from the star to the COM. 

<img width="442" alt="safe0" src="https://user-images.githubusercontent.com/25126947/120913905-4a86db00-c64f-11eb-954c-cfad21bb44f5.png">

<img width="417" alt="safe1" src="https://user-images.githubusercontent.com/25126947/120913901-45c22700-c64f-11eb-99c3-99568a1d17a4.png">

Here's the code to make the plots above (just change the safe mode flag to go between the two plots).

```
sim = rebound.Simulation()
sim.add(m=1)
sim.add(m=1e-3, a = 1)

filename = "testsafemode.bin"
sim.automateSimulationArchive(filename, step = 1)
sim.move_to_com()

sim.integrator = "mercurius"
sim.ri_mercurius.safe_mode = 0
sim.dt = 0.01*sim.particles[1].P


sim.integrate(2, exact_finish_time = 0)


fig, ax = plt.subplots(figsize=(6,6))
sa = rebound.SimulationArchive(filename)
tl = np.array([s.t for s in sa])
dl = np.array([np.linalg.norm(s.particles[0].xyz) for s in sa] )
ax.scatter(tl, dl, label = "simulation archive, safe mode = %d" % (sa[0].ri_mercurius.safe_mode))
ax.legend(loc=(1.0, 0.5), frameon = False)

ax.set_xlim(0,2.1)

ax.set_ylabel("distance from star to COM")
ax.set_xlabel("time")

```

Thanks, and as usual, sorry if this has a simple answer that I've overlooked!

**Comment by hannorein** [comment]
Thanks for this. I got a bit confused myself. 

When you request a given snapshot and the safe_mode is off, then the results are not synchronized. You need to do it manually:

```
tl = np.zeros(len(sa))
dl = np.zeros(len(sa))
for i, s in enumerate(sa):
    s.integrator_synchronize()
    tl[i] = s.t
    dl[i] = np.linalg.norm(s.particles[0].xyz)
```

But when you request a given time, it will synchronize it automatically (e.g. `sa.getSimulation(1.2344)`). I don't think this is very intuitive and we should probably change that...

**Comment by nchoksi4456** [comment]
Great. Thanks Hanno!
