### ISSUE TITLE
IAS15 gives unphysical results for an extremely eccentric system

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#546]
Hi all 

I'm integrating many two-planet, highly eccentric systems. All point masses, so no collisions. For the most part, IAS15 is doing an excellent job of conserving energy. But in a small fraction of my runs (~few out of ~120 realizations) there are huge energy errors and unphysical results. 

Here's an example (q = peri, Q = apo). You can see that all of a sudden both planets go flying away from the star and end up ejected from the system. 

<img width="975" alt="ias15_err" src="https://user-images.githubusercontent.com/25126947/120960168-20492200-c710-11eb-873a-51ebb93ceedc.png">

I think what's happening is that the inner planet is just getting too close to the star, and that is throwing the whole integration off. Still, I'm a little surprised since the energy errors really start to grow around log(t) ~ 3.5, at which point the pericenter is about ~0.002 AU -- small, but not orders of magnitude smaller than, say, Rsun.

Maybe this is just some edge case, which is fine, just hoping to clarify one way or another. Or if there are suggestions about how to catch these cases in-the-act and handle them (e.g. forcing a smaller timestep), that would be great too.

Here's a script that should run out-of-the box (should take ~30 sec to finish). Unfortunately I can't reproduce the error exactly when I re-run on my Mac instead of on our cluster, even with the same random seed etc., though there is a similar large jump in energy error at about the same time. 

```
import numpy as np
import rebound 
import time as ti


G = 6.67e-8         # gravitational constant, cm^3/g/s^2
AU = 1.496E13       # astronomical unit, cm
Msun = 1.99e33      # mass of sun, g
Mjup = 1.898e30     # mass of Jupiter, g
yr = 3.154e7		# seconds in a year


trun = 1e4


def draw_planets():
	# Lay down Np planets, separated uniformly in logspace
	Np = 2

	logalist = np.random.uniform(np.log10(0.03*AU), np.log10(10*AU), size = Np); alist = 10**logalist; alist = np.sort(alist)
	e1 = np.random.uniform(0,1)
	Q1 = alist[0]*(1+e1)
	if(Q1 > alist[1]): # Orbits already crossing
		e2 = np.random.uniform(0,1)
	else: 	# Force the outer planet to cross the inner planet's orbit, q_out = Q_in/2
		rcross = Q1/2
		e2 = 1 - rcross/alist[1]
	elist = np.array([e1, e2])

	mlist = np.zeros(Np) + Mjup 

	# Random angles
	pomegalist = np.random.uniform(0,2*np.pi, size = Np); flist = np.random.uniform(0, 2*np.pi, size = Np)
	Omegalist = np.random.uniform(0, 2*np.pi, size = Np)
	inclist = np.random.uniform(0, 1*np.pi/180, size = Np)
	return mlist, alist, pomegalist, flist, elist, Omegalist, inclist


def call_rebound(idx):
	
	np.random.seed(idx)
	# Generate Rebound initial conditions and call here
	sim = rebound.Simulation()
	sim.G = G; sim.track_energy_offset = 1



	sim.add(m=Msun, hash = "star")
	mlist, alist, pomegalist, flist, elist, Omegalist, inclist = draw_planets()
	count = 0 
	for mv, av, pv, fv, ev, Ov, iv in zip(mlist,  alist, pomegalist, flist, elist, Omegalist, inclist):
		sim.add(m = mv, a = av, e = ev, pomega = pv, f = fv, Omega = 0, inc = 0, hash = "p%d" % count)
		count += 1
	

	filename = "pmerrsavio_trun_%.1f_idx_%d.bin" % (np.log10(trun), idx)
	interval = trun*yr/1e4
	sim.automateSimulationArchive(filename, interval=interval,deletefile=True)
	
	sim.move_to_com()
	start_time = ti.time()
	# First integrate with IAS
	sim.integrator = "ias15"
	times0 = np.arange(0, trun*yr, step = 10*yr)
	start_ias_time = ti.time()
	for time in times0:
		sim.integrate(time, exact_finish_time = 0)
		for i in reversed(range(1,sim.N)):
			dhelio = np.linalg.norm((sim.particles[i]-sim.particles[0]).xyz)
			if(dhelio > 1000*AU):
				Ei = sim.calculate_energy(); sim.remove(i); sim.energy_offset += Ei - sim.calculate_energy();
				sim.move_to_com()
	end_ias_time = ti.time()
	print("IAS runtime = ", end_ias_time - start_ias_time)


	print("\n")
	sys.stdout.flush()	
	end_time = ti.time()
	return end_time - start_time

call_rebound(410)




```

**Comment by hannorein** [comment]
Hm. From the left plot, it looks like your pericenter is much less than 0.002 AU by the the time this happens...

**Comment by hannorein** [comment]
Yeah, I think that's happening. The planet is just **very** eccentric. It seems that IAS15 can only handle this down to about e = 1 - 1e-6. I wish IAS15 were better at this, but it's a difficult problem! For example, it's hard to predict the timestep to resolve pericenter, and at some point floating point number run out of digits which makes it hard for IAS15 to determine if the integration of converged. 

![image](https://user-images.githubusercontent.com/53376/121184463-1b30c380-c833-11eb-80f1-809f87be4bb0.png)

**Comment by nchoksi4456** [comment]
Thanks for confirming Hanno!
