### ISSUE TITLE
Switching integrator after archive reload

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#547]
Hi Hanno,

Hopefully this is a quick one.

Any reason why switching from mercurius to IAS15 or WHFast  after reloading a simulation may cause a segmentation fault or ipython kernel death upon integration? The problem occurs whether I'm setting the new integrator in python or C.

I'm trying to optimize a particular simulation that I'm going to have to run a bunch of times and it would be great to test out different integrators continuing from an initial state that I had previously saved.

Maybe I need to rebuild the simulation "Manually"?

Best,
-Robert

**Comment by Rmelikyan** [comment]
Hi, Sorry I haven't moved forward with an example for this problem yet... 

It is still active, at least for my bin files, but I have a workaround that is working for now.

I will try to generate an example soon.

**Comment by hannorein** [comment]
I'm closing this for now, but feel free to reopen the issue if a problem still persists.
