### ISSUE TITLE
Question about COM vs. heliocentric coordinates

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#549]
Hi all

I'm integrating a simple two-planet system in which one of the planets gets ejected, sailing off to infinity. But, even after the ejected planet is super far away from the remaining planet, so that the system is effectively a two-body (star-planet) system, the orbital elements of the remaining planet go wild IF I use the COM as the primary -- see the pink curves in the left two panels below. 

<img width="1110" alt="com" src="https://user-images.githubusercontent.com/25126947/121558772-f039a180-c9e3-11eb-84d2-175069551646.png">

The ejection happens at log(t) ~ 2.9 (see third panel, black curve for "planet 1"), and by log(t) ~ 3, the ejected planet is so far away that it should not influence the remaining planet at all -- see also the final panel showing the energy of each object. The energies are constant after log(t) ~ 3, again demonstrating that the two planets are not interacting. So this is why I think the issue has to do exclusively with the calculation of orbital elements, and that physical quantities like (x,y,z), (vx,vy,vz) are fine (energy and ang mtm are well conserved).

When I use heliocentric coordinates the orbital elements behave more like how I would expect:

<img width="1111" alt="helio" src="https://user-images.githubusercontent.com/25126947/121558930-17906e80-c9e4-11eb-945c-5b82bcda9afc.png">

I think there must be some subtlety about how the COM elements are calculated that I'm missing...It probably has to do with the star-COM curve (gold in third panel); after the ejection, the star's distance from the COM goes flying, because the ejected planet is so far away that it can drag the COM along for the ride  (the yellow curve is always ~1e-3 of the black curve because the planet-to-star mass ratio is ~Mjup/Mstar ~ 1e-3). But I can't figure out precisely what is causing the behavior. 

Any ideas would be appreciated. Thank you!

**Comment by nchoksi4456** [comment]
The latter, for calculating orbital elements once already in the simulation. i.e. the two plots differ in whether I'm plotting:
 `sim.particles[1].calculate_orbit(primary = sim.calculate_com())` 
vs. 
`sim.particles[1].calculate_orbit(primary = sim.particles[0])`.

**Comment by nchoksi4456** [comment]
Thanks Hanno. I am still a little confused. As you say, for Jacobi coordinates the primary is the COM of all interior planets. So why can't the primary be the COM of *all* planets (which is what I thought the flag `primary = sim.calculate_com()` is doing)?


In any case, even when I use the default `calculate_orbits() ` (i.e., I don't pass any primary to the function), which is Jacobi, I get the same wild results as when I passed `primary = sim.calculate_com()`.
<img width="833" alt="Screen Shot 2021-06-10 at 3 02 09 PM" src="https://user-images.githubusercontent.com/25126947/121582325-dce70000-c9fc-11eb-9df3-27569a5a821d.png">


> I'll need to check the documentation. If the first one is in there as an example, then that's a mistake.

Not sure about the documentation. I'm referring to the comments in the code itself:

<img width="1008" alt="Screen Shot 2021-06-10 at 2 59 50 PM" src="https://user-images.githubusercontent.com/25126947/121582028-87aaee80-c9fc-11eb-9250-49e623c4d698.png">

**Comment by hannorein** [comment]
(Just removed the deprecated part of the documentation -- it was confusing -- sorry!)

The default used Jacobi coordinates. If you're inner planet gets ejected, Jacobi coordinates don't make sense anymore for the outer planet. It is now only orbiting the star, not the star+inner planet. 

I admit it's confusing, but in the end that's because orbital parameters are confusing! They describe a perfect two body orbit, but there are always more than two bodies! It might help to think about what would happen for an equal mass binary (or three particles with equal mass).

**Comment by nchoksi4456** [comment]
Thanks Hanno! I'll keep thinking about it.

One last clarifying question: the calculation of Jacobi coordinates loops over particles, successively adding each particle in the order it is present in the particles array [(referring to this line](https://github.com/hannorein/rebound/blob/f291f87671f035b33759181db6c641fdcaefcaf8/rebound/simulation.py#L1475)). So are particles in the particles array always re-ordered by distance from the origin, sqrt(x^2 + y^2 + z^2)? The documentation notes that particles can in general move around in the particles array, so I'm just trying to figure out how exactly they get shuffled around as the simulation progresses.

In any case, it seems safer to use heliocentric orbital elements over Jacobi elements in systems where there is a lot of movement, including ejections.

**Comment by hannorein** [comment]
You need to add them in the correct order. There is no way to unambiguously do that in an automatic way. For example, imagine two particles in a co-orbital resonance. If particle swap position, then you need to resort them manually (or not use Jacobi coordinates to begin with).

**Comment by nchoksi4456** [comment]
Gotcha, thanks, this explains a lot!

**Comment by hannorein** [comment]
No worries. It is confusing! I only understood orbital elements after writing code which calculates them...
