### ISSUE TITLE
Rebound on IntelPython3

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#550]
Hi Hanno,

I've been having to work on a cluster to run some bigger simulations. I wrote the actual simulation programs in C, but now that I am trying to analyze the resulting simarchives, I want to use the python API.

I have followed my clusters instructions for loading their python module which is intelpython3.

The pip installation of rebound is trivial, but when I try to import rebound in any script or the CLI I get the following OSerror:
>pip install rebound
Collecting rebound
  Using cached rebound-3.17.2-cp37-cp37m-linux_x86_64.whl
Installing collected packages: rebound
Successfully installed rebound-3.17.2
(venv) 16:07:38 [rmelikyan data_analysis]# python
Python 3.7.7 (default, Jun 26 2020, 05:10:03) 
[GCC 7.3.0] :: Intel(R) Corporation on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import rebound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/beegfs/home/rmelikyan/data_analysis/venv/lib/python3.7/site-packages/rebound/__init__.py", line 23, in <module>
    clibrebound = cdll.LoadLibrary(__libpath__)
  File "/opt/intel/2020u2/intelpython3/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/opt/intel/2020u2/intelpython3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /beegfs/home/rmelikyan/data_analysis/venv/lib/python3.7/site-packages/rebound/../librebound.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strcpy

Is this fixable or will I have to try to develop a workaround for accessing the data in C?

Best,
-Robert

**Comment by hannorein** [comment]
I had never heard of "Intel(R) Distribution for Python" before. Maybe your cluster lets you choose a more standard python environment?

FWIW, it looks like python is trying to find a proprietary strcpy function. A quick google search bring up many similar issues like this for other packages. You could try installing REBOUND with the setup.py script rather than pip. 

Someone probably paid money for "intelpython3", so maybe it comes with support and they can fix it? ;-)

**Comment by Rmelikyan** [comment]
😅 Good point! I'll look into what local support I can find... 

To install rebound from the setup.py, would that just be `pip install -e .` kind of thing? or am I executing settup.py?

**Comment by hannorein** [comment]
You should be able to just run `python setup.py install`.

**Comment by Rmelikyan** [comment]
Just Ran that. Still crashing on import. :/

**Comment by hannorein** [comment]
It's really hard to say anything else. This is so specific to your cluster that I think this is a problem for your cluster support people. I suspect there is some mismatch between the libraries the compiler sees when it compiles rebound and the libraries this intel python thing sees when it tries to import rebound. You can probably just switch the module for either the compiler or python. But I don't know how that works on your cluster...

**Comment by Rmelikyan** [comment]
Thanks Hanno for looking into it at all! I'm sure I can sort this out.

Closing :)
