### ISSUE TITLE
What does this Warning Mean?

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound#552]
Hi Hanno,

I receive this warning nearly every time I use simArchives and I haven't found instructions about it in the examples.

>Warning! You have to reset function pointers after creating a reb_simulation struct with a binary file.

What should I be doing differently in C? For context I'm stepping through a simarchive and scraping orbital elements

-R

**Comment by hannorein** [comment]
Did you use REBOUNDx, any additional forces, merger functions? If so, you need to set them again manually.

**Comment by Rmelikyan** [comment]
Nope. It's pretty simple. I'll show here

  ```
int main(int argc, char* argv[]){
          if(argc !=2){
                  printf("Must include 'archive_file_path as argument!\nProgram Terminating");
                  exit(0);
          }
  
          char* archive_file_path = argv[1];
  
          struct reb_simulationarchive* sa = reb_open_simulationarchive(archive_file_path);
          if (sa==NULL){
                  printf("Can not open sim file.\nProgram Temrinating\n");
                  exit(0);
          }
          int num_snaps = 40001;
  
          double p_as[40001][10]={0};
          double p_es[40001][10]={0};
          double p_is[40001][10]={0};
  
  
          for (int i=0; i<num_snaps; i++){
                  struct reb_simulation* r = reb_create_simulation_from_simulationarchive(sa,i);
                  struct reb_particle* particles = r->particles;
                  const double G = r->G;
                  const struct reb_particle star = particles[0];
                  const int N = r->N;
                  for (int j = 0; j < N; j++){
                          const struct reb_particle p = particles[j];
                          if (p.m!=0.) continue;
                          struct reb_orbit o= reb_tools_particle_to_orbit(G, p, star);
                          p_as[i][j-8]=o.a; // I know apriori that there are 8 massive bodies
                          p_es[i][j-8]=o.e;
                          p_is[i][j-8]=o.inc;
                  }
                  reb_free_simulation(r);
          }
  }
```

**Comment by hannorein** [comment]
It depends on what you do when you setup the original simulation (not when you load them in).

**Comment by Rmelikyan** [comment]
Ahah... so if I setup the original simulation incorrectly (Lets just assume I did...) then I will always get this warning whenever I access the Sim Archive.

What needs to be done to avoid this in the future?

**Comment by hannorein** [comment]
It has nothing to do with doing something right or wrong! It's just a warning. You might have used one for a heartbeat function, collision mergers, etc. REBOUND cannot automatically reset any custom function pointers because the address might be different from when the simulation was ran. I you didn't use any function pointers, or don't need them anymore (like the heartbeat function) just ignore the warning.

**Comment by Rmelikyan** [comment]
Got it. Thanks for the clarification!
