### ISSUE TITLE
Nice model instability 

### ISSUE THREAD

**Issue by georgeBell25189120** [hannorein/rebound#553]
Hello Hanno, 

As discussed previously (https://github.com/hannorein/rebound/issues/534) I have been attempting to replicate the Nice model instability in MERCURIUS. I have as advised tested with a smaller and more accurate timestep but I still haven't had the hoped-for results. The attached file is a typical output
[20Me200521a.txt](https://github.com/hannorein/rebound/files/6748388/20Me200521a.txt)

The majority of my outputs, like this one, have all five giant planets remaining after the instability although one ice giant should be ejected and there are just a couple of mergers between KBO particles and planets. 

Any advice on how to adapt in order to obtain a satisfactory result would be greatly appreciated. Thanks.

**Comment by hannorein** [comment]
Hi George, 

That's a difficult questions to answer. You say one ice giant should be ejected. Why? And do you think the reason you're seeing different results is a numerical or a physical issue? If it's a numerical issue, what kind of tests have you run to check for convergence? Are you able to compare some of your results to other people's work? If so what is different in their numerical setup and results? In general, it's probably good to break this problem down into smaller parts.

Hanno

**Comment by georgeBell25189120** [comment]
Hello Hanno, 

I am trying to replicate the early evolution of our Solar system via the Nice model. Due to the violence of the ensuing instability recent Nice model simulations, informed by the work of Nesvorny and Morbidelli (https://arxiv.org/pdf/1208.2957.pdf) tend to include an extra giant planet which is ejected as this maximises the chances of finishing the simulation with the best results for Jupiter, Saturn, Uranus and Neptune. I have seen other researchers such as Matthew Clement in "Born eccentric: Constraints on Jupiter and Saturn’s pre-instability orbits" perform these kinds of simulations in MERCURY and their work has informed my starting conditions and approach. I am not sure whether the issue is numerical or physical: I can't think of a physical reason why I can't replicate these instabilities. I haven't checked for convergence: what tests would you recommend I carry out?

George

**Comment by hannorein** [comment]
When you run a numerical simulation, there are various parameters which are not present in the physical system. For example the timestep, and when you use MERCURIUS, the hill switching radius. You should always be in a regime where varying these factors will not affect your results. Practically, this means you should run your simulations with different timesteps, different switching radii, etc. Get a feeling for what parameters are suitable for your setup and which ones don't.

**Comment by georgeBell25189120** [comment]
Hello Hanno,

Thank you. I will try varying those. Last time changing the timestep did make a difference but that was quite a large change (over an order of magnitude). I got my default timesteps from Clement's paper, who in turn was influenced by Nesvorny. 

Regards.

George

**Comment by hannorein** [comment]
This is a difficult problem. And there could be so many things going on. So it's key to break down the task into small pieces, make sure they are all working out as expected. For example, run some tests with only one merger.

**Comment by georgeBell25189120** [comment]
Hello Hanno, 

By only one merger do you mean a custom situation with a single merge between a planet and a test particle?

Regards,

George

**Comment by hannorein** [comment]
Yes. That's just one example...

**Comment by georgeBell25189120** [comment]
Hello Hanno, 

Thanks again for all your help, I have submitted convergence tests with varying timesteps and radii to see what happens and I am going to investigate mergers as well. 

Regards, 

George
