### ISSUE TITLE
Readthedocs .ipynb links broken

### ISSUE THREAD

**Issue by sabaronett** [hannorein/rebound#559]
I haven't checked every single example page, but among the several I've come across, any internally linked [[name].ipynb](https://rebound.readthedocs.io/en/latest/ipython_examples/Horizons/Churyumov-Gerasimenko.ipynb) returns an HTTP 404; see for example [Churyumov-Gerasimenko.ipynb](https://rebound.readthedocs.io/en/latest/ipython_examples/Horizons/Churyumov-Gerasimenko.ipynb) in the first paragraph of [Adding particles using NASA JPL Horizons system](https://rebound.readthedocs.io/en/latest/ipython_examples/Horizons/). This could be fixed by a script as the new, valid ipynb URLs seem to drop the trailing `.ipynb` for a simple `/`; e.g.:

(working) `https://rebound.readthedocs.io/en/latest/ipython_examples/Churyumov-Gerasimenko/`,

instead of 

(not found) `https://rebound.readthedocs.io/en/latest/ipython_examples/Horizons/Churyumov-Gerasimenko.ipynb`,

but any reorganized paths (e.g., no `/Horizons/` above) may be tricky.

Also, the current (auto-generated?) 404 page lacks any CSS. I had to scroll down 3/4 of the page to find this:

<img src="https://user-images.githubusercontent.com/51060809/127341433-6a0b80f5-863c-43db-8dca-988057e89f37.png" width=150 >

P.S.: Love the new site look overall.

**Comment by hannorein** [comment]
Thanks for letting me know! Which pages include the internal links?

**Comment by hannorein** [comment]
Never mind, just read your comment more carefully ;-)
