### ISSUE TITLE
Globals free version

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#56]
I'm working on a thread-safe and global variable free version of the code. The current development is on the branch noglobals2.

**Comment by dsspiegel** [comment]
That's awesome, Hanno!  Great job.
I'm not familiar with function pointers inside a struct.  Just read a bit about them on stackoverflow, but I'm still curious what's the purpose of putting them there?

**Comment by hannorein** [comment]
To have a callback function. It allows me to add additional forces, etc.

**Comment by hannorein** [comment]
Now live on the master branch with last commit being c2f35c0eb6bda6e6eff6b9d8325f36b2f663c029

Some features still need fixing, but I'm getting close.
