### ISSUE TITLE
Tracking many particles with unstable orbits 

### ISSUE THREAD

**Issue by pacmanboss256** [hannorein/rebound#561]
So I want to remove the particle from the simulation on collision, but I don't want to shift the index value of the remaining particles. For instance, if particle 2 collides with particle 4, I want particle 2 removed, but particle 4 should still be particle 4 when i call it. I have not found a way to do this in python, so if you could help or have any suggestions please let me know. Thanks!

**Comment by hannorein** [comment]
Hi, 

That's not possible. The particles are stored in one large array and it can't have gaps. One way to be able to handle this sort of situation are hashes: https://rebound.readthedocs.io/en/latest/ipython_examples/UniquelyIdentifyingParticlesWithHashes/
