### ISSUE TITLE
Feature Request: Enhancements to the orbit plot fancy option.

### ISSUE THREAD

**Issue by DeepSkyWonder** [hannorein/rebound#562]
Hi There,

I just want to say that Rebound is a fantastic package, and a joy to use. :-)

I especially like the fancy plot feature and use it with my students. I was wondering if sometime in the future it would be possible to add some of the following as enhancements to this feature...

(1) The ability to change the fancy plot star colour and size to make simulating exoplanetary systems more representative.
(2) The ability to specify the marker size (dot size) for objects to give an idea of relative size in simulations (especially for planets).
(2) The ability to use a background image for the background stars, instead of the programmatically generated stars.
(3) The ability to overlay a transparent PNG of the central body at the central bodies location.
(4) The ability to overlay transparent PNG images for named particles/objects at their location.
(5) The ability to overlay indicative Roche lobes and Lagrange points, calculated based on a particles data.

I have been considering forking this project and having a go myself. I think I have the skills to make some of the changes, but I still have a few things to learn about building and testing a Python package and working with forked code.

Cameron :-)

**Comment by dtamayo** [comment]
Hi Cameron,

I've also found it useful to make custom plots like you describe. Check out the OrbitPlot example notebook for how to take the pieces of what goes into an OrbitPlot and incorporate them into your own custom figures using matplotlib:

https://github.com/hannorein/rebound/blob/main/ipython_examples/OrbitPlot.ipynb

**Comment by DeepSkyWonder** [comment]
Thanks so much Dan, I will definitely have a look. I just watched your (2015) PyCon video and the 67P simulation is really interesting and a cool application. Cameron :-)

**Comment by hannorein** [comment]
Sorry for the slow response (🏕). 

I second what @dtamayo wrote. At some point it just becomes infeasible to incorporate all possible options for the plots. It should be relatively easy to cherry-pick the pieces you like (all the source code is in https://github.com/hannorein/rebound/blob/main/rebound/plotting.py), and expand upon those yourself. 

I'll close the issue for now, but if you run into a specific problem, let us know.
