### ISSUE TITLE
minor typo in documentation

### ISSUE THREAD

**Issue by SuperdoerTrav** [hannorein/rebound#568]
sim.simulationarchive_snapshpt("archive.bin"), had a p instead of an o in snapshot. Found here:
https://rebound.readthedocs.io/en/latest/simulationarchive/

![image](https://user-images.githubusercontent.com/43413776/132918494-5d51716b-84c8-438f-9458-28cadce1df0c.png)

**Comment by hannorein** [comment]
Thanks!
