### ISSUE TITLE
Horizons API

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#569]
NASA Horizons has now an API. This should replace the old TELNET based one in REBOUND.

https://ssd-api.jpl.nasa.gov/doc/horizons.html

**Comment by Findus23** [comment]
This sounds like an fun thing to program.

If noone else voluneers, I'd like to have a go at trying it out.

**Comment by hannorein** [comment]
That would be great! Thing to keep in mind:
- Ideally, this should not break the user facing REBOUND syntax.
- Try to use as few external packages as possible.  
- If external packages are needed, use the "default" ones as much as possible. 
- Astropy is great, but it is huge. It can probably query Horizons but I would try to avoid it as a dependency.
- Getting this to work with python 2+3 might require some care.
