### ISSUE TITLE
Default Timestep Inconformity Between Docs and Code

### ISSUE THREAD

**Issue by Lingfeng-Wei** [hannorein/rebound#571]
In the [documentation](https://rebound.readthedocs.io/en/latest/simulationvariables/#timestepping), it says the default timestep is 0.01. However, when I run
```
sim = rebound.Simulation()
sim.status()
```
It says the current timestep is 0.001. Is this a typo in the documentation?

**Comment by hannorein** [comment]
Thanks for letting us know!
