### ISSUE TITLE
HORIZONS query 

### ISSUE THREAD

**Issue by AstroEloy** [hannorein/rebound#577]
Hi! For some reason, it seems that REBOUND has a different performance when querying HORIZONS.

Now it cannot be queried a Julian date with more than 3 decimals (before yes).

By the way, it would be nice to query date from YYYY-MM-DD HH:MM:SS not only YYYY-MM-DD HH:MM, so we can have more accurate ephemerides if needed. Is there a reason why REBOUND does not allow YYYY-MM-DD HH:MM:SS query format?

 Thank you!

```
import rebound

sim = rebound.Simulation()

date = "JD2456666.2139"

sim.add("Sun", date=date)
sim.add('Geocenter', date=date)
```

**Comment by hannorein** [comment]
I suspect this is due to the recent changes in the Horizons API. @Findus23 do you have any idea if that is easy to fix?

**Comment by hannorein** [comment]
This should all be working now! Thanks for pointing this out!

**Comment by AstroEloy** [comment]
Thanks! Julian date query is working fine, YYYY-MM-DD HH:MM:SS format is not.

It is needed to changee also `"%Y-%m-%d %H:%M"` to `"%Y-%m-%d %H:%M:%S"`

**Comment by hannorein** [comment]
I think it should work. Did you check the latest version?

**Comment by AstroEloy** [comment]
Yes sorry, I just checked the first modification. Thank you! :)
