### ISSUE TITLE
Small typo in the documentation?

### ISSUE THREAD

**Issue by porpose** [hannorein/rebound#578]
Hi Hanno,

I was looking at how can one access the angular momentum of a particle in REBOUND, and on [this page](https://rebound.readthedocs.io/en/latest/simulationdiagnostics/) there is a line of C code saying:

`double energy = reb_calculate_angular_momentum(r);`

I guess that's a small typo for the variable name? Might make more sense with:

`double angular_momentum = reb_calculate_angular_momentum(r);`

**Comment by hannorein** [comment]
Indeed. Do you want to send me a pull request?

**Comment by porpose** [comment]
> Indeed. Do you want to send me a pull request?

I have just created [one](https://github.com/hannorein/rebound/pull/579), please let me know if I have done it correctly!

**Comment by hannorein** [comment]
Great. Thanks!
