### ISSUE TITLE
Rebound 3.19 is not working in google colaboratory

### ISSUE THREAD

**Issue by malsuar** [hannorein/rebound#581]
Rebound version 3.19 does not currently working on collaboratory.
I recommend installing the previous version with the following command: 

>!pip install rebound==3.18

* Error msg:
>!pip install rebound 

Collecting rebound
  Downloading rebound-3.19.0.tar.gz (255 kB)
     |████████████████████████████████| 255 kB 12.3 MB/s 
Building wheels for collected packages: rebound
  Building wheel for rebound (setup.py) ... error
  **ERROR: Failed building wheel for rebound**
  Running setup.py clean for rebound
**Failed to build rebound**
Installing collected packages: rebound
    Running setup.py install for rebound ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qxkxbp1s/rebound_b11d5aebf05c4369ad1fe1455fbe508e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qxkxbp1s/rebound_b11d5aebf05c4369ad1fe1455fbe508e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-m4fdq_zx/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/rebound Check the logs for full command output.

**Comment by hannorein** [comment]
Thanks for letting me know. For some strange reason, the compiler on colaboratory did not like 

```
static const int maxOrder = 18;
static const int sequence_length = maxOrder / 2;
```

so I changed it to 

```
static const int maxOrder = 18;
static const int sequence_length = 9;  
```

🤷‍♂️ It should work now.
