### ISSUE TITLE
How to resolve -> ImportError: bad magic number in 'rebound': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by haisamido** [hannorein/rebound#585]
What am I doing wrong? I'm on max os x and when I copied the example and executed my `rebound_example.py` program I get:

```
./rebound_example.py 
Traceback (most recent call last):
  File "./rebound_example.py", line 3, in <module>
    import rebound
ImportError: bad magic number in 'rebound': b'\x03\xf3\r\n'
```
the content of `rebound_example.py` is simply:

```
#!/usr/local/bin/python3

import rebound
sim = rebound.Simulation()
sim.add(m=1.0)
sim.add(m=1.0e-3, a=1.0)
sim.integrate(1000.)
sim.status()

```

**Comment by haisamido** [comment]
resolved, I first had my file named as rebound.pyc which clearly wouldn't work with the circular import rebound, so I renamed it. I guess when I did pip3 install rebound it created rebound.pyc and when I deleted that things are ok! got the idea from https://github.com/Miserlou/Zappa/issues/854#issuecomment-331717384

**Comment by hannorein** [comment]
Glad you figured it out!
