### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#59]
I'm in the process of adding documentation to the code. I plan to use the following documentation of tools for automatically generated html pages from doc strings in the source code:

- doxygen
  - For documenting the C part, the shared library librebound.
  - This creates xml output
- sphinx-dox
  - For documenting the python module
  - This creates HTML output
- breathe
  - Allows sphinx to include the doxygen xml output, thus all documentation can be in one place and style.

**Comment by hannorein** [comment]
Development is happening on the `sphinx` branch.

**Comment by hannorein** [comment]
I think this is almost ready to me merged into the main branch. The only problem is that there is a bug in ReadTheDocs which prevents me from including the iPython examples in the documentation. I don't want to precompile them and include them in the git repository as that would take up a lot of space (due to binary images). I'll add a link to the github rendered iPython notebooks for now.

**Comment by dtamayo** [comment]
That sounds reasonable to me
