### ISSUE TITLE
multiprocessing pool 

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#590]
There was a long-standing issue with multiprocessing pools not working very nicely with ipython/notebooks. This is why we included an interruptible pool within REBOUND itself. This doesn't seem to work anymore for me in the latest python version. However, the multiprocess (note without "ing") seems to work just fine. Maybe we should switch to that in the examples.

**Comment by zhexingli** [comment]
I'm curious what was the issue related to this? I seem to have some problem with multiprocessing pools along with emcee within ipython and had issues where in the middle of the mcmc chain one of the cores just stuck in the process not finishing.  Not sure if that had anything to do with the issue described here...

**Comment by hannorein** [comment]
I haven't investigated this yet. Including the interruptible pool in REBOUND was always a bit of a hack. Did you try the multiprocess (without ing) module?

**Comment by zhexingli** [comment]
I haven't tried to use multiprocess, but I've been able to use interruptible pool in REBOUND without any problems. Would be interesting to see somebody else to comment on the use of multiprocess :)

**Comment by kittipongwangnok** [comment]
> I haven't tried to use multiprocess, but I've been able to use interruptible pool in REBOUND without any problems. Would be interesting to see somebody else to comment on the use of multiprocess :)

Dear zhexingli,

I just started to use rebound and my simulation is a bit slow. 
I would like to run this simulation on HPC and I have no primary multiprocess pool on a rebound.
Could you provide an example of a multiprocess pool code?

Best regards,
Kittipong

**Comment by zhexingli** [comment]
> > I haven't tried to use multiprocess, but I've been able to use interruptible pool in REBOUND without any problems. Would be interesting to see somebody else to comment on the use of multiprocess :)
> 
> Dear zhexingli,
> 
> I just started to use rebound and my simulation is a bit slow. I would like to run this simulation on HPC and I have no primary multiprocess pool on a rebound. Could you provide an example of a multiprocess pool code?
> 
> Best regards, Kittipong

I have no experience in using multiprocess either. Sorry. I have used interrrptible pool in REBOUND but that's only for when I have multiple scenarios to test so that each scenario can be run on a different core. But for a single scenario, I just use one core and let it run for minutes or hours, depending on the nature of the job.

**Comment by hannorein** [comment]
closed in #ca085f96
