### ISSUE TITLE
kicking velocities / comparison to Gauss's perturbation equations

### ISSUE THREAD

**Issue by nchoksi4456** [hannorein/rebound#592]
Hi all,

To preface: this is probably not an issue with REBOUND, and almost certainly is just a silly mistake on my end. But I can't find it, so any help would still be appreciated. 

I've been experimenting with "kicking" a particle by changing its velocity vector. I'd like to know how the orbital elements change because of the kick. REBOUND automatically calculates the new orbital elements. As a sanity check, I tried comparing to the analytic prediction from Gauss's perturbation equations (Murray & Dermott Section 2.9, or see section 2 [here](https://w.astro.berkeley.edu/~echiang/classmech/gauss_kick.pdf)  if you don't have a copy of MD on you). But I'm not finding good agreement. Here is an example:

```
sim = rebound.Simulation()
sim.G = 1
sim.add(m = 1)
sim.add(m=0,a=1,e=0.01, inc=0, Omega = 0, omega=0, f=0.95*2*np.pi ) # NC: initialize particle just before peri
sim.move_to_com()

e0 = sim.particles[1].e # NC: record eccentricity before kick
print("e0 = ", e0)

dvr = 1e-2 # NC: apply a purely radial kick with magnitude 1% of the Keplerian orbital velocity
dvx = dvr*np.cos(sim.particles[1].theta)   # NC: separate the radial kick into cartesian components
dvy = dvr*np.sin(sim.particles[1].theta)
de_gauss = dvr*np.sin(sim.particles[1].f) # NC: analytic prediction from Gauss, de = dvr*sin(true anomaly)

sim.particles[1].vx += dvx
sim.particles[1].vy += dvy

ef = sim.particles[1].e # NC: post-kick eccentricity according to REBOUND


print("de_gauss = ", de_gauss)
print("(ef - e0)/de_gauss = ", (ef - e0)/de_gauss)# NC: prints  -0.5680629819037879
```

Any ideas would be appreciated. Thanks!

-Nick

**Comment by hannorein** [comment]
I think your kick is just a bit large. Try `dvr = 1e-5` and the agreement is pretty good!

**Comment by nchoksi4456** [comment]
Thanks Hanno. Interesting. I thought a kick of just 0.01*v_kep was still pretty small. Is there a way to intuit roughly what order of magnitude for `dvr` I should expect Gauss's equations to break down?

**Comment by hannorein** [comment]
I'm not sure. I would need to look at the derivation again. But note that:
1) delta e/e is 0.3 in your example
2) if e~0, then f is not well defined (which goes into the calculation of delta e)
So maybe it's not that surprising?

**Comment by nchoksi4456** [comment]
Good points. Thanks again for your help!
