### ISSUE TITLE
Cannot use h and k variables together with inc

### ISSUE THREAD

**Issue by zhexingli** [hannorein/rebound#601]
Hello,

I'm trying to use h and k variables to define my planetary orbits so that they can treat the near circular orbits more nicely than the traditional e and omega. I was planning to dynamically fit the data by using this set of variables while varying the orbital inclination, but got the following error message:
`ValueError: You cannot mix Pal coordinates (h,k,ix,iy) with the following orbital elements: e,inc,Omega,omega,pomega,f,M,theta,T. If a longitude/anomaly is needed in Pal coordinates, use l.`

May I ask if there's any intrinsic reason why we can't use h & k together with inclination? Does that mean in order to treat inclination as an extra variable, I have to resort back to the e and omega parameters (which is not quite ideal for near circular orbits)? 

Thanks.

**Comment by hannorein** [comment]
If you look at the [implementation](https://github.com/hannorein/rebound/blob/main/src/tools.c#L1158), you'll see that all the h, k, ix, and iy coordinates are used in the same function. I guess in principle, one could separate one from the other, but I don't see a good reason to do that. Your fit will work better if you use ix and iy (in the same way it works better in h and k). Specifically, you would need to do something about i and Omega being cyclic variables. That can be a pain. [The transformation to ix and iy](https://arxiv.org/pdf/0904.0324.pdf) is easy:

$i_x = 2 \sin(i/2) \cos(\Omega) $ 
$i_y = 2 \sin(i/2) \sin(\Omega) $ 

So I suggest you just run the fit in h, k, ix, and iy and then afterwards convert to whatever coordinates you want to quote. You can use REBOUND to do that conversion for you.

**Comment by zhexingli** [comment]
Ah I see. Thank you for pointing me to that direction! One quick follow up question if you don't mind and sorry if the answer to it might be obvious: if I'd like to fix Omega for the ix and iy variables, is it ok if I pick Omega=0 so that iy is essentially 0 as well and leaving only ix being the single variable (along with h and k of course)? Or is it better to pick a number that gives a non-zero ix and iy results?

**Comment by hannorein** [comment]
If you're fixing Omega, then you're fixing the plane of the orbit with respect to the reference coordinate system (see [the illustration here](https://rebound.readthedocs.io/en/latest/orbitalelements/)). You can do that if you want to in which case it's equivalent to setting iy = 0. Whether that makes physically sense or not depends on what you're trying to do.

**Comment by zhexingli** [comment]
Sounds good. Thank you so much Hanno for all the help!!

**Comment by zhexingli** [comment]
How does Rebound internally determine the e and w values if the orbits are initialized under this Lagrangian h and k elements? I understand for e is simple, just sqrt(h**2+k**2), but for w, arctan(h/k) could lead to degeneracy in w.
For example, a set of h and k that gives arctan(h/k) = -0.302 would make w = 2.84 and w = 5.98 equally likely, just a pi difference. But this pi offset could have a significant impact on the orbit configuration.

**Comment by hannorein** [comment]
I think the function you're looking for is [atan2](https://en.wikipedia.org/wiki/Atan2).

**Comment by zhexingli** [comment]
Thanks!
