### ISSUE TITLE
reference time for orbital elements

### ISSUE THREAD

**Issue by PS-OnGit** [hannorein/rebound#610]
Hello,
I am using rebound for some n-planet simulations with dynamic interactions, and was wondering if it is possible to get the orbital elements for a specific reference time, or if they are always updated to the current time-step?

**Comment by hannorein** [comment]
The orbital elements are always instantaneous, calculated from the current cartesian coordinates. If you want to get orbital elements at a specific time, you need to integrate to that time first.
