### ISSUE TITLE
Rebound Youtube Channel

### ISSUE THREAD

**Issue by DavidRRice** [hannorein/rebound#612]
I noticed the rebound youtube channel has been de-listed. I know some things may be outdated, but I found those videos very helpful.  Could you include links to them even if you don't want them public? I was curious, thanks!

**Comment by hannorein** [comment]
Ah. Good point. I think those got removed after they started charging for accounts and I deleted one of mine. I'll look into reuploading them.

**Comment by hannorein** [comment]
I can't seem to find the original video files anymore. So I'm going to record new videos. Anything you'd like to see in particular?

**Comment by danielk333** [comment]
I vote for some mercurius tutorial, i think that might be the hardest to get started with from scratch, also a list of "good practices with rebound and reboundx" that you have learned trough the pain of getting stuff to work for real studies is always good to put out there :+1:

**Comment by DavidRRice** [comment]
Ah! That's rough, but thank you for being willing to make new ones! Just the very basics of getting started were really helpful and easy to look back on. Putting particles in, integrating their orbits, and not getting too bogged down in the details.

**Comment by hannorein** [comment]
For reference, YouTube channel is here: https://www.youtube.com/channel/UCNmrCzxcmWVTBwtDPPLxkkw.

I'll be adding more video as time permits.

Closing this for now.
