### ISSUE TITLE
Error when trying to install Rebound on Windows

### ISSUE THREAD

**Issue by fluentportuguese** [hannorein/rebound#619]
Trying to install rebound on my Windows device. Typing `pip install rebound` returns an error of "command ...path...\c1.exe failed with exit status 2".

Anyone know a workaround?

**Comment by hannorein** [comment]
Did you follow the instruction for Windows on this page? https://rebound.readthedocs.io/en/latest/quickstart_installation/

**Comment by hannorein** [comment]
Closing this for now. If the documentation didn't help, feel free to reopen the issue..
