### ISSUE TITLE
Runtime Warning that never executes the code

### ISSUE THREAD

**Issue by ruaSulaiman** [hannorein/rebound#621]
Hello,

I am trying to continue a simulation starting from a binary file. The only change that I made is the accuracy of the integrator (I increased it). The simulation is taking so much time and it is still not running. When I change the accuracy back to the original one, the simulation works fine. I was thinking if there is a way to fix that, or is it not possible to change the accuracy of the integrator in the second simulation?  

Thank you.

**Comment by hannorein** [comment]
What integrator do you use and what parameter do you change when you say you change the accuracy?

**Comment by hannorein** [comment]
It might just be the case that you're trying to achieve an accuracy which is too high. If the accuracy gets close to machine precision, then the integrator might never converge, thus trying to reduce the timestep further and further. I would try out different epsilon parameters and see where it stops working.

**Comment by ruaSulaiman** [comment]
Indeed I tried different smaller accuracy and the code ran. However, I already have another simulation that is running that has the same high accuracy (from the beginning of the simulation) that I was trying to switch to in the first simulation that never ran. Do you think it is still a problem due to the machine's precision?

**Comment by ruaSulaiman** [comment]
I apologize for that but I think my sentence was not clear. What I meant is that I have a simulation that is running with a very small epsilon (epsilon = 1e-18) that I started the simulation with from the beginning. On the other hand, I have another simulation whose initial epsilon = 1e-10. When I try to continue this simulation with epsilon = 1e-18 the simulation does not run, however, it runs fine when I change epsilon to e-14. What I am trying to say is that simulations with epsilon = 1e-18 are working only if I set their epsilons to be that small from the beginning, but not when I try to switch to epsilon = 1e-18 later (meaning after I start the simulation already with a different epsilon). Is this still related to my machine's precision?

**Comment by ruaSulaiman** [comment]
I see, but the thing is that in my simulation, along with using BS integrator, I am using the merging collision module. The energy is not conserved, but no merging events are happening (the number of particles is always the same). I thought that this was because of the accuracy of the integrator. Then I thought "is it possible then that it is because of the time step?" So instead of continuing the simulation with higher accuracy, I run it with the epsilon = e-10 but with smaller time steps. The result is still the same, the energy is violated with no merging events. I am not sure why this is happening.

**Comment by hannorein** [comment]
BS is an adaptive integrator. It sets the timestep automatically depending on what you choose for the accuracy parameter eps.

**Comment by ruaSulaiman** [comment]
Right, but I thought that if I indicate the time step for the integrator explicitly the results might change. But I still do not understand why there is a violation in energy even though there are no merging events.

**Comment by hannorein** [comment]
I don't think I can provide any advice here. You'd need to post a minimal example that reproduces the issues.
