### ISSUE TITLE
Question on NASA Horizons

### ISSUE THREAD

**Issue by Shellyneko** [hannorein/rebound#623]
Hello,
    I am trying to import data about Sun and planets in the solar system by the NASA Horizons in the examples.But I failed to derive the data and there are some errors as below:
![a](https://user-images.githubusercontent.com/116542932/200579724-68571eae-3ef5-4fd0-87cf-92aa81b967e9.png)
![b](https://user-images.githubusercontent.com/116542932/200579732-bd3a08f2-f474-49d7-a8ef-3098a123b6a1.png)
![c](https://user-images.githubusercontent.com/116542932/200579736-fd5c4942-f420-416c-973c-26c02cda2399.png)
![d](https://user-images.githubusercontent.com/116542932/200579739-e18da4d9-6c38-4ea8-ad0f-a330c592c3a2.png)
![e](https://user-images.githubusercontent.com/116542932/200579742-16f11e92-d77e-443e-935d-12f38133670e.png)
![f](https://user-images.githubusercontent.com/116542932/200579750-e32c073d-6192-4e7b-b58c-1ef758a2dd64.png)
![g](https://user-images.githubusercontent.com/116542932/200579753-e1b3d000-7925-44f8-be53-403bf0894b10.png)
![h](https://user-images.githubusercontent.com/116542932/200579756-1ddc438c-ffd5-42c6-9be0-c24fbf19aaaa.png)
    What should I do to solve the problem?
thanks.

**Comment by hannorein** [comment]
This works for me. I suspect this was either a temporary issue with the NASA servers, or a connection issue on your end. Can you access the API directly, e.g.: https://ssd.jpl.nasa.gov/api/horizons.api?format=text&COMMAND=%27499%27&OBJ_DATA=%27YES%27&MAKE_EPHEM=%27YES%27&EPHEM_TYPE=%27OBSERVER%27&CENTER=%27500@399%27&START_TIME=%272006-01-01%27&STOP_TIME=%272006-01-20%27&STEP_SIZE=%271%20d%27&QUANTITIES=%271,9,20,23,24,29

**Comment by Shellyneko** [comment]
I am not able to connect the website.So what should I do now?

**Comment by danielk333** [comment]
I'm able to connect so this seems to be an internet connectivity issue on your side. Are you sure your local router/firewall is not blocking the traffic?

**Comment by hannorein** [comment]
I agree with @danielk333. This is most likely an issue with the internet connection on your side.

**Comment by hannorein** [comment]
I'm closing this for now because I think this is not a rebound issue but rather something related to your network. Feel free to reopen if you think otherwise and the problem persists.
