### ISSUE TITLE
Using in CMake projects?

### ISSUE THREAD

**Issue by ethindp** [hannorein/rebound#633]
I'd like to integrate this into a CMake-based project, but I'm unsure how. I found [this thread](https://discourse.cmake.org/t/external-project-using-makefile/2692/5), but it seems to be dependent on the project your adding, though I might be missing something.

**Comment by hannorein** [comment]
This seems to be more of a CMake question than a REBOUND question. I have no experience with CMake, I'm afraid. I'll close this issue as I don't think you'll find much advice here.
