### ISSUE TITLE
Rebound OrbitPlot Issues

### ISSUE THREAD

**Issue by ofoofoo** [hannorein/rebound#652]
I'm having an issue with rebound.OrbitPlot. I've been trying to follow the example given at https://rebound.readthedocs.io/en/latest/ipython_examples/OrbitPlot/. Specifically, I have tried to copy the first three code cells and run them directly. However, whenever I run the third cell (`op.fig.savefig("orbit.png")`), I get the following error: `AttributeError: 'tuple' object has no attribute 'fig'`. Is there a known fix to this issue? I also have the same error when trying to run `op.ax.text()`.
`

**Comment by hannorein** [comment]
Are you using the latest version of rebound?

**Comment by ofoofoo** [comment]
Just updated and the problem is resolved. Thank you!

**Comment by hannorein** [comment]
You’re welcome. I’m glad it was a simple fix.
