### ISSUE TITLE
Wrong binary load for z-axis

### ISSUE THREAD

**Issue by malsuar** [hannorein/rebound#654]
Description: I initialised and simulated a system of particles and then saved the simulation in a binary file. I then loaded the binary into another program, but the initial conditions do not match in the z-direction.
Both figures were generated by the same code.

These are the figures: 
![rebound_original_report](https://user-images.githubusercontent.com/5066804/214088525-d718eb7a-6f5b-4e64-b1d1-577394f5d1c9.png)

![rebound_load_report](https://user-images.githubusercontent.com/5066804/214091325-e229af2e-e9d8-46c5-83df-9e53aba5a039.png)

**Comment by hannorein** [comment]
Hi Mario!

This is strange. Can you post some code along with this. Otherwise it's really hard for me to help you debug this.

**Comment by malsuar** [comment]
In the meantime, this is basically how I load the simulation:


```
t_max = tiempo
sa       = rebound.SimulationArchive("./bin/bkp3/chkpd_%s_%d.bin"%(moon.name,t_max))
sim     = sa.getSimulation(t=0)

for i in range(ndp):
    xprm[i] = (sim.particles[i+2].x-sim.particles[0].x)/moon.radius 
    yprm[i] = (sim.particles[i+2].y-sim.particles[0].y)/moon.radius 
    zprm[i] = (sim.particles[i+2].z-sim.particles[0].z)/moon.radius 
    
rprm = (xprm**2+yprm**2+zprm**2)**0.5   
``` 
And finally, I create the figure in this way:

```
plt.figure(figsize=(12,4),constrained_layout = True)

ax1=plt.subplot(131)
ax1.scatter(rprm,xprm, s=0.4)
ax1.set_ylabel("x")
ax1.set_xlabel("r")

ax2=plt.subplot(132)
plt.title("Loaded REBOUND at t=0")
ax2.scatter(rprm,yprm, s=0.4)
ax2.set_ylabel("y")
ax2.set_xlabel("r")

ax3=plt.subplot(133)
ax3.scatter(rprm,zprm, s=0.4)

ax3.set_ylabel("z")
ax3.set_xlabel("r")

plt.savefig('./figures/rebound_load_report.png')
```

**Comment by malsuar** [comment]
The content of `zprm` 'is' zero: 

![image](https://user-images.githubusercontent.com/5066804/214108305-724b8af6-e990-48a3-9b4f-693eba9ec44f.png)

**Comment by hannorein** [comment]
That looks all good. So the issue must be somewhere else.

**Comment by hannorein** [comment]
I'm pretty sure this is not a bug related to binary files. The particles probably had already a z position of 0 before you've saved the simulation to a file.

**Comment by malsuar** [comment]
How odd!

For instance, this is how I save the binary in the original program:

`sim.automateSimulationArchive("./bin/chkpd_%s_%d.bin"%(moon.name,t_max),interval=0.1,deletefile=True)`

And this is the plot created at the end of the simulation, for t=100.  Note that z !=0: 
![Final_configuration_301_b](https://user-images.githubusercontent.com/5066804/214116853-04832942-4c24-4607-8797-a44efd7e6b47.png)

On the other hand, this is what I get, after reading the binary at t=100.
![detail_Moon_t60](https://user-images.githubusercontent.com/5066804/214117181-fe4446c2-262d-4361-a521-4ae6ea0c9628.png)

Also, snapshots for t > 0 have values for z != 0. for t=50 i get:

![detail_Moon_t50](https://user-images.githubusercontent.com/5066804/214117549-8ff8fb52-b275-444b-95e4-a3a03b89f558.png)

**Comment by malsuar** [comment]
Mmmm... These lines also work well for me. Even when I change the integrator, or get the status from the Horizon system. 
I will create a more refined version of the code to share with you.
Thank you so much!

**Comment by hannorein** [comment]
Any update?

**Comment by malsuar** [comment]
Hi, Hanno. 
You were right from the beginning!
I tried loading the binary files from other simulations of the same dataset and it worked quite well.  
I also ran the simulation again, and it worked without problems. However, I couldn't figure out what was wrong with that first experiment.

Thank you very much for your time and cooperation. I will let you know if anything strange happens. ':)

**Comment by hannorein** [comment]
Glad to hear it was resolved!
