### ISSUE TITLE
Getting error when running makefile on Mac

### ISSUE THREAD

**Issue by JonathanHammer2** [hannorein/rebound#663]
Hello, I'm having trouble when it tries to link.  Please help.

I tried installing Xcode; this is the version I get:

Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

This is the error I get:

(base) cycloastro@Lindas-MBP simplest % make                  
Compiling shared library librebound.so ...
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../src/

Linking share library librebound.so ...
cc -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -Wno-unknown-pragmas -fPIC -DLIBREBOUND -shared rebound.o tree.o particle.o gravity.o integrator.o integrator_whfast.o integrator_saba.o integrator_ias15.o integrator_sei.o integrator_bs.o integrator_leapfrog.o integrator_mercurius.o integrator_eos.o integrator_tes.o boundary.o input.o binarydiff.o output.o collision.o communication_mpi.o display.o tools.o rotations.o derivatives.o simulationarchive.o glad.o integrator_janus.o transformations.o -L/usr/local/lib -o librebound.so 
Undefined symbols for architecture x86_64:
  "_reb_display_init", referenced from:
      _reb_integrate in rebound.o
     (maybe you meant: _reb_display_init_data)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [librebound.so] Error 1
make: *** [librebound] Error 2

**Comment by hannorein** [comment]
Could you try running
```bash
make clean
make
```

**Comment by JonathanHammer2** [comment]
That seemed to work.

Thank you.



From: Hanno Rein ***@***.***>
Date: Wednesday, March 1, 2023 at 10:57 AM
To: hannorein/rebound ***@***.***>
Cc: Jonathan Hammer ***@***.***>, Author ***@***.***>
Subject: Re: [hannorein/rebound] Getting error when running makefile on Mac (Issue #663)

Could you try running

make clean

make

**Comment by hannorein** [comment]
Glad it worked. This error occurred because you probably tried some example with OpenGL Visualizations turned on and some with them turned off.

**Comment by JonathanHammer2** [comment]
Hello again,

Simplest worked fine, but I tried making the solar system example and it crashed.  I tried “make clear” again and it still crashed.

Also I’m curious as to what units are being used for position and velocity in the solar system C file?  They don’t look anything like what I see on NASA’s Horizon.  Thanks very much.

Here’s the output:



Compiling problem file ...

cc -I../../src/ -Wl,-rpath,./ -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 problem.c -L. -lrebound -L/usr/local/lib -lglfw -framework Cocoa -framework OpenGL -framework IOKit -framework CoreVideo -o rebound

ld: warning: directory not found for option '-L/opt/homebrew/lib'

ld: library not found for -lglfw

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [all] Error 1

(base) ***@***.*** solar_system % make clean

Cleaning up shared library librebound.so ...

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../src/ clean

Removing object files *.o ...

Removing shared library librebound.so ...

Removing coverage files ...

Cleaning up local directory ...

(base) ***@***.*** solar_system % ls

Makefile      problem.c

(base) ***@***.*** solar_system % make

Compiling shared library librebound.so ...

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../src/

fatal: not a git repository (or any of the parent directories): .git

Compiling source file rebound.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o rebound.o rebound.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file tree.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o tree.o tree.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file particle.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o particle.o particle.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file gravity.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o gravity.o gravity.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator.o integrator.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_whfast.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_whfast.o integrator_whfast.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_saba.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_saba.o integrator_saba.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_ias15.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_ias15.o integrator_ias15.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_sei.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_sei.o integrator_sei.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_bs.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_bs.o integrator_bs.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_leapfrog.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_leapfrog.o integrator_leapfrog.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_mercurius.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_mercurius.o integrator_mercurius.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_eos.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_eos.o integrator_eos.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file integrator_tes.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o integrator_tes.o integrator_tes.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file boundary.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o boundary.o boundary.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file input.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o input.o input.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file binarydiff.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o binarydiff.o binarydiff.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file output.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o output.o output.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file collision.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o collision.o collision.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file communication_mpi.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o communication_mpi.o communication_mpi.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

fatal: not a git repository (or any of the parent directories): .git

Compiling source file display.c ...

cc -c -std=c99 -Wpointer-arith -D_GNU_SOURCE -O3  -I/usr/local/include -Wall -g  -I/opt/homebrew/include -L/opt/homebrew/lib -Wno-unknown-pragmas -fPIC -DLIBREBOUND -D_APPLE -DOPENGL -DGITHASH=0000000000gitnotfound0000000000000000000 -o display.o display.c

clang: warning: argument unused during compilation: '-L/opt/homebrew/lib' [-Wunused-command-line-argument]

display.c:50:10: fatal error: 'GLFW/glfw3.h' file not found

#include <GLFW/glfw3.h>

         ^~~~~~~~~~~~~~

1 error generated.



From: Hanno Rein ***@***.***>
Date: Wednesday, March 1, 2023 at 11:01 AM
To: hannorein/rebound ***@***.***>
Cc: Jonathan Hammer ***@***.***>, Author ***@***.***>
Subject: Re: [hannorein/rebound] Getting error when running makefile on Mac (Issue #663)

Glad it worked. This error occurred because you probably tried some example with OpenGL Visualizations turned on and some with them turned off.

**Comment by hannorein** [comment]
This is explained in the documentation: https://rebound.readthedocs.io/en/latest/quickstart_installation/

**Comment by JonathanHammer2** [comment]
I hate to seem dumb, but I guess I am.  Here’s what I got when I followed the instructions at the link you sent:


(base) ***@***.*** rebound-main % brew tap homebrew/versions

zsh: command not found: brew

(base) ***@***.*** rebound-main % sudo apt-get install libglfw3-dev

Password:

Sorry, try again.

Password:

Sorry, try again.

Password:

sudo: 3 incorrect password attempts



I tried my password for the Mac, I guess I typed it wrong 3 times,  then it seemed to work but I get another error, it can’t find apt-get:





(base) ***@***.*** rebound-main % sudo apt-get install libglfw3-dev

Password:

sudo: apt-get: command not found

(base) ***@***.*** rebound-main %

Thanks again for your help.

Jonathan

From: Hanno Rein ***@***.***>
Date: Wednesday, March 1, 2023 at 7:52 PM
To: hannorein/rebound ***@***.***>
Cc: Jonathan Hammer ***@***.***>, Author ***@***.***>
Subject: Re: [hannorein/rebound] Getting error when running makefile on Mac (Issue #663)

This is explained in the documentation: https://rebound.readthedocs.io/en/latest/quickstart_installation/<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Frebound.readthedocs.io%2Fen%2Flatest%2Fquickstart_installation%2F&data=05%7C01%7Cjhammer2%40gmu.edu%7C95abf1856ed74dda9f4a08db1ab864e1%7C9e857255df574c47a0c00546460380cb%7C0%7C0%7C638133151510190339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k%2FzwYticohLiEFcm2uAzp89pSpWoUMlmnS9fZr02%2BRU%3D&reserved=0>

**Comment by hannorein** [comment]
I can't help you with the password issue. You can turn off OpenGL visualization in the makefile if you're not able to install the glfw library.

**Comment by JonathanHammer2** [comment]
Ok. I installed homebrew, then reset glfw3 to glfw and it worked.  I had tried to follow your instructions to try glfw3.

** Still have a question:  can you tell me what the units are on position and velocity in the solar system example?  Also, if I want to run the simulation backwards to go back in time, do I just need to reverse the initial velocities?

Thank you again.

From: Hanno Rein ***@***.***>
Date: Wednesday, March 1, 2023 at 8:23 PM
To: hannorein/rebound ***@***.***>
Cc: Jonathan Hammer ***@***.***>, Author ***@***.***>
Subject: Re: [hannorein/rebound] Getting error when running makefile on Mac (Issue #663)

I can't help you with the password issue. You can turn off OpenGL visualization in the makefile if you're not able to install the glfw library.

**Comment by hannorein** [comment]
They are listed in the code. AU, day, kg.

**Comment by JonathanHammer2** [comment]
Ok.  Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JonathanHammer2** [comment]
Dear Hanno,

Over the last few weeks, I have asked you a few specific questions about how to get Rebound running, which I’ve done successfully so far.  I have appreciated your patience and responsiveness in answering my questions.

I am working with a research team from George Mason University.  We are considering using Rebound for our project, and I wanted to ask you a couple of high-level questions about the software.

For background, a substantial group of researchers is involved in a multi-year cyclostratigraphy project called “Cycloastro.”   Cyclostratigraphy involves analyzing solar influences on earth’s geologic stratigraphy.  As such, we calculate the solar “insolation,” or the amount of sunlight energy that earth is exposed to over geologic time.  Integration of the solar system through geologic history is a crucial piece of the puzzle:  the state of the solar system impacts the earth’s obliquity, precession, and eccentricity, which directly relate to solar insolation.  Here is a link to the Cycloastro website, which has some more information on our project:  https://sites.google.com/view/cycloastro .

My immediate team is a small research team under the auspices of Cycloastro.  We are working on a new method to try to correlate the geologic record with solar system influences.  We hope that Rebound will aid us in our work.


  1.  As we expect our work to take place over the next few years, continued support of Rebound will be important to us.  What are your expectations for the continued maintenance and support of Rebound?

  2.  One of our Cyclo Astro team members (Richard Zeebe) has done work using a package called HNbody.  I’m attaching a paper of his.  It appears to me that HNbody is no longer maintained, as the last update I could find seems to have been made in 2014.  Also, I found a number of dead links on the HNbody website.  Are you familiar with HNBody, and do you know if Rebound has similar capabilities to HNbody?  Do you think we will we be able to run comparable models with similar (wall-time) speed to what Richard reports in the attached paper (the abstract talks at a high level about this, so you hopefully you won’t need to dive into it too much unless you want to).

  3.  A few of us meet regularly on Tuesday afternoons from 1 to 3 pm US eastern time.  I am wondering if you or another Rebound team member might be interested in presenting a brief summary / tutorial on Rebound during one of these sessions?

I very much appreciate your help.  We are very enthusiastic about Rebound and hope to use it as a critical element in our research.

Jonathan Hammer
Research Scientist
[page1image55562928]
Fairfax, VA 22030
