### ISSUE TITLE
Rotations warning?

### ISSUE THREAD

**Issue by tigerchenlu98** [hannorein/rebound#671]
Hi Hanno,

This is very minor, but I thought I'd bring it to your attention. Creating a reb_rotation object to the same axes leads to NaNs in the rotation object. For instance,

struct reb_vec3d newz = reb_vec3d_add(reb_tools_angular_momentum(sim), rebx_tools_spin_angular_momentum(rebx));
struct reb_vec3d newx = reb_vec3d_cross((struct reb_vec3d){.z =1}, newz);
struct reb_rotation rot = reb_rotation_init_to_new_axes(newz, newx);

returns NaNs if newz & newx are the same as the original z & x axes. Clearly this rotation does nothing - but maybe some sort of warning should be put in here?

Thanks!
Tiger

**Comment by hannorein** [comment]
I'm not sure I understand. If the new z is the same as the old z, then the cross product
```c
reb_vec3d_cross((struct reb_vec3d){.z =1}, newz);
```
is not well defined. So I think every function here is doing everything right.

**Comment by tigerchenlu98** [comment]
Oh yes everything is absolutely working correctly. I'm just wondering if it would be good to add warnings in cases like this. But the user should know when it's appropriate to use the rotation so maybe not - up to you!

**Comment by hannorein** [comment]
Where does this code appear?

**Comment by tigerchenlu98** [comment]
This is in one of the example folders in my RBEOUNDx fork:

https://github.com/tigerchenlu98/reboundx/blob/chains/examples/hatp13/problem.c

the issue occurs when you try to shift a completely coplanar system to the invariant frame (which it's already in)

**Comment by hannorein** [comment]
I don't think it makes sense to add a warning message to any of the `reb_` functions. Again, they do exactly what they are supposed to do. Returning NaN when the cross product is not defined is good. It's the same as if you divide by zero. I think you should add an exception to your side of the code. Maybe as simple as
```c
if isnan(rot.r) {
   rot = reb_rotation_identity();
}
```

or

```c
if isnan(reb_vec3d_length_squared(newx)<some_value) {
   rot = reb_rotation_identity();
} 
```

**Comment by tigerchenlu98** [comment]
That's fair! Closing the issue.
