### ISSUE TITLE
Inefficient implementation of "get_min_ratio" in integrator_hybrid.c

### ISSUE THREAD

**Issue by jmpetit** [hannorein/rebound#69]
The current implementation of the double for loop in get_min_ratio is not optimal, with computations that are done identically in the inner loop and could be performed in the outer loop, saving quite some time. Cheking it on the given example in solar_system with REB_INTEGRATOR_HYBRID, I get an improvement of 9% of the overall time.

Current implementation is:

	for (int i=1; i<_N_active; i++){
		struct reb_particle pi = particles[i];
	for (int j=1; j<_N_real; j++){
		if (i==j) continue;
		const double dxj = p0.x - particles[j].x;
		const double dyj = p0.y - particles[j].y;
		const double dzj = p0.z - particles[j].z;
		const double r0j2 = dxj*dxj + dyj*dyj + dzj*dzj;

		const double dx = pi.x - particles[j].x;
		const double dy = pi.y - particles[j].y;
		const double dz = pi.z - particles[j].z;
		const double rij2 = dx*dx + dy*dy + dz*dz;
		
		const double F0j = p0.m/r0j2;
		const double Fij = pi.m/rij2;

		const double ratio = F0j/Fij;
			
		if (ratio<min_ratio){
			min_ratio = ratio;
		}
	}
	}

My proposed implementation:

	for (int i=1; i<_N_active; i++){
		struct reb_particle pi = particles[i];
		const double dxi = p0.x - pi.x;
		const double dyi = p0.y - pi.y;
		const double dzi = p0.z - pi.z;
		const double r0i2 = dxi*dxi + dyi*dyi + dzi*dzi;
		
		const double F0i = p0.m/r0i2;
	for (int j=1; j<_N_real; j++){
		if (i==j) continue;

		const double dx = pi.x - particles[j].x;
		const double dy = pi.y - particles[j].y;
		const double dz = pi.z - particles[j].z;
		const double rij2 = dx*dx + dy*dy + dz*dz;

		const double Fij = pi.m/rij2;

		const double ratio = F0i/Fij;
			
		if (ratio<min_ratio){
			min_ratio = ratio;
		}
	}
	}

It's mathematically identical, but much faster. Since this is not my code, and I'm not familiar with GITHUB, I'd rather let you do the update of the code.

Regards, Jean-Marc Petit

**Comment by hannorein** [comment]
Thanks for the suggestion. The hybrid integrator is not well optimized yet and you found a good starting point to make it faster.

I'd encourage you to open a pull request with these changed!
