### ISSUE TITLE
Is the relativistic effect included?

### ISSUE THREAD

**Issue by phyytang** [hannorein/rebound#690]
Dear Authors,

May I ask whether rebound includes the general relativistic corrections to the potential? Or whether there is a module that can treat generally additional user-defined perturbations to the Newtonian dynamics?

Thanks for your time.

**Comment by dtamayo** [comment]
Yes! Check out to the REBOUNDx library

REBOUNDx.readthedocs.io

**Comment by phyytang** [comment]
Thanks for your quick reply.
