### ISSUE TITLE
the file "communication_mpi.h" is missing in the version 3.25.0 distributed at PyPI

### ISSUE THREAD

**Issue by kinoshitadaisuke** [hannorein/rebound#694]
Hello,

I've found that the file "communication_mpi.h" is missing in the version 3.25.0 distributed at PyPI.
Could you please check about it?

thank you,

Daisuke

**Comment by hannorein** [comment]
Hi Daisuke! Thanks for noticing. I've just pushed a fixed.

(the file `communication_mpi.h` is still not included -- because MPI and python don't work together at the moment, but it is no longer required when compiling)
