### ISSUE TITLE
Using REBOUND to re-discover Neptune

### ISSUE THREAD

**Issue by jbwhit** [hannorein/rebound#709]
First, congrats on a fantastic library. It's been a joy to use over the past couple of weeks. My main initial purpose has been to use REBOUND to attempt to re-derive some parts of Le Verrier's discovery of Neptune via the perturbations of the orbit of Uranus. I'm creating a YouTube video(s) about the historical and scientific thinking behind the event. I would be interested in submitting it when I'm finished as a worked example if you feel that it would belong.

**Comment by hannorein** [comment]
That's great to hear. And yes, if you can come up with a notebook similar in style to the other examples then I would love to include it.

**Comment by jbwhit** [comment]
Wanted to give an update. I created a YouTube video (which used REBOUND for parts of the visuals) here: https://youtu.be/XwWRwEd-xc4 

Unfortunately, giving a rigorous treatment for how to "re-discover" Neptune from simulation is taking a longer time. If others are willing to chat about the approaches, I'd be very happy to make sure that I'm not making some obviously poor rebound-based decisions.

**Comment by hannorein** [comment]
Great. Thanks for sharing. I'll close the issue for now...
