### ISSUE TITLE
selfgravity_disc_mpi Issue

### ISSUE THREAD

**Issue by ruaSulaiman** [hannorein/rebound#710]
Hello,

I have noticed a weird thing while testing the code in the examples provided in rebound (c code), specifically the selfgravity_disc_mpi example. The code is using 4 MPI nodes. I tried to change the number of nodes involved to 1, then 2, then went back to 4. The final number of particles left in the simulation is different after integrating the system for the same amount of time (around 1000 yrs). Does this make sense?

**Comment by hannorein** [comment]
The example uses random initial conditions, so you will alway get a slightly different answer.
