### ISSUE TITLE
How to find old documentation

### ISSUE THREAD

**Issue by kaiwu-astro** [hannorein/rebound#731]
I see REBOUND has published version 4.0, and I am very willing to try it, but for now, I have a deadline-approaching project that does not allow me to explore the new version.

My question is: it seems on https://rebound.readthedocs.io/ I can only access the documentation of the latest version. How can I find the documentation of a history version that I am using?

**Comment by hannorein** [comment]
readthedocs only hosts the latest version. You can access older versions using the git repository under docs/

**Comment by hannorein** [comment]
I've made the last pre-v4 documentation available here: https://rebound.readthedocs.io/en/3.28.4/

**Comment by kaiwu-astro** [comment]
Thank you for your timely help 👍
