### ISSUE TITLE
trying to use variational equations to get Jacobian but get an error...

### ISSUE THREAD

**Issue by JonathanHammer2** [hannorein/rebound#733]
Hello again!  Thanks for your answer to my last question.  What I'm trying to do here is to get the Jacobian of the Earth's eccentricity with respect to the cartesian positions and velocities of the other planets.  So H = [de_earth/dx_mercury, de_earth/dy_mecury, de_earth/dz_mecury, de_earth/dvx_mecury... de_earth/dvz_mecury... de_earth/dx_neptune... etc.

I tried to set this up as follows, but got this error:  ValueError: Variational particles can only be initializes using the derivatives with respect to one of the following: m, a, e, inc, omega, Omega, f, k, h, lambda, ix, iy.

So I'm wondering if there is a straightforward way to do what I want?

my code:
        for j in range(1, 8):
            if j != 2:
                var_dx = sim.add_variation()
                var_dx.vary(j, "x")
                var_dy = sim.add_variation()
                var_dy.vary(j, "y")
                var_dz = sim.add_variation()
                var_dz.vary(j, "z")
                var_dxd = sim.add_variation()
                var_dxd.vary(j, "vx")
                var_dyd = sim.add_variation()
                var_dyd.vary(j, "vy")
                var_dzd = sim.add_variation()
                var_dzd.vary(j, "vz")

**Comment by hannorein** [comment]
The syntax is:
```python
var_dx = sim.add_variation()
var_dx.particles[j].x = 1
```

**Comment by JonathanHammer2** [comment]
Hello Hanno,

Thanks again for the information you provided.

I was talking this over last night with Yujing Wu, my colleague, and she was concerned that the variational equations implementation in Rebound only work with celestial variables, not with Cartesian variables.

I would like to confirm with you that I’m not on a fool’s errand.

Again, what I’m trying to do is to calculate the Jacobian of the Earth's eccentricity with respect to the Cartesian positions and velocities of the other planets. So H = [deccentricy_earth/dx_mercury, deccentricty_earth/dy_mecury, de_earth/dz_mecury, de_earth/dvx_mecury... de_earth/dvz_mecury... de_earth/dx_neptune... etc.


I’ve successfully (I think) initialized the variations as you instructed, see below.  I’m wondering what the 1 signifies in initializing var_dx.particles[j].x = 1?



Now that I think I’ve got the equations initialized, how do I tell Rebound to vary the cartesian coordinates to give me the derivative of eccentricity with respect to them?






for ti, t in enumerate(times):

    for j in range(1, 8):  # we want the variation with respect to the planet other than earth itself:
        if j != 2:
            var_dx = sim.add_variation()
            var_dx.particles[j].x = 1

            var_dy = sim.add_variation()
            var_dy.particles[j].y = 1

            var_dz = sim.add_variation()
            var_dx.particles[j].z = 1

            var_dxd = sim.add_variation()
            var_dx.particles[j].vx = 1

            var_dyd = sim.add_variation()
            var_dx.particles[j].vy = 1

            var_dzd = sim.add_variation()
            var_dx.particles[j].vz = 1

#here I assume I would do the integration step?

    sim.integrate(t)  # Integrate

# then I should be able to get the derivate of earth eccentricity with respect to the varying cartesian coordinates I set up above?

# could you please provide the syntax to do this?

Thanks again for your guidance!

Best regards,


Jonathan Hammer
Research Scientist
[page1image55562928]


From: Hanno Rein ***@***.***>
Date: Thursday, November 30, 2023 at 11:30 AM
To: hannorein/rebound ***@***.***>
Cc: Jonathan Hammer ***@***.***>, Author ***@***.***>
Subject: Re: [hannorein/rebound] trying to use variational equations to get Jacobian but get an error... (Issue #733)

The syntax is:

var_dx = sim.add_variation()

var_dx.particles[j].x = 1

**Comment by JonathanHammer2** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JonathanHammer2** [comment]
Hi Hanno,

Thanks for the message.  Yujing and I still have some questions about how to implement this.  Yujing is going to contact you directly.  We appreciate your help!

Best regards,

Jonathan
