### ISSUE TITLE
Fix formatting issue of docstrings 

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#74]
Some doc strings are not rendered nicely. See e.g.:

![screen shot 2015-08-25 at 9 58 27 pm](https://cloud.githubusercontent.com/assets/53376/9484002/81a78ff0-4b74-11e5-928d-b2e4ce661b20.png)

**Comment by dtamayo** [comment]
Thanks.  How can I see the rendered docstrings before they’re merged into master?

**Comment by hannorein** [comment]
If you install all the dependencies for generating the documentation (might be a bit of a mess, includes doxygen and the ones listed in `doc/requirements.txt`), you can type 
    
    make doc

in the main directory. 

There might be a style option in sphinx to render these docstring properly. I just haven't found it yet.
