### ISSUE TITLE
Attempting to install previous version in order to access read simulation archives.

### ISSUE THREAD

**Issue by spalm99** [hannorein/rebound#748]
Hello, as the title says, I am attempting to read simulation archives from 2017, and I have discovered that this is no longer supported with the current rebound versions. When I try to install a past version (3.26.3), I get this error:

pip install rebound==3.26.3
Collecting rebound==3.26.3
  Using cached rebound-3.26.3.tar.gz (305 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: rebound
  Building wheel for rebound (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for rebound (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\rebound
      copying rebound\citations.py -> build\lib.win-amd64-cpython-311\rebound
      building 'librebound' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DLIBREBOUND -Isrc "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/binarydiff.c /Fobuild\temp.win-amd64-cpython-311\Release\src/binarydiff.obj -fstrict-aliasing -O3 -std=c99 -Wno-unknown-pragmas -DGITHASH=80ae73d76a74ead1f31364e613b2e63108456756 -DLIBREBOUND -D_GNU_SOURCE -fPIC
      cl : Command line error D8021 : invalid numeric argument '/Wno-unknown-pragmas'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rebound
Failed to build rebound
ERROR: Could not build wheels for rebound, which is required to install pyproject.toml-based projects

Previously there was a different error surrounding C++ build tools, but I downloaded the visual studio code tools and I think it resolved that. 
Any help you can provide is greatly appreciated! I've also uploaded the file I am trying to read, in case that helps! 
Thank you.

[File.zip](https://github.com/hannorein/rebound/files/14118526/File.zip)

**Comment by hannorein** [comment]
The old versions of rebound are not compatible with windows.
