### ISSUE TITLE
A weird behavior when integrating as system with Mercurius

### ISSUE THREAD

**Issue by ruochengzhai** [hannorein/rebound#758]
**Environment**
Which version of REBOUND are you using and on what operating system?
 - REBOUND Version: [4.3.2]
 - API interface: [Python]
 - Operating System (including version): [Linux 4.18.0-513.9.1.el8_9.x86_64]

Dear authors, 

I am trying to use `Mercurius` to integrate planetary systems. I found a pretty weird issue in the Python script I attached. On line 55 or 56, I tried to integrate the system for a different time and detect collision or escape. However, the short-time integration (line 55) experiences escape while the longer one (line 56) experiences a collision, which is very confusing.

Another question is when I use the `direct` method to detect collisions and `halt` to resolve them, if the simulation stops right at the moment when a collision happens or not. When I tried to see if any two particles collided after a `rebound.Collision` exception, it was negative.

The archive of the system is also attached for recovery. Thank you so much!

[rebound_sample.zip](https://github.com/hannorein/rebound/files/14633593/rebound_sample.zip)

**Comment by hannorein** [comment]
Your system is most likely chaotic. If you stop a simulation and then restart it, the simulation will be slightly different compared to an uninterrupted simulation due to finite floating point precision. If you absolutely need them to be the same, there are ways to do that (`safe_mode = 1`, `exact_finish_time=0`). 

REBOUND will throw the `rebound.Collision` exception at the end of the timestep during which the collision occurred. For a hybrid integrator like mercurius, the added complication is that there is a global timestep and a smaller timestep used to resolve the encounter. If you need the exact coordinates or time of the collision, you can write your own collision resolve function - which will be called exactly at the time of the collision.

**Comment by Findus23** [comment]
@ruochengzhai I think you might want to look at https://github.com/hannorein/rebound/issues/475 as I did something quite similar back then and also was first a bit confused about how to handle collisions myself.

**Comment by ruochengzhai** [comment]
Thanks, @hannorein. I am fine without stopping simulations when collisions happen. My goal is to record the time of collisions and which two particles collide. Is it possible to access a global variable in a `collision_resolve` function to record the information to avoid halting simulations?

For the tilmestep, I find during close encounters, the integrator is switched to IAS15 with a smaller `sim.dt`. Do you mean that the simulation would not stop right at the very end of this tilmestep, but might at the Mercurius's? Thank you!

**Comment by hannorein** [comment]
Yes, you can access a global variable. And yes, the IAS15 integration will not stop when a collision occurred. The simulation will only stop after the next complete global timestep `sim.dt`.

**Comment by ruochengzhai** [comment]
@Findus23, thank you! I tried to use `collision_resolve` function and wanted to raise `rebound.Collision` using 'sim._status = 7' in the function, like in #479. Sometimes I noticed the function was called without `rebound.Collision` raised so I think this might not be the right method, especially with Mercurius.

**Comment by hannorein** [comment]
This should work. It's exactly what the [default collision routine does](https://github.com/hannorein/rebound/blob/main/src/collision.c#L725).

**Comment by ruochengzhai** [comment]
This works totally fine with IAS15 but sometimes fails to raise `rebound.Collision` with Mercurius. I wonder if this might be related to the integrator switch stuff.

**Comment by hannorein** [comment]
Hm. I'm not saying you're wrong, I can't see how that could happen.

**Comment by ruochengzhai** [comment]
I tried to use a `collision_resolve` function with global variables. Now I can record all information I want from each collision! 

```
def my_collsion_fun(sim_pointer, collision):
    sim = sim_pointer.contents
    i = collision.p1
    j = collision.p2
    if i > j:
        i, j = j, i

    print('Collision between particles {} and {}'.format(i, j))
    sim.remove(index=j)

    sim._status = 7

    return 0
```

But when I used it in the example (the global variable part was omitted) I have used, the function was called twice while only one `rebound.Collision` was raised. I understood that this might be caused by two kinds of timesteps existing simultaneously in Mercurius. The problem is that at the second time, the third particle was removed which was not involved in the collision.

```
Number of particles:  3
Collision between particles 0 and 1
Collision between particles 0 and 1
Collision exception raised
Number of particles:  1
Integration time:  0.0011136531829833984
```

**Comment by hannorein** [comment]
You should not remove a particle in the collision_resolve function directly. Instead return 1 or 2 to indicate which particle REBOUND should remove.

**Comment by ruochengzhai** [comment]
Thanks @hannorein, it indeed works!
