### ISSUE TITLE
Different integrators obtain different orbits

### ISSUE THREAD

**Issue by ntsimon** [hannorein/rebound#761]
I try to use two integrators (whfast and ias15), to simulate a solar system with several planets and one comet for their orbits. However, the result shows that for whfast, the comet leaves the system while for ias15,  it moves around the Sun. why?  The other parameters such as time step remain unchanged
Any comments are welcome.
thanks.

Simon

**Comment by hannorein** [comment]
The two integrators are very different and are expected to give different results, especially if your system is chaotic and sensitive to initial conditions. A few things:

- Note that IAS15 is an adaptive method. You say you set the timestep. But the timestep will change unless you make it especially a non-adaptive method (which is of limited use).
- I assume your comet had orbit crossings with other planets. If you, you should either use IAS15, or WHFast with democratic heliocentric coordinates.  The default WHFast setting is using Jacobi coordinates which is nor ideal for your setup.
- Regardless of what integrator you use, you should make sure your results are converged and do not depend on numerical fudge factors.

**Comment by ntsimon** [comment]
Thanks,

**Comment by hannorein** [comment]
As mentioned above, regardless of what integrator you use, you should make sure your results are converged and do not depend on numerical fudge factors.
