### ISSUE TITLE
run solar system with and without planet to planet gravity forces

### ISSUE THREAD

**Issue by tckosvic** [hannorein/rebound#775]
Would like a tip on how to run full solar system model using WHFast both with body-to-body gravitation forces and also without body-to-body gravitational forces.  Just out of curiosity, I'd like to investigate starting from now after alot of years how solar system would be different. 

Is there a setting in WHFast to make it only consider gravity to act for each planet with the sun (major mass) and ignore interactions between planets?  

Alternatively, might there be a setting to effectively turn off gravity between the planets and only have gravity act between the planet and the sun?

Alternatively again, could some planet property be used to generate the desired effect?

I think I could compare the differences by just looking at the orbit differences for sometime in the future in some manner.

**Comment by hannorein** [comment]
You can simply set `sim.N_active = 1`. See https://rebound.readthedocs.io/en/latest/ipython_examples/Testparticles/
