### ISSUE TITLE
python documentation page missing?

### ISSUE THREAD

**Issue by samlawler** [hannorein/rebound#78]
I've been using rebound and noticed that on the documentation page, the API python documentation suddenly disappeared.  The page is now blank.  Is that easy to restore?  It would be really useful for me to have for reference.  Thank you.

**Comment by hannorein** [comment]
Oh. I did not notice that. Thanks for letting me know.

**Comment by hannorein** [comment]
Fixed it. Thanks again.

**Comment by samlawler** [comment]
Great!  Thanks
