### ISSUE TITLE
how to read snapshots in a loop

### ISSUE THREAD

**Issue by teuben** [hannorein/rebound#782]
**Environment**
Which version of REBOUND are you using and on what operating system?
 - REBOUND Version: 4.0.3
 - API interface: C
 - Operating System (including version): Linux
 

**Goal**
I'm trying to read a SA with many snapshots in a loop and convert to another format. So the essence of the code is:

```
struct reb_simulationarchive *sa=reb_simulationarchive_create_from_file(infile);
for (int64_t j=0; j < sa->nblobs; j++) {
   // You have to reset function pointers after creating a reb_simulation struct with a binary file.
   struct reb_simulation* r = reb_simulation_create_from_simulationarchive(sa, j);
   ...
   reb_simulation_free(r);
}
reb_simulationarchive_free(sa);
```

but in ```reb_simulation_create_from_simulationarchive``` I keep getting a warning I need to reset the function pointers, which I can't do until I have ```r``` according to ```reb_simulation_reset_function_pointers```.   I suspect I have a wrong usage pattern, but how do I process these snapshots?

**Comment by hannorein** [comment]
You're doing it right. You might not need to set the function pointers if you only output data and don't run it.

**Comment by teuben** [comment]
True, i'm only using the data. But is it possible to avoid these warnings? For large numbers of snapshots this gets a little annoying.

**Comment by hannorein** [comment]
You can use the function `reb_simulation_create_from_simulationarchive_with_messages` and then ignore the error message.

**Comment by hannorein** [comment]
See [here](https://github.com/hannorein/rebound/blob/896d6cb6f5c2d8baf150a33fc5455ecd4418e172/src/simulationarchive.c#L92) on how to use it.
