### ISSUE TITLE
There don't appear to be any reference docs?

### ISSUE THREAD

**Issue by jgd10** [hannorein/rebound#785]
I recently started working with rebound (in Python) to try and do some simple simulations and whilst plotting I was wondering if it's possible to change the centre of the plot to be one of the orbiting planets and zoom in on it. The docs didn't contain any examples saying either way, which is fine, so I thought I'd look up the function definition and check out the keyword arguments myself and see if there's anything on `OrbitPlot` that I could use, except I can't find the function definition? None of the Python commands are documented explicitly in the documentation as is common in most Python libraries. Am I looking in the wrong place?

I would expect the documentation to include reference docs that specify the possible functions, classes and methods as well as the arguments they take and the objects they return. E.g. see matplotlib's entry for their `plot` function: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html

Investigating in PyCharm, these reference docs *are* in the code but not in the documentation. 
![image](https://github.com/hannorein/rebound/assets/12530336/4b62aad3-826a-4dfc-8d01-7704c7596b43)
This seems odd to me.

**Comment by hannorein** [comment]
It's actually quite simple. You can just modify the matplotlib axes directly:

```python
import rebound
sim = rebound.Simulation()
sim.add("solar system")
op = rebound.OrbitPlot(sim)
p = sim.particles[3]
op.ax.set_xlim(p.x-0.5,p.x+0.5)
op.ax.set_ylim(p.y-0.5,p.y+0.5)
```
![Unknown](https://github.com/hannorein/rebound/assets/53376/ee69d389-e73c-49eb-a810-392f5cc4945b)

**Comment by jgd10** [comment]
Thank you that's very useful!

Though, to be clear, I meant the absence of the reference documentation in the online docs seemed odd to me.

**Comment by hannorein** [comment]
I see. It was a conscious decision not to include that in the online documentation because the documentation is shared between the python and C version of the code. We group things by module or concept rather than by language which would duplicate the effort and in my opinion make it more confusing to get started. And it's easy enough to see the doc string in python by just typing `help(rebound.OrbitPlot)`, so I don't think much is lost by not having that on readthedocs.
