### ISSUE TITLE
How to get the orbit elements of the first star?

### ISSUE THREAD

**Issue by guobuchi** [hannorein/rebound#790]
Dear friends, 
How to get the orbit elements of the first star?
I simulate a binary and set   sim.move_to_com(), now I want to know the f, M for each star at some time, so I used :

    for t in times:
        sim.integrate(t)
        primary = sim.particles[0]
        secondary = sim.particles[1]

        orbit1=sim.particles[0].orbit()
        true_anomaly1 = orbit1.f  
        mean_anomaly1 = orbit1.M  

        orbit2=sim.particles[1].orbit()
        true_anomaly2 = orbit2.f  
        mean_anomaly2 = orbit2.M  
        
        true_anomalies1.append(true_anomaly1)
        mean_anomalies1.append(mean_anomaly1)
        true_anomalies2.append(true_anomaly2)
        mean_anomalies2.append(mean_anomaly2)

But I got this error:
ValueError: Orbital elements for particle[0] not implemented unless primary is provided  at the line  'orbit1=sim.particles[0].orbit()', 
how can I do?

**Comment by dtamayo** [comment]
REBOUND is giving you back the two body orbit,  which is a property of a
pair of objects. In your case with a binary star, particles[1].orbit is
giving you the orbital elements for the reduced one body problem of
particles[0] and particles[1]. If you want individual orbital elements you
would need to do the usual a1+a2= a (with a the semimajor axis REBOUND
gives back) plus the center of mass condition m1a1 +m2a2 = 0 and pericenter
and true anomaly antialigned

**Comment by guobuchi** [comment]
Can rebound do this? 
I have some questions and want to know the individual orbit elements. For instance, if one star's omega(argument of periapsis) is theta, the omega for another is theta+pi.  How about the mean anomly? I think the mean anomly is the same for them.  
When one star at transit I think the true anomly is  2*pi - omega, and I did some simulation using rebound, the results support this. But in some packages, they asume at transit the true anomly equals  pi/2-omega or omega.   
I want to find the answers. Can you help me or give some suggestions?
Could you help me, please? I would appreciate it.

**Comment by guobuchi** [comment]
Can rebound do this?
I have some questions and want to know the individual orbit elements. For instance, if one star's omega(argument of periapsis) is theta, the omega for another is theta+pi. How about the mean anomly? I think the mean anomly is the same for them.
When one star at transit I think the true anomly is 2*pi - omega, and I did some simulation using rebound, the results support this. But in some packages, they asume at transit the true anomly equals pi/2-omega or omega.
I want to find the answers. Can you help me or give some suggestions?
Could you help me, please? I would appreciate it.

**Comment by dtamayo** [comment]
No, REBOUND won't do the calculation for you, but it's straightforward to solve the two equations above in the center of mass frame to get a1 = m2/(m1+m2) * a and a2 = m1/(m1+m2) * a, where a = particles[1].a. You're right about the pericenter, and the mean anomaly will also be off by pi, since they need to be on opposite sides of the center of mass.
