### ISSUE TITLE
'Barycentre' primary convenience function

### ISSUE THREAD

**Issue by GabrielGABFonseca** [hannorein/rebound#791]
During research pertaining exoplanets in Type-P orbits around binary stars, I need to observe the changes in the exoplanet's orbital elements relative to the two stars' barycentre. Currently, my ugly work-around is using the p3 = p1 + p2 methodology and then utilising p3 as the primary when retrieving the exoplanet's orbital elements.

I've been trying to automate this process such that every N steps, the script will create a new p3, retrieve the exoplanet's orbital elements, and then delete p3 before resuming integrating the simulation for N steps, then rinse repeat.

My life would be made significantly easier if there was some sort of convenience function that could be used to select the as the primary in a sim.orbits operation a barycentre of two other particles; perhaps something like `o = sim.orbits(primary=Barycentre(0, 1))`, where 0 and 1 are the indexes of the two stars. Such a convenience function would be even better if it could be used for an arbitrary number of particles, for instances where one wishes to investigate exoplanets in a rare circumtrinary orbit, perhaps.

In the meantime, I've been having trouble implementing something capable of doing this by myself; I have a for loop that each iteration integrates the simulation by an N number of steps, adds a particle to the simulation equal to Star1 + Star2, read the orbital elements of the exoplanet using the newly added particles as the primary, and then remove the newly added particle proceeding to the next iteration.
In my mind, this _should_ work, but I keep running into 'Particle was not found in the simulation.' or 'index out of list' errors. Any help would be greatly appreciated.

**Comment by hannorein** [comment]
How about this one liner?
```python
orbits = [sim.particles[i].orbit(primary=sim.com(0,2)) for i in range(1, sim.N)]
```
Does that help?

**Comment by GabrielGABFonseca** [comment]
Oh wow
I feel a little silly now, I must admit haha!

I never realised such a function was already in REBOUND; I knew of .move_to_com(), evidently, but I wasn't aware of this one. This seems to do the trick just fine! I assume that its arguments work sort of like the ones in Python's `range()` function, right? Is there anywhere I could read more about it?

And tangentially, if I wanted to retrieve a particle's x, y, or z coordinates whilst using this centre of mass as the coordinate system's zero, is there a way I could do so as well?

**Comment by hannorein** [comment]
Maybe this is what you're looking for?
```
sim.com().xyz
```
