### ISSUE TITLE
User-defined close encounter/colision/ejection condition.

### ISSUE THREAD

**Issue by gabrieltxg** [hannorein/rebound#793]
Hi, everyone!

For context, I'm working on the context of stability of compact planetary systems.

I'm interested in recording close encounters between pairs of planets (and currently I'm using N=7 planets).

Such close encounters in literature are defined as the moment the when the distance between two planets is smaller than their mutual Hill Radius (or the sum of their physical radius).

After some physical reasoning and literature review, however, I found out that for the study that the instability time could provide more insights about instabilities if we considered the time at which the semi-major axis of two adjacent bodies swapped (i.e. $a_{i}>a_{i+1}, \forall i \geq 1$).

That said, what I'm currently doing is integrating the compact system and evaluating it for $N_{out}$ output times, and at each of them I'm verifying all possible combinations of planets looking for those "orbit swaps". This can be quite resource consuming, even more in cases with high $N_{out}$ of weakly chaotic ones.

1. My main question is: I know that ```sim.collision = "direct"``` can raise an exception and stop the integration whenever $r_{ij}<R_{Hill}^{i, j}$, but could I define my own collision function like in the case of ```sim.collision_resolve```? Or should I look at ```sim.Escape```?

2. Moreover, instead of integrating like
```
for tt in range (np.linspace(0, Tint, Nout)):
        sim.integrate(tt)
```
and saving the final array with Noutput lines, I'm starting to make use of the Simulation Archive (which will save snapshots of my simulation for each desired output interval). 

2.1. For now I'm only interested in recording the time at which the instability (orbit swap) occurred, after which I stop the simulation. Could it be done with the simulation archive instead of integrating in a for-loop with a fixed number of Nout? How to stop such an integration after the close encounter condition has been reached? It seems to me that it will be much faster in computational terms.

2.2. Related to the search for the collision condition and the simulation archive: iterating through the particles in each snapshot of the integration in the simulation archive looking for an "orbit swap condition" would be faster than, say, for each ```tt``` in the for-loop integration to look at the semimajor axis of all the particles at the end of the integration?

Those are the two main questions, but I have an extra, non urgent one:

2.3. In a foreseeable future I'm interested in following some orbits even after the first close encounter. In the original "direct" collision solver it easy to record all the post instability close encounters, but in the case of the condition i'm trying to use ($a_{i}>a_{i+1}, \forall i \geq 1$) it can be tricky: since the particles are not shuffled, once the inner particle crosses any outer orbit, every instant of time at which it is still in this orbit, will be regarded as a "close encounter time"). 
* Should I shuffle them, in this case, according to their semi-major axis? It seems quite risky to me in the integrator point of view.
 
Thank you very much and sorry for the big question! I can easily provide code snippets if needed!

Kind regards,
Gabriel.

**Comment by hannorein** [comment]
Hi Gabriel, 

I would not use a collision detection routine for this. I would just periodically check if the particles have swapped their position. You can do that while the simulation is running using a loop, or afterwards using the snapshots saved in the simulationarchive. Unless you check for this condition very often, it should not be a limiting factor for the runtime. You only get the time right approximately, but maybe that's good enough. You can always go back and check more often.

As a side note, when you calculate the semi-major axes of all particles, you probably want to use heliocentric coordinates rather than Jacobi coordinates.

I hope this helps.
  Hanno

**Comment by gabrieltxg** [comment]
Hi, Hanno,

Thanks for the suggestions! I think that checking for around 50.000 output points (worst case scenario, since collisions can be detected earlier) won't be much a of a problem.

For larger integration times, the resolution at the lower end might be a little poor (on the order of 1e3 years, which is around 1e4 orbits of my innermost planet), but it's not an absolute problem for statistical purposes, I guess.

I will definitely pay more attention and make more use of the SimulationArchive, it's much better and easier than having to filter out which variables and analysis to make beforehand. 

I will also keep in mind the change of coordinates and make some experiment with it! Thanks.

I will close it for now!

Kind regards,
Gabriel.

**Comment by gabrieltxg** [comment]
"Manually" check for collision condition after each timestep seems to be simpler for now. CLosing it!
