### ISSUE TITLE
Fatal Error trying Poincare Map

### ISSUE THREAD

**Issue by Bruntonian** [hannorein/rebound#796]
Hello,

I recently wanted to try creating a Poincare Map and ran into issues. I then attempted to follow the [Poincare Map example](https://github.com/hannorein/rebound/blob/main/ipython_examples/PoincareMap.ipynb) verbatim, and got the following error(s) upon running this line: 

```
Nsim = 10
with Pool() as pool:
    res = pool.map(runone,range(Nsim))
```

```
Fatal error! Exiting now. Variational gravity calculation not yet implemented.

Fatal error! Exiting now. Variational gravity calculation not yet implemented.

Fatal error! Exiting now. Variational gravity calculation not yet implemented.

Fatal error! Exiting now. Variational gravity calculation not yet implemented.
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[15], line 3
      1 Nsim = 10
      2 with Pool() as pool:
----> 3     res = pool.map(runone,range(Nsim))

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/multiprocess/pool.py:367, in Pool.map(self, func, iterable, chunksize)
    362 def map(self, func, iterable, chunksize=None):
    363     '''
    364     Apply `func` to each element in `iterable`, collecting the results
    365     in a list that is returned.
    366     '''
--> 367     return self._map_async(func, iterable, mapstar, chunksize).get()

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/multiprocess/pool.py:768, in ApplyResult.get(self, timeout)
    767 def get(self, timeout=None):
--> 768     self.wait(timeout)
    769     if not self.ready():
    770         raise TimeoutError

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/multiprocess/pool.py:765, in ApplyResult.wait(self, timeout)
    764 def wait(self, timeout=None):
--> 765     self._event.wait(timeout)

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py:655, in Event.wait(self, timeout)
    653 signaled = self._flag
    654 if not signaled:
--> 655     signaled = self._cond.wait(timeout)
    656 return signaled

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py:355, in Condition.wait(self, timeout)
    353 try:    # restore state no matter what (e.g., KeyboardInterrupt)
    354     if timeout is None:
--> 355         waiter.acquire()
    356         gotit = True
    357     else:

KeyboardInterrupt: 
```

**Rebound Version: 4.4.1
Python 3.12.2
macOS sonoma 14.6.1**

Any help would be greatly appreciated.

Thanks,
Ian

**Comment by hannorein** [comment]
Hi Ian. That's strange. I've tried it just now (latest REBOUND version, macOS sonoma 14.6.1, but Python 3.9.6). It works for me. It looks like there was a Keyboard Interrupt, If you didn't do that then I'm not sure what could be the problem. Try running the example without the multiprocessing part, just by doing it in serial. It'll be a bit slower, but it should help to narrow down the problem.

**Comment by hannorein** [comment]
Hm. And just to confirm, you didn’t make any changes to the notebook?

**Comment by hannorein** [comment]
Did you install Rebound from source? If so it could be that you did an upgrade and still need to do another pip install.

**Comment by hannorein** [comment]
Strange. Maybe you can post the full code here?

**Comment by hannorein** [comment]
Thanks. I wast just trying to make sure nothing got accidentally changed. This works for me. I suspect there is something wrong with the installation on your end. All I can suggest is:

- create a new virtual environment
- install the latest version of rebound in the new virtual environment

**Comment by hannorein** [comment]
No worries and glad it works now! It can be tricky sometimes to figure out which package python is actually using... (been there myself!)
