### ISSUE TITLE
Unit conversion doesn't apply to particles radii

### ISSUE THREAD

**Issue by alelatt** [hannorein/rebound#799]
**Environment**
Which version of REBOUND are you using and on what operating system?
 - REBOUND Version: 4.4.1
 - API interface: Python
 - Operating System (including version): Linux

Hi all,

I've noticed that the function "convert_particle_units" doesn't apply changes to the length unit to the particles radii.
If I understand correctly the function "units_convert_particle", called by "convert_particle_units", doesn't seem to convert the particles radii. Could you confirm if this is the case?

To reproduce:
```
sim = rebound.Simulation()
sim.units = ('AU', 'Mearth', 'yr')
sim.add(m = 333030, r = 0.00465047)
sim.add(m = 1, r = 4.26352e-5, a = 1)
print(sim.units)
print(sim.particles[0].r, sim.particles[1].r)
sim.convert_particle_units('km', 'Mearth', 'yr')
print(sim.units)
print(sim.particles[0].r, sim.particles[1].r)
```
with output
```
{'length': 'au', 'mass': 'mearth', 'time': 'yr'}
0.00465047 4.26352e-05
{'length': 'km', 'mass': 'mearth', 'time': 'yr'}
0.00465047 4.26352e-05
```

Thank you very much,
Alessandro

**Comment by hannorein** [comment]
Yes. It does not convert the particle radii. I need to think about whether it makes sense to convert the radii as well. There are many other length scales in different variables that do not get converted either (box size, softening length, etc).
