### ISSUE TITLE
Real-time interactive 3D viz is broken in 4.4.5

### ISSUE THREAD

**Issue by arunkannawadi** [hannorein/rebound#807]
**Environment**
Which version of REBOUND are you using and on what operating system?
 - REBOUND Version: 4.4.5
 - API interface: Python
 - Operating System (including version): MacOS Sequoia 15.1.1

**Describe the bug**
Attempting to setup the real-time interactive 3D visualization results in rebound.html that just contains the text `Not Found`.

**To Reproduce**
Run the code snippet presented in the documentation
```python
import rebound
sim = rebound.Simulation()
sim.start_server()
```

Opening `localhost:1234` in the browser gives `Not Found`.

**Additional context**
I believe the root cause is that `rebound.html` is not bundled with the [latest release](https://github.com/hannorein/rebound/releases/tag/4.4.5). The curl command [here](https://github.com/hannorein/rebound/blob/24b708b66dc633d591ea9c84bff76132b7881dc7/src/server.c#L217) tries to download it from the latest release which results in a 404 error. Manually downloading `rebound.html` from an earlier release seems to resolve my issue.

**Name/Affiliation**
Arun Kannawadi - Duke University

**Comment by hannorein** [comment]
Thanks! That was my oversight and it should be fixed now. 

I'll write a script to let the CI do this automatically in the future.

**Comment by arunkannawadi** [comment]
This is broken again with `4.4.8` for the same reason. It might be a good reason to get onto #808 sooner than later :-)

**Comment by hannorein** [comment]
Indeed ;-)

(fixed it)

**Comment by andrewcumming** [comment]
I believe this has happened again with the 4.5.1 release -- I am getting a rebound.html that contains "Not Found". Manually downloading rebound.html from a previous release works.

**Comment by hannorein** [comment]
Thanks for letting me know. I’ll write some scripts to automate this.
