### ISSUE TITLE
reb_collision_search() double counting collisions?

### ISSUE THREAD

**Issue by joshuawallace** [hannorein/rebound#83]
It appears to me as I go through the source code, and when I run my code, that reb_collision_search() in the case of REB_COLLISION_DIRECT counts each individual collision twice, and thus tries to resolve it twice.

In collision.c I find:
line 67:  loop over all the particles (indexed by i, and i runs over all particles)
line 79:  loop over all the particles again (indexed by j, and j runs over all particles)

It seems to me that if a particle given by i=2 is found to collide with another particle given by j=4, that when i=4 a collision will be found when j=2 as the loop is currently set up.  In this way, two collisions are found, but both collisions are between the same two particles.

I wanted to make sure my understanding of the code as it is now set up is correct.

A suggested edit is to change line 79 from:
for (int j=0;j<N;j++){
to
for (int j=i+1;j<N;j++){

then no collisions will get double counted (and the statement on line 81, to prevent a particle from colliding with itself, would no longer be necessary).

**Comment by hannorein** [comment]
I think you might be right. 

But note that depending on how you resolve the collision, the second time you come around to the particle pair, the two particles might not be colliding anymore. So if you use a hard sphere model, then the collisions would not be counted twice, but if the particles just pass through each other, then you would. 

Feel free to open a pull request with the change.

**Comment by hannorein** [comment]
I'll close this (see pull request).
