### ISSUE TITLE
integrate()

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#94]
I hate to bring this up again, but I think there might still be a bug for some cases where the integrate function does not integrate up to where it should be. This might only affect borderline cases such as

    t = 0
    tmax = t + dt

There also seems to be an issue with 

    t = 1
    dt = 0.01
    tmax = 0

**Comment by dtamayo** [comment]
I can’t seem to replicate this.  With both IAS15 and WHFast, if I integrate to tmax = 0 or tmax = dt, print(sim.t) gives the right answer.  Also sim.t = 1, sim.dt = 0.01, tmax=0., sim.integrate(tmax), print(sim.t) gives me the right answer.

**Comment by hannorein** [comment]
I'll try to come up with a test case (PS: I didn't specifically ask you to look into it, I just create an issue to remember it).

**Comment by dtamayo** [comment]
No problem, I’m happy to try and help.

**Comment by hannorein** [comment]
The following fails for some reason. Trying to figure out why:

    import rebound
    sim = rebound.Simulation()
    sim.add(m=1.)
    sim.add(a=1.)
    sim.t = 0.
    sim.dt = 1.
    sim.integrate(0.)
    sim.integrate(1.)
    sim.integrate(2.)
