### ISSUE TITLE
Units module updates all instances

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#95]
If one updates the units on one simulation objects, it gets updates on all simulation objects.

    >>> import rebound
    >>> sim1 = rebound.Simulation()
    >>> sim2 = rebound.Simulation()
    >>> print sim1.units, sim2.units
    {'length': None, 'mass': None, 'time': None} {'length': None, 'mass': None, 'time': None}
    >>> sim1.add("Earth")
    Searching NASA Horizons for 'Earth'... Found: Earth-Moon Barycenter (3).
    >>> print sim1.units, sim2.units
    {'length': 'au', 'mass': 'msun', 'time': 'yr2pi'} {'length': 'au', 'mass': 'msun', 'time': 'yr2pi'}

**Comment by hannorein** [comment]
I think the problem is that `_units` is a class variable. This means we also have a bug related to the `_afp`, `_corfp`, `_ptmp` and `_extras_ref` variables.

**Comment by dtamayo** [comment]
Yes, I was just trying to reproduce this, but

import rebound
sim1 = rebound.Simulation()
sim2 = rebound.Simulation()
sim1._afp = 3
print(sim2._afp)

gives None

and 

def foo():
    pass
sim1.additional_forces = foo
print(sim2.additional_forces)
print(sim1.additional_forces)

gives None
<CFunctionType object…>

I’m not sure why this wouldn’t give the same behavior…looking into it…

**Comment by hannorein** [comment]
The difference might be that we initialize the `_units` class variable but not the others. Python looks first for instance variables and if not found, it tries to find the class variable with the same name. 

<speculation> For additional forces, it doesn't see a class variable as it's `None` and thus creates an instance variable. </speculation>

In either case, all these should be instance variables. Unfortunately, we can't just copy and paste the 5 lines into the constructer. That might fail if the instance gets created via ctypes in which case the constructer does not get called. So for every occurrence of `_afp` (and others) we'd need to check if the attribute exists before using it with `hasattr`.

**Comment by hannorein** [comment]
Actually, all the variables except `_units` should be straightforward to fix as they are used only once in the entire code.

**Comment by dtamayo** [comment]
I thought the conclusion we came to (for I think the same reason as you just mentioned) was that we’d make the ctypes pointers to simulations private and that these should never be used by the user (and probably not by us either).  That if we used the simulation pointer, it should be on the C side.

**Comment by hannorein** [comment]
Yes. I think we should make this explicit by raising an exception in the getter for `additional_forces`.

I don't think #96 is going to work though. For the reason mentioned above. It will fail if you get a simulation instance from a c-pointer and try to do anything related to units.

**Comment by dtamayo** [comment]
So I just went through rebound.h and I think the only function that returns a reb_simulation is reb_create_simulation.  So it seems like the only way to run into a problem is if the user manually accessed the “private” _sim pointer in extras, or made their own ctypes implementation with a sim pointer.  What do you think of keeping _units as an instance variable, and having the units functions check whether self._units is set, and raising an exception if it’s not, alerting the user that they shouldn’t be doing that?

**Comment by hannorein** [comment]
There is also the `reb_create_simulation_from_binary` one. 

Right now this fairly straight-forward scenario would fail: Create a simulation, add planets, then save to binary, read binary back in later and add an additional planet with Horizons. In that case `_units` will not be set and a key exception will be thrown in `simulation.add()` when accessing `_units["length"]`.

**Comment by hannorein** [comment]
By the way, we can never make this work perfectly because the units module is python only. I still think we should make the above case work.

**Comment by hannorein** [comment]
(this is a reply to your e-mail, but I'll put it here to keep a log)

I think all the ones except `_units` are very straightforward. We simple add an exception in the getters (since nobody should call it anyway). This was we don't even need to initialize the variables in the constructor. See pull request above.

**Comment by dtamayo** [comment]
Hm, it’s still a bit counterintuitive to me.  It *looks* like (when looking at the code) if you set one instances ._afp, you would be changing all of the simulation instances ._afp.  Of course it doesn’t, for the special reason you mentioned that they’re initialized to None rather than something else.

I realize this is a stylistic decision, but it seems more clear to me that they would be in the constructor as instance variables to explicitly show each instance will have its own.  The downside that having ctypes instantiate a simulation would bypass the constructor doesn’t seem like a big problem to me, since if you set afp in a simulation and then had ctypes instantiate a pointer to it, afp would no longer be set in the new one either.

**Comment by dtamayo** [comment]
(the last clause was referring to the code as it stands now)

**Comment by hannorein** [comment]
We can add `self._afp = None` in the constructor, but it has no effect.

**Comment by dtamayo** [comment]
Sorry, I missed that you’d removed all the _afp = None statements, which I agree gets rid of the confusion I was talking about.  The only remaining thing is that we’d added extras_ref in there to be explicit that it can hold a reference to another instance, rather than monkeypatching.  Maybe setting it = None in the constructor makes this clear, even if it doesn’t actually have any effect on the code?  Again, this is a small stylistic point, but we talked about it for a while when going through this

**Comment by hannorein** [comment]
I don't mind either way. Not monkey patching sounds good. But someone could also argue we're already monkey patching Particle, so why not Simulation.

**Comment by dtamayo** [comment]
Did we resolve this or is there still a loose end?

**Comment by hannorein** [comment]
I think it's closed, but I don't remember.

**Comment by hannorein** [comment]
Ok. It should be closed.
